### ISSUE TITLE
Unrecognized game mode: skyrimspecialedition | Even after latest update

### ISSUE THREAD

**Issue by saa1234** [Nexus-Mods/Nexus-Mod-Manager#1002]
**Describe the bug** 
When I click a url to download mod, I get the error message "Unrecognized game mode: skyrimspecialedition" and is unable to download any mod.

**Environment**
- NMM version: _0.71.3_
- Mod(s) used: _<none>_

**To Reproduce**
 Try to download any link for mods on the nexus for skyrim special edition, the message will show.

**Additional information** 
I had this error, then I updated my nexus mod manager because I was told it would fix the problem, but the problem persists. Only workaround I have as of yet is modifying the download url nxm://skyrimspecialedition/mods/xxx/files/xxx to nxm://skyrimSE/mods/xxx/files/xxx to be able to download anything through the manager.

**Comment by DuskDweller** [comment]
Make sure you really updated to 0.71.3 .

**Comment by saa1234** [comment]
![bilde](https://user-images.githubusercontent.com/64136177/79974296-5a6a4c80-8499-11ea-9661-e9bbb4835f7b.png)
![bilde](https://user-images.githubusercontent.com/64136177/79974352-7b32a200-8499-11ea-8203-39a55d774144.png)

My window says this. Any more ways to know for sure?

**Comment by DuskDweller** [comment]
Then this can only mean you got another old install of NMM somewhere else that's catching dowload requests.

**Comment by saa1234** [comment]
Seems like that was the problem. The old nexus manager was still in C:/Games/Nexus Mod Manager. 

Deleted the .exe, and tried to download a mod, and my browser then asked what program I wanted to open the link, then I selected the newest install of the mod manager. Thank you.
