### ISSUE TITLE
NMM "Change Game Mode" not working!

### ISSUE THREAD

**Issue by dwharper34** [Nexus-Mods/Nexus-Mod-Manager#1006]
_Please give as much information as you can, replace/remove italicized text._
Windows 7 64-bit SP1
Intel® Core™ i7-7700K Processor
AMD Radeon RX 5700 XT
[LoadOrder_Skyrim_2020-04-19T00-15-16.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/4526570/LoadOrder_Skyrim_2020-04-19T00-15-16.txt)

**Describe the bug** 
I am having some problems with Nexus Mod Manager. On version 0.71.2, I checked the box "Don't ask me next time." when selecting a game at startup. I was playing for about a  month when I decided to play another game. When I press "Change Game Mode" nothing happens. When I tried to reinstall, versions 0.71.1, 0.71.2 and 0.71.3, all go directly to the game I had been playing, without running the game scan. That is bad. I just had to re-install Windows 7, so I had to reinstall all my games too! I installed version 0.71.0 and it re-scanned my games for me. I did not check the box "Don't ask me next time." this time, so I can run the game scan when I want. The button to "Change Game Mode" still will not work in 0.71.0 either. I didn't try any earlier NMM versions.

How do I re-enable the original screen that I disabled?

**Environment**
- NMM version:  0.71.0
I don't have any links to mods on Nexus.

I don't think trace logs will help.

**To Reproduce**
Open Nexus Mod Manager, then click on the button "Change Game Mode" in the upper right hand corner.

**Additional information** 
I have more than one game installed.

**Comment by squid-box** [comment]
This doesn't seem to be a general problem, as the button works for me with 0.71.3 (and it hasn't been changed for quite a while).

So, when you click the button - what happens?
Do you see a list of possible actions like these:
![image](https://user-images.githubusercontent.com/864820/80248029-6f003d80-866f-11ea-906b-6a4613ba3499.png)

Or simply nothing? 
Do you have multiple monitors? I've had instances where the menu shows up on another display.

**Comment by dwharper34** [comment]
I get absolutely nothing. I do have Picture in Picture for a 2nd display. I never use it.
That was it!  I went to change resolution, choose Display 2, then changed only show desktop on Display 1. Now it works perfectly! Thank You!
