### ISSUE TITLE
Certain mods will keep getting turned off when loading a save.

### ISSUE THREAD

**Issue by Dreamedcar** [Nexus-Mods/Nexus-Mod-Manager#1026]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
So mods such as WATM and Sim settlements will get auto turned off when the game changes the load order after i activate them. I cant even activate them without the game automatically turning them off

**Environment**
I dont use any mod managers. i download manually I have checked and they all are in the Plugins file.

**To Reproduce**
Not certain: Get a repack of FO4 Download the following mods: WATM Sim settlements More automatron voices FO4 unofficial patch, Automatron Reboot. Try to enable these mods. Leave the load order and watch as FO4 automatically turns it off.

**Additional information** 
My version is cracked. however i dont believe that that has anything to do with the bug due to other mods i have working just fine

**Comment by DuskDweller** [comment]
So:

- you're not using any mod manager and you're asking for help in a mod manager support forum,
- you're using a cracked game and you're complaining cause stuff isn't working as intended,

Seriously!?
