### ISSUE TITLE
Structures - BUGS

### ISSUE THREAD

**Issue by RominGamer** [Nexus-Mods/Nexus-Mod-Manager#1029]
Good night, I would like to report a new bug in nitrox, when a friend on the server makes his own home, when restarting the server some unfinished pink structures appear and cannot be removed, and the rest of the structures are obstructed without being able to enter at home. Correct construction errors, only I as a host can build without errors, but my friends don't. Soon I'll post the world save for you to check!

**Comment by squid-box** [comment]
As this was never updated, I assume you figured out this wasn't the place to ask - but for clarity's sake this repository manages the Nexus Mod Manager, not issues with mods.
