### ISSUE TITLE
System.Security.SecurityException.CallNextHookEx crashes NMM with System.Security.SecurityException

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#103]
Happens when attempting to install TTW fomod, when hitting 100%.

System.Security.SecurityException: 'Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.'

Raised on https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/DockPanelSuite/Docking/DockPanel.FocusManager.cs#L84

Quick Watch:
https://my.mixtape.moe/xmnxxy.png

**Comment by ousnius** [comment]
The installer of TTW is a C# script. It edits the .ini files as well, make sure those aren't set to read-only for you.
