### ISSUE TITLE
OpenMW Support

### ISSUE THREAD

**Issue by xirsoi** [Nexus-Mods/Nexus-Mod-Manager#1040]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
OpenMW supports multiple data file directories, which dramatically simplifies mod installation. It would be nice if Vortex could recognize OpenMW and install mods in the preferred OpenMW way, including editing the openmw.cfg as necessary to reference new directories.

**Comment by squid-box** [comment]
Just a note, this repository is for the NMM application, not Vortex.

I've still added the Enhancement label as OpenMW support could be seen as a good addition. It doesn't seem like there's a separate section for it at Nexus though, so proper support might be iffy.

**Comment by xirsoi** [comment]
Thank you for the clarification, and your caveats are noted.
