### ISSUE TITLE
Can't install any mods

### ISSUE THREAD

**Issue by Valcrisss** [Nexus-Mods/Nexus-Mod-Manager#1041]
Hi, it's been about two months (I think) since my NMM can't install any mods (from any games). It's always telling me that the server can't be reached. I already tried to reinstall NMM but nothing change, even after updates. I'm also currently using the last version of Nexus manager (0.72.1). 

Here are some exemples : 
For Skyrim : 
Server Unreachable: nxm://skyrim/mods/57141/files/1000315036?key=bGgmy1vL_7tnyMlThf60wA&expires=1595804732&user_id=55618342
Here is the mod I was trying to download (Morskom Estate 2.1) https://www.nexusmods.com/skyrim/mods/57141?tab=files&file_id=1000315036&nmm=1

And the same for Fallout 4 : 
Server Unreachable: nxm://fallout4/mods/46101/files/187535?key=9epOjgKpnsXBN35sBpWWhQ&expires=1595804028&user_id=55618342
The mod (Classic Holstered Weapons System - v1.04b) https://www.nexusmods.com/fallout4/mods/46101?tab=files&file_id=187535&nmm=1

I don't know how I'm supposed to send the trace log, or even just found it.

**Comment by Thrainkillmum** [comment]
bro same, 130 mods into Skyrim se my NMM just doesn't allow me to manually download, only straight from the site.

**Comment by Thrainkillmum** [comment]
I've been all over forums and Reddit talking about the same thing

**Comment by Valcrisss** [comment]
Well I'm glad I'm not the only one! I kinda thought I did something wrong wich broke forever NMM

**Comment by Valcrisss** [comment]
Now that you told me that peoples were talking about it on Reddit, I went to check it out. And from what I noticed it's simply because the Nexus no longer supports NMM and therefore has switched to Vortex for good. 
I think it's the kind of information that could have been better highlighted for those who still used NMM.
