### ISSUE TITLE
Download link issue

### ISSUE THREAD

**Issue by keiberto** [Nexus-Mods/Nexus-Mod-Manager#1044]
Hello. I tried to download this mod https://www.nexusmods.com/stardewvalley/mods/6578 but it seems like the download is broken as I couldn't click on it (I download my mods manually). Is there a way to repair the link or any other solutions? It would be great if you can fix this issue.

Thank you.

**Comment by squid-box** [comment]
Hi!

You'll have to contact the Nexus team for website issues, this repository only handles the (no longer supported by Nexus) Mod Manager.
