### ISSUE TITLE
NMM 0.72 versions are broken, and going to an older version also broke modding

### ISSUE THREAD

**Issue by ReeceBar** [Nexus-Mods/Nexus-Mod-Manager#1050]
So with the latest version of NMM 0.72 I can't install or download multiple mods, as that crashes it. So I've gotten an older version. This broke modding FNV it takes forever to install mods, and when it 'does' I can instantly disable them as it doesn't actually install them or anything. Fo4 and SSE works fine with the older version of NMM that I use, 0.71.4.

**Comment by DuskDweller** [comment]
Solved with release 0.72.2 .
