### ISSUE TITLE
NMM 0.72.1 Can not install any selection of multiple files....

### ISSUE THREAD

**Issue by HLCaerdic** [Nexus-Mods/Nexus-Mod-Manager#1051]
_Please give as much information as you can, replace/remove italicized text._the newest NMM 0.72.1 crashes each and every time I try to add with the + button multiple files.... older versions could do this easily..... this is not activating the mods in game just loading them into the NMM screen from saved files from the Nexus site. 

It will add the files one at a time but you have to wait till it is completed with one file before starting with a new one... also files Downloaded directly from the Nexus Site installs perfectly.

I have tons of Mods that are no longer available and wish to install them in the time honored fashion... I could do one at a time but that takes time and I wanna play NOW!!! ( :-P 

Trace Log 

[TraceLog20200902131033.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/5164810/TraceLog20200902131033.txt)

**Comment by DuskDweller** [comment]
Solved with release 0.72.2 .
