### ISSUE TITLE
Program Crash on adding more than one local mod at a time.

### ISSUE THREAD

**Issue by dazzaXx** [Nexus-Mods/Nexus-Mod-Manager#1053]
**Describe the bug** 
Adding more than one local zip mod at a time results in the program crashing and closing on the second zip.

**Environment**
- NMM version: 0.72.1
- Mod(s) used: Any local zips.

**To Reproduce**
Add any 2 zips from your local drive in one go and it will crash attempting to add the second one, the tracelog should be generated when it attempts to add the second local mod.

**Comment by DuskDweller** [comment]
Solved with release 0.72.2 .

**Comment by dazzaXx** [comment]
Nice to hear, thank you very much!
