### ISSUE TITLE
Premium Membership not recognized

### ISSUE THREAD

**Issue by rtraffis** [Nexus-Mods/Nexus-Mod-Manager#1064]
![Screenshot_1](https://user-images.githubusercontent.com/73587555/97425297-4d1a9880-18e8-11eb-9f7d-77c05520595b.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/73587555/97425306-5277e300-18e8-11eb-9dc1-85a454f0d404.jpg)

**Comment by DuskDweller** [comment]
The problem was caused by the Nexus website, it was reported and solved this morning.

**Comment by squid-box** [comment]
Given the deathly silence I assume this was resolved and I'm closing the issue.
