### ISSUE TITLE
NMM does not count ESL flagged light plugins correctly in version 0.72.3

### ISSUE THREAD

**Issue by TKHBMVP** [Nexus-Mods/Nexus-Mod-Manager#1070]
Some already installed plugins have been flagged as light plugins with SSEEdit 4.03 
On the plugins tab they are missing the load order and index values.
But on the status bar they are still counted as normal esps.
The game behaves correctly and starts, even NMM shows more than 255 active plugins, because it doesn't deduct the light plugins.

**Comment by DuskDweller** [comment]
Currently NMM doesn't properly recognize that kind of plugin (esl flagged esps), you should just ignore for the time being.

**Comment by DuskDweller** [comment]
Fixed in 0.80.12
