### ISSUE TITLE
premium membership

### ISSUE THREAD

**Issue by vinncool** [Nexus-Mods/Nexus-Mod-Manager#1073]
My acount username is vinncool, I just bought a premium membership by accident. I would like to be refunded the 90.68$CAD that I paid for the membership. Please contact me on my email to : v.abbatiello@live.ca ; transaction number from paypal : 85S244770M678841W.

**Comment by DuskDweller** [comment]
This is the NMM community edition support section, you need to check for help on the Nexus website.
