### ISSUE TITLE
Cant find the exe files for supported tools

### ISSUE THREAD

**Issue by kvanbiljon** [Nexus-Mods/Nexus-Mod-Manager#1083]
When I go to Supported Tools and hit configure x, then navigate to the folder the tool is located, for some reason the executable file isn't appearing.  How do I fix this?

**Comment by CoroNaut** [comment]
On my client, you can select any supported tool that is grayed out and it will open a **folder** search dialog box. I locate the folder that contains the executable and it picks up the actual program automatically from the folder.

For instance, if you are installing BodySlide... the folder is probably "...\Data\CalienteTools\BodySlide". This is the folder you would select when navigating through the folder search dialog box.
