### ISSUE TITLE
Weird bug involving skyrim special edition, reinstalled NMM and the game several times, cleared out all files related.  Still here

### ISSUE THREAD

**Issue by DocValentine2** [Nexus-Mods/Nexus-Mod-Manager#1084]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Could not load file or assembly 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
Happens when attempting to enable/install any mods

**Environment**
Version: 21 April 2020, latest.

Trace file has been created: TraceLog20210110161908.txt
Mod Manager Version: 0.72.3.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) SkyrimSE
Game Mode Factory Selected: Skyrim Special Edition (SkyrimSE)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim Special Edition (SkyrimSE)
    Installation Path: D:\Steam\steamapps\common\Skyrim Special Edition
    Install Info Path: D:\Program Files\TEMPINSTALLINFO
    Mod Path: D:\Program Files\modsforNexus
    Mod Cache Path: D:\Program Files\modsforNexus\cache
    Mod Download Cache: D:\Program Files\modsforNexus\downloads
    Overwrite Path: D:\Program Files\TEMPINSTALLINFO\overwrites
    Virtual Install Path: D:\Program Files\modsforNexus
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: D:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: D:\Program Files\Nexus Mod Manager\GameModes
            Checking: SkyrimSE.CSharpScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.CSharpScript.SkyrimSECSharpScriptType
            Checking: SkyrimSE.XmlScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.XmlScript.SkyrimSEXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: D:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: D:\Program Files\modsforNexus
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: D:\Program Files\TEMPINSTALLINFO\InstallLog.xml
    Loaded from XML.
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: D:\Steam\steamapps\common\Skyrim Special Edition\Data
                Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm
                Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm
                Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm
                Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm
                Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm
            Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm
                Registered.
            Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm
                Registered.
            Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm
                Registered.
            Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm
                Registered.
            Found: D:\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm (IsNull=False)
            Loading D:\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm (IsNull=False)
            Loading D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm (IsNull=False)
            Loading D:\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm (IsNull=False)
            Loading D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: D:\Steam\steamapps\common\Skyrim Special Edition\SkyrimSE.exe (IsNull=False)
    SKSE Command: D:\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command: D:\Program Files\LOOT\LOOT.exe (IsNull=False)
    Wrye Bash Command:  (IsNull=False)
    SSEEdit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm) (False)
    Loading: Update.esm (D:\Steam\steamapps\common\Skyrim Special Edition\Data\Update.esm) (False)
    Loading: Dawnguard.esm (D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dawnguard.esm) (False)
    Loading: HearthFires.esm (D:\Steam\steamapps\common\Skyrim Special Edition\Data\HearthFires.esm) (False)
    Loading: Dragonborn.esm (D:\Steam\steamapps\common\Skyrim Special Edition\Data\Dragonborn.esm) (False)
Setting up listener on Nexus Mod Manager-SkyrimSEIpcServer/SkyrimSEListener at 2021-01-10 16:19:10
Running Application.
Adding Mod to running instance of client: nxm://skyrimspecialedition/mods/12604/files/35407?key=P1Vb0Tg-xplffEjoSbmDSw&expires=1610486371&user_id=81714883
[nxm://skyrimspecialedition/mods/12604/files/35407?key=P1Vb0Tg-xplffEjoSbmDSw&expires=1610486371&user_id=81714883] Adding Mod to AddModQueue
[nxm://skyrimspecialedition/mods/12604/files/35407?key=P1Vb0Tg-xplffEjoSbmDSw&expires=1610486371&user_id=81714883] Starting Add Mod Task.
[nxm://skyrimspecialedition/mods/12604/files/35407?key=P1Vb0Tg-xplffEjoSbmDSw&expires=1610486371&user_id=81714883] Starting Add Mod Task.
[nxm://skyrimspecialedition/mods/12604/files/35407?key=P1Vb0Tg-xplffEjoSbmDSw&expires=1610486371&user_id=81714883] Downloading Files.
[nxm://skyrimspecialedition/mods/12604/files/35407?key=P1Vb0Tg-xplffEjoSbmDSw&expires=1610486371&user_id=81714883] Launching downloading of https://cf-files.nexusmods.com/cdn/1704/12604/SkyUI_5_2_SE-12604-5-2SE.7z?md5=3vLQjjw0lHhiBqsTPqIshQ&expires=1610327975&user_id=81714883.
[https://cf-files.nexusmods.com/cdn/1704/12604/SkyUI_5_2_SE-12604-5-2SE.7z?md5=3vLQjjw0lHhiBqsTPqIshQ&expires=1610327975&user_id=81714883] Retrieving meta data.
[https://cf-files.nexusmods.com/cdn/1704/12604/SkyUI_5_2_SE-12604-5-2SE.7z?md5=3vLQjjw0lHhiBqsTPqIshQ&expires=1610327975&user_id=81714883] Downloading.
[D:\Program Files\modsforNexus\downloads\SkyUI_5_2_SE-12604-5-2SE.7z] Adding mod from archive.
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command: D:\Program Files\LOOT\LOOT.exe (IsNull=False)
    Wrye Bash Command:  (IsNull=False)
    SSEEdit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Launching LOOT
    Command: D:\Program Files\LOOT\LOOT.exe
    Succeeded
Preparing to write load order to file "C:\Users\Doc\AppData\Local\Skyrim Special Edition\plugins.txt".
Got access to "C:\Users\Doc\AppData\Local\Skyrim Special Edition\plugins.txt".

Tracing an Unhandled Exception:
Exception: 
Message: 
	Could not load file or assembly 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
Full Trace: 
	System.IO.FileNotFoundException: Could not load file or assembly 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Nexus.Transactions.TransactionScope..ctor()
   at Nexus.Client.PluginManagement.ApplyLoadOrderTask.DoWork(Object[] args)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Running Threads (1)
    14 () 
        Aborted

**Comment by DocValentine2** [comment]
Been about a week and I've gone over and tried anything, this same issue occurs with every game.  It seems that even Vortex and Mod Organizer don't work either, none of the mods are loading into the "plugins" section and I've given up hope for a fix.  Which sucks because I would like to be able to actually mod the games that are popular for their, well, mods.

**Comment by seeknknow** [comment]
You likely have some kind of corrupted install of a piece of software. I'm having zero issues. Vortex has default notifications to let you know you must "fix" where it installs the mods. Follow the onscreen instructions. You can't install mods on a different drive than your game. Vortex is likely downloading the files to a storage location that is not accessible from your game directory. Fix those issues and you may have better luck. I have NEVER had a problem installing mods through NMM or Vortex. Heck even MO always worked and I can't stand MO. Just follow the instructions given and recommendations in the notifications carefully. At this point I'd say reinstall Vortex and wait for the program to throw you the "issues" and "fix" notifications. They're like "Quest objectives" except more informative. 😄

**Comment by seeknknow** [comment]
Preparing to write load order to file "C:\Users\Doc\AppData\Local\Skyrim Special Edition\plugins.txt".
Got access to "C:\Users\Doc\AppData\Local\Skyrim Special Edition\plugins.txt".

This is pointing to the wrong location you need to fix this in the settings of NMM or Vortex. That's where the error is coming from.

**Comment by seeknknow** [comment]
From a quick google search it could be an issue with your .NET installs Might need to backup and reinstall windows. Something ain't right if it's not what I said earlier.

**Comment by seeknknow** [comment]
Plus it looks like you're using windows 8....maybe time to upgrade to Windows 10.

**Comment by DocValentine2** [comment]
Thank you for replying, I'll go ahead and clear some things up.
I am using windows 10 lol
I once did some very funky filework to get mods to work even on a different drive, since Skyrim SE has the missing sounds bug if installed on another drive other than your boot drive (a strange anti-piracy measure even though I bought the game and have it on steam).  I've went ahead and reinstalled/changed the settings of the mod managers as well several times but might do another clean slate if fixing the odd load order issue that you noticed and I didn't (thankfully)

Once again I thank you for replying,  this is the first time I've ever had issues like this and it probably stems from my odd file work around

**Comment by DocValentine2** [comment]
Update: I tried with New Vegas, files all match up, still the same error.
https://imgur.com/a/R4O8qnP happens when enabling a mod.

**Comment by seeknknow** [comment]
Then it's likely a .NET problem. Try to reinstall 

Installed .NET Versions:
CDF SP 0
v2.0.50727 SP 2
v3.0 SP 2
v3.5 SP 1
v4 SP 0
v4.0 SP 0
v4.5: 4.6 or later

If you can do so individually great but I'd just try a fresh install of windows at that point. The error seems to stem from there.

**Comment by DocValentine2** [comment]
Apologies for the super late reply but yes, reinstalling windows fixed it.  Thank you for your help my friend.
