### ISSUE TITLE
Download ETA Incorrect for times over one hour.

### ISSUE THREAD

**Issue by SlinkyThePerson** [Nexus-Mods/Nexus-Mod-Manager#1089]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
For very large mod downloads, In excess of approx. 4 gigabytes at the Non-premium 2Mbps download speed, the ETA for the download appears to truncate the hour segment of the time. For example, an estimated time of 1 hour, 45Minutes and 30 seconds would display as "45:30" instead of the expected "1:45:30". This occurs regardless of the width of the column in which ETA is displayed and is not a result of the hour label being obscured by the border.

**Environment**
- NMM version: _0.72.3_
- Mod(s) used: _[Fallout: The Frontier](https://www.nexusmods.com/newvegas/mods/68009)_

**To Reproduce**
Start a mod download that will take more than one hour to complete, This is most easily achieved with a non premium account, or by throttling your data connection. Then look at the ETA column in the Download Manager tab. It will list only the minutes and seconds.

**Additional information** 
Link to a screenshot pointing to the area affected by the bug: https://imgur.com/a/NeGnIFN

**Comment by DuskDweller** [comment]
A new version should be out in a few days and it will also fix this issue.

**Comment by DuskDweller** [comment]
Fixed in 0.80.0
