### ISSUE TITLE
NMM installs 'Scripts' folder to wrong directory in Skyrim SE

### ISSUE THREAD

**Issue by karmacat77** [Nexus-Mods/Nexus-Mod-Manager#1090]
When using NMM v0.72.3 with Skryim SE, NMM installs the 'Scripts' folder of a mod to the wrong directory.  This occurs when the zipped mod has been packaged as follows:

Top folder:  Unique name (excluding 'Data')
Next level folder:  'Scripts' folder only (nothing else)

and is downloaded using the 'Mod Manager Download' button on Nexus Mods, and installed via NMM.  NMM will consistently install such a packaged mod to '...Data\[Unique name]\Scripts' instead of to '...\Data\Scripts'.  

Under most other mod packaging scenarios, the scripts folder will be correctly recognised and intalled.  Examples:

Top folder:  -Missing-
Next level folder:  'Scripts' folder only 

Top folder:  Unique name
Next level folder:  'Scripts' folder as well as at least one other recognised folder or file which can include eg. 'textures', 'meshes', .esp, .esm, etc.

Top folder:  'Data'
Next level folder:  'Scripts' folder only

This bug can be reproduced by creating dummy mods with varying folder structures and testing the install, which I've done before posting.

An example of a mod I've recently experienced this with is 'Immersive Horses Script Fixes' on Nexus:
https://www.nexusmods.com/skyrimspecialedition/mods/40543

**Comment by DuskDweller** [comment]
There's a new release in the works, it should be ready this week or the next and it will fix this issue.

**Comment by karmacat77** [comment]
Great, thank you.
