### ISSUE TITLE
NMM installs MWSE folder to wrong location in Morrrowind

### ISSUE THREAD

**Issue by karmacat77** [Nexus-Mods/Nexus-Mod-Manager#1093]
This issue with Morrowind and MWSE folders looks similar to the one I posted about Skyrim SE and Scripts folders on 10 Feb 2021.

When using NMM v0.72.3 with Morrowind, NMM installs MWSE mods to the wrong location. This occurs when the mod has been archived as follows:

Top folder: Unique name (not 'Data Files')
Next level folder: 'MWSE' folder only

and is downloaded using the 'Mod Manager Download' button on Nexus Mods and installed via NMM.  NMM will install it to 'Data Files\[Unique name]\...' instead of to 'Data\MWSE\...'.

Under several other mod packaging scenarios the MWSE folder will be correctly recognised and intalled. Examples:

Top folder: -Missing-
Next level folder: 'MWSE' folder only

Top folder: Unique name
Next level folder: 'MWSE' folder as well as at least one other recognised folder or file, including eg. 'textures', 'meshes', .esp, .esm, etc.

Top folder: 'Data Files'
Next level folder: 'MWSE' folder only

This behaviour can be reproduced by creating dummy mods with varying folder structures and testing the install, which I've done before posting.

An example of a mod I've just experienced this with is 'Apoapse's Attack' v3.0 on Nexus:
https://www.nexusmods.com/morrowind/mods/44007

**Comment by DuskDweller** [comment]
Thanks for the report, I'll fix this in the next patch.

**Comment by DuskDweller** [comment]
Fixed in the next release.

**Comment by karmacat77** [comment]
Thank you!
