### ISSUE TITLE
Nephilim mod dowload issue

### ISSUE THREAD

**Issue by MrSlim3234** [Nexus-Mods/Nexus-Mod-Manager#110]
Nephilim // A problem occurred during install: 
The execution has failed due to the bug in the SevenZipSharp.
Please report about it to http://sevenzipsharp.codeplex.com/WorkItem/List.aspx, post the release number and attach the archive.
The mod was not installed. // Install //  

This is what it told me trying to download a mod called Nephilim.

**Comment by ousnius** [comment]
Do you have enough space on all your drives? Did you check if the download isn't corrupted if you download the archive manually and open it up?

**Comment by squid-box** [comment]
With no reply in almost a year, I'm assuming this problem is no more.
