### ISSUE TITLE
Locks up on right click

### ISSUE THREAD

**Issue by excalculus** [Nexus-Mods/Nexus-Mod-Manager#1101]
Selecting any already installed mod on the mods tab and then right clicking that mod causes NMM to lock up.  NMM must be shut down to recover.  Before the update to 0.80.0, right clicking an already installed mod gave a number of options in a context menu such as disable, reinstall, etc.   None of this works any more as the program locks up immediately upon right clicking.

- NMM version: 0.80.0

**Comment by squid-box** [comment]
I'm unable to reproduce this, could you give us a bit more info? What game and mod(s) is causing this for you?
Even better would be if you could [force a trace log creation](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log), cause the problem, and then upload the resulting trace log to this issue.

**Comment by excalculus** [comment]
I had the issue with Skyrim LE and any installed mod.  Had it occur on two installs on two different machines (one Win 7 and one Win 10).  That was yesterday.  Today, no issue.
