### ISSUE TITLE
Cyberpunk 2077 - Mods goes to wrong Folder

### ISSUE THREAD

**Issue by giant0815** [Nexus-Mods/Nexus-Mod-Manager#1112]
Downloaded Mods from Nexus or other sources, that have the correct folderstructure for Cyberpunk 2077, did not installed in the correct folder, but alway to folder Cyberpunk 2077\archive\pc\patch.

Example Mod "Cyber Engine Tweaks - Bug fixes" (Attachment)
Correct Install Folder = Cyberpunk 2077\bin\x64
NMM Install Folder = Cyberpunk 2077\archive\pc\patch\bin\x64
[Bug fixes-107-1-11-4-1613669433.zip](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6178618/Bug.fixes-107-1-11-4-1613669433.zip)

Please fix. Thanks a lot.

**Comment by DuskDweller** [comment]
Thanks for the report, I'll fix this with the next release.

**Comment by giant0815** [comment]
Version 0.80.3 not fixes the CYBERPUNK2077 Bug. The Mods goes still to the wrong folder. For this game the Manager is still useless. Hope for a quick fix - cant wait ;-). Thank you.

**Comment by DuskDweller** [comment]
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.80.4

**Comment by giant0815** [comment]
Yeah, the update 0.80.4 fixed it. I'm not a friend of vortex & co. My favourite is NMM, because its slim an not so overkilled like the other ones. Superb job. Thank you oncemore.
