### ISSUE TITLE
Cant login after the latest update

### ISSUE THREAD

**Issue by phoenixfabricio07** [Nexus-Mods/Nexus-Mod-Manager#1114]
waiting ad infinitum for  login attempt

**Comment by BlazeStryker** [comment]
Can't Login, can't download, This is a real peach of an "upgrade", straight out of the Microbethie playbook.

**Comment by phoenixfabricio07** [comment]
Well, after reboot the PC , its logged . Hope it was only an isolated failure.

**Comment by BlazeStryker** [comment]
I backgraded. After the last few years, I get hives when I see shinies that don't work. Heck, I can't even update my GeForce Experience drivers anymore as they outstripped Fallout 4.

**Comment by DuskDweller** [comment]
All login issues are related to the Nexus and the Nexus API, if you want to be one of those people that just love to complain about anything since Microsoft stopped updating your Windows XP, then please, go ahead.
