### ISSUE TITLE
Release 0.80.4 BUG

### ISSUE THREAD

**Issue by OldGamerDarthy** [Nexus-Mods/Nexus-Mod-Manager#1121]
hello, after click on setting on NMM opened, is istant crash, i try to open with privileges or compatibility options, but the crash continues, can fix ? thanks if need i can send the crash logs (i use windows 10 on Gaming notebook asus tuf)

**Comment by DuskDweller** [comment]
Please check here:
https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/1123
