### ISSUE TITLE
NMM Crashing when Pressing Settings Button

### ISSUE THREAD

**Issue by pirate1337** [Nexus-Mods/Nexus-Mod-Manager#1122]
[Tracelog](https://gist.github.com/pirate1337/669ac099564e809cbeaeb113d8c5ce5b)

When attempting to press the settings icon in the manager, NMM crashes. This happens every time and it has not worked whatsoever.

**Comment by Hault360** [comment]
I'm having the same issue and it's preventing me from fixing an issue I'm having with SkyUI, please does anyone have a solution.

**Comment by DuskDweller** [comment]
Please check here: 
https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/1123
