### ISSUE TITLE
Settings not opening in NMM

### ISSUE THREAD

**Issue by FallenJedi9294** [Nexus-Mods/Nexus-Mod-Manager#1125]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

Everytime i try to open the settings in NMM it crashes my NMM and i have to restart it

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

[TraceLog20210403230608.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6259042/TraceLog20210403230608.txt)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by DuskDweller** [comment]
Check here:
https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/1123
