### ISSUE TITLE
Enderal SE Support

### ISSUE THREAD

**Issue by phoenixfabricio07** [Nexus-Mods/Nexus-Mod-Manager#1126]
Hi, I would like to ask: Can we expect a support for the  Enderal Special Edition ? Now it has a standalone version from Steam.

**Comment by DuskDweller** [comment]
Yes,  already tested it, but I can't tell whether it will be in the next release or you will have to wait a bit more.

**Comment by DuskDweller** [comment]
Added in 0.80.5
