### ISSUE TITLE
NMM still crashing when opening the settings tab after 0.80.5

### ISSUE THREAD

**Issue by LokiTSO** [Nexus-Mods/Nexus-Mod-Manager#1127]
Even after the update, NMM still crashes after pressing the settings button...

- NMM version: 0.80.5
-Win10

[TraceLog](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6266516/TraceLog20210406132047.txt)

**Comment by DuskDweller** [comment]
Check the 0.80.6 hotfix please, it seems it wasn't working on any OS setup.
