### ISSUE TITLE
Cant enter in Enderal Special Edition Game Mode

### ISSUE THREAD

**Issue by phoenixfabricio07** [Nexus-Mods/Nexus-Mod-Manager#1128]
Using NMM 0.80.6, I've just selected the mod folder  and tried to open. I got a message saying it cant initialize..... =/  Do I need to do something else ?  before open, I create a folder in a different HD to be a mod folder. Is there something to do with it ? Is there a way to revert it ? 

![Capturar](https://user-images.githubusercontent.com/81188555/113787247-09d31a00-9711-11eb-8fb3-553d1e287f97.PNG)

**Comment by phoenixfabricio07** [comment]
I found this part in the last tracelog: 

Determining Game Mode: (Requested Mode: enderalspecialedition) enderalspecialedition
Game Mode Factory Selected: Enderal Special Edition (enderalspecialedition)
Creating Game Mode mutex (Attempt: 0)
Could not build game mode!
Exception: 
Message: 
	Unsupported game: Enderal Special Edition (enderalspecialedition)

**Comment by DuskDweller** [comment]
If you were using the previous Enderal and you set the same NMM folders for Enderal Special Edition that's not going to work.
If that's not the case then please attach the full tracelog file.

**Comment by phoenixfabricio07** [comment]
The folder is not the same. Here's the full tracelog

[TraceLog20210406190925.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6267944/TraceLog20210406190925.txt)

**Comment by DuskDweller** [comment]
Are you on the Discord server? We can perform a quick test.

**Comment by phoenixfabricio07** [comment]
I have Discord, Don't use it so much. What can I do to enter in the NNM server ?

**Comment by DuskDweller** [comment]
There's a Discord button on the NMM interface, upper right, you can't miss it

**Comment by phoenixfabricio07** [comment]
ahh ok, I'll do that now!

**Comment by phoenixfabricio07** [comment]
Done! I'm already on the server
