### ISSUE TITLE
NMM 0.80.5 crashes when try to open settings icon

### ISSUE THREAD

**Issue by TKHBMVP** [Nexus-Mods/Nexus-Mod-Manager#1129]
Log:
Tracing an Unhandled Exception:
Exception: 
Message: 
	Die AddShellExtensions-Eigenschaft konnte nicht aus ihrem Standardwert erstellt werden. Fehlermeldung: Fehler im XML-Dokument (2,9).
Full Trace: 
	System.ArgumentException: Die AddShellExtensions-Eigenschaft konnte nicht aus ihrem Standardwert erstellt werden. Fehlermeldung: Fehler im XML-Dokument (2,9).
   bei System.Configuration.SettingsPropertyValue.Deserialize()
   bei System.Configuration.SettingsPropertyValue.get_PropertyValue()
   bei System.Configuration.SettingsBase.get_Item(String propertyName)
   bei System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   bei Nexus.Client.Properties.Settings.get_AddShellExtensions()
   bei Nexus.Client.Settings.OsSettingsGroup.Load()
   bei Nexus.Client.Settings.UI.SettingsForm.set_ViewModel(SettingsFormVM value)
   bei Nexus.Client.MainForm.tsbSettings_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Comment by DuskDweller** [comment]
Already fixed, please download the latest release.
