### ISSUE TITLE
issue with the "Launch EnderalSE" button 

### ISSUE THREAD

**Issue by t3tesla** [Nexus-Mods/Nexus-Mod-Manager#1134]
NMM version: 0.80.7.0
OS: Windows 10 Famille N 64-bit (10.0, Build 19041)

I have installed Enderal SE with Steam.
Steam put two .exe file to launch the game : "skse64_loader.exe" and "Enderal Launcher.exe" in the directory K:\SteamLibrary\steamapps\common\Enderal Special Edition

On NMM, the two buttons "Launch EnderalSE" and "Launch SKSE" dont launch the game as expected.
It seems NMM doesn't use the appropriate name for the .exe files.

Here is the log file: 

Launching EnderalSE (Plain)...
    Command: K:\SteamLibrary\steamapps\common\Enderal Special Edition\EnderalSE Launcher.exe
    Failed:
        System.ComponentModel.Win32Exception (0x80004005): Le fichier spécifié est introuvable

Launching EnderalSE (SKSE)...
       Command: K:\SteamLibrary\steamapps\common\Enderal Special Edition\skse_loader.exe
       SKSE does not appear to be installed.

Of course, the issue disappear if i rename the .exe files.

**Comment by DuskDweller** [comment]
Thanks for the feedback, the launcher issue is fixed in 0.80.8 I just released, the skse one I will fix in the next release.

**Comment by DuskDweller** [comment]
It seems they were both broken somewhere else, I already fixed them but you will have to wait for the next release for a fix.

If you're on the Discord server ping me in the Skyrim channel and I'll send you a fixed installer.

**Comment by t3tesla** [comment]
> It seems they were both broken somewhere else, I already fixed them but you will have to wait for the next release for a fix.
> 
> If you're on the Discord server ping me in the Skyrim channel and I'll send you a fixed installer.

Thanks for your proposition of a fixed installer, but I can wait the next release, this bug is not a big deal.

**Comment by DuskDweller** [comment]
Solved with 0.80.9 .
