### ISSUE TITLE
The Sims 4 - "The Sims 4 Mods Directory" incorrect for german version of the game

### ISSUE THREAD

**Issue by giant0815** [Nexus-Mods/Nexus-Mod-Manager#1135]
NMM v0.80.8 -> Settings -> Tab The Sims 4:

The Selection for "The Sims 4 Mods Directory" always point to the Subfolder "The Sims 4" (or create it, if not exist) regardless, if i point the the correct folder "Die Sims 4" for the german version of the game.

Please fix. Thank you.

**Comment by DuskDweller** [comment]
Localizing a game name is so dumb.

I'll add a fix for the mods directory not acknowledging your edit to the next release, it seems this specific setting is currently only enabled on Witcher 3.

**Comment by DuskDweller** [comment]
If you can join the NMM Discord server I'll send you a test version for this fix.

**Comment by DuskDweller** [comment]
I sent you the installer over Discord.

**Comment by DuskDweller** [comment]
When you're able to, check again please.

**Comment by DuskDweller** [comment]
Solved, with 0.80.9 you can properly switch to your localized folder in the Settings menu for the specific game mode.
