### ISSUE TITLE
All works fine but this one mod does download but never shows (SS2 Extended)

### ISSUE THREAD

**Issue by Ioandar** [Nexus-Mods/Nexus-Mod-Manager#1136]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 

All runs fine, using NMM for ages. 
have many mods added 
But there us 1 mod that does download but never shows up
Oddly it shows version 1.0.11 when it should show 1.0.7

other mods - all fine
Sim Settlements 2 - all fine
SS2 Extended - downloads but never shows...

**Environment**
- NMM version: _0.80.8_
- Mod(s) used: [Sim Settlements 2](https://www.nexusmods.com/fallout4/mods/47976?tab=files) and many more

**To Reproduce**
 _How to reproduce the problem_
every time. since many version. only that file.
download and manual install works fine

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
Fallout 4, never had any problems...
![image](https://user-images.githubusercontent.com/5900479/115121839-1844ef80-9fb5-11eb-9828-cb19a5b9bb8f.png)

**Comment by DuskDweller** [comment]
![image](https://user-images.githubusercontent.com/7575288/115381548-f70e1a00-a1d3-11eb-981c-1b9bdb1ff5a9.png)

I just downloaded it and it seems to work as intended.

**Comment by Ioandar** [comment]
will try now with NMM version 0.80.10

![image](https://user-images.githubusercontent.com/5900479/115548940-58072200-a2a8-11eb-8847-e783379d7948.png)

will report shortly....

![image](https://user-images.githubusercontent.com/5900479/115549953-918c5d00-a2a9-11eb-82c5-0db5d3a82b06.png)

Not There... Only the manually added file. 
![image](https://user-images.githubusercontent.com/5900479/115550055-b254b280-a2a9-11eb-9a74-7f9915f7800d.png)


it shows up in "InstallLog.xml"
`<file path="G:\Game_Tools\Nexus Mod Manager\Fallout4\VirtualInstall\SS2 Extended-47976-1-0-7-1612548416\SS2Extended.esp">
      <installingMods>
        <mod key="5gzhunmg" />
      </installingMods>
    </file>
`
And is "Nexus Mod Manager\Fallout4\Mods"
![image](https://user-images.githubusercontent.com/5900479/115550673-6bb38800-a2aa-11eb-8f7a-044d39b762ed.png)

SSD still has 169GB free and nothing write protected
But since it works for you and nobody else reports anything, it has to be on my side
I am puzzled and out of ideas... All other mods show up normal and all works perfect!

I will backup that drive. remove NNM completely and make re-install it and check again...

I close this topic now because it looks like the problem is on my side only!
Thank you for checking and all the work on the awesome NMM! 
cheers

P.S.: Minor Thing: 
your downloaded SS2Extended shows as v1.0.10 which is the version of SS2 itself. SS2Extended is v1.0.7!
Maybe a nexxus thing because other mods show same version over all their files 
Only the first version is shown corretly
