### ISSUE TITLE
i cant backup, i do have space in my ssd

### ISSUE THREAD

**Issue by nipey17** [Nexus-Mods/Nexus-Mod-Manager#1137]
when i click ok it says right away back up complete then the error
[TraceLog20210420225724.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6344552/TraceLog20210420225724.txt)
![Screenshot (1)](https://user-images.githubusercontent.com/82892659/115419528-fc4b8300-a22c-11eb-86b6-6570972e1091.png)
![Screenshot (2)](https://user-images.githubusercontent.com/82892659/115419537-fe154680-a22c-11eb-8f71-2ddbeeaf092f.png)

**Environment**
- NMM version: 0.80.10.0

**Comment by DuskDweller** [comment]
This will be fixed in the next release (next weekend).

**Comment by DuskDweller** [comment]
Fixed in 0.80.11
