### ISSUE TITLE
Can't disable more than 1 at a time.

### ISSUE THREAD

**Issue by NorokVokun** [Nexus-Mods/Nexus-Mod-Manager#114]
I wanted to disable a bunch of my skyrim mods and because it is arround 60mods i tried to all "mark" them and as i klicked the disable/deactivate button it only worked for the first one but the rest did not get deactivated. Activation of a bunch like that works fine but not disableing them. I tried restarting the NMM and even my PC but it did not help.

Greetings and hope for a bugfix

Norok

ps.: Sorry for my bad english but it is not my native language.

**Comment by squid-box** [comment]
This was fixed by PR #189.
