### ISSUE TITLE
Subnautica and Subnautica: Below Zero Support game support?

### ISSUE THREAD

**Issue by BrandonPotter0** [Nexus-Mods/Nexus-Mod-Manager#1142]
If it hasnt been requested before, Id like to request support for 'Subnautica' and 'Subnautica: Below Zero'

Both games require their own versions of QModManager installed (Much like a Bethesda script extender), but NMM would be writing mods to the 'QMods' folder in the games base directory.

**Comment by DuskDweller** [comment]
Added in 0.80.12
