### ISSUE TITLE
i need your help please for this logiciel

### ISSUE THREAD

**Issue by hmzb2l** [Nexus-Mods/Nexus-Mod-Manager#1146]
hello 
I would like to apologize in advance if this kind of question has already been asked but I have just arrived on the site and I am French so here is my problem I play Dragon's dogma and I would like to know how the software works and how I can use it. I have been advised to use it to replace "arctools" but I can't find any tutorial so basically could you explain to me a little more how this software works please, I don't understand at all how I could use it.

**Comment by DuskDweller** [comment]
You install it, you launch it and set it up, you download a mod from NexusMods it will be automatically handled by NMM if you click on "Download with manager", when it's in your Mods list, you double click on it to activate it.
