### ISSUE TITLE
my mods completely broke my fallout 4 (i fixed 

### ISSUE THREAD

**Issue by CRdog400** [Nexus-Mods/Nexus-Mod-Manager#1147]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
well originally it was my character had some odd texturing now FO4 wont work after i tried everything 

**Environment**
- NMM version: _0.80.11_
- Mod(s) used: _<link to mod(s) on Nexus>_ don't question me please
- https://www.nexusmods.com/fallout4/mods/35117
https://www.nexusmods.com/fallout4/mods/41053
https://www.nexusmods.com/fallout4/mods/2781 
https://www.nexusmods.com/fallout4/mods/50847
https://www.nexusmods.com/fallout4/mods/47728
https://www.nexusmods.com/fallout4/mods/38943
https://www.nexusmods.com/fallout4/mods/47262
https://www.nexusmods.com/fallout4/mods/45174
https://www.nexusmods.com/fallout4/mods/46822
https://www.nexusmods.com/fallout4/mods/41832
https://www.nexusmods.com/fallout4/mods/47396
https://www.nexusmods.com/fallout4/mods/6144
https://www.nexusmods.com/fallout4/mods/23464
https://www.nexusmods.com/fallout4/mods/37535
https://www.nexusmods.com/fallout4/mods/47779
https://www.nexusmods.com/fallout4/mods/48433
https://www.nexusmods.com/fallout4/mods/40666
https://www.nexusmods.com/fallout4/mods/6982
https://www.nexusmods.com/fallout4/mods/44879
https://www.nexusmods.com/fallout4/mods/51615
https://www.nexusmods.com/fallout4/mods/49444
https://www.nexusmods.com/fallout4/mods/11253
https://www.nexusmods.com/fallout4/mods/48748
https://www.nexusmods.com/fallout4/mods/38066
https://www.nexusmods.com/fallout4/mods/49678
https://www.nexusmods.com/fallout4/mods/38120
https://www.nexusmods.com/fallout4/mods/49163
https://www.nexusmods.com/fallout4/mods/36410
https://www.nexusmods.com/fallout4/mods/31965
https://www.nexusmods.com/fallout4/mods/25
https://www.nexusmods.com/fallout4/mods/15
https://www.nexusmods.com/fallout4/mods/50092
https://www.nexusmods.com/fallout4/mods/50309
https://www.nexusmods.com/fallout4/mods/51171
https://www.nexusmods.com/fallout4/mods/19107
https://www.nexusmods.com/fallout4/mods/19108
https://www.nexusmods.com/fallout4/mods/51729
https://www.nexusmods.com/fallout4/mods/33313
https://www.nexusmods.com/fallout4/mods/50520
https://www.nexusmods.com/fallout4/mods/5602
https://www.nexusmods.com/fallout4/mods/6686
https://www.nexusmods.com/fallout4/mods/45932
https://www.nexusmods.com/fallout4/mods/11402
https://www.nexusmods.com/fallout4/mods/50121
https://www.nexusmods.com/fallout4/mods/133
i believe i had the SP sanctuary rebuild cheat mod from bethesda.net
_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
I think it was just the base trace log. I did not notice anything wrong trace log wise  

**To Reproduce**
 _How to reproduce the problem_
download the mods notice there were some character problems disable all mods 
still not fixed. want to strangle yourself because you were having a lot of fun on fallout 4 
contemplate life. rinse and repeat 

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
i used some bethesda.net mods. i think thats about it

**Comment by DuskDweller** [comment]
Sadly this is just to report NMM issues, we can't help you on modding specific games, I might try joining the Discord server and asking in the game section, but I think your request is too specific, better handle it in the NexusMods forum section for Fallout 4.

**Comment by CRdog400** [comment]
> Sadly this is just to report NMM issues, we can't help you on modding specific games, I might try joining the Discord server and asking in the game section, but I think your request is too specific, better handle it in the NexusMods forum section for Fallout 4.

i fixed it 
i originally thought it was something to do with the loader, so i posted it here 
i just replaced some missing files and it worked again 
thx
