### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by Supr3mo00** [Nexus-Mods/Nexus-Mod-Manager#1150]
Hi. I'm having a problem, since last night my NMM won't let me log in to my account and gives me this error
"Not logged in: Network error"
I'm getting worried because it happened out of the blue and I don't understand what is the reason of the problem, so I ask you kindly to give me a hand to solve it.

Version NMM 0.80.12

**Comment by DuskDweller** [comment]
You should check if you're able to log in into NexusMods, since that's what the NMM login does.
If you're still experiencing this issue and you are able to log in on NexusMods then please report back.

**Comment by Supr3mo00** [comment]
Hi. Yes, when I go to the Nexus mod site I am logged in with my account and everything works perfectly, then I open NMM and it gives me the error I showed you, this is very strange. What can I do?

**Comment by DuskDweller** [comment]
On the NMM top bar, on the right click on the button besides the Discord icon, the button to check for NMM updates, let me know what you get.

**Comment by Supr3mo00** [comment]
I did what you asked and got this....
The following updates failed:
Nexus Mod Manager Updater: Could not get version information from the update server.

**Comment by DuskDweller** [comment]
Then it's 100% something blocking NMM, either Windows or your Antivirus/Firewall.
- Try Windows first, go on the NMM executable file, right-click on it, select Properties, if there's a unblock box at the bottom click it, then try again.
- if it's not that, then it's your antivirus/firewall, you have to allow NMM through it, but it changes from software to software, version to version, so I can't guide you through it, you will have to find a guide for your specific av.

**Comment by Supr3mo00** [comment]
I'm currently on NMM exe properties, but I don't understand what you mean by "if there's a unblock box at the bottom click it, then try again"

**Comment by DuskDweller** [comment]
Like this:
![image](https://user-images.githubusercontent.com/7575288/118838150-bdf5c200-b8c5-11eb-9734-71390f15596f.png)

**Comment by Supr3mo00** [comment]
WTF I don't have any of this from me, under attributes there is only an empty space
Oh shit, I guess I have to try with firewall, which I have no idea how to do, because the antivirus I have already disabled it but nothing has changed

**Comment by Supr3mo00** [comment]
hey man, i opened the NMM and this time i got this out
[
![IMG_20210519_175512](https://user-images.githubusercontent.com/84426564/118845308-f6989a00-b8cb-11eb-8666-0ab4d2a4caa3.jpg)
](url)
I clicked on "Authorize" but it gave me "the authentication failed due to a network problem, and then this comes out
![IMG_20210519_175529](https://user-images.githubusercontent.com/84426564/118846004-90f8dd80-b8cc-11eb-9f09-713a34d0f552.jpg)
takes me to the nexus mod site where I go to copy the key to insert, and once added literally does nothing and the NMM remains with "you are not logged in"

**Comment by DuskDweller** [comment]
Does the button to check for NMM updates work?

**Comment by Supr3mo00** [comment]
no, it still doesn't work. I should also add that at the moment I have deactivated the AVG antivirus and manually updated to the latest version of NMM... But now that I think about it, a few days ago I updated my network drivers, they dated back to 2006 the last update LOL, and I wouldn't want that to have anything to do with it....

**Comment by DuskDweller** [comment]
I'm not sure about what is causing the issue, but until that update check button doesn't work it means there's still something blocking NMM. (that button is just checking the new version parameter on a website)

**Comment by Supr3mo00** [comment]
Also looking for help on google I read about how to fix the firewall but I'm not sure I can fix it, because I don't have windows 10 at the moment and I don't have the updates done of windows 7, so I don't know what to do... You say it can't be their problem with the API servers than mine?

**Comment by DuskDweller** [comment]
Wow, you should really think about upgrading to W10 or at least update your Windows 7, it's not safe to keep it outdated, there as so many hacks around that could target it.

**Comment by Supr3mo00** [comment]
yes yes but in fact you're right, I will install windows 10 already this week. Anyway, do you recommend something else to do? I'll close this thread anyway, then maybe open another one if I still need assistance.

**Comment by Supr3mo00** [comment]
however, according to me it is a problem of theirs at this point, I am carrying out every solution that they say from internet and it doesn't work anyway
