### ISSUE TITLE
TraceLog error

### ISSUE THREAD

**Issue by Supr3mo00** [Nexus-Mods/Nexus-Mod-Manager#1155]
I encountered this log file where it says "unable to access deleted object". Can anyone help me? Thanks
[TraceLog20210609235545.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6627425/TraceLog20210609235545.txt)

**Comment by DuskDweller** [comment]
Thanks for the report.
This is a known issue that happens rarely when sorting plugins with external programs but we've yet to find the root cause for it.

**Comment by Supr3mo00** [comment]
I have always ordered my loading orders with LOOT. Anyway, is there a solution to fix this problem?

**Comment by Supr3mo00** [comment]
Two requests for help I made and both times I had to do it myself. Great, great help
