### ISSUE TITLE
Cant Install mods

### ISSUE THREAD

**Issue by Zanderwarpx** [Nexus-Mods/Nexus-Mod-Manager#116]
After i have finished downloading mods. i click to install them and then almost instantly it gives me a error saying that a problem occurred during install, then gives me no information. tends to only happen on bigger mods like SMM and Unofficial skyrim patches. It also occurs on reinstalls.

(This has never happened before.)

**Comment by Ghostwalker71** [comment]
The most likely cause is the mod file has become corrupt, delete the files and download them again.

**Comment by squid-box** [comment]
@Zanderwarpx: Is this still happening with the latest version of NMM?

If so you can probably get more info by hovering the mouse over the error message, it by running NMM in Trace Mode.
