### ISSUE TITLE
Signing in Problem

### ISSUE THREAD

**Issue by sanskeleton67** [Nexus-Mods/Nexus-Mod-Manager#1167]
The bug that i found is related to signing in for the first time. I basically get the wrong email and can't get the 4 digit email to  verify my email adress 
 I tried to download a mod for Jurassic world evolution. I needed to sign in to download it, so i tried creating an account. I inputed my email adress and the site told me to check my emails for an email with a 4 digit code. I checked my email and got a message saying that someone tried creating and account with my email, and asking me if it is me (email screenshot under) but in the email, there was no link to anything, neither that 4 digit code. I tried 4 times, without any improvement. I never created an account on this site, so it shouldn't be a problem. I tried resetting my password but never got an email back.
![Capture d’écran (111)](https://user-images.githubusercontent.com/88739048/128918759-cd91bb7a-fd70-4083-93eb-e3baf11b6633.png)

**Comment by squid-box** [comment]
This repo is for the old Nexus Mod Manager (which Nexus no longer maintains) - for issues with the website please contact Nexus' support instead.

Hope you figure it out! :)
