### ISSUE TITLE
Mod list empty Witcher 3

### ISSUE THREAD

**Issue by chascos69** [Nexus-Mods/Nexus-Mod-Manager#117]
hi
When enter in nexusmod and list is empty...¿???? I try reinstalll, compatibility mode to Win7, admin priveleges, etc..

[sshot-1](https://user-images.githubusercontent.com/4881364/27510530-000442c8-5913-11e7-8767-ea98241c1ed0.gif)

thanks

**Comment by skwerlman** [comment]
it looks like you haven't installed any mods. you have to go to the mod page for each mod you want, and click "Install with Manager"

**Comment by chascos69** [comment]
Yes! Sorry

**Comment by squid-box** [comment]
I'm just going to assume this was actually resolved back in 2017 and close the issue...
