### ISSUE TITLE
owerwrite prompts don't show up anymore

### ISSUE THREAD

**Issue by SiXX92** [Nexus-Mods/Nexus-Mod-Manager#1173]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
nmm doesn't ask if you want to overwrite conflicting files anymore. what happened

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by DuskDweller** [comment]
Fixed in 0.81.1 .

**Comment by SiXX92** [comment]
thanks
