### ISSUE TITLE
NMM crashes when uninstalling/deleting mod after recent update

### ISSUE THREAD

**Issue by leehelck** [Nexus-Mods/Nexus-Mod-Manager#1180]
whenever i try to uninstall or delete a mod i get a popup message about a fatal error. which causes me to restart nmm again. frustrating to no end.

EDIT: here is the trace log.
[TraceLog20211025083817.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7413482/TraceLog20211025083817.txt)

**Comment by DuskDweller** [comment]
Please read the crash window and do as it says (namely, pick the generated tracelog file from your HD and upload it here).

**Comment by skyrimmodder** [comment]
I'm getting the same error.  Tracelog attached.

[TraceLog20211025054431.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7410135/TraceLog20211025054431.txt)

**Comment by DuskDweller** [comment]
I can't replicate the issue but I made sure it won't happen anyway.

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.82.1

**Comment by skyrimmodder** [comment]
It's no longer happening for me.  Thanks very much.

**Comment by Lkalter** [comment]
The same here 
[TraceLog20211025102557.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7410716/TraceLog20211025102557.txt)
-

**Comment by Lkalter** [comment]
> ## O mesmo aqui
> [TraceLog20211025102557.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7410716/TraceLog20211025102557.txt)

I've seen the solution sorry
