### ISSUE TITLE
Newly installed NMM crashes after clicking "Settings" button

### ISSUE THREAD

**Issue by metabyte144** [Nexus-Mods/Nexus-Mod-Manager#1182]
**Describe the bug** 
NMN crashes after clicking the Settings button. This happens after it's freshly installed with nothing done so far (was just following a NMM guide). This only happens with the 0.82 version (I've tested it with the 0.81.1 version and it worked fine)

**Environment**
- NMM version: 0.82.1
- Mod(s) used: none (just installed)
My PC is Win 8.1 (current patch level)

**To Reproduce**
Install NMM, Start NMM, Click the Settings button -> crash

**Trace** 
Trace file has been created: TraceLog20211026110315.txt
Mod Manager Version: 0.82.1.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Games\SkyrimMod\NMM\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BaldursGate3.dll
        Initializing: Nexus.Client.Games.BaldursGate3.BaldursGate3GameModeFactory
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: Cyberpunk2077.dll
        Initializing: Nexus.Client.Games.Cyberpunk2077.Cyberpunk2077GameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: EnderalSE.dll
        Initializing: Nexus.Client.Games.EnderalSE.EnderalSEGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: MonsterHunterWorld.dll
        Initializing: Nexus.Client.Games.MonsterHunterWorld.MonsterHunterWorldGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: MountAndBlade2Bannerlord.dll
        Initializing: Nexus.Client.Games.MountAndBlade2Bannerlord.MountAndBlade2BannerlordGameModeFactory
    Checking: Newtonsoft.Json.dll
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Sims4.dll
        Initializing: Nexus.Client.Games.Sims4.Sims4GameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StardewValley.dll
        Initializing: Nexus.Client.Games.StardewValley.StardewValleyGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: Subnautica.dll
        Initializing: Nexus.Client.Games.Subnautica.SubnauticaGameModeFactory
    Checking: SubnauticaBelowZero.dll
        Initializing: Nexus.Client.Games.SubnauticaBelowZero.SubnauticaBelowZeroGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load C:\Games\SkyrimMod\NMM\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) SkyrimSE
Game Mode Factory Selected: Skyrim Special Edition (SkyrimSE)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim Special Edition (SkyrimSE)
    Installation Path: C:\Games\SkyrimMod\Skyrim Special Edition
    Install Info Path: C:\Games\SkyrimMod\Mods\Install Info
    Mod Path: C:\Games\SkyrimMod\Mods
    Mod Cache Path: C:\Games\SkyrimMod\Mods\cache
    Mod Download Cache: C:\Games\SkyrimMod\Mods\downloads
    Overwrite Path: C:\Games\SkyrimMod\Mods\Install Info\overwrites
    Virtual Install Path: C:\Games\SkyrimMod\NMM\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Games\SkyrimMod\NMM\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Games\SkyrimMod\NMM\GameModes
            Checking: SkyrimSE.CSharpScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.CSharpScript.SkyrimSECSharpScriptType
            Checking: SkyrimSE.XmlScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.XmlScript.SkyrimSEXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Games\SkyrimMod\NMM\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: C:\Games\SkyrimMod\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\SkyrimMod\Mods\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Games\SkyrimMod\Skyrim Special Edition\Data
                Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dawnguard.esm
                Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dragonborn.esm
                Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\HearthFires.esm
                Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Skyrim.esm
                Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Update.esm
            Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dawnguard.esm
                Registered.
            Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dragonborn.esm
                Registered.
            Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\HearthFires.esm
                Registered.
            Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Skyrim.esm
                Registered.
            Found: C:\Games\SkyrimMod\Skyrim Special Edition\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Games\SkyrimMod\Skyrim Special Edition\Data\Skyrim.esm (IsNull=False)
            Loading C:\Games\SkyrimMod\Skyrim Special Edition\Data\Update.esm (IsNull=False)
            Loading C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dawnguard.esm (IsNull=False)
            Loading C:\Games\SkyrimMod\Skyrim Special Edition\Data\HearthFires.esm (IsNull=False)
            Loading C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dragonborn.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Games\SkyrimMod\Skyrim Special Edition\SkyrimSE.exe (IsNull=False)
    SKSE Command: C:\Games\SkyrimMod\Skyrim Special Edition\skse64_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command: C:\Games\Tools\LOOT\LOOT.exe (IsNull=False)
    Wrye Bash Command:  (IsNull=False)
    SSEEdit Command:  (IsNull=False)
    SSEEditQuickAutoClean Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    Nemesis Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (C:\Games\SkyrimMod\Skyrim Special Edition\Data\Skyrim.esm) (False)
    Loading: Update.esm (C:\Games\SkyrimMod\Skyrim Special Edition\Data\Update.esm) (False)
    Loading: Dawnguard.esm (C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dawnguard.esm) (False)
    Loading: HearthFires.esm (C:\Games\SkyrimMod\Skyrim Special Edition\Data\HearthFires.esm) (False)
    Loading: Dragonborn.esm (C:\Games\SkyrimMod\Skyrim Special Edition\Data\Dragonborn.esm) (False)
Setting up listener on Nexus Mod Manager-SkyrimSEIpcServer/SkyrimSEListener at 2021-10-26 11:03:19
Running Application.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.Settings.OsSettingsGroup.Load()
   at Nexus.Client.Settings.UI.SettingsForm.set_ViewModel(SettingsFormVM value)
   at Nexus.Client.MainForm.tsbSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Comment by DuskDweller** [comment]
I no longer need any tracelog or config file for this issue.

**Comment by tangodown18** [comment]
[TraceLog20211027214517.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7430370/TraceLog20211027214517.txt)

Having the exact same issue here. On Win 11 though so may not be of much help. 
NMM ver. 0.82.1
Just have SKY UI installed so far

(Changed user.config to .txt as Git would not take the .config file)

**Comment by Adefor** [comment]
hi, i'm having the same problem, Win 8.1, NMM ver 0.82.1 and no mods installed.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Riferimento a un oggetto non impostato su un'istanza di oggetto.
Full Trace: 
	System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in Nexus.Client.Settings.OsSettingsGroup.Load()
   in Nexus.Client.Settings.UI.SettingsForm.set_ViewModel(SettingsFormVM value)
   in Nexus.Client.MainForm.tsbSettings_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.NativeWind

**Comment by DuskDweller** [comment]
> 
> 
> [TraceLog20211027214517.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7430370/TraceLog20211027214517.txt) [user - Copy.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7430381/user.-.Copy.txt)
> 
> Having the exact same issue here. On Win 11 though so may not be of much help. NMM ver. 0.82.1 Just have SKY UI installed so far
> 
> (Changed user.config to .txt as Git would not take the .config file)

Thanks I should be able to fix this later today.

**Comment by jordialdeguer** [comment]
I have suffered the same isue

[TraceLog20211029094440.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7439937/TraceLog20211029094440.txt)

Changed to txt file to bypass to github rejecting it

**Comment by DuskDweller** [comment]
Is any of you on the NMM Discord?
I can't replicate the issue but I think I found what could cause it, I wanted to share with one of you a test build to check whether it's fixed or not.

**Comment by OldGamerDarthy** [comment]
Hello, on the version 0.81.1.0 same problem, after click settings imediate crash, i add log, please fix :)
[TraceLog20211029201054.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7446078/TraceLog20211029201054.txt)
[TraceLog20211030100621.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7446079/TraceLog20211030100621.txt)

**Comment by DuskDweller** [comment]
Release 0.83.0 should fix your issue, if it doesn't please join the NMM Discord so we can perform some real-time testing.

**Comment by Adefor** [comment]
Hi, i've just updated NMM but i've found the same error  after ckliking the setting button. So i proceed to delete NMM and installing again, just to be sure, and then the same error occured. Sorry for my poor english
[tracelog 2.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/7446527/tracelog.2.txt)
d.

**Comment by DuskDweller** [comment]
I no longer need any Tracelog file or user config file. I just need one of you to join the Discord server here: 
https://discord.gg/JZ4tZ5KFQX
So we can perform some realtime testing.

**Comment by Adefor** [comment]
With 0.83.1 release the error is gone.

**Comment by DuskDweller** [comment]
Thanks for the feedback!
