### ISSUE TITLE
1ST TIME BANNED BY MISTAKE need to appeal

### ISSUE THREAD

**Issue by Cullam89** [Nexus-Mods/Nexus-Mod-Manager#1217]
I WAS TOLD TO VISIT HERE to try to get an appeal  BANNED ACCOUNT RENEWAL FOR -   CULLAM89
hoping i can get my account back by trying to reach out and get in touch with 3 moderator approval of re-instatement..
a way of getting my account back...    i was banned by mistake.    
1st attempt wasnt on purpose someone took it offensive and reported me and i didnt think an image upload can make someone so mad
IM STILL LEARNING THIS SITE RULES...   IM NEW..    not even a few months in and having a nice time..   BOOM..   BAN FOR PIRACY..

i said no wayyy...   HOW...   i only upload image ideas...  that make ppl say whoa that is awesome. and wish id have thought of that everyone is entitled of trying to make themselves look good..   but the thought of someone stomping on my hard work and enjoyment... 
it hurts..    sure whoever is reading this  doesnt want that happening to them.. i wasnt meaning anything by it..
-------------------
hope to hear back from someone soon..   i want back into my account again...

**Comment by DuskDweller** [comment]
I'm sure nobody told you to visit here, since this is the Github issue board for Nexus Mod Manager that is no longer supported by NexusMods.

**Comment by Cullam89** [comment]
wait a sec....     how do i get in contact with whoever can reinstate my account...    the rule page said visit here to get an appeal...   thats what im doing

**Comment by DuskDweller** [comment]
No it doesn't.
Please stop commenting here, this issue board is in no way affiliated with NexusMods.

https://help.nexusmods.com/article/33-what-can-i-do-if-my-account-has-been-banned

**Comment by Cullam89** [comment]
im exactly where i need to be....   i was banned from nexusmods...    they are the ones who can reinstate me

**Comment by Cullam89** [comment]
i keep getting that link sent to me...   there is noone answering that gmail support@nexus.     ive spent 7 messeges no response i meant

**Comment by Cullam89** [comment]
nevermind if you gonna be an ass...    dont reply back here...   THIS IS BS..
