### ISSUE TITLE
Can no longer open NMM.

### ISSUE THREAD

**Issue by jenders97** [Nexus-Mods/Nexus-Mod-Manager#124]
I use NMM for FO4 and Skyrim. I have a bunch of mods managed by NMM for both. I had a system crash while trying to open FO4, with F4SE, and now I can't open NMM at all. I've tried rebooting and reinstalling, but neither worked. I attached two error logs from the event viewer that happen anytime I try opening it. Any help would be greatly appreciated.
   
[Error 1.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1123147/Error.1.txt)
[Error 2.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1123148/Error.2.txt)

**Comment by jenders97** [comment]
I did a system restore and that fixed it. I must have had a corrupted system file or something.

**Comment by jenders97** [comment]
It happened again. I opened FO4, which crashed the same way as it had earlier. I had to do a hard shut down and after that I couldn't open NMM again. Doing a system restore fixed it again.

**Comment by squid-box** [comment]
It looks like the application settings file is corrupted in the crash. In 0.65.5 NMM can now handle this (to an extent), from PR #339.
