### ISSUE TITLE
dont start skyrim se

### ISSUE THREAD

**Issue by bank3r** [Nexus-Mods/Nexus-Mod-Manager#125]
if i start nexus mod manager, i can choose skyrim or fallout 4. fallout 4 works normal. if i choose skyrim se, it loads infinitely. its load only to the half of the n at "nexus". it used my cpu, but nothing happens. i waited a hour. sry for my bad english.

**Comment by papc67** [comment]
exactly same problem

**Comment by squid-box** [comment]
Is this still a problem for you with the latest NMM? If so could you grab some trace logs from when this is happening? See [this page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#how-to-collect-information) on how to do this.

**Comment by squid-box** [comment]
With no reply in over a month I'm closing the issue
