### ISSUE TITLE
NMM resorts to the old (non-asterisk) format of Plugins.txt if Fallout4.exe is a renamed F4SE executable

### ISSUE THREAD

**Issue by alexpolozov** [Nexus-Mods/Nexus-Mod-Manager#126]
Hi. I have the latest NMM (0.63.14), F4SE, and Fallout 4.  
Recently, I had to perform [a trick with renaming f4se_loader.exe to Fallout4.exe](https://steamcommunity.com/sharedfiles/filedetails/?id=682660057) to enable launching F4SE directly from Steam (without that, Fallout would not work with my controller correctly). However, it broke NMM's mod management. Now it tries to track the mods in my `Plugins.txt` in the old style (with just the names of the active mods), as opposed to the new style (with `*` in front of the active mods). 

Needless to say, it now does exactly the opposite of what it needs to do to maintain the mods, and I have to keep track of the asterisks manually in the file. Before the renaming, everything worked flawlessly.

I see from the source code that `GameMode.GameVersion` for Fallout 4 is detected from its executable (which, in turn, causes my problem when the management mode is decided in [PluginOrderManager.cs](https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/1744e84aa1ee1e762d48022fddfb92e317b8a90d/GamebryoBase/PluginManagement/LoadOrderManager/PluginOrderManager.cs#L288)). Is there perhaps some other source that would store the version, maybe somewhere in the registry or config files?

**Comment by DuskDweller** [comment]
That's because NMM checks the FO4 exe version to decide how to handle fo4 plugins.

**Comment by alexpolozov** [comment]
Yes, I explained that in the issue. I am asking if there exists some other source whence NMM can get the version info instead of `Fallout4.exe`.

**Comment by DuskDweller** [comment]
You should change the NMM source code to address your issue.

**Comment by DuskDweller** [comment]
I felt so amazing this morning that I decided to fix your issue, you owe me a pizza 😄 
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.63.15

**Comment by alexpolozov** [comment]
@DuskDweller Works, thanks! If you're ever in Seattle, drop me a line 🙂
