### ISSUE TITLE
The Nexus won't let me download some mods

### ISSUE THREAD

**Issue by mathues123** [Nexus-Mods/Nexus-Mod-Manager#128]
I've tried to download some mods before and i get this error message saying that NMM doesn't support SSE, but i don't have SSE installed on my pc.

**Comment by squid-box** [comment]
It's the mod you're trying to download made for Skyrim SE?

Is this still a problem for you with the latest NMM? If so could you grab some trace logs from when this is happening? See [this page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#how-to-collect-information) on how to do this.

**Comment by squid-box** [comment]
With no reply for a month, I'm assuming my question above is the cause for this, and I'm closing the issue.
