### ISSUE TITLE
84.6 won't recognise I don't have Skyrim GOG, so it won't let me download Mods, it just keeps asking me to rescan my Games instead

### ISSUE THREAD

**Issue by RoaanHorrigan** [Nexus-Mods/Nexus-Mod-Manager#1284]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by RoaanHorrigan** [comment]
The latest NMM update 0.84.6 will not let me install Mods via Mod Manager Download, it is telling me I must rescan my Games as it cannot find Skyrim GOG, I rescanned hoping it would recognise I do not have GOG, I have SkyrimSE, but it still will not let me download via the Mod Manager Download, it continues to insist I scan again for GOG. Is there a way I can roll back to the previous version of NMM please?

**Comment by redim1709** [comment]
I have the same problem

**Comment by DuskDweller** [comment]
Just fixed it!
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.84.7

**Comment by redim1709** [comment]
Updated, same error

**Comment by DuskDweller** [comment]
You should open NMM by yourself (not by clicking on a mod download) and change the Skyrim download mode if it's not set to Skyrim SE (you can check what's written at the bottom).

Anyway I released 0.84.8 that will automatically fix it for you.

**Comment by DuskDweller** [comment]
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.84.8

**Comment by redim1709** [comment]
You were able to fix it! Thank's man!

**Comment by RoaanHorrigan** [comment]
Thank you :)
