### ISSUE TITLE
add support for starfield

### ISSUE THREAD

**Issue by commanderdarkkirby** [Nexus-Mods/Nexus-Mod-Manager#1295]
any chance you can add in support for starfield so we can install mods using this mod manager?

**Comment by TylerCode** [comment]
I've only made some smaller contributions to this repo so take this with a grain of salt:

I'm not against this happening but I do want to point out that Starfield and [Vortex](https://github.com/Nexus-Mods/Vortex) have the same supported OS requirements so I'm not sure what the value of NMM getting Starfield would be. 

Roast me if I'm missing something though. 

Edit: I guess BG3 is the same case, fair.

**Comment by Shanthetrickster** [comment]
> I've only made some smaller contributions to this repo so take this with a grain of salt:
> 
> I'm not against this happening but I do want to point out that Starfield and [Vortex](https://github.com/Nexus-Mods/Vortex) have the same supported OS requirements so I'm not sure what the value of NMM getting Starfield would be.
> 
> Roast me if I'm missing something though.
> 
> Edit: I guess BG3 is the same case, fair.

I cannot speak for the OP but for me, Vortex is kinda garbage.

**Comment by susistuart** [comment]
Thanks for the contributions, Tyler, but if we wanted to use Vortex instead of NMM, I think we would have all done that by now.

**Comment by commanderdarkkirby** [comment]
to be honest, i tired using vortex once and it was kind of complicated and was missing some features that NMM had. i prefer NMM since its simpler to use.

**Comment by TylerCode** [comment]
> Thanks for the contributions, Tyler, but if we wanted to use Vortex instead of NMM, I think we would have all done that by now.

Fair, I'll be honest my understanding up until this issue was that the only people who used NMM were people with older/less powerful PCs and/or people who are using it to mod older games.

**Comment by commanderdarkkirby** [comment]
looks like starfield support is now out so i'm closing this
