### ISSUE TITLE
Issues with Storage Spaces / ReFS

### ISSUE THREAD

**Issue by lamharry** [Nexus-Mods/Nexus-Mod-Manager#131]
NMM encounters issues when the game install is on Storage Spaces, which uses ReFS as the file system. Mods aren't properly installed and unexpected behavior occurs within games.

This may be due to the lack of hard link support on the file system. There is a related issue with FAT/exFat:

https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/19

The big issue is that there is no warning alerting users of this issue.

**Comment by squid-box** [comment]
With 0.65.5 (PR #331) there's now a check when scanning for games to see if it's installed on an incompatible file system. I doubt anyone will put in the effort of providing an alternative way of installing mods for these special cases, so I'm closing this issue now.

Please create a feature request if you really think someone should implement an alternative.
