### ISSUE TITLE
Vaildating API Key error at start NMM

### ISSUE THREAD

**Issue by giant0815** [Nexus-Mods/Nexus-Mod-Manager#1334]
When i start nmm, it shows at the bottom line "Vaildating API Key". After a few seconds it shows "Not logged in: Status "Unkown".

**Environment**
- NMM version: 0.87.0

**Comment by DuskDweller** [comment]
![image](https://github.com/Nexus-Mods/Nexus-Mod-Manager/assets/7575288/b49c235b-25aa-4688-9c0c-4edead662a47)

**Comment by DuskDweller** [comment]
https://nexusmods.statuspage.io/

**Comment by giant0815** [comment]
Sorry, i did know this. Everything ist working fine again. Thanks
