### ISSUE TITLE
"Error: Stack empty" on only a few mods

### ISSUE THREAD

**Issue by rad666a** [Nexus-Mods/Nexus-Mod-Manager#1348]
NMM version 87.4
OS: Windows 10

I took a step away from gaming awhile back and now I am back and updating my Starfield mods. I downloaded many (20+) mods and was in the process of installing them, when I get this error when attempting to add the mod to the NMM's mod list on seven of them (single example included for brevity, all look the same):

Error registering this mod: [insert file name here]Error: Stack empty. 

Closing and restarting NMM results in a dialog box appearing with the following (again, single example)

Error loading the following mods:
[mod file path]

Deleting the mod file from NMM's mod folder removes dialog error message. 

I have tried redownloading the files, as well as not changing the format (zip/rar to 7zip) or renaming the files (both of which I do habitually). The only things the files have in common is the source, Nexus Mods, and type, SFSE mods. I don't think the SFSE thing matters, since other SFSE mods added/installed fine (one example that does not work is "Address Library for SFSE Mods v1.7"). 

Like I stated above, I installed may mods, and they worked fine, just a few threw the error and I am at a loss as to what is going on.

**Comment by DuskDweller** [comment]
Fixed in 0.87.5 !

**Comment by rad666a** [comment]
That was FAST! 

Thank you so much!

Confirmed as fixed in 87.5.
