### ISSUE TITLE
Timeout! Cannot reach login server

### ISSUE THREAD

**Issue by racaholic** [Nexus-Mods/Nexus-Mod-Manager#136]
I've been having this issue for months, I'm using the latest version and have redownloaded and installed it about a dozen times.  Some of the things I've tried include: 
I've reinstalled multiple times.
Updated Windows 10 and .net Framework.
Double checked my firewall settings, even tried disabling my firewall.
I'm running it as administrator.
I enabled literally every available permission for NMM. 
I've uninstalled it, ran a registry cleaner, rebooted and reinstalled it again.

**Comment by racaholic** [comment]
Resolved - I was shocked that it was a firewall related issue in the end after I had tried multiple times turning off the firewall completely.  The solution was making an outbound rule in advanced firewall settings - which didn't initially appear to work on the first try - but then I restarted my PC and it worked after that.

**Comment by squid-box** [comment]
Closing issue as it seems to have been resolved.
