### ISSUE TITLE
Ive tried countless things but still same problem with login

### ISSUE THREAD

**Issue by CannibalTF** [Nexus-Mods/Nexus-Mod-Manager#141]
I cant log in everytime i try it comes up with this message: nexus mods Your password is working on our forums but not on the website? You can try to change your password or have a look at this help thread.  Sorry for the inconvenience!

then when i try to change my password i follow it step by step then this message appears: Oops! something went wrong! the validation key you supplied to recet your password does not appear to be valid. any suggestions on how to fix? please help

ive tried clearing my browser cache, using a different browser and making a new account but even then i got the same problem

**Comment by squid-box** [comment]
Am I understanding this correctly that you're having troubles logging in on the website? If so you'll have to ask on the Nexus forums, this repo is for the Nexus Mod Manager - we can't really help to with website problems.

**Comment by squid-box** [comment]
After a week with no reply, I'm closing this issue.
