### ISSUE TITLE
Mod Load error: ApachiiSkyHair_v_1_6_Full

### ISSUE THREAD

**Issue by ray792** [Nexus-Mods/Nexus-Mod-Manager#144]
NMM gives this error 

Error registering this mod: ApachiiSkyHair_v_1_6_Full-10168-1-6-Full
Error: String was not recognized as a valid Boolean. 

was working just fine till recently

**Comment by squid-box** [comment]
It's this still happening for you, with the latest version of NMM?

Please add some more information from when this problem occurs (see [this page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#how-to-collect-information).

**Comment by squid-box** [comment]
No reply in a month, closing the issue.
