### ISSUE TITLE
7 ZipSharp Bug

### ISSUE THREAD

**Issue by Unzoned9** [Nexus-Mods/Nexus-Mod-Manager#149]
I uninstalled a  Clothing mod for fallout 4 on the Nexus Mod Manager and when i tried to reinstall it and activate it, I got a pop up saying that there was a 7 Zipsharp Bug. I do not know how to fix this i was wearing the clothes in game when i uninstalled the mod i do not know if that has anything to do with it. Please help me if ypu can.

**Comment by Arefu** [comment]
Screenshots?

**Comment by squid-box** [comment]
With no response for 5+ months, I'm closing the issue.
