### ISSUE TITLE
NMM doesn't recognise Fallout 4 DLC plugins as hardcoded to be always active

### ISSUE THREAD

**Issue by Ortham** [Nexus-Mods/Nexus-Mod-Manager#15]
This was discovered by @pStyl3 while debugging a reported crash with the new version of LOOT (full conversation so far is posts #91 to #103 [here](http://forums.bethsoft.com/topic/1611336-rel-loot-thread-26/?p=25264226)). 

The FO4 master file and DLC plugins are all hardcoded to always be active and always load first (if present, in the case of the DLC plugins), but NMM doesn't seem to know this and so if a DLC plugin is not marked as active in `plugins.txt`, it gets displayed as inactive. pStyl3 specifically reported it happening for the Nukaworld plugin, I don't know if it's just that one or any DLC plugin.

**Comment by DuskDweller** [comment]
Thanks for the report, it looks like we forgot to add the DLCNukaWorld entry to the official plugin list inside NMM!

**Comment by DuskDweller** [comment]
Fixed for the next release (we also added the new management we're using for Skyrim SE to Fallout 4).
