### ISSUE TITLE
ESL Support

### ISSUE THREAD

**Issue by danielnichols** [Nexus-Mods/Nexus-Mod-Manager#152]
Since the new .esl format has been introduced for Fallout 4 and soon Skyrim: SE, it is my understanding that NMM will not support these files without some changes.

**Comment by jbostrus** [comment]
I got tired of waiting so I made changes myself. I just submitted a pull request. Hopefully it'll be recognized and resolved soon.

**Comment by squid-box** [comment]
This was included with PR #168.
