### ISSUE TITLE
SLOW download

### ISSUE THREAD

**Issue by grefsrun** [Nexus-Mods/Nexus-Mod-Manager#154]
I'm only getting 1-5kb/s
![nmm](https://user-images.githubusercontent.com/31707490/30129760-4757760e-9347-11e7-8165-7fcb5e2b9ea0.png)

Ran Nexus Download Diagnoser and got these results:
--------------------------------------------------------------------------------
Proxy detected: none
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Diagnosing http://filedelivery.nexusmods.com/1/2/256MB-1-0-1.rar?ttl=2147483647&setec=94cadea35b83be28c03f37ee675c2373
--------------------------------------------------------------------------------
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
CF-RAY: 39a3af2c62ba4267-OSL
Content-Type: text/html
Date: Wed, 06 Sep 2017 19:02:43 GMT
Last-Modified: Thu, 12 Jan 2017 16:54:50 GMT
Set-Cookie: __cfduid=dcef3600f00b03283d99699f0b7f857b31504724563; expires=Thu, 06-Sep-18 19:02:43 GMT; path=/; domain=.nexusmods.com; HttpOnly
Server: cloudflare-nginx
Status Description: OK.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Expected size was: -1,0 B.
Downloaded 1,2 KB in 1 seconds.
Calculated speed: 1,2 KB/s.
Maximum instant speed reached: 0 B/s
--------------------------------------------------------------------------------

**Comment by Arefu** [comment]
http://www.speedtest.net/#

Post screenshot of results.

**Comment by squid-box** [comment]
After 4 months without a reply, this seems to no longer be an issue. I'm closing this.
