### ISSUE TITLE
Cannot run Skyrim SE with SKSE64 through NMM(version 0.63.14)

### ISSUE THREAD

**Issue by KagurazakaNyaa** [Nexus-Mods/Nexus-Mod-Manager#158]
NMM can run Skyrim with SKSE, but cannot run SKSE64 alpha
![image](https://user-images.githubusercontent.com/7751303/30780686-7cfed19e-a143-11e7-9f95-64be5afeaab3.png)

**Comment by BernardoCBranco** [comment]
This was apparently fixed in https://github.com/Nexus-Mods/Nexus-Mod-Manager/commit/4d57dfa4bfe2559fc199bda1122a4a016b8b5f66 but you'll have to compile it yourself as there's not a new release with the fix.
