### ISSUE TITLE
Crash on launch attempt

### ISSUE THREAD

**Issue by Chaython** [Nexus-Mods/Nexus-Mod-Manager#164]
Nexus mod manager is not set up to work with skyrim special edition if skyrim special edition is installed rescan for installed games from the change game toolbar item
As it was previously set as the default game, there's no option to use the change game toolbar option as the default client doesn't launch.

**Comment by jokermatt999** [comment]
Confirming I had the same issue. If the game set to launch by default is uninstalled, or games are rescanned without confirming that game, it just gives an error message and closes.

Suggestion to fix? Bring up the list of installed games (Games Selection menu) to select from instead. 

Edit: confirmed it happens even if the directory is just found but not confirmed.

**Comment by squid-box** [comment]
PR #483 will change it so that if the default game mode is not installed (scanned and confirmed by NMM) it will clear the default game mode setting and show the game mode selection menu instead.

Hopefully included in whatever version comes after 0.65.8.

**Comment by squid-box** [comment]
Released in [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9).
