### ISSUE TITLE
Dragon Age Setup issue

### ISSUE THREAD

**Issue by MasterZoen** [Nexus-Mods/Nexus-Mod-Manager#165]
When trying to setup Nexus Mod Manager for Dragon Age, it defaults the various directories to the C: drive. When I try to change the fields to point to D: drive where all my mods are located it refuses to finish and a little exclamation mark shows the following when I hover the mouse over it:

"You MUST set the Virtual Directory on the same HD as the usual mod install folder: Selected HD: D:\ - Expected HD: C:\"

I don't want ANYTHING installing to C:\ drive, so how do I bypass this?

**Comment by squid-box** [comment]
Do you have your games installed on C: or D: ?

Does this happen with other games as well, or only Dragon Age?

**Comment by squid-box** [comment]
Dragon Age stores its mod files on C: , so you're stuck putting the virtual install folder on C:.
