### ISSUE TITLE
Nexus Mod manager Download Error

### ISSUE THREAD

**Issue by afyilmaz09** [Nexus-Mods/Nexus-Mod-Manager#167]
2 days ago , I got a error when I was downloading mod . its " filename+cant be added -size - incomp."

 How can I fix that

**Comment by Ghostwalker71** [comment]
I believe that error is caused by a corrupted download, delete the file and download it again.

**Comment by squid-box** [comment]
@afyilmaz09: is this still a problem? 

If so could you provide a trace log from the error, and/or the file you're trying to add?

**Comment by afyilmaz09** [comment]
I've fixed . thanks

2018-05-24 22:32 GMT+03:00 Joel Ahlgren <notifications@github.com>:

**Comment by squid-box** [comment]
Good to hear, then I'm closing this issue :)
