### ISSUE TITLE
Cannot sort any mods in 0.67.17 if CC ESLs are present.

### ISSUE THREAD

**Issue by jbostrus** [Nexus-Mods/Nexus-Mod-Manager#177]
This problem appears to have came up because I originally had the CC ESLs being put directly after ESMs but before custom ESLs because the in game manager displays 3rd party ESLs after ESMs before ESPs. The logic check in GamebryoPluginOrderValidator.ValidateOrder() checks that no ESMs come after ESLs of any kind. Since CC ESLs are now in an unmanaged list which gets put at the top before ESMs this causes the validation to fail resulting in the inability to change any sorting. Removing that check allows it to work correctly for the most part but also allows changing the load order of the unmanaged DLCs and CC ESLs which shouldn't be possible.

**Comment by calscks** [comment]
additionally, the OFFICIAL_UNMANAGED_PLUGINS is missing the ccbgsfo4023-powerarmorskin(camo02).esl which is the CAMO paint for PA.

I also have to remove the check for booIsPreviousLightMaster && plgPlugin.IsMaster && !plgPlugin.IsLightMaster too else sorting will not work. is there any possible solution to fix it? like making two sets of unmanaged plugin lists?

**Comment by ousnius** [comment]
You should now be reading the new Fallout4.ccc or Skyrim.ccc files in the root folder of the games to detect the CC ESL archives instead of a hardcoded list.

**Comment by calscks** [comment]
sure, but how do you get the installation path of the game's root folder? been searching around the source code to no avail,.

EDIT: nevermind, found the attribute for it.

**Comment by squid-box** [comment]
Grab [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), and you should have no problems reordering your plugins, even with .esl's present.
