### ISSUE TITLE
Error or Support for FAT/ExFAT

### ISSUE THREAD

**Issue by Haravikk** [Nexus-Mods/Nexus-Mod-Manager#19]
When I installed Nexus Mod Manager I didn't realise that it didn't support FAT/ExFAT, or I believe, any file-system without symbolic linking support.

Understandable I suppose, except that NMM gives no indication of this; in fact I happily downloaded and activated a bunch of mods, but only realised something was wrong when I restarted NMM and found some mods were deactivated, and later when running LOOT found that some had missing animation files (and in fact hadn't been installed at all). I've since switched to NTFS for my games partition, which has resolved the problem.

I'd like to recommend the following tweaks:

* A warning dialogue when a game is located on a volume that doesn't support links.
* Detection of linking errors during installation, as NMM should not report mods as successfully installed when they're not (and linking occurs can still occur on NTFS if the file-system is full, read-only etc.).

Now the actual behaviour is debatable; the obvious would be to simply tell the user that NMM can't be used on unsupported file-systems, however, I'd personally like to see copying used as a fallback if possible, with a warning instead informing the user this will happen (i.e- installing on an unsupported file system will waste more space). But since I don't know anything about the internals I don't how feasible copying would be to implement, hopefully someone who knows can comment!

Either way I think something needs to be done to make users aware of this potential issue; it should be easy enough to test whether a file-system supports symbolic links during the setup process I think?

**Comment by squid-box** [comment]
With 0.65.5 (PR #331) there's now a check when scanning for games to see if it's installed on an incompatible file system. I doubt anyone will put in the effort of providing an alternative way of installing mods for these special cases, so I'm closing this issue now.

Please create a feature request if you really think someone should implement an alternative.
