### ISSUE TITLE
Instant crashing

### ISSUE THREAD

**Issue by zpocalypse** [Nexus-Mods/Nexus-Mod-Manager#195]
![bug](https://user-images.githubusercontent.com/33883697/33105009-fc830e20-cedf-11e7-8410-b41f9c9eea85.png)
I just got back into playing fallout and modding, and downloaded the Unofficial Fallout Patch. after it appeared in my mod menu on NMM, i tried clicking on it. NMM crashed immediately. i can't select it, let alone install it, or delete it. whenever i click on it or highlight it using the arrow keys, NMM crashes immediately. I am able to click on/highlight other mods, along with installing/uninstalling.

**Comment by Arefu** [comment]
Do you have the crashlog from C:\Users\<USER>\Documents\Nexus Mod Manager you can post? They should be called Tracelog<DATE>.txt

**Comment by squid-box** [comment]
@zpocalypse: Please attach the file asked for in the previous comment, or I'll assume this is no longer a problem.
