### ISSUE TITLE
Instant Crash (Skyrim)

### ISSUE THREAD

**Issue by SirScrubL0rd** [Nexus-Mods/Nexus-Mod-Manager#197]
I only have 2 mods in my profile and when I launch the game from the Mod Manager it gets passed the Bethesda screen and then instantly crashed. I tried restarting the Manager and my computer and nothing worked so far.

**Comment by Arefu** [comment]
This doesn't seem like an NMM issue, it sounds like your mods are missing dependencies. Look into LOOT and check the pages of the mods for any requirements.
