### ISSUE TITLE
Fallout 3 GOTY refuses to let me sign in, it even bugs out and lies.

### ISSUE THREAD

**Issue by EmersonBiggons** [Nexus-Mods/Nexus-Mod-Manager#198]
When I click sign in (even though it should be automatic) because the manager wouldn't download the mods, then it "Appeared" to sign me in, but it didn't and as soon as I restart the manager it just does the whole prosses over again. Just please tell me I'm an idiot and it's a simple fix.
![screenshot 6 _li](https://user-images.githubusercontent.com/33952378/33201822-5589373c-d0b7-11e7-8995-6af02b8bdd72.jpg)

**Comment by squid-box** [comment]
NMM won't automatically sign you in, but it should save your login details (if you check the checkbox) and should log you in easily on the next start (just by clicking login).

Are you having problems downloading mods? If so, which, and what errors are you getting?

**Comment by EmersonBiggons** [comment]
I don't even own Fallout 3 on my pc anymore this was WAY too late.

**Comment by squid-box** [comment]
Good to hear, then I'll close the issue.

**Comment by EmersonBiggons** [comment]
Yes
do that
