### ISSUE TITLE
Fallout 4 "VirtualInstall" in wrong location.

### ISSUE THREAD

**Issue by DarwinTrue** [Nexus-Mods/Nexus-Mod-Manager#2]
VirtualInstall folder still in disk C:
C:\Users\darwin\Documents\Nexus Mod Manager\Fallout4\Mods\VirtualInstall

But all configured to be in disk F:
F:\Games\Other\Nexus Mod Manager\Fallout4

![default](https://cloud.githubusercontent.com/assets/12689122/15855481/4368c4fc-2ce2-11e6-9ff1-5351e3345ab5.PNG)

**Comment by squid-box** [comment]
@DarwinTrue: Is still an issue for you (with NMM 0.65.4)?

**Comment by squid-box** [comment]
With no reply after a week I'm closing the issue.
