### ISSUE TITLE
Unable to add any mods from files

### ISSUE THREAD

**Issue by have-a-boy** [Nexus-Mods/Nexus-Mod-Manager#204]
I have tried multiple versions of NMM now, but it seems that with all of them I am unable to install a mod for Skyrim SE from a file (.7z). Regardless of whether I try to drag it into the GUI or click on the plus sign and select the files in the dialog, NMM shows absolutely no reaction at all. No Error, no crash, nothing happens.
I've tried this with multiple mods from Nexus and elsewhere, none of them do anything regardless of packaging method. Among others, I've tried this with DynDOLOD (Standalone and Resources file) from [here](http://forum.step-project.com/topic/12479-dynamic-distant-objects-lod-dyndolod-235/), SKSE, Bottles of Skyrim and other random small mods I could find on the frontpage of Nexus.

Before anyone asks, downloading and installing via the NMM download manager works fine. Basically I have not run into any issues modding Skyrim SE aside from this one.

Tell me if I'm doing something wrong or if you need any additional information.

Edit: Seems that restarting NMM makes the mods show up in the download queue as "Paused" downloads and clicking the cotinue download button with one of those entries selected installs that mod and also makes all the others show up in the main mod list as uninstalled files. I doubt that this is intended behaviour, but if so it should probably be changed to refresh the mod list immediately, so you can actually see that the program reacts to your input when installing mods from a file.

**Comment by squid-box** [comment]
@have-a-boy: are you still seeing this behavior with the latest NMM 0.65.2 it higher?

If you are it would be good to get a trace file from when you're trying to add a file mentally. To get that you can start NMM in Trace Mode (shortcut in the start menu), do the steps you've described, and then the file is found in your Documents folder under Nexus Mod Manager.
