### ISSUE TITLE
Add support for Fallout 4 VR edition

### ISSUE THREAD

**Issue by joakimlemb** [Nexus-Mods/Nexus-Mod-Manager#206]
The modding behaves excactly as Fallout 4 with the exception that the directory for plugins.txt is different and the .exe file has a new name, so hopefully this should not require a lot of code additions.

**Comment by Mithoran** [comment]
Also, it appears to be necessary to add an asterisk before each line in the plugins.txt file (a format change from Fallout 4). 

More discussion here: [https://www.reddit.com/r/fo4vr/comments/7kfvdx/detailed_guide_to_easily_use_nexusmodmanager/](url)

**Comment by squid-box** [comment]
Until someone more competent comes along, I hacked together a version that works for me. It's an ugly hack (i.e. not in a state to be a pull request), but it seems to work fine: 
https://github.com/squid-box/Nexus-Mod-Manager/releases/
