### ISSUE TITLE
I installed the NMM and it found my Skyrim sepcial edition. I set up the paths as recommend. When i try to download something i get the error that nmm is not set up to work with skyrim and i schould rescan. I reinsatlled it several times. What should i do?

### ISSUE THREAD

**Issue by Cvsader** [Nexus-Mods/Nexus-Mod-Manager#209]

**Comment by squid-box** [comment]
It sounds like you're trying to add mods for Skyrim to Skyrim SE, which will not work (NMM will try to start in Skyrim mode, which you don't have installed/scanned).

**Comment by squid-box** [comment]
With no reply in over a month, I'm assuming what I wrote above is correct.
Please reopen and provide more info if that is not the case.
