### ISSUE TITLE
Should be able to redo mod installer

### ISSUE THREAD

**Issue by Zaflis** [Nexus-Mods/Nexus-Mod-Manager#21]
Some mods come with special installers with user selections. If i install such mod once and then realize i did something wrong, currently it looks like i will have to delete it and redownload the whole file. If you disable a mod and re-enable it, it just uses same setup as before and does not open installer.

Mostly these sort of installers are only added to the biggest downloads on the site, like several hundred megabytes of armor textures etc. So i would imagine adding this feature could also potentially reduce nexus traffic a little bit.

And this is on NMM 0.63.11 with Skyrim SE

**Comment by squid-box** [comment]
At least in 0.65.6 this is possible, if you select to Reinstall a mod.
I'm closing the issue, but if I'm misunderstanding feel free to re-open it.
