### ISSUE TITLE
How can I recover my username and password?

### ISSUE THREAD

**Issue by JoelWarnick** [Nexus-Mods/Nexus-Mod-Manager#218]

**Comment by wills661** [comment]
My Passwords will not work on Nexus And i cannot change either

**Comment by squid-box** [comment]
This repo handles issues repleted to the Nexus Mod Manager application, we can't really help with account management. 

It seems you can use [this page] (https://forums.nexusmods.com/index.php?app=core&module=global&section=lostpass) to recover your login.
