### ISSUE TITLE
Manager is installing mods into old directory after changing to new directory

### ISSUE THREAD

**Issue by SickSean** [Nexus-Mods/Nexus-Mod-Manager#222]
I recently changed my Fallout 4 directory to my Fallout 4 VR directory, and when I install mods they are installed to the Fallout 4 directory. While I also changed the install and mod directories as well to keep both games from overlapping, the mod manager is using these directories but still doesn't install.  I am currently running windows 10 and Nexus Mod manager version 0.63.14

**Comment by squid-box** [comment]
See #156
