### ISSUE TITLE
Permission denied on forum links in README, for new devs

### ISSUE THREAD

**Issue by Mithoran** [Nexus-Mods/Nexus-Mod-Manager#223]
I was thinking I'd get started on a pull request, so I read the README and tried to go look at the two forum links (the "start here" and coding conventions links), but both links lead to a "permission denied" error.

"You do not have permission to view this forum."

This is true even when logged in. Are those posts stale? Are there other copies of the on-boarding instructions?

**Comment by squid-box** [comment]
I'm in the same position as you, and I'm assuming it's due to NMM being declared "End of Line": https://forums.nexusmods.com/index.php?/topic/5159340-nmm-is-currently-end-of-line-read-why-and-what-this-means/

**Comment by squid-box** [comment]
It looks like that forum is deleted or at the very least locked down tight.
I've found no other documentation for getting started, but it should just be a matter of having a standard .NET development environment and you can get started.
