### ISSUE TITLE
"Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down."

### ISSUE THREAD

**Issue by amberdunn11** [Nexus-Mods/Nexus-Mod-Manager#240]
Whenever I try to login, it gives me this error "Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down." I can however, log in on the website and my firewall is not blocking

**Comment by Arefu** [comment]
Duplicate of #237

**Comment by squid-box** [comment]
Given the age of this issue and the fact there's a more fleshed out one (#237), I'm closing this issue.

Please see other issue for some helpful tips.
