### ISSUE TITLE
After Uninstalling Vortex, Nexus mod manager does not respond to downloads from website

### ISSUE THREAD

**Issue by SnakeEyes1111** [Nexus-Mods/Nexus-Mod-Manager#243]
I installed vortex, checked it out, thought it was cool, unistalled to wait for full or more finished releases and Nexus mod manager no longer installed anything. Plz help

**Comment by SerClegane** [comment]
Reboot your PC and look into 
Nexus mod manager settings, it can forgot about links from Nexus site

**Comment by jbostrus** [comment]
You'll need to **run NMM as Administrator** for the option to be available. From there load any game of choice. Click the big giant gear icon to open NMM Settings. Right on the first tab (General) in the top section is Associations.  Check the box for Associate with NXM URLs. If it is already checked and not working, uncheck it. Click ok. Close NMM. Relaunch NMM as Administrator again and repeat.

![x2scrap23](https://user-images.githubusercontent.com/12855515/36284421-73a74736-125c-11e8-9b3f-9a600309b73f.png)

**Comment by squid-box** [comment]
With no further activity in 4 months I'm assuming the instruction above helped.

Closing the issue.

**Comment by YuMingC233** [comment]
Thanks, this solution works for me.
