### ISSUE TITLE
Problems with 64.1

### ISSUE THREAD

**Issue by CrankyCat** [Nexus-Mods/Nexus-Mod-Manager#251]
I've been using 63.19 without too many issue since it came out; just the esl files being deactivated after I run LOOT.

I installed 64.1 and immediately had issues with a mod installing "a problem occurred" but nothing traced or, worse, it'd fail in the middle of an install or uninstall and not update the log correctly. I ended up having to restore from a backup. [Workshop Rearranged 6.1](https://www.nexusmods.com/fallout4/mods/16181) wouldn't install on 64.1 but after I uninstalled that and reinstalled 63.19 it worked as expected. The optional patches are where I ran into issues (see attached)
[DisposedObjectError.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1733341/DisposedObjectError.txt)

This happened repeatedly until I went back to 63.19.

**Comment by squid-box** [comment]
@CrankyCat: If you click the red icon to the right of "A problem occurred", you should get some additional information - What does the popup say?

![image](https://user-images.githubusercontent.com/864820/36344897-6975d00e-1421-11e8-9e11-c2ca256217b7.png)

**Comment by CrankyCat** [comment]
I thought I had tried but nothing happened but perhaps not. I haven't had this happen since I went back to 63.19 though and I don't want to risk messing up my game again.

**Comment by MrJamesFreeze** [comment]
Had same issue with 64.0 but don't know error, because I went back to 63.9 too.
I will try it again and write here if it happened again and which error it throws.

**Comment by CasperTheLich** [comment]
in my case this seems to have something to do with NMM not finding a specific temp folder.

---edit
took me a few to search through my tempfiles... well anyway, error reads:
Could not find a part of the path "C:\Users\myname\App Data\Temp\NexusModManager\tempfile_55bclraa.zn0". the mod was not installed

**Comment by squid-box** [comment]
@CasperTheLich: Then that's probably what I introduced, and have submitted a fix for: #252
Until #252 is pulled into a future installer, the workaround would be to create the folder "%TEMP%\NexusModManager", and you should be able to install mods. (Or go back to 0.64.0)

**Comment by CasperTheLich** [comment]
lol, figured if nmm couldn't find a temp folder i might try creating one myself. was going to post just now that it worked.

**Comment by DuskDweller** [comment]
Fixed in 0.64.2!

**Comment by CrankyCat** [comment]
Yep, definitely fixed! Thanks.
