### ISSUE TITLE
NMM 0.64.0 Issue with Temp file path when uninstalling/reinstalling mods, w/easy workaround.

### ISSUE THREAD

**Issue by Sgtspoon** [Nexus-Mods/Nexus-Mod-Manager#259]
Hi, seems NMM 0.64.0 sometimes randomly loses it's association with it's temp file location, even tho the path is unaltered from default in the settings causing an error upon uninstalling or reinstalling of a mod, stating it cannot find a temp file. 

it's easily cleared by going into settings to the temp file path setting and hitting browse and simply re-selecting the default temp folder path (unknown if this bug pertains to custom temp paths or not, but would assume so) and then closing NMM and restarting it and then resuming the uninstall or reinstall. this clears the error state that shows on the mod. 

seems a minor bug with an easy fix, not more than an occasional annoyance but it does happen often perhaps once a day or more. I am using a heavily modded fallout 4 with both .esp's and .esl's with over 250 active plug ins.. I am basically doing a test play through of multiple mods to see what plays well with what and for different play styles before making merged patches.. so doing a lot of playing around with load order, install/uninstall, conversion to .esl, etc... 

I do not remember if I am installed into the default path for NMM or not, if that is a factor.. my path is C:/Games/Nexus Mod Manager

Windows 10 pro, 64 bit. 

thanks all for your good work! let me know if any more information is needed, I'm happy to help..

**Comment by DuskDweller** [comment]
This issue should be solved in 0.64.2 .

**Comment by MrJamesFreeze** [comment]
nope, still in 0.64.2

**Comment by squid-box** [comment]
@JamesFreezeCZ: Could you provide us with a trace log from the crash you're seeing?
