### ISSUE TITLE
Support for Skyrim VR

### ISSUE THREAD

**Issue by Helios747** [Nexus-Mods/Nexus-Mod-Manager#271]
Yes, this issue was coming. Everybody knew.

Anyways, looks like Skyrim VR is in fact based on Skyrim SE, and mods that work with SE work with VR.

Right now, you can kinda sorta hack around NMM not actually supporting SVR by following [these instructions](https://www.reddit.com/r/skyrimvr/comments/89705e/how_to_install_mods_in_skyrim_vr_easy_guide_nexus/dwpcqfp/) but this would all be avoidable if an entry was added for Skyrim VR and was just treated like SE.

**Comment by squid-box** [comment]
It's probably as easy as adding support for Fallout 4 VR, so anyone looking into this could get some inspiration and avoid the mistakes I made in PR #224

**Comment by squid-box** [comment]
This was included with 0.65.7.
