### ISSUE TITLE
Andromeda - Standing Stones of Skyrim not appearing in mod list or plugin load order after download

### ISSUE THREAD

**Issue by GeorgeStoll** [Nexus-Mods/Nexus-Mod-Manager#275]
I just made a significant update to NMM and Im trying to download Andromeda - Standing Stones of Skyrim through the mod manager but after it downloads in the download manager in NMM it does not appear in either my mods tab or the load order under the Plugin tab

**Comment by squid-box** [comment]
Is this still a problem for you with the latest NMM? If so could you grab some trace logs from when this is happening? See [this page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#how-to-collect-information) on how to do this.

**Comment by squid-box** [comment]
No reply in a month, closing issue.
