### ISSUE TITLE
Incorrect number of active .esp plugins

### ISSUE THREAD

**Issue by Fallout4Why** [Nexus-Mods/Nexus-Mod-Manager#276]
It counts esl plugins as .esp and says you;re over the 255 limit. any way this can be tweaked?

**Comment by squid-box** [comment]
Duplicate of #178.

**Comment by Fallout4Why** [comment]
My mistake XD

**Comment by squid-box** [comment]
With 200+ open issues it's easy to miss one, no worries :)

I'll close this one though.
