### ISSUE TITLE
help! i can't login to nexus mod manager

### ISSUE THREAD

**Issue by dogpole252** [Nexus-Mods/Nexus-Mod-Manager#279]
it keeps saying "login error: wrong username or password" but I'm sure I got it right, how do i fix this?

thank you in advance

**Comment by SolidusBlindSnake** [comment]
Update your nmm to the newest version (0.65.2). Word of caution; there's reports of issues on Fallout4 nmm. In some instances like for me it just can't open, null error for which I have yet to find a solution anywhere on the nexus.

**Comment by jaredlanny** [comment]
I'm experiencing the same problem; I've only just installed NMM on this computer, so it's definately the 0.65.2; I've copy/pasted my username from NM website; and changed my password an half dozen times over the last couple of days to make sure I'm using the correct password... still nothing. I've confirmed that NMM is an exception on my firewall,

So I did a full uninstall (removing all settings and leftover files) and reinstalled NMM; still no dice.

Mine, like dogpole's, is the same error: "wrong username or password"

It's getting very frustrating.

**Comment by squid-box** [comment]
I'm guessing you're trying to log in with your email as username, this won't work in NMM. You need to use your Nexus username.

**Comment by squid-box** [comment]
Note that NMM cannot authenticate you with an email address as your username, you need to use your Nexus username when logging in.

With [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), the login form will now enforce using a username (won't allow email). Hopefully that will resolve most login issues people are reporting.

Closing this issue.
