### ISSUE TITLE
Crashes at launch - no aftermarket antivirus installed

### ISSUE THREAD

**Issue by Andrew-InTheBox** [Nexus-Mods/Nexus-Mod-Manager#283]
[TraceLog20180424191221.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1945026/TraceLog20180424191221.txt)

Trace log attached.  It was running fine and I installed the newest version 0.65.0 on top of 0.64.3 and it crashes on open.  Uninstalling and rolling back to 0.64.3 is still giving the same behavior.

**Comment by squid-box** [comment]
This is the same issue as #300, look there for how to fix this.
