### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by loganextreme** [Nexus-Mods/Nexus-Mod-Manager#284]
I am unable to log in on Nexus manager...It keeps telling me wrong username or password...I go to the Nexus mod manager page and I log in....I go back to the manager close it and reopen to log in...tells me wrong password or username...I copy the username and i redo the password still nothing...been fighting with it for over two hours...

**Comment by phoenixrm1** [comment]
Im having the same issue. Did you ever get a fix for it?

**Comment by loganextreme** [comment]
so I was a fool and didn't pay attention to my information. what i did to make sure i was seeing the right information I copied my log in info and pasted it to get mine. sorry probably not helpful

________________________________

**Comment by squid-box** [comment]
@phoenixrm1: still having problems? Otherwise I'll close this issue.
