### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by SpartanII118** [Nexus-Mods/Nexus-Mod-Manager#285]
When i try to log in i get an error telling me that the version of nexus, I have downloaded the newest version and it still tells me to update, I have also tried to use the in software update and it said i was up to date anyone have answers?

Full error message
https://imgur.com/a/lfkXxyD

**Comment by squid-box** [comment]
It looks like you're on 0.65.1, try 0.65.2 or higher (currently latest version is 0.65.5.

Let us know if that works or not.
