### ISSUE TITLE
It crashes after launch please help

### ISSUE THREAD

**Issue by OwlHG** [Nexus-Mods/Nexus-Mod-Manager#286]
whenever I try to launch fallout 4 it crashes and says "cannot access file" because it is being used by another program
[TraceLog20180426065042.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1951221/TraceLog20180426065042.txt)
[TraceLog20180426063645.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1951226/TraceLog20180426063645.txt)

EDIT- Now is wont even give the message it just wont open

**Comment by OwlHG** [comment]
the tracelog's are different

**Comment by squid-box** [comment]
It's weird, I've never seen an applications settings for be blocked... You could try going to the path given (`C:\Users\Rowena\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_mflwfiwatesrlvey1q2sax5h5mo2d1at\0.65.2.0\`) and delete the files in there and see if NMM starts.

Let us know if you're still stuck after that.

**Comment by squid-box** [comment]
This was fixed in 0.65.8, please try that version.
