### ISSUE TITLE
Error after Launch

### ISSUE THREAD

**Issue by BEJ256** [Nexus-Mods/Nexus-Mod-Manager#289]
[TraceLog20180428220900.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1958391/TraceLog20180428220900.txt)

**Comment by Brownman371** [comment]
yea when i load fallout 4 through the latest NMM update it crashes.

**Comment by Brownman371** [comment]
i figured it out i deleted the creation club gauss rifle esl and it worked

**Comment by squid-box** [comment]
@BEJ256: check #300 , I'm guessing you've renamed your Fallout 4 executable or tried to trick NMM into modding FO4VR?
