### ISSUE TITLE
EnvironmentPermissions error in script installation - Skyrim/SkyUI

### ISSUE THREAD

**Issue by phibroptix** [Nexus-Mods/Nexus-Mod-Manager#290]
When installing SkyUI, NMM returns error "An exception occurred in the script."

![image](https://user-images.githubusercontent.com/37635207/39453080-d709a30e-4c91-11e8-9f6b-8c83eafb0a9e.png)

![image](https://user-images.githubusercontent.com/37635207/39453105-e87afcc8-4c91-11e8-87ee-2e71977a8498.png)

NMM Version 0.65.3
Win 7
Skyrim LE
SKSE is installed and functioning

**Comment by LuiMaster** [comment]
Hello there, same problem with me and everything is working(SKSE and NMM) altho its with some other random mods !

**Comment by hiroxe** [comment]
Same problem here

**Comment by squid-box** [comment]
In #380 it's mentioned that this problem could be fixed by removing .NET 3.5 - Does that work for any of you..?

**Comment by weikanglim** [comment]
@squid-box The stack trace seems to indicate a different error than #380. I can reproduce the same issue attempting to install Fallout Character Overhall 3.0 in FalloutNV.

What I can tell from the stack trace:
![image](https://user-images.githubusercontent.com/2322434/42859894-5a6469bc-8a1a-11e8-92bd-3f61f065defd.png)

1. We're creating a separate AppDomain for executing the untrusted C# script packaged with the mod.
2. The mod calls InstallFolderFromFoMod which proxies back to NMM's InstallFileFromMod.
3. When InstallFolderFromMod is called, we use the environment's temp path as part of the process, which System.IO.GetTempPath checks for Unrestricted EnvironmentPermissions -- permissions to environment variables, which is not granted to the AppDomain created in 1. This throws the SecurityException.

**Comment by squid-box** [comment]
You're right, this one is likely fixed by #500, which hopefully it's included in the next version.

**Comment by phibroptix** [comment]
That fix is included in 65.9 and that fixed my issue, thanks!
