### ISSUE TITLE
after about 5-15 mins of gameplay fallout 4 ctd

### ISSUE THREAD

**Issue by aow-lizardshaman** [Nexus-Mods/Nexus-Mod-Manager#292]
As it says in the title when i play for around 5 -15 mins of gametime the game randomly crashes to desktop with no indication as to why. It also seems to crash when i go to build in vault 88. Other useful info includes:
operating system: windows 10 
game version: steam
nmm version: 0.63.14

 below are screenshots of my mods and active plugins 

![screenshot 1](https://user-images.githubusercontent.com/28312288/39509282-8c862578-4d9a-11e8-80b6-a15c038573c0.jpg) 
![screenshot 2a](https://user-images.githubusercontent.com/28312288/39509393-fe9c12c6-4d9a-11e8-9db4-e570ea3b60f1.jpg)

**Comment by DuskDweller** [comment]
I'll ask @TanninOne to help you on this!

**Comment by aow-lizardshaman** [comment]
looked around a bit online and issue was probably Bethesda's shit coding as to the temp memory not clearing it self after the game was closed or something like that.
