### ISSUE TITLE
Nexus Crashing on Load of Fallout 4vr

### ISSUE THREAD

**Issue by DubieDoo** [Nexus-Mods/Nexus-Mod-Manager#293]
[TraceLog20180503143052.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1972187/TraceLog20180503143052.txt)

I had it working before but I just formatted my pc for a clean install and now i cant get it working again. Changed the directory from fallout 4 to fallout 4vr if that matters.

**Comment by DubieDoo** [comment]
To be clear, it crashes before it even gets to the mod loading part. RIght after I choose the game.

**Comment by Ghostwalker71** [comment]
Did you remember to run the game launcher once before trying to use NMM?

**Comment by DubieDoo** [comment]
I must have I guess, I could have sworn I did but maybe it wasn't finished downloading. I tried removing nexus mods along with the install folders for it as well as Fallout 4 and reinstalled in the proper order but I'm still getting the crash. Was there something else I was supposed to clear out to clean install nexus?

**Comment by Ebbe67342** [comment]
NMM seems to try to get some kind of version(?) information from "Fallout4.exe", which of course does not exist for Fallout 4 VR. This causes the "Value cannot be null." error.

I've created an empty file named "Fallout4.exe" in my "SteamApps\common\Fallout 4 VR" folder (empty text file created with a text editor like Notepad++ and saved as "Fallout4.exe", of course without extension .txt). Now NMM starts for Fallout 4 VR.

**Comment by DubieDoo** [comment]
Okay now its saying i need a fallout 4.ini file, can i just create a dummy file just as with the fake exe?

**Comment by DubieDoo** [comment]
Also, it does go to the mod loading screen now.

**Comment by DubieDoo** [comment]
oops nevermind i found a solution for the ini fix. Thanks for the help!
