### ISSUE TITLE
Need Help With Nexus Mod Manager Null Error

### ISSUE THREAD

**Issue by HelpMe456** [Nexus-Mods/Nexus-Mod-Manager#294]
I don't know what has caused the error, I have reinstalled multiple times with uninstalling each time as well. I've tried looking for anything that causes the error. Please help

Trace file has been created: TraceLog20180504030146.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Morrowind.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Oblivion.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Breaking Wheel (BreakingWheel)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\545890\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Dragon's Dogma (DragonsDogma)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\367500\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout3\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout 4 (Fallout4)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\377160\Installed
                Getting Steam install folder.
                Fallout4 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout4\Installed Path
                Found C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\
            Returned: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\ (IsNull=False)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\FalloutNV\Installed Path
                Found 
            Returned:  (IsNull=True)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    No Man's Sky (NoMansSky)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\275850\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Oblivion\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Skyrim\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim Special Edition (SkyrimSE)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\489830\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\SkyrimSE\Installed Path
                Found 
            Returned:  (IsNull=True)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236930\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    The Witcher 3 (Witcher3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\292030\Installed
                Getting install folder from Uninstall.
                Found 
            Getting GOG install folder.
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    XCOM 2 (XCOM2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\268500\Installed
                Getting Steam install folder.
                XCOM2 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Starting search.
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	Value cannot be null.
Parameter name: v1
Full Trace: 
	System.ArgumentNullException: Value cannot be null.
Parameter name: v1
   at System.Version.op_LessThan(Version v1, Version v2)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.InitializeManager()
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeBase.SetupPluginManagement(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    4 () 
        Aborted

**Comment by DuskDweller** [comment]
Is this a legit Fallout 4? It doesn't look like it from this crash you got.

**Comment by HelpMe456** [comment]
Yes I bought The Game Of The Year Edition Off Steam

**Comment by SolidusBlindSnake** [comment]
Did you do edits to your game .exe files or any other edits for that matter and what, if any, tools are installed. I'm only asking because i'm also getting the null error  after update with a legit all dlc fallout4 from humble bundle code on steam.

**Comment by SolidusBlindSnake** [comment]
There's a solution found by paul mcgoldrick that answers the null error: https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/300

**Comment by squid-box** [comment]
From the other people reporting the same crash, I'd guess you've renamed your Fallout4.exe, as this crash will really only happen when the executable isn't found.

See #300 for workarounds.
