### ISSUE TITLE
Nexus doesn't download mods

### ISSUE THREAD

**Issue by Lordkevin89** [Nexus-Mods/Nexus-Mod-Manager#295]
Been clicking for 5 minutes on download now

**Comment by wertercatt** [comment]
Are you using 32-bit? That version only supports .7z files for some reason.

**Comment by squid-box** [comment]
@Lordkevin89: I'm assuming you're clicking "download" on the Nexus website, but NMM isn't starting any downloads?

I'd suggest going to NMM settings, and checking if "Associate with NXM URLs" is checked:
> ![image](https://user-images.githubusercontent.com/864820/40568982-67f77c88-607e-11e8-947b-ff9c2711caec.png)

If it is, you could try another browser, or:
1. Opening NMM settings.
2. Unchecking "Associate with NXM URLs".
3. Pressing OK.
4. Opening NMM settings again.
5. Checking "Associate with NXM URLs" again.
6. Pressing OK.

If it's still not reacting to you clicking these links, record a [Trace Log](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) of you having NMM started, then clicking the link.
