### ISSUE TITLE
Bug with  scripted FOMOD installers

### ISSUE THREAD

**Issue by Sinist3rPT** [Nexus-Mods/Nexus-Mod-Manager#297]
Hi I just installed the last version available here (0.65.4) of nexus mod manager and unfortunately it seems that the scripted mods installation bug still presists. mods such as mcm or uio cant be installed due to the script it uses being incompatible with the program's new version. the error message it presents when it fails to install the mods says something about security environment permissions. I'm sorry if you need any more info that I didn't provide to solve the problem. I'm not a coder so I don't know if you need anything else. either way any other info you may need to solve the issue just ask.
in case you are wondering I'm not currently running any anti virus software besides the one that comes with the OS and I'm running Windows 10 x64 Insider (RS5)

PS: here's some of the mods I mentioned so you can test it on your own:
https://www.nexusmods.com/newvegas/mods/57174
https://www.nexusmods.com/newvegas/mods/42507
https://www.nexusmods.com/newvegas/mods/44515

**Comment by DuskDweller** [comment]
This issue has nothing to do with the XML bug that was present in the latest releases.
Those mods you are trying to install are using c# scripts and that always required NMM to be ran as Administrator.

**Comment by ghost** [comment]
It's not related to XML, but for some reason the latest versions cannot install any mod I tried that has a CS script. Some of the most popular FO3 and NV mods at the Nexus are using such scripts (even when they don't have to, but they still fail to be installed with the latest NMM).

**Comment by Sinist3rPT** [comment]
But I always run the program as an admin. It just doesnt work for some reason. It used to work before version 0.65 but now it doesnt. Im sorry for forgetting to tell you that i was running it as an admin. Anyway i hope the issue gets solved in the next release. Good luck and thank you for your hard work in the development of this awesome mod manager.

**Comment by DuskDweller** [comment]
This is because either Windows or your antivirus are freaking out on a very new NMM version, nobody can do anything about it, you need to sort it out on your own with your windows and/or av .

**Comment by Sinist3rPT** [comment]
the last version of nexus mod manager i had before updating to 0.65 was the one on the nexus page (0.63 i think) and that one worked fine so I dont think its an issue with how my windows is setup. I have no other av besides the one that already comes with the os (windows essentials) and besides aparently I'm not the only one having this issue as saxonis also has it. I think the problem is with the program itself.  but if it is a problem the security perms on my os could you perhaps give me a clue to where I might fix the issue? its just I really dont like the idea of moving my stuff over to vortex as I've tried it and I still prefer everything about  NMM, when it works that is.

**Comment by DarkwingDuckling** [comment]
Same problem here. How come that in 0.63 scripted installers worked and in 0.65.4 they don't. I didn't change my OS, didn't change my AV or its settings and I always run NMM as an admin. The only thing that has changed is NMM itself so it has to be the culprit of the problem. I run Win 8.1 Pro x64 and Kaspersky IS. Never had any problems with NMM until now.

**Comment by ghost** [comment]
Windows 10, run as admin, no antivirus, same issue.
Windows 7, run as admin, no antivirus, same issue.

**Comment by tiwuno** [comment]
Same issue. Running NMM as administrator, no antivirus interference. Some mods install just fine, others fail no matter how much I troubleshoot.

**Comment by Sinist3rPT** [comment]
Im sorry squid-box for starting a new thread but yeah the problem still hasnt been resolved in version 0.65.5. I hope you solve it fast! good luck and thank you

**Comment by squid-box** [comment]
I was about to dismiss this since it worked for me as well, but then I downloaded the 0.65.5 installer from Github (previously ran the version built on my own machine) and I'm getting the same behavior with or without elevating NMM.

@DuskDweller: Could it be that since NMM is no longer signed this is a problem when running code built on someone elses computer? 
I have no idea how the C# scripting works, so I'm flailing in the dark here :)

You could try my theory by installing the [installer](https://build.ahlgren.io/viewLog.html?buildId=222&buildTypeId=GitHub_Nmm_Build&tab=artifacts) my private build server made (login as guest should work).

**Comment by changhe3** [comment]
@squid-box I tested installation latest FWE mod on fallout 3 using your private build and it seems not working.

**Comment by squid-box** [comment]
Sorry, that would be expected - that version will only work on my machine (if my theory is correct) - I meant for DuskDweller to try it out and see if it worked for him or not :)

**Comment by changhe3** [comment]
This is a terrible dilemma since on the one hand I cannot install mods with 0.65+ and on the other hand I cannot downgrade NMM, say, to 0.64.x due to the HTTPS update. Do you know is there any quick and dirty way to fix this? It seems the error is about security policy on .NET. Is there anyway to lower it or not? Thanks.

**Comment by squid-box** [comment]
I'm not read up on this at all, so my work-around would be to downgrade to the older NMM, then download the mods through your browser and add them manually to NMM (add from file).

Sorry :(

**Comment by ghost** [comment]
Some users claim that they can fix this issue by enabling some irrelevant settings. [This might help find a permanent solution.](https://www.reddit.com/r/fnv/comments/8p3hyf/mod_help_sorry_for_bad_resolution_can_someone/e08522b/?st=ji4dvjnx&sh=c0598aae)

**Comment by Sinist3rPT** [comment]
Thanks for trying to help Saxonis but I just tried it and it doesnt work. perhaps its the solution to another problem?

**Comment by Sinist3rPT** [comment]
I think the problem has finally been fixed in version 0.65.6. thanks a lot DuskDweller and squid-box!

**Comment by squid-box** [comment]
OK, a dumb question: Have you installed the New Vegas Script Extender?

With 0.65.6 I can reproduce the issue with "The Weapon Mod Menu" and "The Mod Configuration Menu", but "UIO - User Interface Organiser" works fine.

However, installing NVSE (downloading and unzipping it to the FNV game folder), I'm able to install all mods fine...

**Comment by Sinist3rPT** [comment]
I already said the problem has been apparently been fixed in version 0.65.6 squid-box in my last comment. i even thanked you for the attention you brought to the issue haha anyway thanks again guys for fixing the problem

**Comment by squid-box** [comment]
There was nothing done to fix it in the update to 0.65.6, so that seems coincidental. Like I wrote I could reproduce it with 0.65.6.

Plenty of other people are having the issue, so I want to make sure it's actually resolved. So my previous question was more aimed at the others in this issue: @Saxonis , @DarkwingDuckling , @tiwuno , @changhe3 .

**Comment by tiwuno** [comment]
@squid-box It was fixed for me by enabling "Add Shell Extensions for Supported File Types". Any idea why that fix works for some people, if it's irrelevant?

**Comment by squid-box** [comment]
I really don't understand how that would fix it, but if it works for you that's good :)

**Comment by ghost** [comment]
Version 0.65.9 states _"Fixed security exception while running C# install scripts. (thanks to user ousnius on Github)"_ and I can confirm this issue has been fixed. Thanks.
