### ISSUE TITLE
I can not login.

### ISSUE THREAD

**Issue by AndruxaFeed** [Nexus-Mods/Nexus-Mod-Manager#298]
I can not download the mods, gives an error message. Sorry, I dont know english, so I was use google translate...

**Comment by ximrm** [comment]
same for me

**Comment by cinghiale2** [comment]
I do not want to log in, keep giving me password error

**Comment by DarthCulator** [comment]
Use the latest [release](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases). I had the same problem until I updated. HTTPS login was added three releases back and it seems to be required now.

**Comment by werlock** [comment]
its working with latest release
 thanks @DarthCulator

**Comment by squid-box** [comment]
Going to assume this was the case for everyone in this issue, so I'm closing it.

Let me know if that's not the case.
