### ISSUE TITLE
After upgrade from 0.63 cant move load order on Fallout mods, skyrim works ok

### ISSUE THREAD

**Issue by silhouett** [Nexus-Mods/Nexus-Mod-Manager#299]
I noticed that the arrows are grey no matter where I am in the load order and I can not change the order. I tried saving the order and reloading it and still can not shift any mod with the arrows as they  remain grey.
I switched to skyrim and they work in that game.

**Comment by pokara** [comment]
surry my english, its not my native language.
exact my issue, after updating from 0.63.somethin to 0.65.2 (downloaded from nexus) i cant sort my files, i cant on fo4, and i cant on skyrim se..   dont have more games. it was working with no problem before.
i did the update cause i have with 0.63 a lot of issues trying to login from application. now, i have no problems with the login, but like i said, i cant sort my mods.
the green arrows are like desactivated, grey color..
any advice please? thanks for reading

**Comment by silhouett** [comment]
Pokara, I am just a user of it like you so we are both looking for answers.  I did find an older mention of someone who had this problem in 2016  and they said to remove the .ESL  files and try it then ?

**Comment by pokara** [comment]
thanks for response, i tried and it work, now the arrows are green..  but do you mean i have to 'move' all my esl files (i have a lot of them from creation club, i think ive got all them) every time i want to install a mod and change my load order?  it coulb be fine a fix for this.
anyway thanks for the advice. it works without esl files..  i know what happenning, thanks.

**Comment by squid-box** [comment]
This is fixed in the latest version (and worked for a number of versions before 0.65.8), grab [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), and you should be able to reorder plugins even with .esl's present.
