### ISSUE TITLE
Mods are not updating.

### ISSUE THREAD

**Issue by biship** [Nexus-Mods/Nexus-Mod-Manager#3]
I upgraded from 0.57.x and the mods do not update. I compiled the code from 6/22. Tell me what logging I can enable, or what to debugging I can do to help.

**Comment by squid-box** [comment]
It's been a long time, but if this is still an issue you can start NMM with the `/trace` parameter (there should also be a shortcut for this in your start menu) and it will write a trace file to an NMM directory in your documents directory.

If you're no longer experiencing this (2 years later...) or don't reply, I'll close the issue :)

**Comment by squid-box** [comment]
With no reply in a week, I'm closing the issue.
