### ISSUE TITLE
[63.12] NMM Locks Up (Not Responding)

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/Nexus-Mod-Manager#30]
Every time I try to Cancel the selected Download, NMM locks up. I can't even use task manager to end task because it still doesn't end task. Task Manager is showing it using (currently while typing this) 28.1% CPU & locked at 85.8 MB of Memory, but it's still not responding.

I have to keep restarting Windows to finally shut down NMM (I've done this 5 times, now going to be 6). So, I'll just keep this file listed in the Download Manager, even though my OCD screams at me to keep tying to cancel the download.

![nmm 2017-01-16](https://cloud.githubusercontent.com/assets/18717349/21988407/2513af7e-dbd5-11e6-8a0d-b1bf13a0e4ff.jpg)

![task manager nmm 2017-01-16](https://cloud.githubusercontent.com/assets/18717349/21988412/298a071a-dbd5-11e6-8805-2a443fcd376b.jpg)

**Comment by Tazgma311** [comment]
was told the 63.12 version of NMMhas lot of bug and is no longer support.

**Comment by DontBlnkBadWolf** [comment]
Knew it had a lot of bugs, but didn't know it was no longer supported. That would have been nice to know

**Comment by squid-box** [comment]
@DontBlnkBadWolf: Is this still occurring with the latest version (0.65.4 at this time)? 

If so, could you start NMM with `/trace` as a parameter (or use the shortcut in the start menu), trigger this problem, and then upload the resulting trace file (can be found in your Documents directory, under Nexus Manager)?

There's no official support for NMM from Nexus anymore, but there are still community-fueled fixes happening intermittently.

**Comment by squid-box** [comment]
With no reply in a week, I'm closing the issue.
