### ISSUE TITLE
have a problem to login/download

### ISSUE THREAD

**Issue by eternalinsane** [Nexus-Mods/Nexus-Mod-Manager#303]
the nmm report is: login error: cannot reach the nexus login server.Either your firewall is blocking nmm or the login server is down.
But  my firewall have the NMM with an exception and i dont know happened,

help plz.

thanks

**Comment by Krayton12** [comment]
Same here

**Comment by CountVictor** [comment]
I have the exact same problem

**Comment by Kisaragi55** [comment]
mine is now doing it too an its pissing me off

**Comment by mrmason** [comment]
https://www.nexusmods.com/skyrimspecialedition/news/13481
