### ISSUE TITLE
issues with NMM

### ISSUE THREAD

**Issue by Kisaragi55** [Nexus-Mods/Nexus-Mod-Manager#304]
**_the nmm report is: login error: cannot reach the nexus login server.Either your firewall is blocking nmm or the login server is down.
But my firewall have the NMM with an exception and i don't know happened,Ive went to the main nexus page an reset my password an checked my ABP ad blocker an nothing seems to work please help!!!_**

**Comment by mrmason** [comment]
#303

**Comment by Kisaragi55** [comment]
@mrmason 
https://github.com/mrmason

when i went to your link it still says error - unable to execute file c://program files/nexus mod managerclient.exe 
createprocess failed: code 740 the requested operation requires evaluation

please help
