### ISSUE TITLE
NMM won't update to v0.65 

### ISSUE THREAD

**Issue by PockenLocken** [Nexus-Mods/Nexus-Mod-Manager#306]
Keeps saying that it can not get update information from update server. Also I can't login but that could because I can't update. What do man?

**Comment by MrUnknownPlayer** [comment]
Same for me and because of this bug I can't log in which is very annoying because I have to download mods and add them to nexus manualy. Anyone know how to fix that bug?

**Comment by SolidusBlindSnake** [comment]
I downloaded the new versioni of NMM manually and installed over old version but now i'm stuck with an unfonctionnal FO4 nmm giving me null value error message, check my report for more details.

**Comment by Rowse62** [comment]
This is the same thing I get to. HELP
Keeps saying that it can not get update information from update server. Also I can't login but that could because I can't update. What do man?

**Comment by chakazulu90** [comment]
I have the same problem as PockenLocken, can't update, can't login. First I thought it was related to my AntiVirus but turned everything off and still the same....

**Comment by grissena5** [comment]
This article from the nexus news bulletin should solve your problem.
[https://www.nexusmods.com/news/13481](url)
 It explains that they changed things up so you have to download it from the website link.  I just finished updating mine and i can tell you that it works now! ^.^

**Comment by chakazulu90** [comment]
Thanks a lot!!!

2018-05-14 2:15 GMT+02:00 grissena5 <notifications@github.com>:

**Comment by squid-box** [comment]
Closing issue, for anyone encountering this problem: you can't connect to the servers without the new version, so you'll need to download and update NMM manually.
