### ISSUE TITLE
Release 0.65.4 FOMOD CTD

### ISSUE THREAD

**Issue by kkthebeast** [Nexus-Mods/Nexus-Mod-Manager#307]
If installing another mod first, then attempting to installing a FOMOD NMM will softcrash when highlighting any of the options to read the provided text. when this happens the text (description will not display, only a blank area on the right) sometimes dismissing the error and canceling the fomod install then rerunning it will work. best fix to to restart NMM.

Thanks for you work :)

**Comment by squid-box** [comment]
@kkthebeast: can you provide a trace log, or stack trace from the event viewer if it's complete crash?
