### ISSUE TITLE
Sending login data causes indefinite freeze

### ISSUE THREAD

**Issue by Strazyplus** [Nexus-Mods/Nexus-Mod-Manager#31]
After attempting to log in causes the freeze, the application then refuses to respond and will not resume operation. Task manager shows application on 0% CPU, DISK, and NETWORK usage. Forcing the application to close gives the following error within .NET Framework

I have the latest .NET framework which is linked on Nexus for NMM.

Cannot access a disposed object
Object name: 'MainForm'

http://pastebin.com/xhaiR57b  << the full detail log

**Comment by squid-box** [comment]
@Strazyplus: Are you still having this issue with the latest version of NMM?

**Comment by squid-box** [comment]
With no reply in a week, I'm closing the issue.
