### ISSUE TITLE
Unrecognised Game mode

### ISSUE THREAD

**Issue by arnehgail** [Nexus-Mods/Nexus-Mod-Manager#310]
![alert](https://user-images.githubusercontent.com/39235543/39965892-4271715a-56e5-11e8-985e-0bd33e356e07.PNG)
This alert comes up in my NMM application every time I try to download a mod. I'm using Skyrim Special Edition, and none of the files directories are incorrect. I have done as the alert says but it still doesn't work. Any ideas?

**Comment by squid-box** [comment]
This will appear if you're trying to download a mod for a game that you do not have scanned and added to NMM - in this case you're trying to download a Skyrim mod, but have Skyrim SE added.

**Comment by squid-box** [comment]
With no response in 27 days, I'm closing the issue.
