### ISSUE TITLE
65.4 - NMM update fails. Could not get version information from server.

### ISSUE THREAD

**Issue by Valethar** [Nexus-Mods/Nexus-Mod-Manager#313]
Greetings,

Recently updated to v65.4 from v65.2 due to errors trying to update NMM. 65.4 is reporting the same error as 65.2, "Unable to get version information from server". 

Steps to reproduce:

1) Launch NMM.
2a) NMM update auto-check will fail if it runs.
2b) Manual check for updates will fail if run.

Tried to find any logs for NMM, but couldn't locate them, and a Google search utterly failed in that regard. Doesn't seem to be any info in the program itself that I could find that would indicate where they're saved, so I don't know that any were actually created.

I did get a screenie of the error message, however.  

If there's a particular location I should look at for logs that may help chase this down, let me know and I'll see if I have them to post here.

![nmm error 001](https://user-images.githubusercontent.com/33778407/39972534-1de6c57e-56c7-11e8-87a0-873563d68d83.jpg)

**Comment by grissena5** [comment]
i think this news article on nexus should help with your problem. 
[https://www.nexusmods.com/news/13481]

**Comment by stargatedalek** [comment]
I'm having this too, it only started this afternoon, I've been running the most recent for the past week or so with no issues until now.

I'm also unable to reorder my mod list, arrows are greyed out, tried reinstalling to no effect.

Can still download mods from nexus, but the load order can't be adjusted, even through LOOT.

**Comment by Valethar** [comment]
Sadly, installing the 'updated' version from that article did nothing to solve the issue. The error still persists. :/

**Comment by ghost** [comment]
I'm having the same issue with latest release 0.65.4.

**Comment by thegoodsenator11** [comment]
yeah same thing has happened to me sadly. I have no idea what to do.

**Comment by MickCasanova** [comment]
Having the same issue with 0.65.4

**Comment by squid-box** [comment]
This problem is caused by #346, but there's not likely to be any newer version than 0.65.2 on the Nexus server either way. You'll have to grab the latest installers from [Github instead](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases).

**Comment by squid-box** [comment]
Several changes have been made, and now with 0.65.8 (available under [Github releases](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases)), this error is fixed.
