### ISSUE TITLE
NMM

### ISSUE THREAD

**Issue by Armelkonyan** [Nexus-Mods/Nexus-Mod-Manager#319]
Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down.

**Comment by stargatedalek** [comment]
https://www.nexusmods.com/site/mods/4/?tab=files

Try manually installing the latest version.

**Comment by squid-box** [comment]
@Armelkonyan: Did you install 0.65.2 (or higher)? 

Are you still having this problem?
