### ISSUE TITLE
NMM incomplete mods

### ISSUE THREAD

**Issue by Aktredon** [Nexus-Mods/Nexus-Mod-Manager#32]
When I want to download new mod for Skyrim, in most cases (no all) it is incomplete and I can't repare it in any way.

**Comment by CorneliusCornbread** [comment]
Yeah same with fallout 4, latest update broke mod install. THANKS OBAMA.

**Comment by LavCorps** [comment]
(Using 0.63.13) Same issue here with Skyrim. Can't add mods from files or from URLs, always shows up as "Incomplete".

After using the latest Github release ([0.61.21](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.61.21)) it appears to work fine

**Comment by Aktredon** [comment]
I recently started using Mod Manager, and everything is ok, so it is
definitly a problem with NMM. But if you want to just mod in peace, switch
to Mod Manager for now.

2017-03-20 18:51 GMT+01:00 【♪Lavvy♥】 <notifications@github.com>:
