### ISSUE TITLE
FO4:  Nexus mod manager keeps crashing if i touch old or try to install new mods.

### ISSUE THREAD

**Issue by Fukowski** [Nexus-Mods/Nexus-Mod-Manager#322]
I keep getting these error's even after reinstalling fallout 4 and Nexusmodmanager.
The crash happens when i click an old mod in the Mods menu.
I have no idea of the inner workings of the Modmanager so here's the Tracelog

[TraceLog20180516152816.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2009123/TraceLog20180516152816.txt)
And this is the tracelog when i try to download new mods.
[TraceLog20180516155634.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2009184/TraceLog20180516155634.txt)

**Comment by Fukowski** [comment]
Also the manager keeps complaining about not connecting to the update servers properly everytime i reinstall it.

**Comment by squid-box** [comment]
It's weird, both traces point to not being able to find System.Web (but with very varied causes), which I would assume is related to only having a Client Profile version of .NET installed - but that was discontinued from 4.5 and onward (and your traces say you have 4.6+)... The only suggestion I can give you is to repair / reinstall .NET and see if that changes anything.

Not being able to connect to the update servers is a global problem, so you can ignore that for now.

**Comment by Fukowski** [comment]
Thank's that seems to have fixed it, i bet that was the reason most of my games have had problems recently.
