### ISSUE TITLE
I can't log in/update nexus mod manger?

### ISSUE THREAD

**Issue by AmericanSkyper** [Nexus-Mods/Nexus-Mod-Manager#323]
![afbeelding](https://user-images.githubusercontent.com/39337573/40118091-37a13950-5919-11e8-9f6d-7b971bf6eb49.png)

**Comment by Veolin** [comment]
I am having the same problem NMM says "Cannot reach the Nexus login sever. Either your firewall is blocking NMM or the login server is down." I saw lots of people having same problem but ı cant find a solution for that. Please somebody help me.
my account name is: Veolin
if anybody want to contact: arda.81873@gmail.com

**Comment by error55o** [comment]
I got this error, been about 5 days now, also updated to latest and it don't even have a dialog box to log in with now...

correction, after leaving it for a min or two, tried again and it now works

**Comment by Paul111King** [comment]
i have the same problem, i used nmm at school with a vpn and now it doesnt update, cant login. it has been a week now waiting for it to disappear, i even reinstaled it but it doesnt solve anything.

when somebody finds out how to repair this please, i need to know

**Comment by Ghe33TT0KoolAid** [comment]
I'm having the same problem, I know the servers are up, and I also started NMM with my firewall turned off, so I know neither is the problem. I have been having this problem for several days now.

**Comment by BoogieBr0** [comment]
Hey guys,I just reinstalled NMM and it worked for me.

**Comment by squid-box** [comment]
So there seems to be a few different problems reported here, but in short:
1. You need to manually update to 0.65.2 or higher, or you won't be able to login, following changes to the Nexus servers.
2. The update check isn't working right now, pending #346.

If you can't log in after updating to 0.65.2 or higher, please [provide a trace log](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) from when you're trying to log in.

**Comment by squid-box** [comment]
@AmericanSkyper / @Veolin / @error55o / @Paul111King / @Ghe33TT0KoolAid :

I've tried to look into what could go wrong during the login process, but the error message people are getting is pretty much a vague catchall for many possible problems. I've made a debug version of NMM from [this branch](https://github.com/squid-box/Nexus-Mod-Manager/tree/login-debug), and an installer can be found [here](https://build.ahlgren.io/viewLog.html?buildId=227&buildTypeId=GitHub_Nmm_Build&tab=artifacts) (**login as guest**).

If someone who's getting the _"Cannot reach the Nexus login sever. Either your firewall is blocking NMM or the login server is down."_ message could install this version, start it and try to log in, then send me the Trace Log that's generated in `%USERPROFILE%\Documents\Nexus Mod Manager` I might be able to help.

**Comment by squid-box** [comment]
Ignore that build, it seems likely you need to log in with your username, not your email address.

With no replies here for two months I'm closing this issue as dead.
