### ISSUE TITLE
NMM 0.63.13 massive RAM drain while uninstalling a mod.

### ISSUE THREAD

**Issue by SundaySnooker** [Nexus-Mods/Nexus-Mod-Manager#33]
Like the topic says, right after picking to "Uninstall or Delete > From all profiles", the NMM starts to drain RAM and then swap file until force closing by Task Manager.

**Comment by squid-box** [comment]
@SundaySnooker: Are you still seeing this issue with the latest NMM?

If so, could you describe your computer setup? How much RAM do you have, how many mods are installed?

**Comment by squid-box** [comment]
With no reply in a week, I'm closing the issue.
