### ISSUE TITLE
Mod Categories

### ISSUE THREAD

**Issue by name1esstyrant** [Nexus-Mods/Nexus-Mod-Manager#334]
I recently had to reinstall my Nexus Mod Manager, as a mod required me to reduce to an older version. After I installed the previous version, Nexus stopped working. I completely uninstalled everything and reinstalled the most recent version, which fixed the issue with it working; however, I can no longer see my mod categories. They have been stuck with names like W... Uti... Ga.... Is there any way to fix this issue?

![screenshot 2](https://user-images.githubusercontent.com/39491667/40313557-c08c284a-5cdb-11e8-867c-06850b2bc7ce.png)

**Comment by SolidusBlindSnake** [comment]
You're joking right? Your categories names haven't changed it's just the space setting on the top bar, where it says ''name'', ''category'' and so on,  that's too small to view the full name, just point to the top bar setting you wish to change the size till the vertical bar with arrows on each side appears then click and drag and space out till you can see the name.... I'm sorry if my answer doesn't seem nice or something.

**Comment by name1esstyrant** [comment]
Thanks @SolidusBlindSnake! It may have not seemed nice, and I know the names didn't change. I just couldn't figure out how to fix the issue with the names being shortened like that. Fixed my issue!

**Comment by SolidusBlindSnake** [comment]
my pleasure and that also applies for the other settings in the tab so you can make it show you whatever else you wanna see rather then other settings. Happy modding and gaming
