### ISSUE TITLE
FOMOD install fails

### ISSUE THREAD

**Issue by Hilli1** [Nexus-Mods/Nexus-Mod-Manager#335]
Obviously install problems with scripted installers still persist. FOMOD installer for my mod: https://www.nexusmods.com/skyrimspecialedition/mods/16680 fails with NMM. The same FOMOD installer works well with MO2 without any issues. So I have to assume the install problem is related to NMM. A user provided a report: https://pastebin.com/s942C6j7

**Comment by squid-box** [comment]
The log you attached looks to be a log from Vortex, not NMM. Are you sure they are using NMM?

**Comment by Hilli1** [comment]
I have a lot of complaints from users regarding failed install with NMM. So, yes.

**Comment by squid-box** [comment]
OK, so I installed SSE and verified that it is a problem, unfortunately the trace file doesn't contain anything useful in this case. NMM reports: 

```
A problem occurred during install: 
The element 'plugin' has invalid child element 'image'. List of possible elements expected: 'description'.
The mod was not installed.
```

So it's probably the same issue as Vortex encounters. This problem appears at least back to NMM 0.63.17, so it's nothing new.

**Comment by TanninOne** [comment]
The fomod is invalid, plain and simple.

It contains this install step:
```
<installStep name="Step 7 - Choose Language">
  <visible>
    <flagDependency flag="Reworked_Selected" value="selected"/>
  </visible>
  <optionalFileGroups>
    <group name="Language" type="SelectExactlyOne">
      <plugins order="Explicit">
        <plugin name="English">
          <image path="FOMOD\header.jpg"/>
          <conditionFlags>
            <flag name="EN_Selected">selected</flag>
          </conditionFlags>
          <typeDescriptor>
            <type name="Recommended"/>
          </typeDescriptor>
        </plugin>
        <plugin name="German">
          <image path="FOMOD\header.jpg"/>
          <conditionFlags>
            <flag name="GE_Selected">selected</flag>
          </conditionFlags>
          <typeDescriptor>
            <type name="Optional"/>
          </typeDescriptor>
        </plugin>
      </plugins>
    </group>
  </optionalFileGroups>
</installStep>
```

As you can see the plugins here have no description, but in the fomod spec the description is not optional, every plugin needs one.

We'd have to ask @DuskDweller if this was ever different but with the current fomod spec it's a bug in the installer, not in NMM or Vortex.

**Comment by Hilli1** [comment]
Thank you very  much for finding the problem. I don't know why MO2 worked and NMM not, but this was exactly the culprit of the problem. Anyway. I am happy that it works now. Thanks again and I apologize for for wasting your time. Issue closed.
