### ISSUE TITLE
Nexus Mod Manager Has Encountered an Error

### ISSUE THREAD

**Issue by jbarker243** [Nexus-Mods/Nexus-Mod-Manager#337]
[TraceLog20180522200329.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2029005/TraceLog20180522200329.txt)

_Please give as much information as you can, replace/remove italicized text._

When I try to open the mod manager, I get an error message that says the mod manager has encountered an error and needs to close.  I clicked the link provided with the error message to try and find a solution, but could not find a fix.  I have also verified that a virus program or firewall is not the issue.  I have attached the trace log as well to this message.  Please let me know how to fix this problem.

_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
@jbarker243: The tracelog says that NMM is trying to read the version Fallout 4 executable, but it seems that it's no longer in the expected place. 

Did you change your Fallout 4 installation in any way?

A possible work-around to get NMM working again is to go to `%LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_<gibberish>\0.65.4.0` (or the version number you're trying to use) and renaming user.config to something else and see if that removes the crash.

**Comment by jbarker243** [comment]
No.  I have not changed anything with my game or directory it resides in.  I am however running the VR version of fallout 4.  If I copy or rename the fallout 4 VR executable to just say fallout 4, should that work?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by squid-box** [comment]
So then it makes sense that NMM can't handle your setup, I guess you followed some guide to trick NMM to work with FO4VR?

It will probably work if you have a copy named "Fallout4.exe", but no guarantees as FO4VR is not supported.

**Comment by squid-box** [comment]
I'm assuming this is the same problem as #300, so I'll close this issue - please check the other issue for info/workarounds.
