### ISSUE TITLE
Weird name for categories

### ISSUE THREAD

**Issue by crazybalidog** [Nexus-Mods/Nexus-Mod-Manager#338]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
My mods categories are all named very weird. Basically shortened version of themselves which is very annoying since there are a TON of categories and it's basically very hard to read

**Environment**
- NMM version: 0.65.2
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 No idea

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._ please help
![problem](https://user-images.githubusercontent.com/39564389/40436561-c853b316-5ee5-11e8-882d-1c4712f8da15.PNG)

**Comment by squid-box** [comment]
Looks like the column just has a very small width. Grab the line between Name and Category and resize it, see if it looks better. (See #334)
