### ISSUE TITLE
Incorrect dialog box when trying to close program while mod is installing/uninstalling

### ISSUE THREAD

**Issue by agsimmons** [Nexus-Mods/Nexus-Mod-Manager#34]
If you try to close the program while installing/uninstalling a mod, the dialog box asks you if you are sure you want to close NexusModManager, but the only option is OK, and when it is pressed, nothing happens.

The relevant code can be seen at https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/fe9662ad505f93002e02c12ec551d25d0e9c216f/NexusClient/MainForm.cs#L704

I'm not familiar with c#, but I am guessing that
MessageBoxButtons.OK
has to be replaced with
MessageBoxButtons.YesNo

Then, this would match the MessageBoxButtons used here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/fe9662ad505f93002e02c12ec551d25d0e9c216f/NexusClient/MainForm.cs#L697

http://i.imgur.com/LEFmiT0.png

**Comment by squid-box** [comment]
This was fixed in pull request #234.
