### ISSUE TITLE
Cannot login at NMM although beeing Logged in at Nexusmods

### ISSUE THREAD

**Issue by slimythewolf** [Nexus-Mods/Nexus-Mod-Manager#345]
Anytime i want to download with NNM, it says that i am not logged in (which is true). It says "login Error: Cannot reach the Nexus login Server. Either your firewall is blocking NMM or the login Server is down."

I have  NMM version 0.63.14.
My firewall is not existent, so it's not blocking anything.
I use avast antivirus.
I have already downloaded mods with this environment in the past without any problems.
I already checked my login-data, restartet my PC, loged in, loged out. No issues with my Login at Nexusmods.

I have attached some screenshots
![errormessage down below](https://user-images.githubusercontent.com/39633042/40562522-9e74a42e-6061-11e8-9ed0-407c8c6cfdda.jpg)
![errormessage when trying to download a mod](https://user-images.githubusercontent.com/39633042/40562524-9e913fd0-6061-11e8-8686-f6507903702f.jpg)

**Comment by squid-box** [comment]
You'll need to update to 0.65.2 (or higher). Explanation can be found [here](https://www.nexusmods.com/news/13481). 

There's a link for 0.65.2 on that page, or you can grab the latest update from Github [here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases).
