### ISSUE TITLE
Issue with actavating or uninstalling/deleting mods

### ISSUE THREAD

**Issue by Rokusenpai** [Nexus-Mods/Nexus-Mod-Manager#348]
**Describe the bug** 
not sure what the bug is. Also not too good with computers. Trace log is about all I've got to go on.
the mod is _Requiem 2.0.1 - The Phantom Agony (with bugfix pack 1)_
**Environment**
- NMM version: _0.65.2_
- Mod(s) used: _<https://www.nexusmods.com/skyrim/mods/19281?tab=files>_

Trace log attached 
**To Reproduce**
 _IDK_

**Additional information** 
_I only used NMM
[TraceLog20180526205258.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2042241/TraceLog20180526205258.txt)
._

**Comment by squid-box** [comment]
The problem is that NMM apparently can't get access to your Skyrim folder: 
>Access to the path 'c:\program files (x86)\steam\steamapps\common\Skyrim\Data\meshes\Requiem\ammo\daedric' is denied.

You could try running NMM as administrator (elevated privileges) and see if it's able to access the folder.

Let me know how it goes :)

**Comment by Rokusenpai** [comment]
Thanks for the advice I did as you said and everything works now. :)

**Comment by squid-box** [comment]
Great to hear :)
