### ISSUE TITLE
Crash at startup on a NullReferenceException

### ISSUE THREAD

**Issue by AgathiaKimiya** [Nexus-Mods/Nexus-Mod-Manager#351]
I updated the app and since I simply can not start it at all. It crashes instantly. Sorry for the screenshot but it does not write a trace file either, so... here you go.

**Describe the bug** 
Crash on start.

**Environment**
- NMM version: 0.65.2

![image](https://user-images.githubusercontent.com/20950399/40592197-6052c57e-61ea-11e8-8a98-b4397c9754a3.png)

**Comment by paulmcgoldrick** [comment]
Possibly related #300
