### ISSUE TITLE
NMM cant update

### ISSUE THREAD

**Issue by KleenerKlopfer** [Nexus-Mods/Nexus-Mod-Manager#352]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
The follwing Updates failed: Nexus Mod Manager Updater: Could not get Version Information from the Update Server

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_
NMM Version: 0.65.2

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
This has been fixed in 0.65.8.
