### ISSUE TITLE
NMM Won't Open

### ISSUE THREAD

**Issue by CapitalistKevin** [Nexus-Mods/Nexus-Mod-Manager#353]
Nexus Mod Manager will not open for me. I have tried uninstalling and reinstalling various versions. I have allowed the file location on my antivirus and even turned my antivirus off temporarily with still not luck. I have also tried to run as administrator.

I'm on Windows 10.

**Comment by squid-box** [comment]
Have a look under [this Wiki article](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#how-to-collect-information) and please attach a Trace Log if you can, or an Event Viewer log if no Trace Log is available.

Also please specify at least a few of the various versions you've tried.

**Comment by CapitalistKevin** [comment]
I have tried versions 0.65.2, 0.52.4, 0.56.2 on nexus and 0.65.5, 0.65.4, and 0.63.15 from here. Below is the most recent Trace Log. I do not have a trace log or even an event viewer log for the other versions of Nexus. 

Trace file has been created: TraceLog20180528113257.txt
Mod Manager Version: 0.52.4.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager - Legacy\GameModes
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DarkSouls.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DarkSouls2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DarkSouls2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DragonAge.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonAge2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DragonAge2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Grimrock.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Grimrock.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Morrowind.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Oblivion.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: Starbound.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Starbound.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Witcher2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: WorldOfTanks.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\WorldOfTanks.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout3\Installed Path
                Found C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\
            Returned: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\ (IsNull=False)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Getting Steam install folder.
                Found c:\program files (x86)\steam\steamapps\common\Fallout New Vegas
            Returned: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas (IsNull=False)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Morrowind\Installed Path
                Found 
            Returned:  (IsNull=True)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Oblivion\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Getting Steam install folder.
                Found c:\program files (x86)\steam\steamapps\common\Skyrim
            Returned: c:\program files (x86)\steam\steamapps\common\Skyrim (IsNull=False)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236390\Installed
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Found 
            Returned:  (IsNull=True)
    Starting search.

Tracing an Unhandled Exception:
Exception: 
Message: 
	The property 'InstalledGames' could not be created from it's default value. Error message: There is an error in XML document (2, 3).
Full Trace: 
	System.ArgumentException: The property 'InstalledGames' could not be created from it's default value. Error message: There is an error in XML document (2, 3).
   at System.Configuration.SettingsPropertyValue.Deserialize()
   at System.Configuration.SettingsPropertyValue.get_PropertyValue()
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Nexus.Client.Properties.Settings.get_InstalledGames()
   at Nexus.Client.Bootstrapper.GetInstalledGameModes(GameModeRegistry p_gmrSupportedGameModes)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] p_strArgs)
   at Nexus.Client.Program.Main(String[] p_strArgs)

Running Threads (0)

**Comment by squid-box** [comment]
It would be better with the trace log from 0.65.5, but from the one you posted it looks like there's some unexpected setting in the config file. I'd suggest going to `%LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_<gibberish>\<version>` and deleting the user.config file there and try starting NMM again.

If that doesn't work please see if you can give me a trace log from a more recent version.

**Comment by CapitalistKevin** [comment]
I have deleted the user.config file, but it still did not work. I have also tried finding a trace log from my current version, which is 0.65.5, but there was no trace log or event viewer log.

**Comment by squid-box** [comment]
There's a some info on how to toggle Trace Mode on this wiki page: https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log

**Comment by CapitalistKevin** [comment]
I was not able to find a Trace Mode, but I was able to find a lot of .wer files, which I'm guessing is similar if not the same. Here is the latest one...

Version=1
EventType=APPCRASH
EventTime=131733285207954124
ReportType=2
Consent=1
UploadTime=131733285213629372
ReportStatus=2147487752
ReportIdentifier=48e74496-0a2a-433e-b4b9-6d240938cc56
IntegratorReportIdentifier=c02435af-5975-4ea8-a176-e91ba6f45fbb
Wow64Host=34404
NsAppName=NexusClient.exe
AppSessionGuid=00001f30-0001-00ab-4002-c695b902d401
TargetAppId=W:000603b8b0d1046d3c03f123ba2716132d5700000000!00007cd43f5064d5b05fc6c6f67cb97c6be127b09c2d!NexusClient.exe
TargetAppVer=2016//04//26:22:04:03!2eb131!NexusClient.exe
BootId=4294967295
TargetAsId=1179
Response.BucketId=206e514f27532f4427d50df4ba7a4cde
Response.BucketTable=4
Response.LegacyBucketId=1717294177663470814
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=NexusClient.exe
Sig[1].Name=Application Version
Sig[1].Value=0.61.20.0
Sig[2].Name=Application Timestamp
Sig[2].Value=571fe5d3
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.16299.371
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=6369e29f
Sig[6].Name=Exception Code
Sig[6].Value=e0434352
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000014008
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.16299.2.0.0.768.101
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=d2ad
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=d2ad1e8952ec0af50a6d397a729e8aee
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=8c84
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=8c84057b3cff1ed03c16a72a294e2901
UI[2]=C:\Program Files\Nexus Mod Manager\NexusClient.exe
UI[3]=Nexus Mod Manager has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\Nexus Mod Manager\NexusClient.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[11]=C:\WINDOWS\System32\combase.dll
LoadedModule[12]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[13]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[14]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[15]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[16]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[17]=C:\WINDOWS\System32\USER32.dll
LoadedModule[18]=C:\WINDOWS\System32\win32u.dll
LoadedModule[19]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[20]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[22]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[24]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\a39512bde949dc065175a3be81664375\mscorlib.ni.dll
LoadedModule[25]=C:\WINDOWS\System32\ole32.dll
LoadedModule[26]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[27]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[28]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\d41b66a8a5dde18b54c79b7b42b5c951\System.ni.dll
LoadedModule[29]=C:\WINDOWS\System32\OLEAUT32.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=16299
OsInfo[3].Key=ubr
OsInfo[3].Value=371
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=237350
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.371.16299.0-11.0.60
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16384
OsInfo[19].Key=svolsz
OsInfo[19].Value=930
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=170928
OsInfo[22].Key=bldtm
OsInfo[22].Value=1534
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs3_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.16299.371.amd64fre.rs3_release.170928-1534
OsInfo[30].Key=buildflightid
OsInfo[30].Value=FE2BA97F-43C5-48BE-97E6-ACB9DE47C182.1
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=containerid
OsInfo[34].Key=containertype
OsInfo[35].Key=edu
OsInfo[35].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Nexus Mod Manager
AppPath=C:\Program Files\Nexus Mod Manager\NexusClient.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=9401A5C42824623C641492561B9CF3A9
MetadataHash=2091742894

**Comment by squid-box** [comment]
Sorry, I lost this issue along the way. That is really no help, use the guide I linked to force a trace log from a more recent version.
