### ISSUE TITLE
Cant access NMM

### ISSUE THREAD

**Issue by bearmang** [Nexus-Mods/Nexus-Mod-Manager#359]
Can't access NMM at all, when I try to open it, I get an immediate error, when going in to trace log, this appears:

The process cannot access the file 'C:\Users\user\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_gain1zdhkpbyw2jzilftlyqygdtwzisk\0.65.2.0\szc102ro.newcfg' because it is being used by another process.

I have no clue on what is using it? I just installed it today, I've tried reinstalling, restarting PC, and nothing works. If I search for black tree on my pc, nothing shows up. Not sure what to do at this point

**Comment by bearmang** [comment]
Anyone?

**Comment by squid-box** [comment]
The only things I can suggest is:
- Go to the folder pointed out and delete any file in the folder `0.65.2.0`.
- Update to the latest version ([currently 0.65.5](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.5), there's a bit of error handling around the config files.

**Comment by bearmang** [comment]
So that seemed to work somewhat, I get the error from time to time but a reboot of the program fixes it. however some mods give me a similar error

Miel Follower Final Hopefully // A problem occurred during install: 
The process cannot access the file 'C:\Users\user\AppData\Local\Temp\NexusModManager\tempfile_jknwhtwq.him' because it is being used by another process.
The mod was not installed. // Install // 

Running it as admin, this happens with several mods and now i dunno whats going on

**Comment by Lonewolf575** [comment]
Same issues, now running at 0.65.5. Same error message as the first post.

**Comment by neoh4x0r** [comment]
@bearmang 
@arkman575 

I would use process explorer:
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

You can choose from the menu bar the option to search for a handle by string.
If you use the filename as the search term....and if it finds any open handles...they will be reported in the dialog.

The benefit of doing this is that it will show you all programs that have opened a handle to a file or path with that search string.

PS: Sometimes windows will attempt to do things behind-the-scenes that will lock a particular file/path....actually I should not say **attempt to** (as windows always does this).

**Comment by Lonewolf575** [comment]
Any way to prevent this? This seems more a diagnosis rather than a cure.

**Comment by squid-box** [comment]
The first message is for the NMM settings file, and many are seeing this - I can't really say what's causing this.

The second message is the temporary files generated when installing mods, but they are randomized so it really shouldn't be possible for these collisions...

In both cases it would be better to upload the entire Trace Log, so we can get info about what's happening before the error.

(Often you need a diagnosis before you can provide a cure :))

**Comment by Lonewolf575** [comment]
most recent tracelog. This was after I uninstalled the game, purged all the files related to both and reinstalled everything. It worked for a day, then broke again. Same error.

[TraceLog20180608160023.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2086431/TraceLog20180608160023.txt)

**Comment by squid-box** [comment]
Now that I've had a little time to sit at my computer, it looks to me like it's the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting). 

I'll close this issue as a duplicate, but please check #389 for any progress made, but I can't promise it will be fixed anytime soon.
