### ISSUE TITLE
Nexus don't download mods

### ISSUE THREAD

**Issue by Stigher** [Nexus-Mods/Nexus-Mod-Manager#36]
Every time,with every mod(size doesn't matter),it starts and then it just stops saying this :
http://prnt.sc/e2aoua
I re-instaled the nexus,my games and it dont work !
IDK if is the server because i'm brazilian,so pls someone help

**Comment by kashmonez1029** [comment]
Same thing has been happening to me for the past 24 hours. cannot download any file from nexus mods. both the nmm download and manual download arent working. im on a US server. please fix

**Comment by jaran13579** [comment]
I have this bug too. It's been 3 days, I reinstalled my nmm, game, steam, net framework and check my anti-virus program but still happening. Both nmm download and manual download aren't working.
I'm korean user, maybe its server problem? (when i download other files in other site it works)
sorry for shitty english but really. I need help.

**Comment by peltonmonster17** [comment]
Doesn't work on US servers, Brazil Servers, or Korea servers? No way this is a small problem. Something's going on. I've had this for 2 or 3 days now and it's pretty aggravating.

**Comment by squid-box** [comment]
It's been over a year since the last comment, I'll close this issue. 
Please create a new one if you're still having download troubles.
