### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by griffinlord775** [Nexus-Mods/Nexus-Mod-Manager#361]
**Describe the bug** 
Uninstalling from NMM 0.65.2, downloading and trying to run NMM 0.65.5 gives me this error message:

> Unable to execute file:
C:\Program Files\Nexus Mod Manager\NexusClient.exe
CreateProcess failed; code 740.
The requested operation requires elevation.

**Environment**
- NMM version: _0.65.5_
- Mod(s) used: _NA_

**To Reproduce**
 _Windows 10, not latest version, version unknown._

**Additional information** 
_NA_

**Comment by griffinlord775** [comment]
It turns out that the manager will still load regardless of the issue. However, the game names when loading are blanked out.

**Comment by squid-box** [comment]
PR #349 will take care of the missing titles, should be included in the next release.
