### ISSUE TITLE
Can't install certain mods ( XML Schema)

### ISSUE THREAD

**Issue by KorneelGrumieau** [Nexus-Mods/Nexus-Mod-Manager#362]
**Describe the bug** 
When i try to install NVAC and proceed to install it , it stops and displays the following message when i click on the '?' icon.
A problem occurred during install: The headelement of a W3C XML-schema should be <schema> and the headspace should be https://www.w3.org/2001/XMLSchema . The mod was not installed - loosely translated

**Environment**
- NMM version: 0.62.2
- Mod(s) used: *check screenshots* , bug occured during install of https://www.nexusmods.com/newvegas/mods/53635/ : NVAC

Trace log : When i try to install it , it doesnt produce / send me a 'normal' error with a trace log , my most recent trace log is from yesterday ( when i didnt have it installed ) though i will add it IF it helps
[TraceLog20180601170851.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2064830/TraceLog20180601170851.txt)

**To Reproduce**
Reinstalling NVC --> download manager --> error occured

**Additional information** 
Screenshots of the problem ( translation is at the top of the report ) https://i.imgur.com/xPzehxE.png https://i.imgur.com/Iw9UxjG.png https://i.imgur.com/FQdOcim.png

**Comment by Dope2001** [comment]
I get the same problem when I try to install mods.

**Comment by squid-box** [comment]
This error was fixed in 0.65.4, so update NMM and see if you're still getting this error.

**Comment by squid-box** [comment]
No reply in almost a month, assuming this problem was solved by 0.65.4.
