### ISSUE TITLE
login error : cannot reach the nexus login server. either your firewall is blocking NMM.

### ISSUE THREAD

**Issue by arnophilip** [Nexus-Mods/Nexus-Mod-Manager#366]
The problem is simple, when a upload a mod on nexus mod for skyrim, my nexus mod Manager open and can't Login because of this "login error. Cannot reach the nexus login server. EITHER YOUR FIREWALL IS BLOCKING NMM or problem with the server". But i had shecked my firewall and for him NMM is ok. And my password is ok too, this is like that sins 3 weeks and this make me angry... Please help me i don't know what to do, sins 3 weeks i upload mods on steam workshop

**Comment by squid-box** [comment]
I'm doing to assume you mean you're downloading mods, and point you to [this forum post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager) - You have to update to 0.65.2 or above in order to login/download mods through NMM.

**Comment by squid-box** [comment]
With no reply in 4 months I'm assuming this was indeed the issue.
