### ISSUE TITLE
Stuck at loading screen...forever.

### ISSUE THREAD

**Issue by Manahotep** [Nexus-Mods/Nexus-Mod-Manager#368]
_Please give as much information as you can, replace/remove italicized text._
I cannot load a previous game or create a new one> i have the same mods i have played with for over 300+ hours but have not played in a few months. 
**Describe the bug** 
_A short description of what the problem is_
The launcher allows me to hit play, the the garage scene comes up and i can hit new or continue etc. The game then plays the music and camera pans around the garage.... and does that forever. 
I also cannot launch the game using F4SE as i have a newer version of the game? Can i go backwards?

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
This sounds like a problem with a modded game, not with NMM? If so you'll have a better chance to get help from the Nexus Forums, this repo is just for the NMM application.

**Comment by squid-box** [comment]
With no reply in a month I'm closing the issue.
