### ISSUE TITLE
cant update my nexus

### ISSUE THREAD

**Issue by veke123** [Nexus-Mods/Nexus-Mod-Manager#370]
the following updates failed:
Nexus mod manager updater;Could not get verison
information from the update server

**Comment by AHawke117** [comment]
I'm having the same issue. Plus I'm not able to sign in.

**Comment by squid-box** [comment]
You'll need to update to 0.65.2 (or higher). Explanation can be found [here](https://www.nexusmods.com/news/13481). 

There's a link for 0.65.2 on that page, or you can grab the latest update from Github [here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases).
