### ISSUE TITLE
Crash on selecting game.

### ISSUE THREAD

**Issue by TheQKnight** [Nexus-Mods/Nexus-Mod-Manager#372]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
I went through the installation of the mod and selected fallout 4. Once run it again and select fallout 4 again, it crashes with this log.

**Environment**
- NMM version: 0.65.2

**To Reproduce**
Idk how, no one else seems to be having an issue

Heres the log:
[TraceLog20180604170917.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070354/TraceLog20180604170917.txt)

**Comment by squid-box** [comment]
Trace indicates this is the same issue as #300, NMM can't find Fallout4.exe.

Check #300 for potential solutions.
