### ISSUE TITLE
"Loot launch parameters" feature seems to be borked?

### ISSUE THREAD

**Issue by Valethar** [Nexus-Mods/Nexus-Mod-Manager#373]
Just downloaded the latest NMM update (0.65.5). On the main page here, the update states it contains the following:

New features:
    Added launch parameters to LOOT for supported games

Where exactly does one change this? It appears to be defaulted to Oldrim, which is overriding the settings in LOOT itself for me. I've got LOOT set to default to SSE, but it _always_ opens to Oldrim instead, even if I go in and change the default in LOOT to _any_ of the other supported games. 

I can't find a setting in NMM to alter this. How does one go about actually setting or clearing this parameter so that LOOT will do what it's supposed to do on startup?

**Comment by squid-box** [comment]
It's hard coded in NMM, and added following what [LOOT's documentation](https://loot.github.io/docs/0.7.1/LOOT%20Readme.html) states (under Initialisation) meaning it'll launch with the parameter --game=x, where x is Oblivion, Skyrim, Fallout3 or FalloutNV.

SkyrimSE is not mentioned in the documentation, so I set Skyrim for both  Skyrim and SkyrimSE - sounds like that was a mistake.

I'll revert that and hopefully it makes it into the next release.

**Comment by Valethar** [comment]
That explains it. 

Never occurred to me that it might be hard coded, I was thinking there was an option somewhere I just wasn't finding, either in a menu or a settings file.  I'm in the process of reinstalling SSE and starting my mod installs from scratch because I goofed up somewhere and now have a corrupted 100+ hour save I can't salvage. LOOT was driving me nuts because it kept defaulting back to Oldrim and I didn't notice it at first, so couldn't figure out why the reinstall wasn't going as planned.  LOL

Thanks for the reply!  :D
