### ISSUE TITLE
Nexus NMM won't update or log me in.

### ISSUE THREAD

**Issue by Toastynipps45** [Nexus-Mods/Nexus-Mod-Manager#376]
I just downloaded Fallout 4 and I'm trying to download games for it. Except when I go on the Mod manager it doesn't allow me to log in. And when I try it keeps telling me that my firewall is blocking NMM or the login server is down. when I look for updates to solve the problem it keeps saying "update failed" and refuses to update. I'd really appreciate if you guys can tell me what's wrong and help me solve it.

**Comment by TromboneFreak** [comment]
[This is what I get every time](https://i.imgur.com/zcPxmXH.png)

**Comment by squid-box** [comment]
@Toastynipps45: Check [this forum post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager) - You have to update to 0.65.2 or above in order to login/download mods through NMM.

@TromboneFreak: that is a known issue and there's no fix currently.

**Comment by squid-box** [comment]
0.65.2 will never be possible to update through NMM - [download manually from Github](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and future updates will work.
