### ISSUE TITLE
Update Fail

### ISSUE THREAD

**Issue by djohn1** [Nexus-Mods/Nexus-Mod-Manager#378]
Manually updated to 65.2 and am able to login, but won't update/update fail.

![update fail](https://user-images.githubusercontent.com/40003767/41057764-9a3cb704-698d-11e8-8e23-f52496b1f43b.PNG)

**Comment by squid-box** [comment]
0.65.2 will never be possible to update through NMM - [download manually from Github](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and future updates will work.
