### ISSUE TITLE
Cant re-allow a mod

### ISSUE THREAD

**Issue by SagivLevy2003** [Nexus-Mods/Nexus-Mod-Manager#38]
i accidentally misclicked and disabled a mod, and when i tried to enable it, it just did nothing.. i can enable other mods but not this one .. i know that some mods need the installers, but its not the problem as my NMM has been up for the whole day and nothing popped up.. in game it warns me that the mod is missing too. help?

**Comment by Aster92** [comment]
I had a similar problem.
Try deleting it and reinstalling it. Worked for me.

**Comment by squid-box** [comment]
@JabbaTheTrump: Are you still having this issue with the latest version of NMM? If so could you attach a trace log of when you're trying to enable the mod?
