### ISSUE TITLE
titles of categories and mod names are condensed 

### ISSUE THREAD

**Issue by AcTenebras** [Nexus-Mods/Nexus-Mod-Manager#382]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
titles of categories and mod names are condensed to 4 letters making it super hard to use the manager

**Environment**
- NMM version: 0.65.2
no mods yet can't  install because of the title issue
![desktop screenshot 2018 06 07 - 18 42 00 78](https://user-images.githubusercontent.com/40044894/41131716-8b20e02e-6a82-11e8-9ecc-f7556d2a2092.png)

 install because of the title issue

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by SuckMyPixels** [comment]
Above all of the categories are individual sliding tabs labeled [ Name, Category, Install date, ] etc. You are able to click and drag those tabs to expand them to your liking. For your instance, in between the "Name" and the "Category" tab, click and drag the vertical bar separating those two tabs to the right to expand the category names. Hope i explained this well enough.. Let me know if you need further help. 

![example](https://user-images.githubusercontent.com/40651023/42011891-740c6a20-7a4a-11e8-954e-312c12db42d5.png)
