### ISSUE TITLE
Can't Connect To Server

### ISSUE THREAD

**Issue by Dragonscale1234** [Nexus-Mods/Nexus-Mod-Manager#385]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
For a good 2 months I've tried to install mods using NMM and have failed. Every time I try to install a mod NMM requires me to login again. I put in my information and it tells me, "Login error: Unexpected response from the Nexus login server. Please try again later." I've had to resort to installing manually which is a pain and doesn't work all the time. Could someone please give me options on how to fix this?

**Environment**
- NMM version: _0.63.14_
- Mod(s) used: _<link to mod(s) on Nexus>
Any mods
_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
It doesn't give me any trace logs. I've checked my folder and all of them are like a year old.

**To Reproduce**
 _How to reproduce the problem_
I don't know. Maybe just log out or disconnect from the servers and try to connect again.

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
I don't have anything else installed but if there is anything you would want to have just reply.

**Comment by squid-box** [comment]
Check [this forum post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager) - You have to update to 0.65.2 or above in order to login/download mods through NMM.

**Comment by ghost** [comment]
Okay, I presume I'll have to reinstall since I can't update it because it won't accept my login info. Will this effect any of my mods that are currently installed?

**Comment by squid-box** [comment]
The update will be the same whether you'd download it through NMM or manually. 

While your current version is fairly old, I believe it should "just work" after the update - though if you're worried I'd recommend doing a backup before upgrading.

**Comment by ghost** [comment]
Okay thank you for your help.
