### ISSUE TITLE
mod manager wont active mods

### ISSUE THREAD

**Issue by Whisper911** [Nexus-Mods/Nexus-Mod-Manager#39]
downloaded new mod manager it deactivated all mods and wont reactive them.new mods active

**Comment by TylerCode** [comment]
Can you give a little more detail? Such as any errors you are receiving or what happens when you try to actually activate them?

**Comment by Whisper911** [comment]
On Tuesday, April 11, 2017 11:01 AM, Tyler C <notifications@github.com> wrote:
 

 Can you give a little more detail? Such as any errors you are receiving or what happens when you try to actually activate them?—
