### ISSUE TITLE
"An exception occured in the script" when installing UIO

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#404]
So I'm getting this error when trying to install a mod called User Interface Organizer, for either Fallout 3 or Fallout New Vegas on an otherwise clean/vanilla game:

https://i.imgur.com/XE7GJS6.png

- NMM version: 0.65.6
- Mod(s) used:
https://www.nexusmods.com/newvegas/mods/57174 (FNV version)
https://www.nexusmods.com/fallout3/mods/20867 (F3 version)
- OS: Windows 10 build 1803 (17134.112)

Thank you!

**Comment by NXtGamer5000** [comment]
I am also getting this same issue and to no extent have not been able to fix it or find a way around it. Even vortex is getting a similar issue where when installing mods it freezes and crashes. Making it impossible for me to play with any mods

**Comment by ghost** [comment]
You can try using NMM 0.56.2, which can be downloaded here:
http://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=20&game_id=2295&source=FileExpander
It's the latest version which doesn't have this issue.

**Comment by NXtGamer5000** [comment]
i tired that but it does the same thing

**Comment by squid-box** [comment]
Some improvements were recently made that should resolve this, grab the latest version [here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and see if that works better.

**Comment by ghost** [comment]
It now installs the mod correctly, but there's another issue most likely related to this one, I'll file it soon.
