### ISSUE TITLE
0.65.6 Nexus Mod Manager constant crashing

### ISSUE THREAD

**Issue by unluckerdog** [Nexus-Mods/Nexus-Mod-Manager#407]
**Describe the bug** 
Constant crashing when I'm trying to load into the app, if it doesn't instacrash it starts running as a background process and becomes non-interactable
**Environment**
- NMM version: _0.65.6_
- Mod(s) used: _Nexus Mod Manager_

**To Reproduce**
Just occurs anytime I try to start the app

**Additional information** 
When I finally get past the game selection and load in, it will usually work fine.  Once I have launched the game it has never crashed a single time.  Before today it was crashing often but working enough to play games, now its unusable.

[TraceLog20180614212710.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2104517/TraceLog20180614212710.txt)
[TraceLog20180614212801.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2104518/TraceLog20180614212801.txt)
[TraceLog20180614212713.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2104519/TraceLog20180614212713.txt)

**Comment by squid-box** [comment]
Looks to be the same error as #389.

**Comment by squid-box** [comment]
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.
