### ISSUE TITLE
crashes when i start NMM 

### ISSUE THREAD

**Issue by andygami** [Nexus-Mods/Nexus-Mod-Manager#408]
tried reinstalling so many times. 

[TraceLog20180615142710.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105014/TraceLog20180615142710.txt)
[TraceLog20180615142800.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105015/TraceLog20180615142800.txt)
[TraceLog20180615142848.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105016/TraceLog20180615142848.txt)
[TraceLog20180615143030.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105017/TraceLog20180615143030.txt)
[TraceLog20180615143528.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105018/TraceLog20180615143528.txt)
[TraceLog20180615142459.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105019/TraceLog20180615142459.txt)
[TraceLog20180615142534.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2105020/TraceLog20180615142534.txt)

**Comment by squid-box** [comment]
This is the same issue as #300, look there for a solution.
