### ISSUE TITLE
Nexus mods wont connect to my skyrim SE

### ISSUE THREAD

**Issue by Preston132** [Nexus-Mods/Nexus-Mod-Manager#41]
My game crashed a few days ago and i have tried everything i can think of to get the Nexus mods to be recognized on the game. If anyone knows how to fix this please let me know because i cannot get it to work.

**Comment by squid-box** [comment]
@Preston132: Is this still a problem for you? If so, could you provide some more information?
What is happening, can you not find Skyrim SE with NMM (scanning for game modes)? Is NMM activating the mods, but they're not available in-game?

If this is no longer a problem I'll close the issue.

**Comment by squid-box** [comment]
With no reply after a week I'm closing the issue.
