### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by chima69** [Nexus-Mods/Nexus-Mod-Manager#411]
whenever I try to download a mod from Nexis to the manager, it requires me to login, so naturally I tried to but whenever I enter my info it say firewall Is blocking it. Plz someone help

**Comment by squid-box** [comment]
Check [this forum post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager) - You have to update to 0.65.2 or above in order to login/download mods through NMM.

**Comment by squid-box** [comment]
With no reply in 17 days I assume the problem is fixed.
