### ISSUE TITLE
Virtual Install [Solved]

### ISSUE THREAD

**Issue by yalisnna** [Nexus-Mods/Nexus-Mod-Manager#412]
**Describe the bug** 
I recently install Skyrim and I wanted to start modding it but I can't even start Mod Manager with this tracelog showing: [https://drive.google.com/file/d/1CrNM2U5i1QoKS26QsP8RTTM0WOUHCEEB/view?usp=sharing](url). I think that most important part of this is 'Could not find a part of the path 'F:\Games\Nexus Mod Manager\Skyrim\Mods\VirtualInstall'. I reinstall Skyrim and NMM.

**Environment**
- NMM version: _0.65.2
- Mod(s) used: none

Thanks.

**Comment by yalisnna** [comment]
Okay, I solved it. If anyone will have the same problem in directory D:\Nexus Mod Manager\Skyrim\Mods\virtualinstall put this file https://drive.google.com/open?id=1jRypdO2yAYxvd2EWAUUdRxxFbXxC2VrK

**Comment by squid-box** [comment]
Using the file you provided will only work if they have the same directory structure as you, and the exact same mods as you. I'd recommend against that as a solution.

In the first post and the trace log it references `F:\...\VirtualInstall\` and in your second post you point to `D:\...\virtualinstall\` - did you move your installations around in between? 

Did you maybe setup NMM first, then change folders around, and then NMM started crashing?

**Comment by dyslexicanaboko** [comment]
Just one more note on this moving your installation will result in a mismatch with the registry
