### ISSUE TITLE
"The hard-drive where you normally install mods for this game" is always seen as C:, while I've installed Dragon Age on E:

### ISSUE THREAD

**Issue by cristi1990an** [Nexus-Mods/Nexus-Mod-Manager#414]
In the setup for the game it asks me to choose the directory where I'll store my mods and install info. The virtual install path though gives me a warning. My game is installed on E: my mods I want stored on D: and C: I reserve for Windows and other programs.

![2018-06-17_17h48_58](https://user-images.githubusercontent.com/23399600/41509066-f2191612-7256-11e8-8b58-09abb33c2cf0.png)

**Comment by squid-box** [comment]
As the warning states, you need to have the mods and the virtual install folder on the same drive, this isn't something that NMM can change, if you want this set up then use a Multi-HD install as instructed in the warning.

**Comment by cristi1990an** [comment]
Ok, but I don't get it... I have no mods or games on my C drive

**Comment by squid-box** [comment]
What does the C: drive have to do with anything? You're still trying to put the mods and the virtuall install on two different drives, D: and E:.

To use the Virtual Install option you'll need to have both on the same drive, it doesn't matter which it is.

**Comment by cristi1990an** [comment]
Ah, sorry. No, no, that's not the problem. Here, probably you'll understand from this picture: 

![2018-06-18_13h02_30](https://user-images.githubusercontent.com/23399600/41530174-0ed16f74-72f8-11e8-996f-c402471b38b8.png)

It says "Expected HD: C:\"

**Comment by DuskDweller** [comment]
Dragon Age install mods in the Documents folder ( Documents\Bioware\Dragon Age ) that is on C.

**Comment by cristi1990an** [comment]
Ah, gotcha. Thank you!
