### ISSUE TITLE
Being Used In Another Process

### ISSUE THREAD

**Issue by Kylestar1875** [Nexus-Mods/Nexus-Mod-Manager#416]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
every time i try to open nexus or download a mod i get a error with the trace log window opening up

**Environment**
- NMM version: Latest
- Mod(s) used: any
Trace file has been created: TraceLog20180618001146.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout 4 (Fallout4)
    Installation Path: F:\Steam 2\steamapps\common\Fallout 4
    Install Info Path: F:\Games\Nexus Mod Manager\Fallout4\Install Info
    Mod Path: F:\Games\Nexus Mod Manager\Fallout4\Mods
    Mod Cache Path: F:\Games\Nexus Mod Manager\Fallout4\Mods\cache
    Mod Download Cache: F:\Games\Nexus Mod Manager\Fallout4\Mods\downloads
    Overwrite Path: F:\Games\Nexus Mod Manager\Fallout4\Install Info\overwrites
    Virtual Install Path: F:\Games\Nexus Mod Manager\Fallout4\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Users\aaron\OneDrive\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Users\aaron\OneDrive\Nexus Mod Manager\GameModes
            Checking: Fallout4.CSharpScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.CSharpScript.Fallout4CSharpScriptType
            Checking: Fallout4.XmlScript.dll
                Initializing: Nexus.Client.Games.Fallout4.Scripting.XmlScript.Fallout4XmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Users\aaron\OneDrive\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: F:\Games\Nexus Mod Manager\Fallout4\Mods
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Armor and Weapon Keywords Community Resource v4.02-6091-4-02.rar
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Armorsmith Extended v3.32 incremental update from v3.31-2228-3-32.rar
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Caliente's Beautiful Bodies Enhancer - v2.6.1-15-2-6-1 (2).7z
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Caliente's Beautiful Bodies Enhancer - v2.6.1-15-2-6-1.7z
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Commonwealth Cuts 2.4-11402-2-4 (2).zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Commonwealth Cuts 2.4-11402-2-4.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Craftable Ammo 0.9-798-0-9.7z
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\DEF_UI 1.4.3-10654-1-4-3.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\EBT_Basic v101-212-1-01.7z
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Eli's Armour Compendium - CBBE and BodySlide 1.5-22431-1-5.7z
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Fortaleza Armor - BodySlide Files-10692-5-1.rar
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Fortaleza Armor - Main file-10692-5-1.rar
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Fortaleza Armor - Merge patch-10692-5-1.rar
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Full Dialogue Interface - All languages - NMM installer - Beta12-1235-Beta12.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\HUDFramework 1.0f-20309-1-0f.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Improved Map with Visible Roads 2.0-1215-2-0.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\LooksMenu v1-6-8-12631-1-6-8.7z
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Mod Configuration Menu 1.27-21497-1-27 (2).zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Mod Configuration Menu 1.27-21497-1-27.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Ponytail Hairstyles by Azar v2_5a - Loose files-8126-2-5a.zip
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\The Eyes of Beauty Fallout Kaleidoscope Edition - All-in-One-133-3-2.7z
            Registered.
        Found: F:\Games\Nexus Mod Manager\Fallout4\Mods\Valkyr Face Texture v1.1-3841-1-0.rar
            Registered.
        
        Tracing an Unhandled Exception:
        Running Threads (1)
    3 () 
        Aborted
        Exception: 
Message: 
	The process cannot access the file 'C:\Users\aaron\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_1grgskuxockvazi0t2rvja3arnhlf1u5\0.65.2.0\rs2ics4h.newcfg' because it is being used by another process.
Full Trace: 
	System.IO.IOException: The process cannot access the file 'C:\Users\aaron\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_1grgskuxockvazi0t2rvja3arnhlf1u5\0.65.2.0\rs2ics4h.newcfg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetCreationTimeUtc(String path, DateTime creationTimeUtc)
   at System.Configuration.Internal.WriteFileContext.DuplicateFileAttributes(String source, String destination)
   at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success)
   at System.Configuration.Internal.InternalConfigHost.StaticWriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at Nexus.Client.ModManagement.ModRegistry.DiscoverManagedMods(IModFormatRegistry p_frgFormatRegistry, IModCacheManager p_frgCacheManager, String p_strSearchPath, Boolean p_booRecurse, IEnvironmentInfo p_eiEnvironmentInfo, IGameMode p_gmdGameMode, String[] p_strExcludedSubDirectories)
   at Nexus.Client.ApplicationInitializer.InitializeServices(IGameMode p_gmdGameMode, IModRepository p_mrpModRepository, NexusFileUtil p_nfuFileUtility, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
Looks to be same issue as #389.

**Comment by squid-box** [comment]
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.
