### ISSUE TITLE
Folder and Mod Name Condensed

### ISSUE THREAD

**Issue by HowzitMan** [Nexus-Mods/Nexus-Mod-Manager#417]
All folder and mod names are condensed and only way to see full name is to highlight item to rename. Can't find a way to fix issue. Have tried uninstall and reinstall to no avail.

**Environment**
- NMM version: 0.65.2

https://lh3.googleusercontent.com/m_ZXYlnS8KPfaL2DtNA3EVU5U67aOkSnMD6MUu8d3_CG3yE8NUjIt0WfADN2WtWucZqMXPnE9WDzjNTZT1KBLdQ5qa3xUwsUnlqgogtam3cwqlYH6b2mxvnAoDfZeHZ5RHOLPuB_fsFkn_rqLd2IVGkxOKBszV8hIad4qmPpZG7LSBCAZZbjd6C6Hy4zc-dgxh2vIrp4sdY8-GFN-EDqTlROfeaW1seTj8F0AuAihwvNuwOPIYYuVB7smPQNr3rClobM3vzivrTKUeAuc-fMfc0qLQ8M4QGGnwkY4ggndjnbkzE044hME4gB1QynPlaGzdvFI7N-tJIzWAScqSwHpay5lRoFA_fHExKr8OIQdZWUuQvNsr6vvQPk1TP1qiPJJjnWPkR04-M2e1b5y3ZsJd7HjmYFIskNCwff8EUQwETC7W24LL8odde3fDBCIWZdnbu6XVDInTZ_zybb1L-GmLpls1fH4Gn28YE7mplJbK23d-mZBdb5lpE0XBpVo4tURT7zDvS7aSNQWKTV4Zvvq_-T4fRgRjycSad0IDDUAxpsFR4eqEkAESB_s5yC3UhFqkU-jQWLUCDnm3l_HiQ3N90iuWtC3k5DpAe2KlwU=w1299-h974-no

**Comment by squid-box** [comment]
You just need to resize the columns, here's a video showing how: https://youtu.be/c9pgqyPG0vo
