### ISSUE TITLE
Launch LOOT from NMM

### ISSUE THREAD

**Issue by hjstaruk** [Nexus-Mods/Nexus-Mod-Manager#42]
When I launch LOOT from the NMM Supported Tools drop-down list, it always starts with the game that I last used LOOT for. Switching games in NMM does not effect the game that LOOT runs for.
When I launch LOOT from outside of NMM, I use shortcuts that have a "--game=" parameter.
Does NMM not support "--game=" parameters or do I have something wrong in my setup?
Thanks

**Comment by squid-box** [comment]
As of 0.65.5 this is added to NMM.
