### ISSUE TITLE
NMM Startup Crash

### ISSUE THREAD

**Issue by Smerdokryl** [Nexus-Mods/Nexus-Mod-Manager#422]
**Describe the bug** 
NMM throws an error on startup. Reinstall did not help

**Environment**
- NMM version: _0.65.2.0_

[TraceLog20180620162249.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2119467/TraceLog20180620162249.txt)

**Comment by squid-box** [comment]
Could be the same as #384 - you could try upgrading to 0.65.6 and see if it works better.

**Comment by Smerdokryl** [comment]
I recently got fed up with the whole .NET framework thing, so I deleted **_all_**of it, including the registry folder, and installed the latest core and framework. The NET Framework Setup folder, however, does not seem to have been created (there is a ".NET FRAMEWORK" folder, though). Perhaps, that is the reason? How could I fix it?

**Comment by Smerdokryl** [comment]
(I mean the registry folder, just in case)

**Comment by squid-box** [comment]
Sorry, no idea. I'd look into repairing your .NET installation. Not much that can be done from the NMM side of things for this.
