### ISSUE TITLE
NMM won't start 

### ISSUE THREAD

**Issue by paczpan** [Nexus-Mods/Nexus-Mod-Manager#427]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
NMM is failing to load after I choose Fallout 4. I installed mods using NMM and it worked last time and I havent installed any mods since. 

**Environment**
- NMM 0.65.2-4-0-65-2 (installation file)
- Mod(s) used: there are many. If it's so important then I will give you a list later. I will skip that for now

[TraceLog20180621092911.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2122592/TraceLog20180621092911.txt)

**Comment by squid-box** [comment]
Same problem as #300 - check that issue for workarounds.

**Comment by paczpan** [comment]
Oh yeah. Renamed exe file. Thanks!
