### ISSUE TITLE
Nexus Mod Manager not recognizing INI file...

### ISSUE THREAD

**Issue by BillStewart1973** [Nexus-Mods/Nexus-Mod-Manager#43]
Ok so apparently there is a path issue here. I am not sure how to fix it, could someone please assist me with this issue. thanks.

**Comment by BillStewart1973** [comment]
It is for Fallout 4, sorry forgot to mention that. I am a little annoyed about it.

**Comment by squid-box** [comment]
@BillStewart1973: If this is still happening, could you provide some more information? What error message are you getting? When do you get it (trying to select Fallout 4 in NMM, when trying to launch it, etc?)

**Comment by squid-box** [comment]
With no reply after a week I'm closing the issue.
