### ISSUE TITLE
NexusModManager bug/thing (I dunno what it really is)

### ISSUE THREAD

**Issue by ItsYaBoiiRoan** [Nexus-Mods/Nexus-Mod-Manager#431]
**Describe the bug**
Whenever I try to launch NNM, I get an error something close to "Can't get access to file C:\Users\User\AppData\Local\Black_Tree_Gaming\NexusClient.exe._Url_2eir2d35cqbpwgw1etv4i5pyavanea0r\0.65.2.0\pq1dg3cn.newcfg because it's already used by another process (I don't know if I translated the last part right, as English isn't my native language)

**Environment**
- NMM version: 0.65.2
- Mod(s) used: I can't start the manager, so I'm unable to send the links of my 60 or so mods.

Please remember to attach any trace logs you get in connection to this problem. Without these, it will often be very hard to track down the bug. 
[TraceLog20180621210720.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2125028/TraceLog20180621210720.txt)

**To Reproduce**
 I have no idea how someone could reproduce it, as I did absolutely nothing to get it and I'm not even sure if it's technically a bug.

**Additional information** 
Unfortunately, as previously said, I have no idea what it could've caused it since it just happened out of nowhere, first time having it too, and it was after I downloaded Skyrim Special Edition after a few months not playing it. (Also, it could be the file is translated in Dutch, so you might want to translate it)

**Comment by squid-box** [comment]
It's a duplicate of #389 , unfortunately a lot of people are reproducing this.

**Comment by squid-box** [comment]
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.
