### ISSUE TITLE
Mod Manger not detecting Skyrim SE on Download

### ISSUE THREAD

**Issue by Grimjoke29** [Nexus-Mods/Nexus-Mod-Manager#435]
**Describe the bug** 
When ever I try and download a mod from the nexus site for Skyrim SE ( https://www.nexusmods.com/skyrimspecialedition/mods/top/ ), Nexus Mod Manager begins scan for games. Skyrim SE is not listed in scanned for games. But when I installed Nexus Mod Manager it detected Skyrim SE. How do I fix this so I can download and install Mods. Do I have to install manually?

- Game: Skyrim SE
- NMM version: 0.65.2
- Mod(s) used: Any from Nexus Mod Site

**Comment by Grimjoke29** [comment]
I can post any files if needed

**Comment by squid-box** [comment]
So if I read this correctly you're not seeing Skyrim SE in the list of games available when scanning for games?

If so, you could go to `C:\Program Files\Nexus Mod Manager\GameModes` (or wherever you installed your NMM) and verify that there are files called `SkyrimSE.dll`, `SkyrimSE.CSharpScript.dll`, and `SkyrimSE.XmlScript.dll` there.

If they're missing, try reinstalling NMM.

**Comment by Grimjoke29** [comment]
Correct, but when I do the initial scan it finds Skyrim SE, but when I download from nexus site using mod manager it doesn't even show the option of Skyrim SE.

**Comment by squid-box** [comment]
OK, I'm a bit lost. So you've scanned for, and found, Skyrim SE:

![image](https://user-images.githubusercontent.com/864820/42535048-b7ac709c-848e-11e8-964d-21b05782d540.png)

And when you try to download a mod from the Nexus website - what happens? You're thrown back into scanning for games and Skyrim SE is no longer found?

![image](https://user-images.githubusercontent.com/864820/42535171-f4a045e6-848e-11e8-8792-1b4250039fb5.png)

**Comment by Grimjoke29** [comment]
bingo, it's not even listed

**Comment by squid-box** [comment]
OK, that's very weird :D

Then could you please run NMM in trace mode ([see here for instruction](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log)) and upload the trace file from when you do this?

**Comment by Grimjoke29** [comment]
I couldn't find trace, so reinstalled after checking for any old Nexus mod manager files.  Found a couple. Now the system is working. thanks sorry for the headache

**Comment by squid-box** [comment]
No worries, it was an interesting problem :)
Happy gaming!
