### ISSUE TITLE
Trying to mod Fallout 4 VR. NMM Crashes on launch.

### ISSUE THREAD

**Issue by Neighboryy** [Nexus-Mods/Nexus-Mod-Manager#437]
I'm trying to use NMM to install mods to Fallout4VR. I am following this guide on how to make it work without installing Fallout4: https://www.reddit.com/r/Fallout4VR/comments/7kq5qe/how_to_get_nexus_mod_manager_to_work_with_fallout/ , but whenever I try to launch NMM It just crashes and it forwards me to a log dump

**Environment**
- NMM version: _0.65.2_
[TraceLog20180622202841.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2128572/TraceLog20180622202841.txt)

**Comment by squid-box** [comment]
Yeah, that guide will give you that crash. See #300 for some work-arounds.
