### ISSUE TITLE
wont show mod catigory name just the first 2 letters

### ISSUE THREAD

**Issue by SidenCorp** [Nexus-Mods/Nexus-Mod-Manager#438]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
wont show mod catigory name just the first 2 letters

**Environment**
- NMM version: _0.65.2_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
You just need to resize the name column, here's a handy pic showing how to resize the category column from the Nexus Forums user DrakeTheDragon:
![image](https://user-images.githubusercontent.com/864820/42532885-7bfab6d6-8488-11e8-871c-f851e09a2af1.png)
