### ISSUE TITLE
NNM do not start under Windows 10

### ISSUE THREAD

**Issue by unhappytroll** [Nexus-Mods/Nexus-Mod-Manager#44]
just traps right after doubleclick on the icon. if anyone can point me where  error log placed I will attach it.

**Comment by vlad76** [comment]
I am having the same issue. Reinstalling the application does not work

**Comment by squid-box** [comment]
If this is still happening for you:

**If it crashes on start**
Try going to %LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_<gibberish>\0.65.4.0 (or the version number you're trying to use) and renaming user.config to something else and see if that fixes the crash.

If that does not help, you could check the Windows Event Viewer logs, specifically look under Windows Logs -> Application.

Scroll down to around the time you were trying to start NMM and see if you can find any Error logs with the Source .NET Runtime (and the application NexusClient.exe). If you do, copy the information from that log and paste it here and we might be able to help you out :)

**If it crashes after it has started**
There should be a trace file in your Documents folder, in an NMM folder.

**Comment by squid-box** [comment]
With no reply after a week I'm closing the issue.
