### ISSUE TITLE
NMM - Legacy 0.52.4 crashing after scanning games

### ISSUE THREAD

**Issue by Clarencio1994** [Nexus-Mods/Nexus-Mod-Manager#441]
After checking the games it just immediately crashes
I'm playing Skyrim on Win7
--
Already tried installing NMM - Legacy 0.52.3 before installing NMM 0.52.3 -- Doesn't help.
0.65 versions doesn't work on my side.

Trace file has been created: TraceLog20180623063222.txt
Mod Manager Version: 0.52.4.0
OS version: Microsoft Windows NT 6.1.7600.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager - Legacy\GameModes
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DarkSouls.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DarkSouls2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DarkSouls2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DragonAge.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonAge2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\DragonAge2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Grimrock.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Grimrock.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Morrowind.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Oblivion.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: Starbound.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Starbound.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\Witcher2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: WorldOfTanks.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager - Legacy\GameModes\WorldOfTanks.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Bethesda Softworks\Fallout3\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Bethesda Softworks\FalloutNV\Installed Path
                Found 
            Returned:  (IsNull=True)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Bethesda Softworks\Morrowind\Installed Path
                Found 
            Returned:  (IsNull=True)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Bethesda Softworks\Oblivion\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Bethesda Softworks\Skyrim\Installed Path
                Found C:\Program Files\R.G. Mechanics\Skyrim - Legendary Edition\
            Returned: C:\Program Files\R.G. Mechanics\Skyrim - Legendary Edition\ (IsNull=False)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236390\Installed
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Found 
            Returned:  (IsNull=True)
    Starting search.

Tracing an Unhandled Exception:
Exception: 
Message: 
	The property 'InstalledGames' could not be created from it's default value. Error message: There is an error in XML document (2, 3).
Full Trace: 
	System.ArgumentException: The property 'InstalledGames' could not be created from it's default value. Error message: There is an error in XML document (2, 3).
   at System.Configuration.SettingsPropertyValue.Deserialize()
   at System.Configuration.SettingsPropertyValue.get_PropertyValue()
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Nexus.Client.Properties.Settings.get_InstalledGames()
   at Nexus.Client.Bootstrapper.GetInstalledGameModes(GameModeRegistry p_gmrSupportedGameModes)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] p_strArgs)
   at Nexus.Client.Program.Main(String[] p_strArgs)

Running Threads (0)

**Comment by squid-box** [comment]
Since you're using the legacy version of NMM, you'll probably get no help here. You could try creating an issue on the [NMM Legacy Github repo](https://github.com/Nexus-Mods/Nexus-Mod-Manager-Legacy) instead, but I doubt anyone works on that version.
