### ISSUE TITLE
ESL file installation issue

### ISSUE THREAD

**Issue by GamerLadyJules** [Nexus-Mods/Nexus-Mod-Manager#443]
**Describe the bug** 
When installing .ESL files, plugin does not show in plugin list until NMM is restarted.  Once restarted then have to manually check the .ESL plugin to make it active.

**Environment**
- NMM version: 0.65.6
- Mod(s) used: https://www.nexusmods.com/fallout4/mods/30866 and https://www.nexusmods.com/fallout4/mods/31732

**Comment by Athelbras** [comment]
I have the same problem with 0.65.6 and the new 0.65.7 ...

When I and other players try to install the .ESL version of one of my mods, the .ESL file is not shown in the Plugins tab and is not activated.  NMM must be exited after the install completes, restarted, and the .ESL file (which is now shown) explicitly activated.

The installer has a simplistic install package; see the Optional Files download: "Settlement Salvage Bot - ESL", which can be found here: 

https://www.nexusmods.com/fallout4/mods/32212?tab=files

[  EDIT:  also occurs with 0.65.10  ]

**Comment by jbostrus** [comment]
Can anyone verify if this is still happening with 0.65.10?

**Comment by Athelbras** [comment]
Yes, this bug continues to occur in 0.65.10.  For me it *always* happens with my .ESL file installs.

Here are some simple install package examples:

Settlement Tidy Bot - ESL
https://www.nexusmods.com/fallout4/mods/33217

Settlement Radar Station - ESL
https://www.nexusmods.com/fallout4/mods/30665

**Comment by jbostrus** [comment]
I pushed a patch to fix this problem. Since there's no telling when a release will be built by DuskDweller I updated the file I put on issue #654.

**Comment by Athelbras** [comment]
I confirm that it fixes the .ESL install/uninstall problems that consistently occurred for my various mods.

Great work.  Thank You!!!
