### ISSUE TITLE
Login error (Fallout new Vegas)

### ISSUE THREAD

**Issue by Kevinladder90** [Nexus-Mods/Nexus-Mod-Manager#446]
Hi ! In these days I had some problems with my Nexus Mod manager.
The program installed on my computer says me that I can't login because the application can not reach the NMM server. I have also disactivated my windows firewall and my antivirus (Avira). But the situation is not changed...So I don't know how to continue to install other mods and login with my account. I can only login on the website, but not on my computer's program. I hope you will help me!

- NMM version: 0.63.14
- NMM mods:
![nexus ](mods](https://user-images.githubusercontent.com/40630713/41970875-a68775f0-7a0c-11e8-8af4-560d6c124d1d.PNG))

![nexus mod manager login error](https://user-images.githubusercontent.com/40630713/41970853-9758b30a-7a0c-11e8-867e-409b2d624aac.PNG)

**Comment by whitefight** [comment]
I am having the same issue with Fallout 4.Not sure if it's an issue with Nexus servers or what,but it's annoying as fuck.

**Comment by squid-box** [comment]
Check [this forum post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager) - You have to update to 0.65.2 or above in order to login/download mods through NMM.

**Comment by Kevinladder90** [comment]
Hi Squid box!I've installed the new version yesterday! Thank you the same
