### ISSUE TITLE
I cannot set up my install folders for the NMM

### ISSUE THREAD

**Issue by tamas9090** [Nexus-Mods/Nexus-Mod-Manager#447]
**Describe the bug** 
Nexus encounters an error and needs to close, i attached the log./ i have had nexus before
[TraceLog20180627162552.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2141912/TraceLog20180627162552.txt) I have copy pasted for you down here. i use NMM 0.65.2

Trace file has been created: TraceLog20180627162552.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Users\user\Desktop\mods mo creatures\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Users\user\Desktop\mods mo creatures\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Breaking Wheel (BreakingWheel)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\545890\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Dragon's Dogma (DragonsDogma)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\367500\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout3\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout 4 (Fallout4)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\377160\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout4\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\FalloutNV\Installed Path
                Found 
            Returned:  (IsNull=True)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    No Man's Sky (NoMansSky)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\275850\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Oblivion\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Skyrim\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim Special Edition (SkyrimSE)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\489830\Installed
                Getting Steam install folder.
                SkyrimSE is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\SkyrimSE\Installed Path
                Found 
            Returned:  (IsNull=True)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236930\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    The Witcher 3 (Witcher3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\292030\Installed
                Getting install folder from Uninstall.
                Found 
            Getting GOG install folder.
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    XCOM 2 (XCOM2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\268500\Installed
                Getting Steam install folder.
                XCOM2 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Starting search.
Loading Game Mode Factories for Installed Games...
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) SkyrimSE
Game Mode Factory Selected: Skyrim Special Edition (SkyrimSE)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Exception: 
Message: 
	The process cannot access the file 'C:\Users\user\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_xquxzsd0iuljt1ubdft5y5kqmb0hrybr\0.65.2.0\rb4n4fxk.newcfg' because it is being used by another process.
Full Trace: 
	System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_xquxzsd0iuljt1ubdft5y5kqmb0hrybr\0.65.2.0\rb4n4fxk.newcfg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetCreationTimeUtc(String path, DateTime creationTimeUtc)
   at System.Configuration.Internal.WriteFileContext.DuplicateFileAttributes(String source, String destination)
   at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success)
   at System.Configuration.Internal.InternalConfigHost.StaticWriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at Nexus.Client.Games.Settings.SetupDirectoriesControlVM.SaveSettings(Boolean p_booDelaySettings)
   at Nexus.Client.Games.SetupBaseVM.Save()
   at Nexus.Client.Games.Gamebryo.SetupForm.wizSetup_Finished(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (1)
    3 () 
        Aborted

Tracing an Unhandled Exception:
Exception: 
Message: 
	Cannot access a disposed object.
Object name: 'ApplicationInitializationForm'.
Full Trace: 
	System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ApplicationInitializationForm'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Nexus.Client.ApplicationInitializationForm.Task_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Nexus.Client.BackgroundTask.set_Status(TaskStatus value)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Environment**
- NMM version: _0.65.2_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
[TraceLog20180627162552.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2141900/TraceLog20180627162552.txt)

**Comment by squid-box** [comment]
Duplicates #389, currently no solution available :(

**Comment by squid-box** [comment]
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.
