### ISSUE TITLE
NMM Crashes when I attempt to activate or deactivate a mod. 

### ISSUE THREAD

**Issue by jdmmax** [Nexus-Mods/Nexus-Mod-Manager#448]
**Describe the bug** 
Any time I am activating or deactivating a mod NMM will crash. 

**Environment**
- NMM version: 0.65.2
- Mod(s) used: https://www.nexusmods.com/fallout4/mods/15

[TraceLog20180628014605.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2144503/TraceLog20180628014605.txt)

**To Reproduce**
From the NMM manager screen click on the disable selected mods button.  The screen will switch over to the progress pop up then crash.  

**Additional information**

**Comment by squid-box** [comment]
Error in question is:
`Access to the path 'C:\Games\Nexus Mod Manager\Fallout4\Mods\VirtualInstall\VirtualModConfig.xml' is denied.`

You could see if you can access that file manually, and maybe check if it's write-protected.

**Comment by jdmmax** [comment]
It worked thank your!

**Comment by Lady3vil** [comment]
[TraceLog20180702154744.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2157072/TraceLog20180702154744.txt)
[TraceLog20180702154951.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2157073/TraceLog20180702154951.txt)
[TraceLog20180702155138.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2157074/TraceLog20180702155138.txt)

mods dont install, or download, my  firewall was turned off at the time when I tried to do what you said above. Dosent work. I find the file and Notepad ++ brings up this: <?xml version="1.0" encoding="utf-8"?>
<virtualModActivator fileVersion="0.3.0.0">
  <modList />
</virtualModActivator>
I right click so I can open the containing file it says it doesn't exist. I go to look for it in my games folder 
C:\Games\Nexus Mod Manager\Fallout4\Mods\VirtualInstall
A file folder called Overwrites (empty), and the VirtualModConfig.xml 

I have no clue what any of this means, can we please get this fixed soon. Thank you.

**Comment by squid-box** [comment]
A long time later, your issue is not the same as the one in this issue - it looks like your Fallout 4 .ini file is in some unexpected state.

If you're still having the issue, please open a separate issue for it with a stacktrace from the latest NMM version.
