### ISSUE TITLE
My game keeps crashing when I try to open Fallout 4 in mod manager

### ISSUE THREAD

**Issue by Antman924** [Nexus-Mods/Nexus-Mod-Manager#449]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
When I open Nexus Mod Manager and press Fallout 4 it gives me a message about an error

**Environment**
- NMM version: 0.65.2.0
- Mod(s) used: Don't know

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
[TraceLog20180628102944.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2145703/TraceLog20180628102944.txt)

**To Reproduce**
 _How to reproduce the problem_
Don't know

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
Headphones and OBS

**Comment by squid-box** [comment]
Duplicates #389, currently no solution available :(

**Comment by squid-box** [comment]
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.
