### ISSUE TITLE
Will not open Nexus mod manager after most recent download. this has never happened. Trace log included

### ISSUE THREAD

**Issue by Tross1990** [Nexus-Mods/Nexus-Mod-Manager#450]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
Everytime i download Nexus and install it on my second drive or main drive it will not open.

**Environment**
- NMM version: _0.65.2_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_
Simply open the installed file "nexus mod manager" and it will crash everytime instantly

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
[TraceLog20180628122802.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2146681/TraceLog20180628122802.txt)

**Comment by squid-box** [comment]
Duplicate of #300, check there for some workarounds,

**Comment by Tross1990** [comment]
fixed it instantly upon renaming. Thank you. I completely overlooked the fact that i renamed the launcher for my steam link.
