### ISSUE TITLE
My Nexus does not load and it crashes after a while.

### ISSUE THREAD

**Issue by GuiBossi** [Nexus-Mods/Nexus-Mod-Manager#452]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
It does not load and it crashes after a while, I have no idea why. Already trird to uninstall it an install it again but it did not work. 

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
[TraceLog20180629125804.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2150753/TraceLog20180629125804.txt)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
Duplicates #389, currently no solution available :(

**Comment by squid-box** [comment]
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.
