### ISSUE TITLE
Crashes almost instantly when I open.

### ISSUE THREAD

**Issue by HyperionExile** [Nexus-Mods/Nexus-Mod-Manager#454]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any
[TraceLog20180701092916.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2152948/TraceLog20180701092916.txt)
[TraceLog20180701092735.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2152949/TraceLog20180701092735.txt)
[TraceLog20180701092504.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2152950/TraceLog20180701092504.txt)
[TraceLog20180701091321.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2152951/TraceLog20180701091321.txt)
[TraceLog20180701085813.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2152952/TraceLog20180701085813.txt)

 trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
The error is:
`Access to the path 'C:\Users\Comp\AppData\Local\Fallout3\plugins.txt' is denied.`

A workaround could be to check whether you can access this file, and maybe see if it's write-protected.

**Comment by dyslexicanaboko** [comment]
I recommend verifying the existence of the file. If it doesn't exist create it. If it does exist inspect the file. You can back up that file, create a new one and copy the contents to it. Then you should be okay because it has your permissions since you created it. This is definitely a permissions issue if I had to guess, possibly attributes aren't being set at the time of creation.

**Comment by dyslexicanaboko** [comment]
@HyperionExile is this still an issue with the latest version?
