### ISSUE TITLE
Could not connect to update server

### ISSUE THREAD

**Issue by Stealch** [Nexus-Mods/Nexus-Mod-Manager#457]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
The following update filed:
Nexus Mod Manager Updater: Could not get version information from the update server.

**Environment**
- NMM version: _0.65.2_
- Mod(s) used: _<link to mod(s) on Nexus>_
Not important
_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
![2018-07-04_12-07-10](https://user-images.githubusercontent.com/14859190/42268234-ab6cadd4-7f83-11e8-9420-84c342712beb.png)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
This bug is presetn on previously version. To 0.65.2 i update manualy. Previously version cold not connect to any server, accept login on nexus. In 0.65.2 login successfully, but the update problem still present.

**Comment by squid-box** [comment]
This is fixed in the latest version of NMM. You'll need to [download it manually from Github](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8).
