### ISSUE TITLE
Trace Log Problem

### ISSUE THREAD

**Issue by YourMotherIsDisappointedInYou** [Nexus-Mods/Nexus-Mod-Manager#458]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
The Trace Log issue is very common, but my problem seemingly does not have an answer. The Trace Log message is : Could not load type 'Nexus.Client.Games.SupportedToolsLauncherBase' from assembly 'ModManager.Interface, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.

**Environment**
- NMM version: 56.2
- Mod(s) used: https://www.nexusmods.com/newvegas/mods/49152/
                       https://www.nexusmods.com/newvegas/mods/37002

Here is the Trace Log I get right now: 
Trace file has been created: TraceLog20180704024039.txt
Mod Manager Version: 0.56.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\DarkSouls.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DarkSouls2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\DarkSouls2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\DragonAge.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonAge2.ModScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\DragonAge2.ModScript.dll: cannot find dependency ModScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Could not load type 'Nexus.Client.Games.SupportedToolsLauncherBase' from assembly 'ModManager.Interface, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.
Full Trace: 
	System.TypeLoadException: Could not load type 'Nexus.Client.Games.SupportedToolsLauncherBase' from assembly 'ModManager.Interface, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo p_eifEnvironmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] p_strArgs)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)
Here is the first Trace Log I got:
      Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading FalloutNV: Supported
Determining Game Mode: (From Selection Form) FalloutNV
Game Mode Factory Selected: Fallout: New Vegas (FalloutNV)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout: New Vegas (FalloutNV)
    Installation Path: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas
    Install Info Path: c:\Games\Nexus Mod Manager\FalloutNV\Install Info
    Mod Path: c:\Games\Nexus Mod Manager\FalloutNV\Mods
    Mod Cache Path: c:\Games\Nexus Mod Manager\FalloutNV\Mods\cache
    Mod Download Cache: c:\Games\Nexus Mod Manager\FalloutNV\Mods\downloads
    Overwrite Path: c:\Games\Nexus Mod Manager\FalloutNV\Install Info\overwrites
    Virtual Install Path: c:\Games\Nexus Mod Manager\FalloutNV\Mods
    NMM Link Path: 
Scanning for read-only files...
    Found C:\Users\wrigh\Documents\My games\FalloutNV\fallout.ini
        Made writable
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: FalloutNV.CSharpScript.dll
                Initializing: Nexus.Client.Games.FalloutNV.Scripting.CSharpScript.FalloutNVCSharpScriptType
            Checking: FalloutNV.XmlScript.dll
                Initializing: Nexus.Client.Games.FalloutNV.Scripting.XmlScript.FalloutNVXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: c:\Games\Nexus Mod Manager\FalloutNV\Mods
        Found: c:\Games\Nexus Mod Manager\FalloutNV\Mods\The Commando - Rifle Animation Pack-38527-1-1b.rar
            Registered.
    Found 1 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: c:\Games\Nexus Mod Manager\FalloutNV\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
    Found The Commando - Rifle Animation Pack-38527-1-1b.rar...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm
                Registered.
        Found 10 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\falloutNV.exe (IsNull=False)
    NVSE Command: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\nvse_loader.exe (IsNull=False)
    FNV4Gb Command: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\fnv4gb.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command:  (IsNull=True)
Loading Plugins into Plugin List: 10
    Loading: FalloutNV.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm) (False)
    Loading: DeadMoney.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm) (False)
    Loading: HonestHearts.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm) (False)
    Loading: LonesomeRoad.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm) (False)
    Loading: OldWorldBlues.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm) (False)
    Loading: TribalPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm) (False)
    Loading: MercenaryPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm) (False)
    Loading: ClassicPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm) (False)
    Loading: CaravanPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm) (False)
    Loading: GunRunnersArsenal.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm) (False)
Setting up listener on Nexus Mod Manager-FalloutNVIpcServer/FalloutNVListener at 2018-06-11 16:26:33
Running Application.
Loading Game Mode Factories for Installed Games...
    Loading FalloutNV: Supported
Determining Game Mode: (Requested Mode: FalloutNV) FalloutNV
Game Mode Factory Selected: Fallout: New Vegas (FalloutNV)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout: New Vegas (FalloutNV)
    Installation Path: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas
    Install Info Path: c:\Games\Nexus Mod Manager\FalloutNV\Install Info
    Mod Path: c:\Games\Nexus Mod Manager\FalloutNV\Mods
    Mod Cache Path: c:\Games\Nexus Mod Manager\FalloutNV\Mods\cache
    Mod Download Cache: c:\Games\Nexus Mod Manager\FalloutNV\Mods\downloads
    Overwrite Path: c:\Games\Nexus Mod Manager\FalloutNV\Install Info\overwrites
    Virtual Install Path: c:\Games\Nexus Mod Manager\FalloutNV\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: FalloutNV.CSharpScript.dll
                Initializing: Nexus.Client.Games.FalloutNV.Scripting.CSharpScript.FalloutNVCSharpScriptType
            Checking: FalloutNV.XmlScript.dll
                Initializing: Nexus.Client.Games.FalloutNV.Scripting.XmlScript.FalloutNVXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: c:\Games\Nexus Mod Manager\FalloutNV\Mods
        Found: c:\Games\Nexus Mod Manager\FalloutNV\Mods\The Commando - Rifle Animation Pack-38527-1-1b.rar
            Registered.
    Found 1 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: c:\Games\Nexus Mod Manager\FalloutNV\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
    Found The Commando - Rifle Animation Pack-38527-1-1b.rar...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm
                Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm
                Registered.
        Found 10 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\falloutNV.exe (IsNull=False)
    NVSE Command: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\nvse_loader.exe (IsNull=False)
    FNV4Gb Command: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\fnv4gb.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command:  (IsNull=True)
Loading Plugins into Plugin List: 10
    Loading: FalloutNV.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\FalloutNV.esm) (False)
    Loading: DeadMoney.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\DeadMoney.esm) (False)
    Loading: HonestHearts.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\HonestHearts.esm) (False)
    Loading: LonesomeRoad.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\LonesomeRoad.esm) (False)
    Loading: OldWorldBlues.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\OldWorldBlues.esm) (False)
    Loading: TribalPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\TribalPack.esm) (False)
    Loading: MercenaryPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\MercenaryPack.esm) (False)
    Loading: ClassicPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\ClassicPack.esm) (False)
    Loading: CaravanPack.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\CaravanPack.esm) (False)
    Loading: GunRunnersArsenal.esm (c:\program files (x86)\steam\steamapps\common\Fallout New Vegas\Data\GunRunnersArsenal.esm) (False)
Setting up listener on Nexus Mod Manager-FalloutNVIpcServer/FalloutNVListener at 2018-06-11 16:28:02
Running Application.
Adding Mod to running instance of client: nxm://falloutnv/mods/38527/files/87143
[nxm://falloutnv/mods/38527/files/87143] Adding Mod to AddModQueue
[nxm://falloutnv/mods/38527/files/87143] Starting Add Mod Task.
[nxm://falloutnv/mods/38527/files/87143] Starting Add Mod Task.
Adding Mod to running instance of client: nxm://falloutnv/mods/38527/files/87143
[nxm://falloutnv/mods/38527/files/87143] Downloading Files.
[nxm://falloutnv/mods/38527/files/87143] Launching downloading of http://filedelivery.nexusmods.com/130/The Professional - Pistol Animation Pack-38527-1-1.rar?fid=87143&ttl=1528781313&ri=8192&rs=8192&setec=140f2370fc903e9675811c7661c833ca.
[http://filedelivery.nexusmods.com/130/The Professional - Pistol Animation Pack-38527-1-1.rar?fid=87143&ttl=1528781313&ri=8192&rs=8192&setec=140f2370fc903e9675811c7661c833ca] Retreiving metadata.
[http://filedelivery.nexusmods.com/130/The Professional - Pistol Animation Pack-38527-1-1.rar?fid=87143&ttl=1528781313&ri=8192&rs=8192&setec=140f2370fc903e9675811c7661c833ca] Downloading.
[c:\Games\Nexus Mod Manager\FalloutNV\Mods\downloads\The Professional - Pistol Animation Pack-38527-1-1.rar] Adding mod from archive.
Adding Mod to running instance of client: nxm://falloutnv/mods/49152/files/1000043818
[nxm://falloutnv/mods/49152/files/1000043818] Adding Mod to AddModQueue
Adding Mod to running instance of client: nxm://falloutnv/mods/49152/files/1000043818
Adding Mod to running instance of client: nxm://falloutnv/mods/49152/files/1000043818
[nxm://falloutnv/mods/49152/files/1000043818] Starting Add Mod Task.
[nxm://falloutnv/mods/49152/files/1000043818] Starting Add Mod Task.
[nxm://falloutnv/mods/49152/files/1000043818] Downloading Files.
[nxm://falloutnv/mods/49152/files/1000043818] Launching downloading of http://filedelivery.nexusmods.com/130/Version 1.87-49152-1-87.rar?fid=1000043818&ttl=1528781791&ri=8192&rs=8192&setec=3bff5ca414e02e744202a0693f4f1c86.
[http://filedelivery.nexusmods.com/130/Version 1.87-49152-1-87.rar?fid=1000043818&ttl=1528781791&ri=8192&rs=8192&setec=3bff5ca414e02e744202a0693f4f1c86] Retreiving metadata.
[http://filedelivery.nexusmods.com/130/Version 1.87-49152-1-87.rar?fid=1000043818&ttl=1528781791&ri=8192&rs=8192&setec=3bff5ca414e02e744202a0693f4f1c86] Downloading.
[c:\Games\Nexus Mod Manager\FalloutNV\Mods\downloads\Version 1.87-49152-1-87.rar] Adding mod from archive.
Adding Mod to running instance of client: nxm://falloutnv/mods/49152/files/1000043818
[nxm://falloutnv/mods/49152/files/1000043818] Adding Mod to AddModQueue
[nxm://falloutnv/mods/49152/files/1000043818] Starting Add Mod Task.
[nxm://falloutnv/mods/49152/files/1000043818] Starting Add Mod Task.
[nxm://falloutnv/mods/49152/files/1000043818] Downloading Files.
[nxm://falloutnv/mods/49152/files/1000043818] Launching downloading of http://filedelivery.nexusmods.com/130/Version 1.87-49152-1-87.rar?fid=1000043818&ttl=1528781800&ri=8192&rs=8192&setec=c91e8674d1e0f6560c241b7d6b479851.
[http://filedelivery.nexusmods.com/130/Version 1.87-49152-1-87.rar?fid=1000043818&ttl=1528781800&ri=8192&rs=8192&setec=c91e8674d1e0f6560c241b7d6b479851] Retreiving metadata.
[http://filedelivery.nexusmods.com/130/Version 1.87-49152-1-87.rar?fid=1000043818&ttl=1528781800&ri=8192&rs=8192&setec=c91e8674d1e0f6560c241b7d6b479851] Downloading.
[c:\Games\Nexus Mod Manager\FalloutNV\Mods\downloads\Version 1.87-49152-1-87.rar] Adding mod from archive.

Tracing an Unhandled Exception:

Tracing an Unhandled Exception:

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Transactions.Transaction.NotifyInDoubt()
   at Nexus.Transactions.Transaction.Rollback()
   at Nexus.Transactions.TransactionScope.Dispose()
   at Nexus.Client.PluginManagement.ApplyLoadOrderTask.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Exception: 
Message: 
	Cannot access a disposed object.
Object name: 'MainForm'.
Full Trace: 
	System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MainForm'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Nexus.Client.MainForm.ViewModel_ApplyingImportedLoadOrder(Object sender, EventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Nexus.Client.PluginManagement.UI.PluginManagerVM.RefreshPluginSorting(String[] p_strPluginList)
   at Nexus.Client.PluginManagement.UI.PluginManagerVM.LoadOrderManager_LoadOrderUpdate(Object sender, EventArgs e)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.FileWatcherOnChangedLoose(Object source, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

Exception: 
Message: 
	Cannot access a disposed object.
Object name: 'MainForm'.
Full Trace: 
	System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MainForm'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Nexus.Client.MainForm.ViewModel_ApplyingImportedLoadOrder(Object sender, EventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Nexus.Client.PluginManagement.UI.PluginManagerVM.RefreshPluginSorting(String[] p_strPluginList)
   at Nexus.Client.PluginManagement.UI.PluginManagerVM.LoadOrderManager_LoadOrderUpdate(Object sender, EventArgs e)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.FileWatcherOnChangedLoose(Object source, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

Running Threads (1)
    27 () 
        Aborted

**Comment by squid-box** [comment]
Since you're using the legacy version of NMM, you'll probably get no help here. You could try creating an issue on the [NMM Legacy Github repo](https://github.com/Nexus-Mods/Nexus-Mod-Manager-Legacy) instead, but I doubt anyone works on that version.
