### ISSUE TITLE
tsbOnlineStatus toolTipText set wrong

### ISSUE THREAD

**Issue by Arefu** [Nexus-Mods/Nexus-Mod-Manager#46]
A very minor error I can't seem to navigate the code to where it's being set or I would submit a pull request with the fix. But before you even login the toolTipText says "Logout" even if you're not even logged in.

This is worse than the floating  [apple](https://i.ytimg.com/vi/cbU-zqHni_w/hqdefault.jpg) in Black Ops 1.

**Comment by Nubbie** [comment]
@squid-box 
Haven't looked in the changelog, but it seems to have been fixed

![image](https://user-images.githubusercontent.com/17282384/58343925-98f42300-7e54-11e9-8baa-43fef73b6762.png)

**Comment by squid-box** [comment]
Yes, I fixed it during the API changes for 0.70. Thanks for reminding me :)
