### ISSUE TITLE
NMM Wont let me log in

### ISSUE THREAD

**Issue by Smeshmouth** [Nexus-Mods/Nexus-Mod-Manager#460]
Ive just installed it and aytime i try to log in it says the login information is wrong im on the latest version also
its fallout 4 NMM if it matters

**Comment by squid-box** [comment]
What version of NMM are you running?

**Comment by Primus4242** [comment]
I'm having the same problem.  I'm running 0.65.2 version.  It won't even connect to the updater.

**Comment by squid-box** [comment]
The updater is broken before ~0.65.7, grab the latest version from Github and it will be fine again.

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest

**Comment by Smeshmouth** [comment]
i did
it still doesnt work

**Comment by Primus4242** [comment]
I got 0.65.8 and it still won't let me log in.

**Comment by squid-box** [comment]
@Smeshmouth / @Primus4242 :

Could you try logging in with your username, not your email address?

**Comment by Primus4242** [comment]
That worked.

**Comment by squid-box** [comment]
With [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), the login form will now enforce using a username (won't allow email). Hopefully that will resolve most login issues people are reporting.

Closing this issue.
