### ISSUE TITLE
I bought the premium lifetime membership but the manager still claims I am not a premium user and my downloads are still throttled

### ISSUE THREAD

**Issue by Havok17171** [Nexus-Mods/Nexus-Mod-Manager#462]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
Just to get a clearer picture of the problem:
* What version of NMM are you running?
* Did you recently upgrade your account? Did it maybe just take some time to propagate, and now works?
* Is NMM recognizing your Premium status at all? Or does it still look like this at the bottom of the window? :
![image](https://user-images.githubusercontent.com/864820/42468328-e7e59c32-83b4-11e8-9ba2-0040fcbbc409.png)

**Comment by Havok17171** [comment]
Everything seems OK now though the dl speed seems to be about the same as it always was. I've been ill so haven't really been playing much. I'll get back in touch if I have any more issues, OK?

**Comment by squid-box** [comment]
Sounds good, happy to hear it might be resolved. 

As far as I know the speed restriction isn't within NMM, but on the CDN side of things. But if you're consistently getting slower speeds when downloading with NMM than when downloading through the browser do create an issue for it :)
