### ISSUE TITLE
Login error: Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down.

### ISSUE THREAD

**Issue by McRaider25** [Nexus-Mods/Nexus-Mod-Manager#469]
I have not been active on my nexus mod manager account for a period of time, now that im getting back into playing Skyrim, I am also back to installing mods. After being required to unlock my account, I went to open the Mod manager, where it still says to log back in to my account on the website. I have already done this.

**Comment by squid-box** [comment]
What version of NMM are you running?

**Comment by McRaider25** [comment]
I was running an old version, finally figured out the problem.

**Comment by sineater985** [comment]
what was the problem because i have the same problem

**Comment by squid-box** [comment]
@sineater985: Best guess is that you're running an old version, you'll need 0.65.2 or later in order to authenticate with Nexus.
