### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by LinkOnRoids** [Nexus-Mods/Nexus-Mod-Manager#47]
Not exactly sure whats going on here but all my directories are right and my mods are in place and this is happening 
![mehehe](https://cloud.githubusercontent.com/assets/26193307/23583591/5bcbd1dc-010e-11e7-8952-2bdc92b93f11.png)

**Comment by Neshotah76** [comment]
I am having this same issue.  I had completely uninstalled NMM, re-installed, added mods, closed and re-opened NMM and received this same message. (Win10). This started about a week or so ago.
I can launch game through SKSE link and all mods load correctly that were installed in NMM but if I open NMM  I get the message. I have been using NMM along time and only seen this once before, a re-install fixed it.

**Comment by squid-box** [comment]
Are either of you still seeing this problem with the latest version of NMM?

If so, could you start NMM in Trace Mode (there's a shortcut for it in the start menu), run NMM until you reach this state, then close NMM and attach the trace log file you find in `%USERPROFILE%\Documents\Nexus Mod Manager` to this issue?

**Comment by squid-box** [comment]
With no reply in a week, I'm closing this issue.
