### ISSUE TITLE
NMM crashes randomly

### ISSUE THREAD

**Issue by muro12** [Nexus-Mods/Nexus-Mod-Manager#472]
Nexus mod manager keeps closing randomly when installing, downloading or just going through menus it creates a trace log which can be found here:https://docs.google.com/document/d/1WgCfCMRrD-4KKKeDE9jLVRxz5fb40FWedInQJ2dKZx8/edit?usp=sharing

- NMM version: 0.65.2

I really don't know what it means to reproduce it just happens randomly

**Comment by squid-box** [comment]
Duplicates #389
