### ISSUE TITLE
Crash on Update --> Backup

### ISSUE THREAD

**Issue by DanDoes** [Nexus-Mods/Nexus-Mod-Manager#473]
**Describe the bug**
When updating, if I click on the Update button, then on the popup that appears I click on the Backup button, I get a crash every time.

**Environment**
- NMM version: 0.65.6
- [TraceLog20180708032540.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2173648/TraceLog20180708032540.txt)

**To Reproduce**
1. Open NMM
2. Click "Update Nexus Mod Manager" from the globe icon in the top right
3. Observe the popup appear for "New version available"
4. Click the "Backup" button
5. Crash

**Additional information**
- 100% repro
- The first time I opened NMM today, it popped up with an update prompt of its own, which I dismissed.

**Comment by squid-box** [comment]
Duplicates #461

**Comment by squid-box** [comment]
A fix for #461 was released as part of 0.65.8, please download that version (manually, your old version(s) will still crash when trying to automatically update) and it should work better when another version is released.
