### ISSUE TITLE
I open mod manager It stays open for awhile and then closes HELP!!!

### ISSUE THREAD

**Issue by jonkiep** [Nexus-Mods/Nexus-Mod-Manager#475]
[TraceLog20180708194519.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2174224/TraceLog20180708194519.txt)
[TraceLog20180708194519.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2174225/TraceLog20180708194519.txt)

_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by jonkiep** [comment]
I put the tracelog twice by accident

**Comment by squid-box** [comment]
Better two of the same log than none :)

This is the same issue as #389.
