### ISSUE TITLE
Plugins.txt.failed ?

### ISSUE THREAD

**Issue by WorfTheWolf** [Nexus-Mods/Nexus-Mod-Manager#478]
**Issue**
This problem seems to only be afflicting FONV. Whenever I try to activate any mod through FOMM, NMM, or even sort the load order through LOOT, I get an instant crash. Apparently, the programs don't have access to plugins.txt. After a couple minutes of googling, I figured I should make sure it isn't set to "read-only". Come to find out, MY file is called plugins.txt.failed and I have no idea what that means. Googling just the file name comes up with one other person who was struggling with the same problem. The suggested fix was a total wipe of nmm and fonv directories and I would like to avoid that if at all possible.

**Environment**
- NMM version: 0.65.2

**To Reproduce**

Happens whenever I try to activate a FONV mod through any mod loader.

**Additional information** 

 ![default failed screenshot](https://user-images.githubusercontent.com/41022322/42468683-97fd6e7e-8383-11e8-9b19-78c7bde7bc52.PNG)

- [LOOTDebugLog.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2177524/LOOTDebugLog.txt)

- [TraceLog20180709141101.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2177527/TraceLog20180709141101.txt)

**Comment by squid-box** [comment]
The issue is: `System.UnauthorizedAccessException: Access to the path 'C:\Users\Owner\AppData\Local\FalloutNV\plugins.txt' is denied.`, for some reason the file is "protected" and the user running NMM isn't allowed to change it.

The fact that NMM crashes here is a bug, but a workaround for you could be to either run NMM as administrator or change the security settings for this file (or rather the folder it's in) manually.

The fact that it's called **plugins.txt.failed** just means that NMM wasn't able to write to plugins.txt and instead wrote the contents to the .failed file in case you want to manually restore plugins.txt.

**Comment by WorfTheWolf** [comment]
@squid-box Running as an administrator isn't working either and the file has total permissions. How would I go about manually restoring plugins.txt?

**Comment by squid-box** [comment]
Just rename `plugins.txt.failed` to `plugins.txt`. (And you should open it and check that it seems to contain the plugins you'd expect to find.

It's weird though, you don't have a plugins.txt file, and NMM gets an UnauthorizedAccess exception trying to create it - **but** it's able to create and write plugins.txt.failed in that same directory...

**Comment by WorfTheWolf** [comment]
@squid-box 

![what](https://user-images.githubusercontent.com/41022322/42469943-20f7d2ac-8387-11e8-8138-2bb5f450455e.PNG)

So it exists, but it's invisible? 
I'm 100% lost.

Edit: So renaming the file to `plugins (2).txt` still hasn't fixed it and I believe i'm still getting the same error.

**Comment by squid-box** [comment]
First thing I'd try is to show hidden files in Explorer (I can't recall how to get there pre-Windows 10, but look for Folder settings or File Explorer Options, under the View tab you should find an option to "Show hidden files, folders, and drives").

If that doesn't reveal the plugins.txt file I'd run cmd.exe as administrator, and:
`cd C:\Users\Owner\AppData\Local\FalloutNV`
`dir /a`

And see if you can see the file.

**Comment by WorfTheWolf** [comment]
@squid-box Found it. Should I try deleting `plugins (2).txt` and leave the original one to see if it would work?

Edit: 
![plugins](https://user-images.githubusercontent.com/41022322/42472027-e8055350-838d-11e8-8c61-2c8675f4e8d9.png)

**Comment by squid-box** [comment]
The original one has always been there, just not visible to you in explorer (it's weird, it shouldn't be hidden). Check the security permissions on it, to verify that your user can read and write to the file, and make sure it isn't write-protected as well.

**Comment by WorfTheWolf** [comment]
![capture](https://user-images.githubusercontent.com/41022322/42472509-8300ffe8-838f-11e8-9509-f9f22436b608.PNG)

Has the same perms through all of them.

UPDATE: Deleting the duplicate plugins.txt SEEMS to have fixed something. FOMM and NMM don't instantly crash when I click a mod. Let me make sure everything is working alright and then I can close this. I just wanna say thank you for all of your help thus far. I really appreciate it.

**Comment by WorfTheWolf** [comment]
@squid-box Yep! Everything seems to be working just fine! Just installed a really quick test mod to see if it'd boot up and it ran with no problems at all! Thank you again for all of your help. I really do appreciate it.

**Comment by squid-box** [comment]
Happy to help!

This is technically still a problem for NMM, but this issue was also technicall a duplicate, so it (the crash at least) will get fixed at some point :)
