### ISSUE TITLE
It don work

### ISSUE THREAD

**Issue by Dcatkins** [Nexus-Mods/Nexus-Mod-Manager#48]
i am trying to install the cbbe and ive followed a tutorial and it doesnt work like  it did for them and i am confused it doesnt change my charicter one bit please help

**Comment by AppleDash48** [comment]
Oldrim mods aren't supported for Skyrim Special Edition. If you're trying this for Skyrim Legendary Edition, then you probably did something wrong.

**Comment by squid-box** [comment]
@Dcatkins: Is this still an issue? If not I'll close this issue.

**Comment by squid-box** [comment]
With no reply after a week I'm closing the issue.
