### ISSUE TITLE
Load order is broken again.

### ISSUE THREAD

**Issue by RaveMan84** [Nexus-Mods/Nexus-Mod-Manager#482]
NMM version: 0.65.8
After update mods can`t be move in load order as was before on early versions with esl support.

**Comment by RaveMan84** [comment]
After update mods can`t be move in load order as was before on early versions with esl support.

**Comment by ThatDudeWilson** [comment]
Just wanted to add that I am also having this issue since updating NMM to 0.65.8. Cannot move mods in Plug-ins as in previous version.

**Comment by Anjebell** [comment]
I'm also having this issue. I had to revert to 0.65.7 in order to move plugins around.

**Comment by squid-box** [comment]
Yeah, I messed this up. PR #491 will restore this.

:(

**Comment by ThatDudeWilson** [comment]
Thanks squid - appreciate all the work you do for this

**Comment by squid-box** [comment]
@RaveMan84 / @ThatDudeWilson , @Anjebell : With [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9) this should be resolved.
