### ISSUE TITLE
yea so I can't update NMM, beacuse I can't login in because it isn't updated! should I just reinstall it?

### ISSUE THREAD

**Issue by ChampionGundyr** [Nexus-Mods/Nexus-Mod-Manager#484]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
Just [grab the latest release from Github](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8) and install it.
