### ISSUE TITLE
NMM 0.65.8 hangs uninstalling mods, doesn't create trace file

### ISSUE THREAD

**Issue by kanguru-au** [Nexus-Mods/Nexus-Mod-Manager#488]
NMM 0.65.8, 0.65.7, 0.65.6 all hang on uninstalling some mods, without generating a trace file. 0.65.2 is the most recent version that does not exhibit this hang. NexusClient.exe process needs to be killed from the Task Manager (or procexp64 in my case). "Hang" means progress indicator stops ~75%, Progress window and NMM window completely unresponsive, won't redraw as the front window when activated on the taskbar (must be a proper way of describing that!). Sysinternals Process Explorer says NexusClient process is in "Suspended" state. Elevating Process Explorer and choosing to "resume" process gets it working again (which I have only JUST discovered!).

Mod versions causing the hang on uninstall include:
Astins Skin Override For Looks Menu - AstinsSkinsOverride v1.2
DEF_UI 1.5

What would cause NMM to "suspend"?

Using Windows 10 Pro 64-bit Version 1803

**Comment by squid-box** [comment]
Under this page you can find info on how to force the creation of a trace file: https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log

To my knowledge there's no time it's expected that NMM completely freezes like you describe, so I'm guessing some task crashes during the installation and brings down NMM with it.

**Comment by kanguru-au** [comment]
Thank you so much @squid-box. Trace attached.
[TraceLog20180712210954.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2188335/TraceLog20180712210954.txt)
Not very helpful (to me).
The process is in Suspended state when that file attached. Resuming the process and deleting further mods 1) works as expected, 2) dosen't produce any more lines in the trace file.

**Comment by dyslexicanaboko** [comment]
This sounds like a deadlock to me. This could be a new issue uncovered by fixing the updater (total guess). I 
@kanguru-au looked at your trace file and like you said it doesn't show any exceptions.

As silly as this sounds could you provide your exact steps in a numbered list format to follow for us to reproduce this. I will try to look at this later.

**Comment by kanguru-au** [comment]
Thank you for considering my issue, but after suffering the problem for a month or so, I can no longer reproduce it. Not quite a Heisenbug, because I looked at it for ages and ages, though when you looked at it... It ran away!
