### ISSUE TITLE
Doesn't find / recognize XCOM2 directory / .exe

### ISSUE THREAD

**Issue by WurstCommander** [Nexus-Mods/Nexus-Mod-Manager#49]
read details here:
https://steamcommunity.com/app/268500/discussions/0/360671583801750371/

Quote :
"A year later and I've found a solution that will work. The nmm is looking for XCOM2.exe but the file is called XCom2.exe 
 Chaining the file in from XCom2.exe to XCOM2.exe fixes the problem."

And it's not really clear if you should link "c:\somedir\steamapps\common\XCOM 2\Binaries\Win64"

or just "c:\somedir\steamapps\common\".

The scanning doesn't recognize XCOM2 at all by the way.

A fix would be great. If you need a tester or something else, I would be ready to help!

**Comment by DuskDweller** [comment]
The correct path to set is: c:\somedir\steamapps\common\XCOM 2

**Comment by WurstCommander** [comment]
Thx. Will there be a fix for scanning?
I guess the scanning process should find XCOM2.EXE and go to directories back to get the right path.

btw. some people get corrupt game installs, after trying to set the path. My install right now is corruped too after trying NMM. Any idea this is happening? A little bit annoying.

**Comment by Menno1981** [comment]
9 months later this issue is still not fixed. Seems an easy fix to me to just set the correct path

**Comment by squid-box** [comment]
I don't have XCOM 2, but I could create a test version for someone to verify the fix with.

Let me know if you're having this issue!

**Comment by squid-box** [comment]
Closing for now, poke me if you want this.
