### ISSUE TITLE
So.. Nexus Mod Manager Will Not Allow Me To Log In

### ISSUE THREAD

**Issue by HARRYtheSTAR** [Nexus-Mods/Nexus-Mod-Manager#490]
Nexus mod manager won't let me log in, it says..

"Login Error: Cannot reach the nexus login server. Either your Firewall is blocking NMM or the login server is down".

Can anyone help?

**Comment by squid-box** [comment]
What version of NMM are you using?

**Comment by HARRYtheSTAR** [comment]
I'm using 0.63.14, is that outdated?

**Comment by HARRYtheSTAR** [comment]
Hold on, i realised that it is outdated. :\

**Comment by HARRYtheSTAR** [comment]
Problem is fixed now.

Sorry for wasting your time, thanks though, you still helped me.

- Harry

**Comment by squid-box** [comment]
You pretty much helped yourself, no worries :)
