### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by Peli0302** [Nexus-Mods/Nexus-Mod-Manager#493]
The text in the mod manager is missing. I can't work with mods i cant read.
![screenshot_20180711_083424](https://user-images.githubusercontent.com/41179509/42673624-93f4584c-866c-11e8-8c90-c7e67ed24689.png)

**Comment by squid-box** [comment]
You just need to resize the columns: https://youtu.be/c9pgqyPG0vo

**Comment by Peli0302** [comment]
Well I feel like an idiot. Thx for the reply.
