### ISSUE TITLE
Nexus Mod Manager

### ISSUE THREAD

**Issue by West125** [Nexus-Mods/Nexus-Mod-Manager#494]
Nexus Mod Manager
Getting the same error when bringing up the Mod Manager.

ERROR:
the following updates failed:
Nexus Mod Manager Updater: Could not get the version
information from the updater server.

I have deleted and reinstalled with the same error.

**Comment by squid-box** [comment]
Have you updated to 0.65.8?

**Comment by West125** [comment]
I have version 65.2. were is 65.8

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by West125** [comment]
I finally read about the mode manager will be coming from GitHub and downloaded the 65.8 and there are no errors. Thanks for the help. Herb

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by squid-box** [comment]
You pretty much helped yourself :)
