### ISSUE TITLE
I have been experiencing problems starting the latest version of NMM for new vegas, however it seems to work fine for both fallout three and four. I have no clue what to do to remedy this situation. 

### ISSUE THREAD

**Issue by johnhenry18** [Nexus-Mods/Nexus-Mod-Manager#496]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
[TraceLog20180713192213.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2194550/TraceLog20180713192213.txt)

**Comment by squid-box** [comment]
This is #389, which luckily was already fixed. Go to Releases on GitHub and grab 0.65.8 and this shouldn't be a problem anymore.

**Comment by dyslexicanaboko** [comment]
@johnhenry18 respectfully, in the future when entering an issue please fill out the bug report and don't put your entire problem in the title. That's what the message body is for. Thanks.
