### ISSUE TITLE
Update Notification: Impossible to read RED text

### ISSUE THREAD

**Issue by C-O-dE** [Nexus-Mods/Nexus-Mod-Manager#497]
To start, yes I am slightly color blind with certain shades of red, but I have normal vision friends who have trouble reading this red on dark grey setup. For myself, it is not only impossible to read, but gives me a headache just looking at it.

![image](https://user-images.githubusercontent.com/41235919/42725478-f1a8c8fc-8751-11e8-8a76-a2ca348241ac.png)

Please drop the grey background, or at least lighten it several shades, or use a different color than red.

**Comment by squid-box** [comment]
For anyone thinking of tackling this, there content of the update notification is taken from a webpage hosted on Nexus, so you'll need to get someone there to change the page (or manually replace the color in the collected content).

**Comment by C-O-dE** [comment]
as they have 'officially' moved to Vortex, shouldn't this be the other way around? Let them pull updates from here, esp as the NMM page there specifically says to come here to keep up to date...

/2bits

**Comment by squid-box** [comment]
The text shown in the window (in your image) is html grabbed from their servers, it's not stored in this git repository.

**Comment by dyslexicanaboko** [comment]
@OrnoCav viola [https://staticdelivery.nexusmods.com/NMM/releasenotes.html](https://staticdelivery.nexusmods.com/NMM/releasenotes.html)

So what you are seeing here is the following styles. I can intercept this and just update it, but I don't know what colors would be best.
```
<style>
	body { background: #606060; font-family: 'Trebuchet MS', Helvetica, sans-serif; font-size: 13px; color: #efefef; }
	h1 { font-size: 17px; }
	h2 { font-size: 14px; }
	.minor { color: #57A462; }
	.major { color: red; }
	ol { margin-bottom: 50px; }
	li { margin-bottom: 4px; }
	div { padding-left: 25px; }
</style>
```
Alternatively @squid-box do you think we should just point to the [GitHub releases page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) for this application? Probably makes more sense IMO.

**Comment by squid-box** [comment]
I think that could be a good idea, but we'd probably also want to include the information about upgrading from 0.56.x, as that is a breaking change.

Or, anyone with 0.56.x will get that webpage anyway, so maybe we should just use the release info from Github. When I played around with it earlier, I figured it'd be best to use the "body" info from [the API call](https://api.github.com/repos/nexus-mods/Nexus-Mod-Manager/releases/latest).

**Comment by C-O-dE** [comment]
IMO, a Silver (#C0C0C0) background a/o a Yellow (#FFFF00) text for major would work.

The Silver background still keeps most of the 'snow glare' off the screen, and the Yellow text on either background still keeps the 'look at me, i'm important' feel without being a complete wash on contrast.

I had considered Orange text, but could feel the glares of those worse off on color blindness just oozing from the ether.

Last option, just go full black on the background and leave the rest.

**Comment by C-O-dE** [comment]
FYI, old trick when doing color palates and considering those visually challenged: Take a screenshot and open it in a photo viewer, then convert to grey scale. If your colors fade together so a person with normal vision can not read them, odds are people with visual impairments are going to have issues.

**Comment by dyslexicanaboko** [comment]
@OrnoCav I remember my friend telling me that and I forgot all about it. He is Red Green color blind and I am still learning about it. Either way that HTML sucks even for people with full spectrum vision, the red is too harsh on that background.

@squid-box I like the API call method, it eliminates the need for a web browser component.

**Comment by squid-box** [comment]
I was considering trying to grab the change logs from all versions released since the users version, but that's a few API calls to head, I think, so I never looked more into it.

Otherwise you only get the changes for the last update.

**Comment by C-O-dE** [comment]
@dyslexicanaboko _"eliminates the need for a web browser component"_ - the fewer holes the better.

@squid-box _"Otherwise you only get the changes for the last update."_ - I think most of us would be looking to the master list anyways if we were a few versions behind. Maybe a convenience "Version History" perma link below the 'whats new' pane that will open the master list in a new browser window.

Anything that Keeps It Clean & Simple gets my vote.

**Comment by DuskDweller** [comment]
That page on the Nexus isn't going to be updated, so the best way to handle it would be to just point new versions to the Github release notes.
