### ISSUE TITLE
Nexus mod Manager (Sorting System Glitch)

### ISSUE THREAD

**Issue by Soda-Master** [Nexus-Mods/Nexus-Mod-Manager#499]
Basicaly when i changed the size of the "Name" Sorting bit almost all of the others dissapeared....
It makes it super annoying to find the newer mods that mix in with the older mods....

It happed again after reinstalling Nexus 

![namnlos](https://user-images.githubusercontent.com/26909953/42734848-f1da6fa2-884a-11e8-8017-ca1e74dfb170.png)

**Comment by squid-box** [comment]
Scroll all the way to the right (see the scroll bar?), and then you should be able to decrease the size of the columns.

The columns behave weirdly, it's a known issue that's not trivially fixed, so you'll have to live with this for now ;(

**Comment by Soda-Master** [comment]
ok i must be half blind to have missed that but thanks =)

**Comment by squid-box** [comment]
Like I said, it behaves very weird, lots of people get confused about it :)
