### ISSUE TITLE
Every time I try to download a mod it says its not setup with Skyrim but it is setup and I did rescan  the "Installed Games" but nothing worked so please respond asap

### ISSUE THREAD

**Issue by KirbyGamerTV** [Nexus-Mods/Nexus-Mod-Manager#503]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by dyslexicanaboko** [comment]
Are you a premium member? Just curious.

**Comment by KirbyGamerTV** [comment]
no

**Comment by dyslexicanaboko** [comment]
Fill out the form you submitted above and include a trace file. Don't put the whole problem in the title like that.
