### ISSUE TITLE
BUG i can't install or uninnstall any mod !

### ISSUE THREAD

**Issue by Draco26** [Nexus-Mods/Nexus-Mod-Manager#504]
When i try to unistall a mod or to install or to install with download with nexus or to do anything , the software say to me that he can' t access to a folder "C:\Users\Dracocraft26\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_gain1zdhkpbyw2jzilftlyqygdtwzisk\0.65.2.0" but when i search it i can. :/ So if you can help me !

**Environment**
- NMM version: 0.65.2.0
https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/new/choose
- Mod(s) used: _<link to mod(s) on Nexus>_ ( what i try to install : https://www.nexusmods.com/fallout4/mods/15251?tab=files )

Trace Log :
[TraceLog20180717130916.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2201361/TraceLog20180717130916.txt)

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**Comment by squid-box** [comment]
Manually upgrade to 0.65.8 or higher, it includes a fix for this bug.

Latest version can be found here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest
