### ISSUE TITLE
Mod manager cannot get version information from server

### ISSUE THREAD

**Issue by Shaun-Meechan** [Nexus-Mods/Nexus-Mod-Manager#516]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
The mod manager cannot get update information from the server.

**Environment**
- NMM version: 0.65.2
- Mod(s) used:https://www.nexusmods.com/skyrimspecialedition/mods/173/? ; https://www.nexusmods.com/skyrimspecialedition/mods/718 ; https://www.nexusmods.com/skyrimspecialedition/mods/4742 ; https://www.nexusmods.com/skyrimspecialedition/mods/5288 ; https://www.nexusmods.com/skyrimspecialedition/mods/5804 ; https://www.nexusmods.com/skyrimspecialedition/mods/14493 ; https://www.nexusmods.com/skyrimspecialedition/mods/245 ; https://www.nexusmods.com/skyrimspecialedition/mods/2357 ; https://www.nexusmods.com/skyrimspecialedition/mods/2424/?

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
[masterlist.zip](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2216254/masterlist.zip)

**To Reproduce**
Open Nexus Mod Manager
Either wait for the program to try and update itself or manually try to update
![capture](https://user-images.githubusercontent.com/22452759/43036831-95b4a2ec-8cff-11e8-8545-113199fc1cc3.PNG)

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
You'll need to update manually from 0.65.2, you can find the latest release here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest
