### ISSUE TITLE
No mod names are appearing 

### ISSUE THREAD

**Issue by serenityarch** [Nexus-Mods/Nexus-Mod-Manager#517]
**Describe the bug** 
I decided to play Skyrim today and I always use nmm but when I download mods right now I don't see the mod names and it's really annoying. Also, I keep getting a pop up on both of my computers since I updated that I cannot reach information from update server
(What it looks like) https://imgur.com/a/vJBl8cu

**Environment**
- NMM version: 0.65.2
- Mod(s) used: doesn't matter it does it with any

I don't know how to get my trace logs

**To Reproduce**
 Anytime I open NMM

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
You need to resize the columns: https://youtu.be/c9pgqyPG0vo
