### ISSUE TITLE
Oblivion Mods loading problem

### ISSUE THREAD

**Issue by OldGamerDarthy** [Nexus-Mods/Nexus-Mod-Manager#520]
Hello, the bug i have found is on loading oblivion libray mods of NMM, after i chose the game, the NMM load 5 secs and close withous show error or more and is impossible to use NMM with oblivion :(, please fix

"sorry for the english i'm italian autodidact"

**Comment by squid-box** [comment]
Have a look at this page: https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting

You really need to provide more info if anyone is going to be able to help you. :)
