### ISSUE TITLE
I do not know how to describe this bug is a consequence of an unfortunate action/first solucionated second,i cant install mods

### ISSUE THREAD

**Issue by eternalinsane** [Nexus-Mods/Nexus-Mod-Manager#524]
1069/5000
At first the game was perfect, but I noticed that it was too slow despite having the graphics at minimum, so I decided to disable some mods.

It was a catastrophe, to begin with I got the error that I show in the screenshot, then I let myself in, but kept doing it sometimes if and sometimes not,
this also told me to do any action within nmm, uninstall, disable, download ...
my antivirus so far never
 gave problems, uninstall nmm previous unistall of all mods, and reinstalled, in some mods I see the tab yes / no to mod, but however this time this
option did not appear, only if or not everything to overwrite the existing data, I give it to itself, but instead of installing the installation started and around 50% / 60% was canceled and only tells me that there has been a error in the installation.
and what I wonder is that most of the mods install them after doing what I said about 50 times.

Someone has been the same? can anybody help me?

Thanks in advance

**Comment by eternalinsane** [comment]
![instalador](https://user-images.githubusercontent.com/39161420/43164640-f1d0bc20-8f91-11e8-9a36-b32ac3b31054.png)
![error de nmm](https://user-images.githubusercontent.com/39161420/43164629-ea82387c-8f91-11e8-91b5-d2ab28daf45c.png)

**Comment by squid-box** [comment]
@eternalinsane: Please attach the trace log file that the error message above is pointing out. Your description makes very little sense, I assume it's been auto-translated..?

**Comment by eternalinsane** [comment]
yep,im sorry,i used google translator

**Comment by eternalinsane** [comment]
[TraceLog20180724212903.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2225704/TraceLog20180724212903.txt)

**Comment by eternalinsane** [comment]
basically the problem is the first screenshot and the second is that to install a mod I have to install many times and the number 50 installs it, (if I'm lucky)

**Comment by eternalinsane** [comment]
and thnks

**Comment by squid-box** [comment]
So the TraceLog points to a crash that was fixed in 0.65.8 - You can [grab the latest version here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest), and that should stop happening.

The first message, asking you to ovewrite files, means either:
1. The mod is already installed (files are present in your game data directory) - In this case overwriting them shouldn't cause any problems.
2. Another mod has already added/modified the file, so you have to decide if you want to overwrite the file with the current mod, or keep the file from the previous mod.

I can't really tell which it is in this case, sorry.

**Comment by eternalinsane** [comment]
you tell me more of i read in forums, thank you.
i apreciate that

**Comment by eternalinsane** [comment]
![sin titulo](https://user-images.githubusercontent.com/39161420/43170461-841080c6-8fa5-11e8-917f-c4da915fb2bc.png)


the sistem say me this,but i open nmm on the desckpot and run,how to check the version of nmm?

**Comment by eternalinsane** [comment]
problem solved,thanks¡
