### ISSUE TITLE
Подскажите почему название всех директорий в NMM куда устанавливаются моды сокращённые из2 букв и название установленных модов тоже сокращённое может надо  что-то изменить в настройках? раньше было всё нормально.

### ISSUE THREAD

**Issue by Wattghern** [Nexus-Mods/Nexus-Mod-Manager#525]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by Wattghern** [comment]
Подскажите почему название всех директорий в NMM куда устанавливаются моды сокращённые из2 букв и название установленных модов тоже сокращённое может надо 
что-то изменить в настройках? раньше было всё нормально.
![default](https://user-images.githubusercontent.com/41664955/43181880-e6b2867e-8fe7-11e8-8ca6-e3045ed248da.PNG)

**Comment by squid-box** [comment]
I have no idea what you wrote, but I'm guessing you want to resize the columns: https://youtu.be/c9pgqyPG0vo

**Comment by Wattghern** [comment]
Thank you! The question is closed.
