### ISSUE TITLE
Old mate Nexus Mod Manager doesn't want to allow me to install mods because of inability to log on to the server or whatever

### ISSUE THREAD

**Issue by Mrdudetoyou** [Nexus-Mods/Nexus-Mod-Manager#526]
Buoys and Grills gather round for a story

Well one afternoon I wanted to log on to good ol' Nexus Mods to install some mods for Fallout 4. I found several that I liked and clicked the 'NMM' install button. When my NMM applications was automatically started, text down the bottom of my screen informed me that to continue installing the mod I must log back in. After I do so the text again informs me: 'Login Error: Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down.' [sic].

Anyways, the big boy NMM has been like this for some time (like several weeks) so I am doubtful that the server has been down for this long or is down only when I log on. I also don't think its my firewall since I disabled it to log on once or twice and it didn't do anything (this was probably pretty in hindsight). I am not very tech literate, so this shit is probably a really easy fix but oh well.

Anyway, if anyone has had this problem before or knows how to fix it, help would really be appreciated. Thank you very much in advance.

Your boy 
-Blonk

PS I forgot to mention a screen shot of two of the text displayed are attached. Thanks lads
![login error screenshot](https://user-images.githubusercontent.com/41737565/43261316-d41b90aa-910e-11e8-888b-84d1f08055b0.png)

**Comment by squid-box** [comment]
If you'd bothered to read a bit before writing this essay, you probably could've fixed this yourself.

Even though you don't even mention what version you're using, I'm convinced you'll find that the updated version of NMM will log you in just fine.

You can find the latest one here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest
