### ISSUE TITLE
Update failed error

### ISSUE THREAD

**Issue by cristi1990an** [Nexus-Mods/Nexus-Mod-Manager#529]
I'm on version 0.65.2 for Dragon Age. Each time I try to update the Nexus Mod Manager, I'm getting "The following updates failder: Nexus Mod Manager Updater: Could not get version information from the update server."

I'm on Windows 10, running as Admin.

**Comment by squid-box** [comment]
It's a bug in 0.65.2, [grab the latest version from here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases), and it'll be fixed.
