### ISSUE TITLE
Error Installing Mods 

### ISSUE THREAD

**Issue by verfilltilly** [Nexus-Mods/Nexus-Mod-Manager#53]
Hello,

I'm having an error installing mods.  While they are loading, the progress suddenly stops and I am met with this error: 

Error: http://filedelivery.nexusmods.com/110/SkyUI_5_1-3863-5-1.7z?fid=1000172397&ttl=1490432774&ri=8192&rs=8192&setec=d23554c603325645350aad839e0f7c11 , unable to finish the download.

I've tried to look up how to deal with this, but the forums I've come across were rather confusing.

Thank you for your time!
:)

**Comment by squid-box** [comment]
@verfilltilly: Are you still having problems downloading with the latest NMM?

If you do, please add a link to the mod you're trying to download and a tracelog (run NMM in Trace Mode (there's a shortcut in the start menu), attempt the download, and then grab the file from your Documents folder, under Nexus Mod Manager).
