### ISSUE TITLE
The process cannot access the file fnigfesw.newcfg' because it is being used by another process.

### ISSUE THREAD

**Issue by Shimororo11** [Nexus-Mods/Nexus-Mod-Manager#531]
Really don't know what to do as I have done everything that the internet said. I have installed nexus before but made sure i uninstalled the previous copies. I have tried everything and keep getting the same message. I really don't know what to do
[TraceLog20180729214441.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2239170/TraceLog20180729214441.txt)

**Comment by squid-box** [comment]
You're in luck, this was fixed in 0.65.8!
You can find it under [releases](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases)
