### ISSUE TITLE
dennis

### ISSUE THREAD

**Issue by dhs1236677** [Nexus-Mods/Nexus-Mod-Manager#535]
_Please give as much information as you can, replace/remove italicized text._

**Is your feature request related to a problem?**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by dhs1236677** [comment]
Why would you close this thank you purposely trying me not to do anything

**Comment by squid-box** [comment]
An issue with no info other than a title "Dennis" is not a reported issue, it's more like spam.

Write an actual issue report and I won't close it
