### ISSUE TITLE
Could not find file or assembly XXX or one of its dependencies

### ISSUE THREAD

**Issue by SpartacusInvictus** [Nexus-Mods/Nexus-Mod-Manager#538]
**Describe the bug** 
Tried to update NMM, chose to have mods uninstalled and installed, on some point there was no more progress (one of the install windows didn't show a progress bar and when clicking on "cancel" nothing happened), I restarted PC and on trying to open NMM received attached tracelog. 

The following sequence of the tracelog translates to "Could not find file or assembly (blablabla) or one of its dependencies. An assembly manifest (?) was expected in the module (?).
Die Datei oder Assembly "file:///C:\Users\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll" oder eine AbhÃ¤ngigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.

**Environment**
- NMM version: 0.65.2.0
- Mod(s) used: many (seemingly not the issue)

[TraceLog20180801091954.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2248448/TraceLog20180801091954.txt)

**Comment by squid-box** [comment]
Could you verify that the file `C:\Users\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll` is actually there, and if so check which version of the dll it is?

And did you install NMM directly in the C:\Users folder?

**Comment by SpartacusInvictus** [comment]
Hi, thanks for attending to my matter, yes the file is there (sorry, what is the dll? But I've never changed it and the only game I play out of those is Skyrim)...
The NMM folder is in the Users folder, but the NMM program is in the NMM folder, which one do you have in mind?

**Comment by squid-box** [comment]
It just seemed odd to have it installed at the same level as user directories are 

I was looking for the version of `Fallout3.CSharpScript.dll`, but given the error message I don't think that's the problem. If you install NMM to it's default path (under Program Files), does it work for you?

**Comment by SpartacusInvictus** [comment]
Are you referring to NMM program or NMM folder?

**Comment by squid-box** [comment]
The .dll's will (should) only be in the program folder.

**Comment by SpartacusInvictus** [comment]
So NMM folder to program files? Are program files in C?

**Comment by SpartacusInvictus** [comment]
ok it seems to be both in program files and in the users folder o.o

**Comment by SpartacusInvictus** [comment]
so should I just delete it from the users folder?

**Comment by SpartacusInvictus** [comment]
I just updated NMM and managed to open it, but I have to install all the mods again ._. when installed, will everything ingame be as it was when I last played the game? Or will it crash at every corner :(

**Comment by squid-box** [comment]
As long as you point NMM to the same directory (for mods) nothing should be lost.

As to whether or not your game will crash I have no idea, guess that depends on your mods

**Comment by SpartacusInvictus** [comment]
Now I couldn't install SkyUI and to solve it I had to run NMM as admin and click mark certain boxes and what not tell me where do you learn all this stuff? I envy you quite much to me this looks like decades of studying or being a superbrain or both to understand all these IT issues o.o Thank you guys (IT experts on these forums) so much for your unpaid help, really appreciated!
