### ISSUE TITLE
TTW/nexus

### ISSUE THREAD

**Issue by LostCause78** [Nexus-Mods/Nexus-Mod-Manager#54]
ok i've installed tales of two wastelands but now i can't download any mods through nexus mod manager

**Comment by Ghostwalker71** [comment]
You need to run the scan for mod manager to detect the newly installed game
In the top right you will see a circular arrow icon with a list panel on the right edge, click the list panel to expand it then scroll to the last option to rescan for games, be sure to click the green check on the games that are found then finish and you should be set

**Comment by squid-box** [comment]
With no further reply in a year, I assume the issue was resolved.
