### ISSUE TITLE
NMM wont allow me to change my load order

### ISSUE THREAD

**Issue by killroyelite718** [Nexus-Mods/Nexus-Mod-Manager#540]
_Please give as much information as you can, replace/remove italicized text._
when I first downloaded NMM it worked fine. as I was loading my mods, I experienced an error and NMM shut down and said something about a tracelog. I closed down NMM and upon restarting I could no longer change my load order. Even when using the L.O.O.T. tool my load order is unaffected.
**Describe the bug** 
_A short description of what the problem is_

Im using NMM version 0.65.2 and the las mod I loaded before the issue was optimized vanilla textures for fallout 4 on Nexus. Link is below. enclosed are the trace logs generated at the time of the errors.
**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_
https://www.nexusmods.com/fallout4/mods/1204
_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

[TraceLog20180801014750.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2252248/TraceLog20180801014750.txt)
[TraceLog20180802001403.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2252249/TraceLog20180802001403.txt)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
Im using windows 10 on my gaming laptop.

**Comment by squid-box** [comment]
Try downloading the latest version from GitHub and at least over if the trace log errors and the ordering problems should be resolved.

Latest version can be found here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest
