### ISSUE TITLE
NMM wont let me install any new mods

### ISSUE THREAD

**Issue by akaswindows647** [Nexus-Mods/Nexus-Mod-Manager#541]
Nexus Mod Manager keeps displaying a message saying that "(insert mod name) cant be added" I have tried with multiple mods and each time it has displayed the same message and I am currently running version 0.65.9

**Comment by squid-box** [comment]
If you attach a trace log from when this problem occurs, we might be able to help you out.

Check [this wiki page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) for how to force a trace log.

**Comment by akaswindows647** [comment]
Thank you it's working now
