### ISSUE TITLE
Log-In problem preventing downloads

### ISSUE THREAD

**Issue by lonewanderer345** [Nexus-Mods/Nexus-Mod-Manager#542]
Using v 0.65.4 up until an hour ago, all was well.
Then tried downloading from Nexus and got the same Paused download awaiting log-in message and the pop up log-in screen that we had before 0.65.4 was released.

I've updated to 0.65.9 but this hasn't resolved the log-in issue and I'm stuck at the point of any downloads being paused and the pop-up log-in screen requiring password, over and over, but doesn't actually seem to change anything.

- NMM version: _0.65.4 & 0.65.9
- Mod(s) used: _<link to mod(s) on Nexus>_

EDIT: may not have been a problem after all - I changed my password, and the log-in has been recognised and downloads completed.

Probably my fault for using the wrong password!

**Comment by lonewanderer345** [comment]
Don't know if related, but in Settings there is a Fix-it! option for Download issues with Chrome. This doesn't work as it becomes stuck on the repeat message - close Chrome - but chrome is closed, so ??

**Comment by squid-box** [comment]
Good to hear, report back if the problem occurs again!
