### ISSUE TITLE
Cannot reach nexus server

### ISSUE THREAD

**Issue by DragonfuryMH** [Nexus-Mods/Nexus-Mod-Manager#546]
This started yesterday, 8/5/2018, all of a sudden the nexus mod manager could not reach the nexus server at all, I can't update, I can't log in and I can't download mods through the manager. When I tried to log in it said that is could not reach the nexus server saying that the server may be down or that my firewall could be blocking it. I was able to log in just fine on the website so I don't suspect that it's the server. Nexus mod manager is already on my list of apps that I let through my firewall but to be sure I turned it off completely, it still didn't work! This is becoming really aggravating. Every other time something like this happened I gave it a day for the servers to come back as I suspected that they were simply down for maintenance but it's been a day and nothing has changed. Please either inform me as to what is going on with the server or please try to work with me to fix it.

I appreciate your time.

**Comment by squid-box** [comment]
What version are you running?

**Comment by DragonfuryMH** [comment]
That was indeed the problem, I was running 0.63.something, it was outdated but I couldn't get to the server to update it, I ended up just going to the nexus page and downloading the installer for the latest version. That did the trick. So important safety tip: every so often check for updates.
