### ISSUE TITLE
Update Failed?

### ISSUE THREAD

**Issue by Minoitchi** [Nexus-Mods/Nexus-Mod-Manager#552]
The Following updates failed:
Nexus Mod Manager Updater: Could not get version information from the update server.

**Describe the bug** 
Well when i try to update the manager it said that it "Could not get version information from the update server." When i try to download SkyUI, a mod that i like, it can't download to the mod manager and it's damn annoying.

**Environment**
- NMM version: (0.65.2)
- Mod(s) used: https://www.nexusmods.com/site/mods/4/?tab=files

**To Reproduce**
 emm idk it just said "nope can't get that version farm, good luck"

**Additional information** 
https://plus.google.com/photos/photo/101151099564190793595/6587375749847948162?authkey=CLug0rPEz_iAEA

**Comment by squid-box** [comment]
Try grabbing [the latest version from GitHub](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest), this problem was fixed a few versions back.

**Comment by Minoitchi** [comment]
thx fam that helped
