### ISSUE TITLE
Mods Directory Not Changing

### ISSUE THREAD

**Issue by DTM450** [Nexus-Mods/Nexus-Mod-Manager#556]
**Describe the bug** 
Changing the Mods Directory in Settings > *Name Of Game Tab* > *Game* Mods Directory doesn't change after NMM restart.

**Environment**
- NMM version: _0.65.2_ and _0.65.9_
- Mod(s) used: _N/A_

**To Reproduce**
Change Mod Directory folder in Settings > *Name Of Game Tab* > *Game* Mods Directory.
Restart Application.
Folder will be unchanged

**Comment by squid-box** [comment]
See also #156
