### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by sotirisbak** [Nexus-Mods/Nexus-Mod-Manager#557]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_i cant update the NMM_

**Environment**
- NMM version: _0.65.2_
- Mod(s) used: _<link to mod(s) on Nexus>_

**To Reproduce**
 _i just try to update it and it says update failed could not get version information from the update server_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
![nmm bug](https://user-images.githubusercontent.com/42294593/43991111-29945a2e-9d6e-11e8-9f23-073b198ee51b.PNG)

**Comment by squid-box** [comment]
Try grabbing [the latest version from GitHub](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest), this problem was fixed a few versions back.
