### ISSUE TITLE
Unable to download any mods.

### ISSUE THREAD

**Issue by byVELTEN** [Nexus-Mods/Nexus-Mod-Manager#56]
Unable to download any mods, with a completely fresh NNM install and windows 10 install

Error: http://filedelivery.nexusmods.com/1704/9.0.1 A Quality World Map - Vivid with Stone Roads-5804-9-0-1.zip?fid=13792&ttl=1490590842&ri=8192&rs=8192&setec=c46a8b0325010125f9cfea09ae190caa , unable to finish the download.

**Comment by squid-box** [comment]
@byVELTEN: Are you still having problems downloading with the latest NMM?

If you do, please add a link to the mod you're trying to download and a tracelog (run NMM in Trace Mode (there's a shortcut in the start menu), attempt the download, and then grab the file from your Documents folder, under Nexus Mod Manager).

**Comment by byVELTEN** [comment]
Hi, this was a while ago, I ended up reinstalling after removing all the files and that fixed it. I assume it was because of using MO2 on the same game earlier.




________________________________
Fra: Joel Ahlgren <notifications@github.com>
Sendt: 25. mai 2018 00:36
Til: Nexus-Mods/Nexus-Mod-Manager
Kopi: byVELTEN; Mention
Emne: Re: [Nexus-Mods/Nexus-Mod-Manager] Unable to download any mods. (#56)


@byVELTEN<https://github.com/byVELTEN>: Are you still having problems downloading with the latest NMM?

If you do, please add a link to the mod you're trying to download and a tracelog (run NMM in Trace Mode (there's a shortcut in the start menu), attempt the download, and then grab the file from your Documents folder, under Nexus Mod Manager).

**Comment by squid-box** [comment]
Alright, then I'll close the issue. Thank you :)
