### ISSUE TITLE
Crashes before start

### ISSUE THREAD

**Issue by Seclusus** [Nexus-Mods/Nexus-Mod-Manager#561]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
Installed latest version and as I attempt to start I get 
"Nexus Mod Manager has stopped working" It won't even load.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	NexusClient.exe
  Application Version:	0.65.2.0
  Application Timestamp:	5ae0ac02
  Fault Module Name:	clr.dll
  Fault Module Version:	4.7.3130.0
  Fault Module Timestamp:	5b175fed
  Exception Code:	c0000005
  Exception Offset:	00000000003dc7e4
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	3c88
  Additional Information 2:	3c8853dce620eef96c8459456d395a66
  Additional Information 3:	7e8e
  Additional Information 4:	7e8e8459dad9fb71e2b8c7382d80b895

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

NMM Ver 0.65.2-4-0-65-2 w/bugfix

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

I have no idea.

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

Win 7 Pro - no mods as yet

**Comment by squid-box** [comment]
You could try grabbing the actually latest version from GitHub: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest

With a little luck it will provide better feedback. Otherwise could you check your Event Viewer log and see if you're getting an error log from ".NET Application", and copy it here?

**Comment by Seclusus** [comment]
Downloaded and installed latest version, checked the log - downloaded latest .Net Framework
Log follows ---

Faulting application name: NexusClient.exe, version: 0.65.9.0, time stamp: 0x5b4fb3af
Faulting module name: clr.dll, version: 4.7.3130.0, time stamp: 0x5b175fed
Exception code: 0xc0000005
Fault offset: 0x00000000003dc7e4
Faulting process id: 0x1660
Faulting application start time: 0x01d43354653ebfd7
Faulting application path: C:\Nexus Mod Manager\NexusClient.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll



 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-08-13T22:24:27.000000000Z" /> 
  <EventRecordID>7699</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DADDY-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>NexusClient.exe</Data> 
  <Data>0.65.9.0</Data> 
  <Data>5b4fb3af</Data> 
  <Data>clr.dll</Data> 
  <Data>4.7.3130.0</Data> 
  <Data>5b175fed</Data> 
  <Data>c0000005</Data> 
  <Data>00000000003dc7e4</Data> 
  <Data>1660</Data> 
  <Data>01d43354653ebfd7</Data> 
  <Data>C:\Nexus Mod Manager\NexusClient.exe</Data> 
  <Data>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll</Data> 
  <Data>a36a0fe7-9f47-11e8-a99b-902b345e59cb</Data> 
  </EventData>
  </Event>

---
Because of what it said about Msoft.Net, I downloaded and installed the latest. The log you just read is what I got afterward.  It still refuses to work. Hope this helps. 

JH Roberts USTC (Ret)

**Comment by squid-box** [comment]
Sorry, what I meant was to look for a log with ".NET Runtime" as source, like this (example):
![image](https://user-images.githubusercontent.com/864820/44063245-1f0ac2e8-9f60-11e8-9337-4f7b66e20e25.png)

**Comment by Seclusus** [comment]
Sorry about that. Hope this is the right one
--
For some reason it doesn't want to c/p properly. Hope the attached is ok.
[Log.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2285497/Log.txt)

**Comment by squid-box** [comment]
Unfortunately this is a problem we can't help you with on the NMM side. A quick Google search gave me this: https://stackoverflow.com/a/4367865

If it worked previous and you recently changed something on your computer you could try to revert that, otherwise the SO answer mentions misbehaving malware detection software, or potentially problems with your RAM.

**Comment by Seclusus** [comment]
thank you, Joel. You've been most helpful. At least I know where to look
now.

Be well, kind Sir.

JH
