### ISSUE TITLE
Nexus Mod Manager Crash on Start after uninstalling skyrim and reinstalling.

### ISSUE THREAD

**Issue by ITry2Miss** [Nexus-Mods/Nexus-Mod-Manager#562]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
I try to click on skyrim through NMM and when I do it says mods may have been moved or deleted which they have been and when I click no I get a tracelog error. 
 
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Problem whilst committing Install Log.
**Environment**
-most recent version of NMM
- Mod(s) used: none

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

to reproduce install skyrim with mods and the uninstall and then reinstall and try playing

**Additional information** 
my mods were in the game folder so when I uinstalled the game I also deleted all mods

I had skyrim SE installed and modded then I deleted skyrim SE through steam without first unistalling the mods and now when I try to open skyrim Se in NMM I get the tracelog error stated above

**Comment by squid-box** [comment]
Without the actual trace log there's nothing we can do here.
If you're still having this issue 1+ year later, add the trace log and reopen this issue.
