### ISSUE TITLE
One of the NMM screens isnt coming up when opened

### ISSUE THREAD

**Issue by FeatherFunk** [Nexus-Mods/Nexus-Mod-Manager#567]
When I open NMM it no longer automatically logs me in and one of the two screens doesn't come up. It is not the load order screen but the other one, were you activate the mods So I haven't been able to add any new mods to my load order page.

**Comment by squid-box** [comment]
Check [this wiki page on what info can be useful in a bug report](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#what-information-is-needed-in-the-bug-report). 

Quick questions:
* What version of NMM are you using?
* What game are you trying to mod?
* Can you attach a screenshot showing the problem?
