### ISSUE TITLE
Cannot open setting.

### ISSUE THREAD

**Issue by tommyonsn** [Nexus-Mods/Nexus-Mod-Manager#568]
![20180815044239](https://user-images.githubusercontent.com/3377588/44117367-b177eb52-a045-11e8-9498-9fdeac072250.png)
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
[TraceLog20180815043831.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2288425/TraceLog20180815043831.txt)

**Comment by squid-box** [comment]
I've managed to reproduce this on my computer and verified that #569 will fix this. Hopefully it's included in the next release.

As a work-around you could reinstall NMM, and ensure "Associate NXM: URLs with Nexus Mod Manager" is checked:
![image](https://user-images.githubusercontent.com/864820/44230896-be088680-a19c-11e8-8030-fb98f2d004b1.png)
