### ISSUE TITLE
NMM will not update

### ISSUE THREAD

**Issue by mac173** [Nexus-Mods/Nexus-Mod-Manager#572]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
when I try to update NMM I get an error message, either when I open NMM and it promps me to update, or if I do it manually. There is a temp folder it says is missing. I tried to add that folder, but it does not work. I am currently on version 0.65.6 and it is trying to update to 0.65.9
[TraceLog20180816183550.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2295445/TraceLog20180816183550.txt)

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_
Open NMM or try to manually update it. 

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
It's a bug in the code used to download the file, it was fixed in 0.65.8 - you'll have to grab it manually from https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/latest and install it. After this it should be working fine though.

**Comment by mac173** [comment]
squid-box, thank you. I have the new release installed.
