### ISSUE TITLE
Nmm has a high chance to stop working when i do anything.

### ISSUE THREAD

**Issue by alexandreleporc** [Nexus-Mods/Nexus-Mod-Manager#573]
anytime i do do something within nmm it will most definitely stop functioning, even when i just start it sometimes it wont open and stop working. I have looked litterally every where online, from every imagineable forum, to 140p ytube videos discussing a similar matter. nothing has helped me. Plz help me figure out the problem! :(

Here is the tracelog, I hope it helps and btw the last part is french, I can translate it if you want.

Trace file has been created: TraceLog20180811010217.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Games\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Breaking Wheel (BreakingWheel)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\545890\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Dragon's Dogma (DragonsDogma)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\367500\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout3\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout 4 (Fallout4)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\377160\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout4\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\FalloutNV\Installed Path
                Found 
            Returned:  (IsNull=True)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    No Man's Sky (NoMansSky)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\275850\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Getting Steam install folder.
                Found c:\program files (x86)\steam\steamapps\common\Oblivion
            Returned: c:\program files (x86)\steam\steamapps\common\Oblivion (IsNull=False)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Skyrim\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim Special Edition (SkyrimSE)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\489830\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\SkyrimSE\Installed Path
                Found 
            Returned:  (IsNull=True)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236930\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    The Witcher 3 (Witcher3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\292030\Installed
                Getting install folder from Uninstall.
                Found 
            Getting GOG install folder.
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    XCOM 2 (XCOM2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\268500\Installed
                Getting Steam install folder.
                XCOM2 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Starting search.
Loading Game Mode Factories for Installed Games...
    Loading Oblivion: Supported
Determining Game Mode: (From Selection Form) Oblivion
Game Mode Factory Selected: Oblivion (Oblivion)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Oblivion (Oblivion)
    Installation Path: c:\program files (x86)\steam\steamapps\common\Oblivion
    Install Info Path: c:\Games\Nexus Mod Manager\Oblivion\Install Info
    Mod Path: c:\Games\Nexus Mod Manager\Oblivion\Mods
    Mod Cache Path: c:\Games\Nexus Mod Manager\Oblivion\Mods\cache
    Mod Download Cache: c:\Games\Nexus Mod Manager\Oblivion\Mods\downloads
    Overwrite Path: c:\Games\Nexus Mod Manager\Oblivion\Install Info\overwrites
    Virtual Install Path: c:\Games\Nexus Mod Manager\Oblivion\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Games\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Games\Nexus Mod Manager\GameModes
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Games\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
        Checking: OMod.dll
            Initializing: Nexus.Client.Mods.Formats.OMod.OModFormat
    Found 2 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: c:\Games\Nexus Mod Manager\Oblivion\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: c:\Games\Nexus Mod Manager\Oblivion\Install Info\InstallLog.xml
    Loaded from XML.
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: c:\program files (x86)\steam\steamapps\common\Oblivion\Data
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCBattlehornCastle.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCFrostcrag.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCHorseArmor.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCMehrunesRazor.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCOrrery.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCShiveringIsles.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCSpellTomes.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCThievesDen.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCVileLair.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Knights.esp
                Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Oblivion.esm
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCBattlehornCastle.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCFrostcrag.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCHorseArmor.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCMehrunesRazor.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCOrrery.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCShiveringIsles.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCSpellTomes.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCThievesDen.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCVileLair.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Knights.esp
                Registered.
            Found: c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Oblivion.esm
                Registered.
        Found 11 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Knights.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Oblivion.esm (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCBattlehornCastle.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCMehrunesRazor.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCSpellTomes.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCShiveringIsles.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCFrostcrag.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCOrrery.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCThievesDen.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCHorseArmor.esp (IsNull=False)
            Loading c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCVileLair.esp (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: c:\program files (x86)\steam\steamapps\common\Oblivion\oblivion.exe (IsNull=False)
    OBSE Command: c:\program files (x86)\steam\steamapps\common\Oblivion\obse_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    Wrye Bash Command:  (IsNull=False)
    LOOT Command:  (IsNull=True)
Loading Plugins into Plugin List: 11
    Loading: Oblivion.esm (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Oblivion.esm) (False)
    Loading: Knights.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\Knights.esp) (False)
    Loading: DLCBattlehornCastle.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCBattlehornCastle.esp) (False)
    Loading: DLCMehrunesRazor.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCMehrunesRazor.esp) (False)
    Loading: DLCSpellTomes.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCSpellTomes.esp) (False)
    Loading: DLCShiveringIsles.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCShiveringIsles.esp) (False)
    Loading: DLCFrostcrag.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCFrostcrag.esp) (False)
    Loading: DLCOrrery.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCOrrery.esp) (False)
    Loading: DLCThievesDen.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCThievesDen.esp) (False)
    Loading: DLCHorseArmor.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCHorseArmor.esp) (False)
    Loading: DLCVileLair.esp (c:\program files (x86)\steam\steamapps\common\Oblivion\Data\DLCVileLair.esp) (False)
Setting up listener on Nexus Mod Manager-OblivionIpcServer/OblivionListener at 2018-08-11 01:02:38
Running Application.
Checking for new client version...
    Could not connect to update server: Le serveur distant a retourné une erreur : (403) Interdit.
    Adding Mod to running instance of client: nxm://oblivion/mods/11364/files/11094
    [nxm://oblivion/mods/11364/files/11094] Adding Mod to AddModQueue
    [nxm://oblivion/mods/11364/files/11094] Starting Add Mod Task.
    Adding Mod to running instance of client: nxm://oblivion/mods/5296/files/1000019647
    [nxm://oblivion/mods/5296/files/1000019647] Adding Mod to AddModQueue
    [nxm://oblivion/mods/5296/files/1000019647] Starting Add Mod Task.
    [nxm://oblivion/mods/5296/files/1000019647] Starting Add Mod Task.
    [nxm://oblivion/mods/5296/files/1000019647] Downloading Files.
    [nxm://oblivion/mods/5296/files/1000019647] Launching downloading of https://files.nexus-cdn.com/101/5296/Unofficial Oblivion Patch-5296-3-5-6.7z?md5=uaMl06gy1k0ei4h7REGrlA&expires=1534115150&user_id=21127829&rip=86.233.128.133.
    [https://files.nexus-cdn.com/101/5296/Unofficial Oblivion Patch-5296-3-5-6.7z?md5=uaMl06gy1k0ei4h7REGrlA&expires=1534115150&user_id=21127829&rip=86.233.128.133] Retreiving metadata.
    [https://files.nexus-cdn.com/101/5296/Unofficial Oblivion Patch-5296-3-5-6.7z?md5=uaMl06gy1k0ei4h7REGrlA&expires=1534115150&user_id=21127829&rip=86.233.128.133] Downloading.
    [nxm://oblivion/mods/11364/files/11094] Starting Add Mod Task.
    [nxm://oblivion/mods/11364/files/11094] Downloading Files.
    [nxm://oblivion/mods/11364/files/11094] Launching downloading of https://files.nexus-cdn.com/101/11364/Oblivion 1_2_416 English-11364.zip?md5=Onp1OpCdnK5L8YTcEuqCbA&expires=1534115201&user_id=21127829&rip=86.233.128.133.
    [https://files.nexus-cdn.com/101/11364/Oblivion 1_2_416 English-11364.zip?md5=Onp1OpCdnK5L8YTcEuqCbA&expires=1534115201&user_id=21127829&rip=86.233.128.133] Retreiving metadata.
    [https://files.nexus-cdn.com/101/11364/Oblivion 1_2_416 English-11364.zip?md5=Onp1OpCdnK5L8YTcEuqCbA&expires=1534115201&user_id=21127829&rip=86.233.128.133] Downloading.
    [c:\Games\Nexus Mod Manager\Oblivion\Mods\downloads\Unofficial Oblivion Patch-5296-3-5-6.7z] Adding mod from archive.
    [c:\Games\Nexus Mod Manager\Oblivion\Mods\downloads\Oblivion 1_2_416 English-11364.zip] Adding mod from archive.
    
    Tracing an Unhandled Exception:
    Exception: 
Message: 
	La valeur ne peut pas être null.
Nom du paramètre : ptr
Full Trace: 
	System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : ptr
   à System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   à SevenZip.SevenZipLibraryManager.InArchive(InArchiveFormat format, Object user)
   à SevenZip.SevenZipExtractor.Init(String archiveFullName)
   à Nexus.Client.Util.Archive.GetExtractor(String p_strPath, Boolean p_booThreadSafe)
   à Nexus.Client.ModAuthoring.ModBuilder.DoFromArchive(IModFormatRegistry p_mfrFormats, String p_strArchivePath, ConfirmOverwriteCallback p_dlgConfirmOverwrite, String& p_strMessage)
   à Nexus.Client.ModAuthoring.ModBuilder.DoWork(Object[] p_objArgs, String& p_strMessage)
   à Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   à Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

    Running Threads (2)
    4 () 
        Aborted
    18 () 
        Aborted

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
