### ISSUE TITLE
No Man Sky mods wont install.

### ISSUE THREAD

**Issue by MithelCelestia** [Nexus-Mods/Nexus-Mod-Manager#574]
For some reason no mod I try to install are added into the MODS folder. I've tried re-searching for the game folder again and Nexus still can't place the files into tue folder. Nexus will say I installed it but upon checking the folder it's just not there.

**Environment**
- NMM version: 0.65.9
- Mod(s) used: Any of them

**To Reproduce**
I just simply attempted to install a mod. As I look into the No Man's Sky mod folder, nothing is added except for the PCBANKS/MODS folder.

**Additional information** 
No Man's Sky was recently updated to NEXT 1.57. Note that the mod still works if I install them manually. The only problem is I can't install them with Nexus.

**Comment by squid-box** [comment]
I know absolutely nothing about modding for No Man's Sky, but trying to install one mod ( https://www.nexusmods.com/nomanssky/mods/616 ) seems to work. NMM does complain that there is no `PCBANKS/MODS` folder, but it is created and the mod .pak file is put in there.

Is this not correct?

**Comment by MithelCelestia** [comment]
There must be something wrong with my install of Nexus for the mods not to install properly. What can I do besides reinstalling to put Nexus back into its freshest state? At least for No Man's Sky. My other game Skyrim doesn't have this problem so it must be a problem with the settings for No Man's Sky.

**Comment by squid-box** [comment]
The only thing to reset NMM would be to remove the config files here: `%LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_Url_<gibberish>\0.65.9.0`

This won't reset the mod state of your games, but it will remove any scanned games, set paths for where mods are saved etc.

You could backup the `user.config` file and then delete it and try running NMM (No need to uninstall/reinstall NMM for this.) and install a mod for No Man's Sky. If it still doesn't work you can restore the `user.config` file, if it does work you'll need to point NMM at the old folders for your other games.

**Comment by MithelCelestia** [comment]
Yeah that fixed it. Thanks. Just a word of note that I had moved the game folder to another drive so maybe the settings have caused something that prevented the mods from installing. I even rescaned the library from time to time and it didn't fix it until the user config was reset.

**Comment by squid-box** [comment]
That's good to know. Given other reports of issues with changing paths not sticking, that seems to be the root cause of this issue.

I'll leave this issue open untill I've had time to read through and try to connect all similar issue together.

**Comment by Jevnaker** [comment]
i have issues with nexus mods downloading an older version of my mod than clicked on when i tried to update an mod for no mans sky.
