### ISSUE TITLE
I can't log in nexus mod manger

### ISSUE THREAD

**Issue by salderosan99** [Nexus-Mods/Nexus-Mod-Manager#575]
I've downloaded the last version of the windows app for NexusModManager, but it fails to login when I try to Download a mod. It's not the firewall. I can easily log in and log out from the web page. I found that this issue has been addressed many times, but I can't find a true answer to the problem. Help?

**Comment by squid-box** [comment]
What version are you using?

What error message are you getting?

Did you try logging in with your username (not your email address)?

Did you try changing your password in the website?

**Comment by salderosan99** [comment]
the version is: 0.65.2

Kind of message: it's just a simple a login error, stating that the password or the usarname is wrong, but i copypasted them, and they work just fine on the websites.
 
Yep.

No, but if you say so i'll try that. Didn't thought about that. (Edit: I tried, but it didn't work. Of course, no human error)

Thank you!

**Comment by squid-box** [comment]
It was brought up on the Nexus forums, it seems some internal systems are triggered when changing the password, that might refresh some data required to log in through the authentication server NMM uses.

I'm just parroting things other people have said, but hopefully something helps out.

And as a side-note, it won't change your login problems, but the latest version at the moment is 0.65.9, and can be found [here on GitHub](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases).

**Comment by Xwolver** [comment]
Any update regarding the login issue with 0.65.2 (which is the one posted on NexusMods web)?
UPDATE: 0.65.9 login is working, once you remove the spaces.
