### ISSUE TITLE
nexus mod manager this game is installed with a unsuitable file system

### ISSUE THREAD

**Issue by sakurarozu** [Nexus-Mods/Nexus-Mod-Manager#580]
i moved my fallout 4 game to a sandisk ssd and when i went to scan my game i get message and i cant add my game. 

how i fix this thank you,.

**Comment by squid-box** [comment]
As the error states, the drive has a file system that NMM can't properly work with, it's one of these:

* FAT
* FAT32
* ReFS
* exFAT

See #331 and its linked issues for some more context.

Edit: The fix in this case would be to format the drive with another file system, eg. NTFS.

**Comment by MCM-Math** [comment]
What does the "invalid" label mean?  I get this error, and I have the game installed on an external Samsung SSD.  Is NMM not designed to work with SSDs?  Are SSDs considered "invalid" disk drives here?  This is bizarre, especially since Vortex is able to work with the drive.

**Comment by MCM-Math** [comment]
Also, this issue is with the GitHub version, but not the Nexus version 0.65.2, at least for me, suggesting it is a bug with the latest version of NMM.

**Comment by squid-box** [comment]
The key problem is which file system your external SSD has, as I outlined above.

This improvement was introduced after 0.65.2 as the unsupported file systems won't properly work with how NMM installs mods.

**Comment by MCM-Math** [comment]
Will external SSD compatibility be added in the future?

**Comment by MCM-Math** [comment]
Is it incompatible with all SSDs, or just external ones?

**Comment by squid-box** [comment]
No, as I said external SSD doesn't matter, *only your filesystem*. HDD or SSD doesn't matter.

**Comment by leehelck** [comment]
this is absolutely unacceptable. how is it that MO2 has no problem using external drives yet this broken mess cannot?! i have two instances of Fallout 4 and both run flawlessly (i deleted the appmanifest in the Steam folder when SSE updated to AE. i did the same with SSE). i am NOT about to reformat my SSD and lose EVERYTHING on it (over a tb of data!) just so this steaming pile will recognize my game. i will never use this train wreck again until this fundamental flaw is fixed. and btw, MO2 is better anyway. rant over.

**Comment by rellikpd** [comment]
> As the error states, the drive has a file system that NMM can't properly work with, it's one of these:
> 
> * FAT
> * FAT32
> * ReFS
> * exFAT
> 
> See #331 and its linked issues for some more context.
> 
> Edit: The fix in this case would be to format the drive with another file system, eg. NTFS.

My external drive 
![Screenshot 2024-03-27 211602](https://github.com/Nexus-Mods/Nexus-Mod-Manager/assets/82239837/56c86c6a-4751-4a6e-80f2-d21f68b225dc)
is exFat. still get the error
