### ISSUE TITLE
Nexus Mod Manager can't connect to the servers

### ISSUE THREAD

**Issue by Zwenksa** [Nexus-Mods/Nexus-Mod-Manager#581]
My problem is rather simple, Nexus Mod Manager is just not able to connect to the servers, which means it can't automatically update the mods and I can't login.
The following error-message appears:
"Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down."

NMM version:  0.65.2
I already tried to reinstall NMM several times and also checked my firewall which is not blocking NNM.

I would be very happy if someone could help me with this, thanks c:

**Comment by Theoryeleven** [comment]
I also have this exact same problem. Its' been this way for months and nothing I can do. Tried uninstalling and reinstalling, tried different versions, tried turning off my firewall completely, I've added it to my allowed apps in the firewall settings, I'm running it as ADMIN and still same error.

**Comment by RoyalShine** [comment]
I have also had this problem for months. It wont even let me install mods

**Comment by RoyalShine** [comment]
I just Downloaded the newest version which is 0.65.10 and everything finally works again. 
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/download/0.65.10/Nexus.Mod.Manager-0.65.10.exe
