### ISSUE TITLE
Can't load up NMM without crashing after a short moment

### ISSUE THREAD

**Issue by melonkill** [Nexus-Mods/Nexus-Mod-Manager#583]
Whenever I try to load NNM it crashes after a moment before I can do anything. I can load it up for a short moment before it crashes and I have no other way to help. I have tried uninstalling the game what I want to use (Skyrim) and reinstalled it while also doing the same for NMM but there is no difference.

- NMM version: _0.65.2_
- No mods_

**To Reproduce**
I have no idea

[TraceLog20180825203941.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320992/TraceLog20180825203941.txt)

**Comment by squid-box** [comment]
The error is `Access to the path 'C:\Users\No\AppData\Local\Skyrim\plugins.txt' is denied.`, so a workaround would be to see if you can "fix" that file. Maybe it's write-protected, maybe its security permissions deny your user to write to it, etc.

**Comment by squid-box** [comment]
OK, after checking the code I actually added some more logging and made sure NMM won't crash when this occurs, if you update to the latest version ([installers can be found here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases)) at least NMM won't crash for you.

**Comment by melonkill** [comment]
Thank you very much for the help. It seems to be working.

**Comment by squid-box** [comment]
Be sure to check that any plugins (mods) your enable are actually enabled, just reopen the issue if you find any problems there.
