### ISSUE TITLE
NMM doesn't start up

### ISSUE THREAD

**Issue by SargentSucc** [Nexus-Mods/Nexus-Mod-Manager#585]
When I open up nexus it shows a crash report saying Nexus mod manager has encountered an error and needs to close. A trace log has been created at:(my info)

[TraceLog20180829163621.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2333712/TraceLog20180829163621.txt)

**Comment by squid-box** [comment]
Duplicate of #389, download the latest version from GitHub and this should be solved.

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases
