### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by zigzag321** [Nexus-Mods/Nexus-Mod-Manager#587]
HI,

I cant register, i can fill out the forms ect in chrome , i register but no mail gets sent to me, I check my junk no email to me has been sent. I had an old account and requested new password originally but nothing got sent, then I tried to re register with same email was ok but again i received no registration email.

Can you register me and send me password then i can change it>?

cheers,  

Me

**Comment by squid-box** [comment]
Sorry, this repository is for Nexus Mod Manager, for problems with the Nexus site, etc. you'll have to contact Nexus instead.

Since you can't create an account you'll have to contact them at support@nexusmods.com 

Good luck!
