### ISSUE TITLE
Morrowind.ini not correctly updated

### ISSUE THREAD

**Issue by kgerickson** [Nexus-Mods/Nexus-Mod-Manager#59]
When adding or removing a mod with a plugin file, that plugin file is correctly added or removed in the Morrowind.ini GameFile list.  However, when changing the plugin order, the ini file is not similarly modified.  Instead, the plugin remains in the entry it had when it was first added.

I tried digging into the code to fix this myself, but I couldn't find where in the Gamebryo base that this is handled.  If you give me a pointer, I can try to fix it myself.

**Comment by kgerickson** [comment]
It looks like Unchecking and rechecking the plugin puts it in the right spot in the ini file.  Moving it up and down the list does not.

**Comment by DuskDweller** [comment]
The plugin order in the list is ignored by the game, that's just the list of plugins to enable, what the game uses as load order is the plugin file timestamp (and that's what NMM changes when you move around your plugins in the list).
