### ISSUE TITLE
Error with updating Nexus Mod manager.

### ISSUE THREAD

**Issue by jeromy384** [Nexus-Mods/Nexus-Mod-Manager#592]
**Describe the bug** 
just opened nexus mod manager and this is what it gave me, i will upload the tracelog file

**Environment**
- NMM version: 0.65.7

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
[TraceLog20180831105221.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2340741/TraceLog20180831105221.txt)

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
![image](https://user-images.githubusercontent.com/28686379/44923132-fd8eb100-ad0c-11e8-8a94-7787110bd29c.png)

**Comment by jeromy384** [comment]
though, i will just download the latest off of github, but i don't understand why i have this issue.

**Comment by squid-box** [comment]
It's a bug in how NMM downloads the update, it has since been fixed and going forward it'll work.
