### ISSUE TITLE
NMM won't let FO4 to be selected at launch

### ISSUE THREAD

**Issue by mkreilis** [Nexus-Mods/Nexus-Mod-Manager#602]
_Please give as much information as you can, replace/remove italicized text._

Installed mod for FO4, encountered unexpected error and forced to close
_A short description of what the problem is_
While trying to set up mods before starting another FO4 binge NMM closed and I could not find a similar error on the forum post. I think it was with CBBE but a few other mods had issues w/ installing before crash. Hadn't even ran FO4 but have since the crash and no change.

**Environment**
- NMM version: BETA 0.65.5
- Mod(s) used: 

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
[TraceLog20180909111259.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2364370/TraceLog20180909111259.txt)

**Comment by squid-box** [comment]
The error is the same as in #300, check there for potential causes and solutions.
