### ISSUE TITLE
0.65.9 cannot log in - NOT FIREWALL

### ISSUE THREAD

**Issue by KriceF** [Nexus-Mods/Nexus-Mod-Manager#605]
Cannot log in with NMM 0.65.9
I either get one of two messages depending on how I approach the log in
1. I log in through NMM and "Login error: Wrong username or password" is the result. It should be noted I use the exact username and password that I use on the Nexus website, and have checked at least 10 times. 
2. I install a mod via the website and open NMM for the download results in an infinite "Login in process... Wait for the login attempt." The app is allowed through firewall.

**Comment by squid-box** [comment]
There have been several people who've been able to log in after changing their password on Nexus once, seems that some authentication server needs to be refreshed and that is accomplished by changing the password.

The second problem is a feature, you can't download anything from Nexus if you're not logged in. It could be that the login dialog is hidden behind NMM.

**Comment by KriceF** [comment]
After changing my password, it works fine now. Really strange as it worked on the site but not the client, oh well. 

Thank you.
