### ISSUE TITLE
nexus crash

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#617]
when I try to check "Add shell extensions for supported file types" in nexus settings, it crashes nmm
[TraceLog20180920234724.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2403860/TraceLog20180920234724.txt)

**Comment by squid-box** [comment]
This was fixed in a more recent version, grab [0.65.10 or later](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and it should work.
