### ISSUE TITLE
The Manager Keeps "encountering an issue and needs to close"

### ISSUE THREAD

**Issue by Dibbins09** [Nexus-Mods/Nexus-Mod-Manager#620]
[TraceLog20180920210434.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404850/TraceLog20180920210434.txt)
[TraceLog20180920210500.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404851/TraceLog20180920210500.txt)
[TraceLog20180921100923.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404852/TraceLog20180921100923.txt)
[TraceLog20180921101020.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404853/TraceLog20180921101020.txt)
[TraceLog20180921105047.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404854/TraceLog20180921105047.txt)
[TraceLog20180914112022.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404856/TraceLog20180914112022.txt)
[TraceLog20180914182121.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404857/TraceLog20180914182121.txt)
[TraceLog20180918134045.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404858/TraceLog20180918134045.txt)
[TraceLog20180920194625.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404859/TraceLog20180920194625.txt)
[TraceLog20180920205813.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404860/TraceLog20180920205813.txt)
[TraceLog20180920210114.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404861/TraceLog20180920210114.txt)
[TraceLog20180920210150.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2404862/TraceLog20180920210150.txt)

**Comment by squid-box** [comment]
There's a few errors appearing, at least some are already fixed.

Install the latest [Github release](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and see if that helps 

Otherwise you'll have to put more effort into your bug report if someone is to be able to help you.
