### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by Hjelm2002** [Nexus-Mods/Nexus-Mod-Manager#628]
Hey ! My NMM interface has a bug and I don't know how to fix it. You see all of the folder's name are minimize in addition to the mod's name can someone help me pls ???

**Comment by squid-box** [comment]
It sounds like the resized column issue, try this: https://youtu.be/c9pgqyPG0vo

**Comment by Hjelm2002** [comment]
ah
that was simple... Now I feel a little bit stupid but thank you very much

**Comment by squid-box** [comment]
It's always easy once you know the answer ;)

Happy to help!
