### ISSUE TITLE
Problem when i try to downaload a mod

### ISSUE THREAD

**Issue by aVeryDarkGalaxy** [Nexus-Mods/Nexus-Mod-Manager#629]
_

**Describe the bug** 
Everytime i try to download a mod i get and error saying nexus mod manager is not setup to work with skyrim, and if skrim is installed rescan for installed games from the change game toolbar.

**Environment**
any mod

**To Reproduce**

**Additional information** 
i have just downloaded nexus i went through a tutorial video and i am at the point to where the guy downloads a mod so i try to follow him and click install with a manager and get this pop up. do i have to make a character ingame or what?

**Comment by Ghostwalker71** [comment]
Have you run the scan so that NMM has located the games you have installed. If so, are you sure you are trying to download mods for the correct version of skyrim. IE Skyrim or Skyrim special edition.

**Comment by aVeryDarkGalaxy** [comment]
Thanks man, I was clicking regualar skyrim and not skyrim se.
