### ISSUE TITLE
Mods tabs too much space

### ISSUE THREAD

**Issue by lIAceIl** [Nexus-Mods/Nexus-Mod-Manager#63]
the name/category/install date/etc use up 3 full screens of space. each tab has about 1/2 a screen of space.

dragging tabs to shrink them only gives the space to the next tab. so there's always 3 screens of tabs and reducing the tabs to 1 page just makes the last tab 2 screens long.

it also always resizes so the mod with the longest name will fit in the "name" tab.

![bug2](https://cloud.githubusercontent.com/assets/10265840/24765196/1ca91c84-1ab4-11e7-881f-93043a2dd859.JPG)

**Comment by DuskDweller** [comment]
Try going in the Tools menu and hit "Reset UI".

**Comment by lIAceIl** [comment]
thanks, that did it


________________________________
