### ISSUE TITLE
MOD LOADING ERROR

### ISSUE THREAD

**Issue by wwolfy77** [Nexus-Mods/Nexus-Mod-Manager#630]
_Please give as much information as you can, replace/remove italicized text._

I have been using NMM for years now.  This morning I began getting these error messages stating an error was made loading some mods.  
**Environment**
- NMM version: 0.65.2
- Mod(s) used: _<link to mod(s) on Nexus>_Its not the mods, they worked fine before and the list changes at every restart of the mod manager.

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 I just start the NMM

**Additional information** 
This is a very inefficient way  of communication, terrible sign up / sign in process that randomly says you need a new password, to this static form that has no guarantee that it is even looked at.  Why don't you just admit you don't support what we don't pay you for.  Waste of time

**Comment by squid-box** [comment]
So you've made no attempt at describing your error, only venting frustrations (in the wrong place) with a team that dropped support for this software several years ago now?

Quoting the NMM download page on NexusMods:

> The Nexus Mod Manager (NMM) was a piece of software developed in-house at Nexus Mods between 2011 and 2016. Since December of 2016 it is now [End-of-Line and no longer officially supported](https://forums.nexusmods.com/index.php?/topic/5159340-nmm-is-currently-end-of-line-read-why-and-what-this-means/) by the Nexus Mods team, except in very rare cases (e.g. a security issue that needs to be patched).

And yes, in general when you pay nothing, you get nothing in return.

If you actually want to solve your issue, try [grabbing the latest installer](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and add actual bug info to this issue, or I'll close it for you in a few days.
