### ISSUE TITLE
Forever stuck loading 0.65.10.0

### ISSUE THREAD

**Issue by kkthebeast** [Nexus-Mods/Nexus-Mod-Manager#636]
[SOLVED]

![2018-10-04_00-25-00](https://user-images.githubusercontent.com/19578281/46454498-0808f400-c76c-11e8-8522-e71adf02ff74.png)
Forever loading (mostly at nights... mostly) 😆 

Sometimes force closing will snap it back to life. 50% of the time it just sits with the hard drive going nuts.

**Comment by kkthebeast** [comment]
This will happen even if there are no changes done on my end

**Comment by kkthebeast** [comment]
And this is why you don't run Bit defender... (Added Nexus to the Ignore list for "Advanced threat detection")... Sigh. Sorry, good to know

**Comment by squid-box** [comment]
Good that you found the cause, would've been hard to troubleshoot :)
