### ISSUE TITLE
Somehow nexus mod manager out of nowhere started crashing and i cant get it to work, it crashes instantly on startup it doesnt show anything

### ISSUE THREAD

**Issue by UrNotDefault** [Nexus-Mods/Nexus-Mod-Manager#643]
It told me to place here the trace file so here u go
[TraceLog20181015002122.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2482431/TraceLog20181015002122.txt)

**Comment by squid-box** [comment]
It looks like your installation has somehow become corrupted, NMM can't find XmlScript.dll, CSharpScript.dll, AntlrUtil.dll, and Fallout4.XmlScript.dll seems to be broken as well.

I would reinstall NMM, and/or check that any antivirus software isn't interfering.

**Comment by UrNotDefault** [comment]
k thx
