### ISSUE TITLE
Trojan in SevenZipSharp.dll?

### ISSUE THREAD

**Issue by Calorion** [Nexus-Mods/Nexus-Mod-Manager#644]
**Describe the bug** 
ClamXAV reports Win.Trojan.7161590-1 in SevenZipSharp.dll.

**Comment by squid-box** [comment]
Which version of NMM are you using?

**Comment by squid-box** [comment]
[Using VirusTotal](https://virustotalstorage.appspot.com/en/file/27ed71126b9b4bb2ff0acf4347babd53f38fbf8ce86f47ff0c62c6f6775bfefb/analysis/) on SevenZipSharp.dll used in 0.65.10 it seems only ClamXAV is reporting this, leading me to believe it's a false positive.

**Comment by Calorion** [comment]
> Which version of NMM are you using?

0.65.10.
