### ISSUE TITLE
Nexus plz fix

### ISSUE THREAD

**Issue by miskovil** [Nexus-Mods/Nexus-Mod-Manager#646]
_Please give as much information as you can, replace/remove italicized text._

every tome that i open NMM it gives me a popup saying basicly that it has to close cuzz a unexpected bugg has happened*

**Environment**
- NMM version: the newest one idk witch one it is
- Mod(s) used: https://www.nexusmods.com/fallout4/mods/32185?tab=files

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
idk

**Additional information** 
[TraceLog20181017170418.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2488037/TraceLog20181017170418.txt)

_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
You're using 0.65.2, which is not the latest version.

The error message you're getting is `There is not enough space on the disk.`, which is pretty self-explanatory.
