### ISSUE TITLE
32-bit DLL

### ISSUE THREAD

**Issue by Calorion** [Nexus-Mods/Nexus-Mod-Manager#647]
**Describe the bug** 
The [wiki](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki) says 

> Nexus Mod Manager needs a different DLL if being used on a 32bit system.
> 
> Please click [here] to download the correct DLL

But "[here]" is not linked.

**Comment by squid-box** [comment]
Hard to tell since it's never been linked and it's not named anywhere. What problem are you having on a 32-bit system?

**Comment by Calorion** [comment]
I'm not sure I'm having any problems (other than being unable to launch FOSE as I mentioned in the other Issue); I just wanted to make sure that it was installed properly.

**Comment by jbostrus** [comment]
I believe it's old documentation referring to the 7zip Sharp that used to be used. Now it uses a different dll and comes with both a 32bit and 64bit version so it's not relevant any longer.

**Comment by Calorion** [comment]
Then perhaps the wiki should be updated?

**Comment by squid-box** [comment]
Well, just for the sake of it I've now removed most of that text from the wiki.
