### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by erykosery** [Nexus-Mods/Nexus-Mod-Manager#656]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
then i wanted to launch myself a new vegas game crashed and i cannot launch even by steam

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
@erykosery: You really need to try harder, provide some information on what you're doing, what's going wrong, and what you're using.

No one can help you with the short sentence you wrote.
