### ISSUE TITLE
plz help me

### ISSUE THREAD

**Issue by giang6996** [Nexus-Mods/Nexus-Mod-Manager#659]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
[TraceLog20181114201728.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2580898/TraceLog20181114201728.txt)

**To Reproduce**
 _How to reproduce the problem_

[TraceLog20181114202318.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2580895/TraceLog20181114202318.txt)

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
See #300.

**Comment by squid-box** [comment]
With no further comments in two weeks, I'm closing this issue.
