### ISSUE TITLE
Can't Delete Mods That I Paused From Downloading

### ISSUE THREAD

**Issue by Skully202** [Nexus-Mods/Nexus-Mod-Manager#66]
This is so annoying some mods I sometimes realize are not worth downloading so I pause them but you can't delete them which is so ANNOYING!

**Comment by Arefu** [comment]
When it's canceled (Not paused) you can delete them... Or am I lost?

**Comment by Skully202** [comment]
Ok,how tf do you cancel?

**Comment by Nubbie** [comment]
Sorry for the dump years later
But if you've downloaded the mod, you can use the button in the bottom (v 0.70.7) so this issue should have been resolved

![image](https://user-images.githubusercontent.com/17282384/58344506-28e69c80-7e56-11e9-909d-d3e2c5fd916c.png)

@squid-box

**Comment by squid-box** [comment]
I believe the order is Praise, Cancel, Remove/Delete.

Either way the issue is two years old and more of a question than a bug, so I'm closing this.
