### ISSUE TITLE
NMM Won't open at all and Skyrim Doesn't load saves

### ISSUE THREAD

**Issue by Madwaq** [Nexus-Mods/Nexus-Mod-Manager#661]
I downloaded a few mods about two months back and the game was going alright. I remember like a month later I couldn't load my most recent save but I fixed this by loading the next save that would load and retracing to my current save. I haven't installed anymore mods at all, nor have I been doing anything that could pressure the game at all. Just casual playing and now the game Won't open at all. I checked NMM and it won't even let me open the interface to see if there's a conflict with my mods. And even if there is I'm not sure why after so long it would just suddenly now be causing problems. I have tried disabling some mods  through Skyrim Launcher, I've tried running the game without skse, Running through admin (Both NMM and Skyrim), I've also tried disabling my antivirus and still no resolve. HELP PLEASE! It gives me a trace error.
[TraceLog20181115125248.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2586619/TraceLog20181115125248.txt)

**Comment by squid-box** [comment]
NMM is crashing due to: 

`Could not find a part of the path 'W:\Games\Nexus Mod Manager\Skyrim\Mods\VirtualInstall'.`

Did you move that folder somewhere else? If it's gone the mods can't be loaded in Skyrim either.

**Comment by Madwaq** [comment]
Oh yeah! I had a hard drive but then it stopped working. It was my W:\ drive. Is there any way I can move it to another location?

**Comment by squid-box** [comment]
You'll have to change the setting manually, it's available in a fairly obscure file (you'll have to browser for it, as I don't know your local path): `%AppData%\Local\Black_Tree_Gaming\NexusClient.exe_Url_<some-random-text>\0.65.2.0\user.config`

Search for the faulty path `W:\Games\Nexus Mod Manager\Skyrim\Mods\VirtualInstall` in the user.config file and either change it to a correct folder, or remove the line and NMM should hopefully prompt you to select a new path when you start it.

It can be a good idea to make a copy of user.config before you modify it, in case something else breaks :)

**Comment by Madwaq** [comment]
Oh my gosh thank you sooo much. You have no Idea what you have done for me. That solution fixed my problem.
