### ISSUE TITLE
Missing NMM folder when downloading CBBE for fallout 4

### ISSUE THREAD

**Issue by StalinTheBallin** [Nexus-Mods/Nexus-Mod-Manager#662]
So downloaded CBBE for fallout 4 a long time ago and because NMM wouldn't install it properly I downloaded it manually (the usual deal of putting it into the data folder and what not). Today since I was going through my mods for fallout 4 I thought I would try downloading it using NMM. I thought it would just replace any files that were already in the game's folder. The mod has a menu that shows up in NMM that shows you the different options and when I selected the nevernude option I got and error. When I looked at the alst bit of the tracelog it said it couldn't find part of the path where some of the mod files should go (Could not find a part of the path 'C:\Users\Sarah\AppData\Local\Temp\NexusModManager\tz0qiaaw.llx\FOMod\NeverNude.jpg'.) When I looked at the path it mentioned I found that there was no nexus mod manager folder in the temp folder. Now I was thinking that simply making the folder would solve it, but I haven't done that yet and wanted to make sure what I was doing was correct.
[TraceLog20181117022037.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2591616/TraceLog20181117022037.txt)

**Comment by squid-box** [comment]
The temp folder is deleted after every NMM run, so it would only fix it once (if it's just the temp folder path missing, and not the temporary mod files.

There have been some improvements in NMM since 0.65.2, you could try using they latest version instead: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by StalinTheBallin** [comment]
Thank you! Turns out just updating NMM solved the issue. Can't believe it was that simple.
