### ISSUE TITLE
Nexus Crashes before opeing fallout 4 

### ISSUE THREAD

**Issue by Eddybears** [Nexus-Mods/Nexus-Mod-Manager#663]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
It only crashes when selecting fallout four 
[TraceLog20181117144726.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2591911/TraceLog20181117144726.txt)

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
See #300
