### ISSUE TITLE
4 Tracelogs, some may be the same, please help

### ISSUE THREAD

**Issue by L1ghtn1ngFlash** [Nexus-Mods/Nexus-Mod-Manager#669]
[TraceLog20181204012605.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2643257/TraceLog20181204012605.txt)
[TraceLog20181204012819.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2643258/TraceLog20181204012819.txt)
[TraceLog20181204013338.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2643259/TraceLog20181204013338.txt)
[TraceLog20181204013724.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2643260/TraceLog20181204013724.txt)

**Comment by squid-box** [comment]
There's two different crashes listed in these logs. At least one of them is fixed in the latest version ([0.65.10](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.10)) - so I would start by updating to it and see if the other crash still happens.
