### ISSUE TITLE
Mod Configuration Menu

### ISSUE THREAD

**Issue by Sevinhand** [Nexus-Mods/Nexus-Mod-Manager#680]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by Sevinhand** [comment]
'Your game version: v1.10.120.0
'Expected game versio:1.10.114.0
Mod Configuration Menu will be disabled
What does this mean and do I need to fix it?
![screenshot 17](https://user-images.githubusercontent.com/46271105/50552696-69e1e700-0ce4-11e9-8036-5fcf91c1187b.png)

**Comment by viper1s** [comment]
You need to update your Mod Configuration Menu to the same level as your game . I believe that would be Fallout 4 and the version of Fallout 4 is 1.10.120.0 The version of MCM to download is 1.34 for that Fallout 4 version
This has zilch to do with NMM

**Comment by squid-box** [comment]
Thanks for clarifying viper1s!

@Sevinhand: Please follow viper1's instructions above, or contact someone involved with Mod Configuration Menu if you get stuck.

I will close this issue.
