### ISSUE TITLE
Unable to install or activate at all

### ISSUE THREAD

**Issue by Lillievela** [Nexus-Mods/Nexus-Mod-Manager#682]
So I started up NMM and an error occered where basically the entirety of NMM got corrupted and i had to reinstall everything, thats fine. But when it said that some where missing and i can no longer install those due to root being missing(?) and i cant activate 2 new mods because of some unknown error. I am on 65.11.0

**Comment by Lillievela** [comment]
I have managed to fix But one mod is not being able to install

**Comment by squid-box** [comment]
You'll need to provide a better description of the problem.

Which mod are you trying to install, and what error message are you getting?

**Comment by Lillievela** [comment]
it was the vampire leather armor set ( https://www.nexusmods.com/skyrim/mods/28887 ) it eventually worked. The error was "A problem occurred during install"

**Comment by squid-box** [comment]
Ok, usually when you get that error you can hover with the mouse cursor on the error message (or the error icon, I can't recall) to get a more detailed description.

If it happens again could you please add that additional info as well? I'm not sure much can be done with this issue without more info - especially if you've got everything working now.

**Comment by viper1s** [comment]
The "missing mods" may have been in the Virtual Install folder that had changed locations on re-install of NMM
When you get an error (and the old red circle stop icon) try activating the mod again. If successful , download another copy of that mod as a manual download . Go back to the mod just installed and do an uninstall and delete mod from NMM. Then load the mod you just did a manual download on , and activate that one.

Or try the simple thing. Close mod manager , bring it back up , and try again
Works for me every time.

**Comment by Lillievela** [comment]
Thank you to Viper1s for the help, I ended up doing that
