### ISSUE TITLE
NNM Keeps crashing due to Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Preyzen** [Nexus-Mods/Nexus-Mod-Manager#689]
It worked perfectly until I restarted my PC, then NMM Doesn't want to work. When I double click the icon on desktop It crashes and gives me a trace log, the problem is Object reference not set to an instance of an object. I'm not sure why it's happening because it worked perfectly.

**Comment by squid-box** [comment]
You really need to provide that trace log if you want to get any help with this.
