### ISSUE TITLE
Fallout 4 plugin moving unusually slow

### ISSUE THREAD

**Issue by BlackTestament7** [Nexus-Mods/Nexus-Mod-Manager#692]
**Describe the bug** 
_A short description of what the problem is_
Moving plugins up and down for Fallout 4 is taking an weird amount of time. One plugin takes around 9 secs or more, multiple plugins moved at once takes full minutes at a time. I'd use notepad++ to just edit that way but I can't import load orders either. I get an error saying "An item with the same key has already been added" which I don't know what that means or how to fix it.

**Environment**
- NMM version:  0.65.11

**To Reproduce**
 _How to reproduce the problem_
I'm not even sure why it's happening. But I do know it started happening when I updated from 0.65.10 to 0.65.11. Although, I haven't been able to import load orders since ESL support came out.

**Comment by Wishkahkid** [comment]
Same here. There's another thread about this down further about this latest update hanging up when it comes to moving plugins. I hope it get's fixed.

**Comment by jbostrus** [comment]
@squid-box You can close this now as it has been merged and built.
