### ISSUE TITLE
Nexus wont update

### ISSUE THREAD

**Issue by Freon7766** [Nexus-Mods/Nexus-Mod-Manager#696]
I have been having this problem for some time now and ive tried everything...everything it has stopped connecting to the server it says and I quote "The following updates failed: Nexus Mod Manager Updater: Could not get version information from the update server" I am running version 0.65.2 i can not find the problem ive tried everything from changing settings back too fresh restart i hope the problem can be found soon...

**Comment by squid-box** [comment]
Automatic updates from 0.65.2 will never work, grab the latest installer from [GitHub](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and subsequent releases will be automatically downloaded.

**Comment by Freon7766** [comment]
That fixed my problem thank you! :)
