### ISSUE TITLE
Please add external SSD compatibility

### ISSUE THREAD

**Issue by MCM-Math** [Nexus-Mods/Nexus-Mod-Manager#697]
I have a laptop, and I use an external SSD for video games, for speed and to make sure there is enough space on my main drives.  However, it seems that NMM is not intended for use with external SSDs (https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/580).  I would not be the only one who would benefit from NMM having better compatibility with external SSDs.

**Comment by squid-box** [comment]
As stated in the contents of #580, the file systems but supported are:
* FAT
* FAT32
* ReFS
* exFAT

This is due to for these file systems handle links, which are used for the virtual install of mods.

**Comment by MCM-Math** [comment]
Okay, so I request that you please add the additional file system support that would allow NMM to work with external SSDs, as well as whatever else is needed.  I would not be the only one who would benefit from NMM having better compatibility with external SSDs.

**Comment by squid-box** [comment]
Please try to comprehend what I'm saying: it's about your file system, not your hardware.
