### ISSUE TITLE
installation file NMM

### ISSUE THREAD

**Issue by Gronoel** [Nexus-Mods/Nexus-Mod-Manager#702]
i tried downloading the NMM main installation file, but i somehow keep getting a .148-file.
i've got no clue what to do with this, and how to fix this.
any advice?

**Comment by squid-box** [comment]
I'm not sure what you mean by a `.148-file`, but have you gone to the [Releases page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) and downloaded the .exe installer?

![image](https://user-images.githubusercontent.com/864820/52906089-9676a180-3245-11e9-99b0-397a3293f001.png)

**Comment by Gronoel** [comment]
I've gone to the official page, where i downloaded the file. Pretty sure it's supposed to download the .exe file from there, as i have seen people do it on YT.
As for the .148-file, i don't know what it is, but the file ends with .148, and when i check it through properties, it tells me that's the file type

**Comment by squid-box** [comment]
If you're having trouble downloading old files from Nexusmods, you'll have to contact them about it. This repo is just for NMM.
