### ISSUE TITLE
trace log issue 

### ISSUE THREAD

**Issue by gunss** [Nexus-Mods/Nexus-Mod-Manager#704]
for fallout nv and 3

I get a trace log and the mod dos not instal _

- NMM version: _0.65._
- Mod(s) used: any mod

Trace file has been created: TraceLog20190306024054.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Breaking Wheel (BreakingWheel)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\545890\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Dragon's Dogma (DragonsDogma)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\367500\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout3\Installed Path
                Found C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\
            Returned: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\ (IsNull=False)
    Fallout 4 (Fallout4)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\377160\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout4\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Getting Steam install folder.
                Found c:\program files (x86)\steam\steamapps\common\Fallout New Vegas
            Returned: c:\program files (x86)\steam\steamapps\common\Fallout New Vegas (IsNull=False)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    No Man's Sky (NoMansSky)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\275850\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Oblivion\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Skyrim\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim Special Edition (SkyrimSE)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\489830\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\SkyrimSE\Installed Path
                Found 
            Returned:  (IsNull=True)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236930\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    The Witcher 3 (Witcher3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\292030\Installed
                Getting install folder from Uninstall.
                Found 
            Getting GOG install folder.
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    XCOM 2 (XCOM2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\268500\Installed
                Getting Steam install folder.
                XCOM2 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Starting search.
Loading Game Mode Factories for Installed Games...
    Loading Fallout3: Supported
    Loading FalloutNV: Supported
Determining Game Mode: (From Selection Form) Fallout3
Game Mode Factory Selected: Fallout 3 (Fallout3)
Creating Game Mode mutex (Attempt: 0)
Checking DLCs location.
    Anchorage...Done
    ThePitt...Done
    BrokenSteel...Done
    PointLookout...Done
    Zeta...Done
Game Mode Built: Fallout 3 (Fallout3)
    Installation Path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty
    Install Info Path: C:\Games\Nexus Mod Manager\Fallout3\Install Info
    Mod Path: C:\Games\Nexus Mod Manager\Fallout3\Mods
    Mod Cache Path: C:\Games\Nexus Mod Manager\Fallout3\Mods\cache
    Mod Download Cache: C:\Games\Nexus Mod Manager\Fallout3\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\Fallout3\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\Fallout3\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: Fallout3.CSharpScript.dll
                Initializing: Nexus.Client.Games.Fallout3.Scripting.CSharpScript.Fallout3CSharpScriptType
            Checking: Fallout3.XmlScript.dll
                Initializing: Nexus.Client.Games.Fallout3.Scripting.XmlScript.Fallout3XmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: C:\Games\Nexus Mod Manager\Fallout3\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\Fallout3\Install Info\InstallLog.xml
    Loaded from XML.
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Anchorage.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\BrokenSteel.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Fallout3.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\PointLookout.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\ThePitt.esm
                Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Zeta.esm
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Anchorage.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\BrokenSteel.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Fallout3.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\PointLookout.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\ThePitt.esm
                Registered.
            Found: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Zeta.esm
                Registered.
        Found 6 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Anchorage.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\BrokenSteel.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Fallout3.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\PointLookout.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\ThePitt.esm (IsNull=False)
            Loading C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Zeta.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\fallout3.exe (IsNull=False)
    FOSE Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\fose_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command:  (IsNull=True)
Loading Plugins into Plugin List: 6
    Loading: Fallout3.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Fallout3.esm) (False)
    Loading: Anchorage.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Anchorage.esm) (False)
    Loading: BrokenSteel.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\BrokenSteel.esm) (False)
    Loading: PointLookout.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\PointLookout.esm) (False)
    Loading: ThePitt.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\ThePitt.esm) (False)
    Loading: Zeta.esm (C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\Zeta.esm) (False)
Setting up listener on Nexus Mod Manager-Fallout3IpcServer/Fallout3Listener at 2019-03-06 02:41:18
Running Application.
Checking for new client version...
    Could not connect to update server: Den eksterne serveren returnerte feilen (403) Forbudt.
    Adding Mod to running instance of client: nxm://fallout3/mods/114/files/32467?key=iAnnNHskleG4cTo7npbzjQ&expires=1552009315&user_id=62000456
    [nxm://fallout3/mods/114/files/32467?key=iAnnNHskleG4cTo7npbzjQ&expires=1552009315&user_id=62000456] Adding Mod to AddModQueue
    [nxm://fallout3/mods/114/files/32467?key=iAnnNHskleG4cTo7npbzjQ&expires=1552009315&user_id=62000456] Starting Add Mod Task.
    [nxm://fallout3/mods/114/files/32467?key=iAnnNHskleG4cTo7npbzjQ&expires=1552009315&user_id=62000456] Starting Add Mod Task.
    [nxm://fallout3/mods/114/files/32467?key=iAnnNHskleG4cTo7npbzjQ&expires=1552009315&user_id=62000456] Downloading Files.
    [nxm://fallout3/mods/114/files/32467?key=iAnnNHskleG4cTo7npbzjQ&expires=1552009315&user_id=62000456] Launching downloading of https://files.nexus-cdn.com/120/114/No Radio Static-114.zip?md5=Hv33ZY9XaDCc6u4nYShr-Q&expires=1552009318&user_id=62000456&rip=81.166.42.37.
    [https://files.nexus-cdn.com/120/114/No Radio Static-114.zip?md5=Hv33ZY9XaDCc6u4nYShr-Q&expires=1552009318&user_id=62000456&rip=81.166.42.37] Retreiving metadata.
    [https://files.nexus-cdn.com/120/114/No Radio Static-114.zip?md5=Hv33ZY9XaDCc6u4nYShr-Q&expires=1552009318&user_id=62000456&rip=81.166.42.37] Downloading.
    [C:\Games\Nexus Mod Manager\Fallout3\Mods\downloads\No Radio Static-114.zip] Adding mod from archive.
    Launching Fallout 3 (Plain)...
    Command: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\fallout3.exe
    Succeeded
Adding Mod to running instance of client: nxm://fallout3/mods/20492/files/1000006003?key=R4Z50fOJa6gptDDyK09NCA&expires=1552009608&user_id=62000456
[nxm://fallout3/mods/20492/files/1000006003?key=R4Z50fOJa6gptDDyK09NCA&expires=1552009608&user_id=62000456] Adding Mod to AddModQueue
[nxm://fallout3/mods/20492/files/1000006003?key=R4Z50fOJa6gptDDyK09NCA&expires=1552009608&user_id=62000456] Starting Add Mod Task.
[nxm://fallout3/mods/20492/files/1000006003?key=R4Z50fOJa6gptDDyK09NCA&expires=1552009608&user_id=62000456] Starting Add Mod Task.
[nxm://fallout3/mods/20492/files/1000006003?key=R4Z50fOJa6gptDDyK09NCA&expires=1552009608&user_id=62000456] Downloading Files.
[nxm://fallout3/mods/20492/files/1000006003?key=R4Z50fOJa6gptDDyK09NCA&expires=1552009608&user_id=62000456] Launching downloading of https://files.nexus-cdn.com/120/20492/Galaxy News Radio - No Static-20492-1.zip?md5=03ItgAC6xJ3mz0Gl0sF_YQ&expires=1552009612&user_id=62000456&rip=81.166.42.37.
[https://files.nexus-cdn.com/120/20492/Galaxy News Radio - No Static-20492-1.zip?md5=03ItgAC6xJ3mz0Gl0sF_YQ&expires=1552009612&user_id=62000456&rip=81.166.42.37] Retreiving metadata.
[https://files.nexus-cdn.com/120/20492/Galaxy News Radio - No Static-20492-1.zip?md5=03ItgAC6xJ3mz0Gl0sF_YQ&expires=1552009612&user_id=62000456&rip=81.166.42.37] Downloading.
[C:\Games\Nexus Mod Manager\Fallout3\Mods\downloads\Galaxy News Radio - No Static-20492-1.zip] Adding mod from archive.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Ingen tilgang til banen C:\Users\Bruker\AppData\Local\Fallout3\plugins.txt.
Full Trace: 
	System.UnauthorizedAccessException: Ingen tilgang til banen C:\Users\Bruker\AppData\Local\Fallout3\plugins.txt.
   ved Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.WriteLoadOrderFile(String p_strFilePath, String[] p_strPlugins)
   ved Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.WriteLoadOrderTask.DoWork(Object[] p_objArgs)
   ved Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   ved Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   ved System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ved System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    9 () 
        Aborted

**To Reproduce**
 instal eny mod this hapens and if it dont it just dont work

**Additional information** 
_ it says its the CSharpScript.dll that cant load_

**Comment by squid-box** [comment]
The fact that it's complaining about missing `CSharpScript.dll` points to an installation issue, have you tried reinstalling NMM, or upgraded to a newer version?

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by Gramurr** [comment]
Hi

I found out it was a „read only„issue with one of the mod manager folder.  An uppdate had changed the basic setting.

Thanks

Sent frá Póstur<https://go.microsoft.com/fwlink/?LinkId=550986> fyrir Windows 10

________________________________
Frá: Joel Ahlgren <notifications@github.com>
Sent: Sunday, May 5, 2019 10:37:22 PM
Til: Nexus-Mods/Nexus-Mod-Manager
Afrit: Gramurr; Manual
Efni: Re: [Nexus-Mods/Nexus-Mod-Manager] trace log issue (#704)


The fact that it's complaining about missing CSharpScript.dll points to an installation issue, have you tried reinstalling NMM, or upgraded to a newer version?

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by squid-box** [comment]
Great, thanks for the quick reply!
As there's not much info to go on, I'm closing the issue. If you have more info for how this happened, feel free to add that.
