### ISSUE TITLE
So I messed up on a mod

### ISSUE THREAD

**Issue by FoxeltheFox** [Nexus-Mods/Nexus-Mod-Manager#705]
To sum it up, I play Oblivion and I like it a lot. My computer is kinda trash so being able to play a game smoothly is a godsend. 

I recently decided to mod it because let's be real, some textures and faces are horrific to see. I don't manually mod because I don't trust myself with files. Today though, I saw a really endorsed mod on the Nexus called something like Oblivion Reloaded. My dad showed me before how to do a manual mod so I was thinking this should be easy... I was wrong. It looked nice but had this blur and it tried doing a first-person camera that did not work well. Now, I'm only assuming it's this because my other mods are automatic and I have them disabled and the only other mod that was manual is OBSE. 

I don't know what I should get rid of and things like that to fix it. I mean I fixed the blur but I can't get rid of the first-person camera issue! There's just a bunch of remanents of the Reloaded mod left behind that I don't know how to get rid of like the main menu to the game now has a video in the background and sure it's cool but I don't want it. I don't really know where else to go for a question like this and I'm not experienced with files so if you're going to help please say in detail! I may be little late to respond so apologizes for that. 

Any help is appreciated, thanks!

**Comment by squid-box** [comment]
So this repository and the issues here are meant to deal with problems with the program Nexus Mod Manager itself - in your case it's more of a question for people knowledgeable in the mods themselves.

I'd recommend you head over to https://forums.nexusmods.com/ and ask for help there - I imagine someone in the [Oblivion Mod Troubleshooting](https://forums.nexusmods.com/index.php?/forum/180-oblivion-mod-troubleshooting/) could be able to help you figure it out.

Good luck!

**Comment by FoxeltheFox** [comment]
Okie dokie, thanks for the rerouting. I dont really go on forums so I
appreciate you redirecting me.
