### ISSUE TITLE
Activate doesn't work in Workshop Mode

### ISSUE THREAD

**Issue by Daniel5152** [Nexus-Mods/Nexus-Mod-Manager#706]
Got New unwanted update, got New Script Extender, Updated Looks Menu, Mod Config. Menu, EDI, and Unofficial Patch, Game loads through SE, but when I enter the Workshop mode I cannot place any objects, My "E" button no longer works in WS mode. I can talk using "E", just cannot use it to place anything while in Workshop Mode. Any suggestions I can revert back to previous game to play in Workshop Mode but that would require re-installing old SE, and previous mods for that Extender. and using one of the Four backup FO4.exe's I have. Any suggestions?

**Comment by squid-box** [comment]
This sounds more like a mod combination problem, than a mod manager problem.
I'd recommend looking for help on the NexusMods forums instead.
