### ISSUE TITLE
Protonmail email accounts unable to recieve verification email

### ISSUE THREAD

**Issue by RishardANoose** [Nexus-Mods/Nexus-Mod-Manager#708]
I recently made an account with nexus mods, and used a protonmail email account. It said it would sent a verification email but after about nine hours and checking my inbox, spam, and junk folders I still haven't received it. I requested to have it resent but still haven't received anything.

**Comment by squid-box** [comment]
This is not the place for Nexus issues, only NMM issues. You'll have to contact Nexus' support for problems like these.
