### ISSUE TITLE
cannot open mod manager at all

### ISSUE THREAD

**Issue by jagdthetiger** [Nexus-Mods/Nexus-Mod-Manager#714]
tried installing mods, got a trace issue, suddenly stopped working and no wont open without reporting a trace issue
[TraceLog20190408203218.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3055982/TraceLog20190408203218.txt)

**Comment by squid-box** [comment]
This is a duplicate of #300, look there for a solution to this issue.
