### ISSUE TITLE
Nexus Mods Downloading Wrong Files

### ISSUE THREAD

**Issue by Jlzbean** [Nexus-Mods/Nexus-Mod-Manager#724]
I am attempting to download the "Seasonal Anime Portraits" mod for Stardew Valley, but whenever I download the file (through either Vortex or Manually), I get the files for the Skyrim Redone Unofficial Patch. The files are completely and utterly unrelated, which is why this is so confusing. I have tried downloading this file a total of 8 times, through both the Vortex application and Manual downloads. When I check the file preview, I can see the files that I should be downloading. They are files related to the various characters' portraits, as well as certain festival events, but whenever I download the mod, I get "fomods" and "standing stones" related files. 

Mods Used: https://www.nexusmods.com/stardewvalley/mods/3202 

This doesn't make any sense. Thank you in advance for your help.

**Comment by squid-box** [comment]
Sorry, this repository is for the program Nexus Mod Manager, we can't really help you with this.
You have to report this to either the Vortex developers, or the website team.

And for reference, when I manually download the mod you've linked, I'm getting the correct files.

**Comment by mrmason** [comment]
This should all be fixed now.
