### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/Nexus-Mod-Manager#725]
I keep getting a Login Error - Cannot reach the Nexus Login Server.

Any attempt to log in results in the above error.  I'm logged into Nexus Mods but cannot log into NMM.

**Environment**
NMM version 65.11

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
Click the Login Buddy at the bottom-left corner of the NMM window.

NMM will ask for one's log-in credentials.

Attempt to log in using said credentials.

The above error message splashes across the bottom-left corner of the NMM window.

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by ghost** [comment]
Same here

![Capture4](https://user-images.githubusercontent.com/20587487/57121462-10391880-6dbb-11e9-84c5-35b918a63b4e.JPG)
![Capture3](https://user-images.githubusercontent.com/20587487/57121463-10391880-6dbb-11e9-859a-accf1ddc6509.JPG)

**Comment by scjohnson1981** [comment]
MO2 users are having the same issues: https://forums.nexusmods.com/index.php?/topic/7614103-mo2-login-failed/

**Comment by Wishkahkid** [comment]
Same here. I think Nexus may have jumped the gun with their cut off date with the new API, which was supposed to be on May 13th. Which turns off access to all mod managers that haven't been updated to use this?

**Comment by scjohnson1981** [comment]
Regardless, this needs to be fixed.  I cannot download any mods at present.

**Comment by squid-box** [comment]
Unfortunately this is nothing we can fix on the NMM side, if the servers are not responding / giving bad responses you're out of luck. There was chatter on the Nexus Discord that there were certificate issues with the old API during the night, @scjohnson1981 are you still having issues?

There is work ongoing to support the new API (#701), but it's still a few days out from being usable.

**Comment by scjohnson1981** [comment]
Just tried to log into Nexus via NMM & it worked.  Thanks for fixing it, albeit temporarily until the new API is working for NMM.
