### ISSUE TITLE
0.70 unable to download mods, server unreachable

### ISSUE THREAD

**Issue by sketchslayer** [Nexus-Mods/Nexus-Mod-Manager#735]
So upon updating to 0.70 I've noticed that any attempt to have NMM download from the nexus give an error along the lines of "Server Unreachable: nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073"
With obvious variation based on the mod selected.

**Comment by sketchslayer** [comment]
Looking at the tracelog the important bit seems to be:

[nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073] Can't get the file: no file.
Adding Mod to running instance of client: nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073
[nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073] Adding Mod to AddModQueue
[nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073] Starting Add Mod Task.
Adding Mod to running instance of client: nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073
AggregateException:Message: One or more errors occurred.
Stacktrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetFileInfo(String modId, String fileId)
Inner exceptions:
----------------
Pathoschild.Http.Client.ApiException: No Game Found: FalloutNV
   at Pathoschild.FluentNexus.Framework.NexusErrorFilter.OnResponse(IResponse response, Boolean httpErrorAsException)
   at Pathoschild.Http.Client.Internal.Request.<Execute>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pathoschild.Http.Client.Internal.Request.<As>d__37`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pathoschild.FluentNexus.Endpoints.NexusModFilesClient.<GetModFile>d__3.MoveNext()
----------------

[nxm://falloutnv/mods/48222/files/1000019146?key=wd-rNqB0BqUMs-oSiEq2Fg&expires=1557932754&user_id=5868073] Can't get the file: no file.
Running Threads (0)

**Comment by grizzeypwnz** [comment]
Same issue. and I just started doing the Nordic Mod Guide for SE last night. SMH

Server Unreachable: nxm://skyrimse/mods/2149/files/8955?key=dqYtyvb4egfqWjOW54ucYA&expires=1557935791&user_id=2562547****

**Comment by sketchslayer** [comment]
I'm trying to get a stable heavily modded NV together which will be slower if I have to manually add every mod to the manager & then work out what ones need removing/replacing with others etc.

Seems this closed issue thread is related https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/730  though his solution did not work for me.

Assuming it has something to do with this new api nexus is using.

**Comment by grizzeypwnz** [comment]
Yea manually adding everything would be a major problem here as well. That guy's fix didn't work for me either.

**Comment by squid-box** [comment]
Yeah, 730 seems to have been a random issue, from the logs you've posted I've got an idea I want to try - unfortunately I have no work-around for you right now.

**Comment by sketchslayer** [comment]
Hey at least you've got an idea, that's more than I have on this one, #730 also mentioned the launch  button not listing executables aside from the main exe which is true for me with 0.70 as well, 0.65.xx used to list NVSE as a launchable exe which 0.70 doesn't.

**Comment by sketchslayer** [comment]
I'm thinking it's to do with having begun modding the game with an earlier version of NMM, just checked it with oblivion (a game I have installed that I hadn't used nexus with prior) and it was able to download a mod from the nexus without issue.

Just noticed a weird thing with oblivion though, it only lists launch Custom Oblivion when I have no custom launch set up (it doesn't list launch oblivion)

**Comment by squid-box** [comment]
My hunch is that we just push the game name, eg. "SkyrimSE", but the new API might expect "skyrimse". I've yet to confirm this.

There's another issue for the launch commands, #732 , that I also hope is a simple fix.

**Comment by sketchslayer** [comment]
I'ma quickly download SSE since it's the other game confirmed to have issues downloading mods through 0.70, if I can download mods through NMM 0.70 for it that would indicate it's something in the files NMM creates for the game that changed between .65 and .70 that .70 can't parse the .65 variant of properly right?

I'm assuming that grizz starting modding SE last night would have meant before the release of 0.70.

Should have an answer as to whether SSE is also giving me the same problems downloading mods in ~20 minutes.

**Comment by grizzeypwnz** [comment]
Yes I started modding on .65 the other night.

**Comment by sketchslayer** [comment]
Okay so I have the same issue with SSE and New Vegas so I think squid may be on to something,
At least it's only some games that have the issue SSE/NV both have it but FO3/Oblivion do not.

**Comment by DuskDweller** [comment]
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.70.1

**Comment by sketchslayer** [comment]
Yep 0.70.1 does indeed fix the problem for new vegas downloads, I expect we'll have another new release before long given that squid seems to have some idea of the specifics of at least one remaining issue with the current NMM (though at least it's a smaller one since NMM being capable of launching executables isn't the biggest deal)

Glad to see the downloading fixed pretty quickly though, Thanks.

**Comment by grizzeypwnz** [comment]
Confirmed fixed for SE as well thank you.
