### ISSUE TITLE
Server Unreachable [Solved in 0.70.1]

### ISSUE THREAD

**Issue by SGTABHI** [Nexus-Mods/Nexus-Mod-Manager#736]
**Describe the bug** 
Server Unreachable when adding mod only in Skyrim SE. Can add and download for other games.

**Environment**
- NMM version: 0.70.0

Trace Log: 

> Adding Mod to running instance of client: nxm://skyrimse/mods/25094/files/89159?key=hidden&expires=1557933213&user_id=hidden
> [nxm://skyrimse/mods/25094/files/89159?key=hidden&user_id=hidden] Adding Mod to AddModQueue
> [nxm://skyrimse/mods/25094/files/89159?key=hidden&expires=1557933213&user_id=hidden] Starting Add Mod Task.
> AggregateException:Message: One or more errors occurred.
> Stacktrace:
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Nexus.Client.ModRepositories.NexusModsApiRepository.GetFileInfo(String modId, String fileId)
> Inner exceptions:
> ----------------
> Pathoschild.Http.Client.ApiException: No Game Found: SkyrimSE
>    at Pathoschild.FluentNexus.Framework.NexusErrorFilter.OnResponse(IResponse response, Boolean httpErrorAsException)
>    at Pathoschild.Http.Client.Internal.Request.<Execute>d__45.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Pathoschild.Http.Client.Internal.Request.<As>d__37`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Pathoschild.FluentNexus.Endpoints.NexusModFilesClient.<GetModFile>d__3.MoveNext()
> ----------------
> 
> [nxm://skyrimse/mods/25094/files/89159?key=hidden&expires=1557933213&user_id=hidden] Can't get the file: no file.
> Running Threads (0)
>

**Comment by sketchslayer** [comment]
Our new threads should probably be merged, it's not just Skyrim SE I ran in to it with Fallout NV

**Comment by DuskDweller** [comment]
https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.70.1
