### ISSUE TITLE
0.70.1 not starting 

### ISSUE THREAD

**Issue by ProninNMM** [Nexus-Mods/Nexus-Mod-Manager#738]
Trace file has been created: TraceLog20190513135349.txt
Mod Manager Version: 0.70.1.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)

I just updated to the newest version of NMM and I keep getting this error every time I try to startup NMM. I can't find anyone who seems to be having this same problem.

**Comment by squid-box** [comment]
"Luckily" this is a duplicate of #728. We haven't figured out the exact cause, but the work-around for now is to uninstall NMM, ensure no old files are left in the program files directory, and installing again. (But keep your config files.)

**Comment by ProninNMM** [comment]
How would I go about keeping the config files? I wouldn't want to make the mistake of accidentally uninstalling something I didn't want to.

**Comment by squid-box** [comment]
You'll get asked if you want to remove the config files when you uninstall NMM - Just select no:

![image](https://user-images.githubusercontent.com/864820/57645109-e1daea80-75bd-11e9-9d00-e1da10893ad5.png)

**Comment by ProninNMM** [comment]
Okay! That fixed my problem(for now)! Thank you so much!

**Comment by squid-box** [comment]
Happy to help! We hope to fix this before long :pray:
