### ISSUE TITLE
cant manual or download or install any new mods. crashes every time version 0.70.1

### ISSUE THREAD

**Issue by Singleminded2020** [Nexus-Mods/Nexus-Mod-Manager#742]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
Really no info here - Could you tell us which mods you're trying to download/install, and provide us with the trace log you're getting from the crash.

**Comment by DuskDweller** [comment]
Manual install will be fixed in the next hotfix.
