### ISSUE TITLE
NMM disabling and uninstalling mods?

### ISSUE THREAD

**Issue by Konron** [Nexus-Mods/Nexus-Mod-Manager#75]
Ok so I don't know exactly what happened, but everything was going completely normal and fine until a little while ago I dropped a new mod into the mod category of NMM for Fallout New Vegas, and suddenly when I restarted nmm for the new mod to register, many mods were disabled and previously installed mods were uninstalled. I don't even know what could've happened, but I've uninstalled and reinstalled nmm already, and it's already running in admin. I don't know if it's the new version anything but I'd really appreciate some help

**Comment by adkins2010** [comment]
More information would be helpful.  Also, I'm guessing that you might not be aware that NMM does things like delete mod files from your gameS installation directory and replace them with symlinks that point to the NMM installation directory.  
Sometimes the symlinks break and can be a real bitch to fix.

**Comment by squid-box** [comment]
With no reply with more info in a year, I'm closing this issue.
