### ISSUE TITLE
Checking for updates breaks link to mod pages

### ISSUE THREAD

**Issue by hillzillah** [Nexus-Mods/Nexus-Mod-Manager#750]
**Describe the bug** 
Unsure if this is a result of the new API stuff or if this is a feature that isn't working correctly? I updated to 0.70.1 today and tested out the 'check for updates' option, even though I'm fairly certain none of my crucial mods needed to be updated. Due to the API rate limit, I hit the 100 per hour limit before it checked everything, so the mods that it was able to check turned black in the "mod version" column, and the ones that were not checked remained blue. However, the ones that were checked now are no longer have working links to direct to the mod page. 

It also changed the names of the mods so that I cannot tell the difference between the patches and the main files. IE For Skyrim SE: CBBE, I have three files for, two of which now have the same name, Amazing Follower Tweaks has two of the same name, and Flower Girls has four all with the same name since checking for updates.

**Environment**
- NMM version: 0.70.1
- Mod(s) used: https://modwat.ch/u/hillzillah/plugins

**To Reproduce**
Simply clicked "Fix download IDs and check for mod updates"
![Capture](https://user-images.githubusercontent.com/50599158/57656764-55253200-75a7-11e9-963c-5e9ce2b78933.PNG)

**Comment by DuskDweller** [comment]
Should be fixed in 0.70.3 .

**Comment by hillzillah** [comment]
I just saw that 70.2 was released and updated and tested that... Will try again in an hour and report back. I did notice that it seemed to check the same 100 mods again, instead of checking a new batch. Will this also be fixed in 70.3?

**Comment by Risttow** [comment]
same here and i'm using the 0.70.3

**Comment by hillzillah** [comment]
70.3 is still causing the same issues for me, unless the mod links are 'broken' and will have to be reinstalled in order to have them working again?

**Comment by PhiMue86** [comment]
Existing links are kept intact now, but newly downloaded mods are not linked at all. "Gets missing mod info" doesn't work, the "Matching Mods" list is empty.

**Comment by Risttow** [comment]
Now that you say about the missing info i notice that too

**Comment by hillzillah** [comment]
Update: after updating to 0.70.3 and checking for updates a handful of times, I still have broken links to mods from the original check that broke them. The duplicate mod names have been corrected thankfully, except for those that have been broken. Those that were not broken seem to be working as expected.

**Comment by PhiMue86** [comment]
Also, looks like updates are not found at all... well, I know of one mod that was definitely updated and the update wasn't found, and there are no other updates found in my quite extensive Morrowind mod list, but admittedly there are many older ones that have not been updated in ages, so I usually only get very few update results. Does it work for anyone else?

**Comment by hillzillah** [comment]
> Also, looks like updates are not found at all... well, I know of one mod that was definitely updated and the update wasn't found, and there are no other updates found in my quite extensive Morrowind mod list, but admittedly there are many older ones that have not been updated in ages, so I usually only get very few update results. Does it work for anyone else?

It's often hard for me to tell at a glance which mods are actually in need of updating just by the ! flags, since some that are flagged for updates are actually just additional files for the same mod. But I usually keep an eye on the updates through the Nexus as I check the trends, new mods, and updates posted through there a couple times a week. Most of my mods have been installed within the last month or so though, (recently purged and rebuilt my mod list) so I can't really offer insight on that.

**Comment by hillzillah** [comment]
@DuskDweller Update: Updated to 0.70.4 today and manually updated the page links to about 10-20 mods. Ran the "check for updates" again to test, and those mods that I had updated were again wiped of their links. :C Names for those mods are still duplicated as they were when I originally posted the screenshot.

**Comment by Risttow** [comment]
Wait there is a new update today?the 70.04? Damn i need update nmm again

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by squid-box** [comment]
@Risttow: I'd advise against that, it's a broken release.

**Comment by hiredgunz48** [comment]
this is also happening to my version 0.70.5.. Applies to all mods managed by NMM.

If you choose the "fix download IDs and check for mod updates" option, all the links to the mod's nexus page are deleted and as seen using the "get missing mod info" link for each mod. Also no hyperlink to nexus for each mod. I have no clue what the problem is.

**Comment by Risttow** [comment]
ah don't worry so far so good at least for me, but i'll update anyway
________________________________
De: Joel Ahlgren <notifications@github.com>
Enviado: quarta-feira, 15 de maio de 2019 19:15
Para: Nexus-Mods/Nexus-Mod-Manager
Cc: Risttow; Mention
Assunto: Re: [Nexus-Mods/Nexus-Mod-Manager] Checking for updates breaks link to mod pages (#750)


@Risttow<https://github.com/Risttow>: I'd advise against that, it's a broken release.

**Comment by hillzillah** [comment]
@squid-box Updated to 70.5 and it is still removing my manually-corrected links for the broken mods. 

Also having an issue when updating a mod, it does not seem to detect that I'm installing a newer or different version of a mod anymore. It used to add a new line in the mod list if it was a different version, but now it just seems to recognize it as the same mod as was already there, when downloading OR installing manually.

By the way guys, _I really do appreciate you continuing to support the abandoned NMM_. I much prefer it over MO and Vortex. It may be quirky, but (at least up until 0.70) I am used to the quirks. Haha

**Comment by Risttow** [comment]
I tried vortex once and my mods mostly didn't Work só i switched back to Nexus,for me vortex os horrible many things he says is broken ir conflicting but is not true as nmm i never had This problem.

I have a doubt,if i get a mod for fallout4 for example.
Says that only needs the game itself but idk a weapon is missing (invisible) is a mod problem or is a problem with the install through the mod manager?


Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by SomeYank** [comment]
> 
> 
> Should be fixed in 0.70.3 .

Im getting the the same thing!  happened using 0.70.3 got the same bug upgrading to 0.70.5.  The mod version links tht suppose to take you to the nexus mod site are dead and blackened.

**Comment by squid-box** [comment]
There's a fix in the pipeline for this particular problem, once #780 is merged, it will be included in the next release, I expect it to be in 0.70.6.
