### ISSUE TITLE
Error registering mod 

### ISSUE THREAD

**Issue by xii7** [Nexus-Mods/Nexus-Mod-Manager#753]
**Describe the bug** 
Unable to download Solitude Towers Flags SSE (error registering this mod)

**Environment**
- NMM version:0.70.1
- Mod(s) used: https://www.nexusmods.com/skyrimspecialedition/mods/25600?tab=posts&BH=0

**To Reproduce**
Attempting to download produces error. No trace logs.

**Comment by squid-box** [comment]
Update to 0.70.3 and try again.
