### ISSUE TITLE
Current Game Missing From Change Game Mode

### ISSUE THREAD

**Issue by viper1s** [Nexus-Mods/Nexus-Mod-Manager#754]
**Very insignificant issue** and may well should have been Add Feature (back)

In previous versions , when clicking on Change Game Mode , the current game was listed as well as the others . Now , with 70.3 , the listing of the current game is not there.
This helped to reload the current game selection instead of closing NMM and reopening 

- NMM version: 0.70.3
- Mod(s) used: N/A

Trace logs N/A

**To Reproduce**
With multiple supported games , click Change Game Mode.

**Additional information** 
Am I nitpicking ?

**Comment by squid-box** [comment]
I actually did this as a feature, but that's only because I never had the need to reload the current game mode.

For the next version I'll make sure it's there, if possible it will say 'Reload <current gamemode>'.

**Comment by viper1s** [comment]
While installing light masters , sometimes it is necessary for NMM to add them to the load order
This is a very minor "bug" . Otherwise , 70.3 is working great
Thanks for the team's engagement of keeping NMM around
I REFUSE to go to Vortex or MO as NMM is what I have used since the beginning of the Nexus site.

**Comment by squid-box** [comment]
This has been released, please verify you're happy with the solution and we'll close the issue :)

**Comment by viper1s** [comment]
I am - Reload Fallout 4 right there on top
Much appreciation
