### ISSUE TITLE
Exception encountered on startup

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#759]
**Describe the bug** 
On attempting to launch NMM a dialogue appears saying it has encountered an error and needs to close.

**Environment**
- NMM version: _0.70.3_

**To Reproduce**
 Just attempt to start NMM, 100% reproducible for me.

**Additional information** 
[TraceLog20190514074828.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3176208/TraceLog20190514074828.txt)

**Comment by DuskDweller** [comment]
Cleanup your NMM program folder and install it again, it seems for some users Windows doesn't let the installer overwrite some of the DLL

**Comment by ghost** [comment]
Thanks, this sorted it.
