### ISSUE TITLE
Não inicia 

### ISSUE THREAD

**Issue by Lkalter** [Nexus-Mods/Nexus-Mod-Manager#760]
[_Please](

- 

- [ ] #1. url

) give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

[TraceLog20190514032740.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3176269/TraceLog20190514032740.txt)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
See #728 for workaround, you'll need to clean the NMM installation directory before installation.
