### ISSUE TITLE
NMM won't load version 0.70.3.0

### ISSUE THREAD

**Issue by MAXIMVStheGREAT** [Nexus-Mods/Nexus-Mod-Manager#761]
**Describe the bug** 
NMM not loading, shows error message

Trace Log:
Trace file has been created: TraceLog20190514104025.txt
Mod Manager Version: 0.70.3.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: E:\Games\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)

**Environment**
- NMM version: 0.70.3.0
- Mod(s) used: about 240 active mods

**To Reproduce**
 Since I progressively updated from 0.65.2 yesterday

**Additional information** 
For the first few updates I opened NMM after each step, but after 3 or 4 I just updated without opening NMM each time. Thus I am not sure which update began to show the problem except that NMM would not load after 0.70.1, 0.70.2 and 0.70.3

**Comment by squid-box** [comment]
This is the same problem as #728 , you'll need to uninstall NMM, remove all lingering files from the Program Files directory, and install NMM again. For some reason some people are having old files remaining after an upgrade, causing this problem.

**Comment by MAXIMVStheGREAT** [comment]
Brilliant!  Uninstalled, re-installed and opened Skyrim and everything works as it should!!!  I struggled a bit at first with the correct pathing, as the defaults didn't know most of my stuff is on my PC's E: drive but, most of all - I couldn't quite believe that all 250 mods would work OK!  Many thanks indeed,
Max
