### ISSUE TITLE
NMM Crash on startup after updating to 0.70.3

### ISSUE THREAD

**Issue by Ondsola** [Nexus-Mods/Nexus-Mod-Manager#766]
[TraceLog20190515065556.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3182234/TraceLog20190515065556.txt)

NMM would fail to update previously, so I manually downloaded the update and installed it. After doing so, NMM crashes upon starting and I have attached the trace log.

**Environment**
- NMM version: _0.70.3_

**Comment by squid-box** [comment]
This is the same issue as #728 , did you remove your old program files before installing 0.70.3?

**Comment by Ondsola** [comment]
> 
> 
> This is the same issue as #273, did you remove your old program files before installing 0.70.3?

Yes. I have since fixed the issue by simply installing again.

**Comment by squid-box** [comment]
Alright, good to hear!
