### ISSUE TITLE
NMM not starting

### ISSUE THREAD

**Issue by RolgarHH** [Nexus-Mods/Nexus-Mod-Manager#768]
**Describe the bug** 
Right after starting I get a small window with an error message and the option to open the Tracelog folder or not.

**Environment**
- NMM version: 0.70.4.0

**Additional information** 
The bug is happening after I updated from 0.65.11.0 to 0.70.4.0
Attached is the tracelog
[TraceLog20190515204513.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3184059/TraceLog20190515204513.txt)

**Comment by squid-box** [comment]
Check #728.

**Comment by RolgarHH** [comment]
[TraceLog20190515213937.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3184195/TraceLog20190515213937.txt)
I tried the following:
1. Renaming the previous installation and installing NMM. Same issue as before "Error Message at start", although the tracelog is different.
2. Deinstallation of NMM and Installation of 0.70.4. Upon start NMM searches for Games and finds them. Then I setup the installation folders for the default game and right after that NMM crashes again. Here is the tracelog.

**Comment by squid-box** [comment]
Your new error (2) is the same as #770 - I'm looking into it now. In the meantime I'd try installing 0.70.3 instead, you can find [an installer for it](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.70.3) under releases.

**Comment by RolgarHH** [comment]
I made a fresh installation of 0.70.3.0. It is working.
