### ISSUE TITLE
Enable the new Nexus API for NMM

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/Nexus-Mod-Manager#769]
_Please give as much information as you can, replace/remove italicized text._

**Is your feature request related to a problem?**
NMM can no longer utilize Nexus Mods' API

**Describe the solution you'd like**
Enable the new API for NMM

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by squid-box** [comment]
You're welcome to join the rest of us in version 0.70+

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by scjohnson1981** [comment]
Thank you.  Found a link to the new version on Nexus.
