### ISSUE TITLE
New Nexus Mod Manager update crashes upon opening it 

### ISSUE THREAD

**Issue by sm1ty** [Nexus-Mods/Nexus-Mod-Manager#776]
The new update crashes my NMM upon opening it, saying there was an error and it needs to be closed, and leaves a trace log. I am simply going to use an older version of NMM at this point. However, where can I find a usable version of NMM online?

**Comment by squid-box** [comment]
You can find all releases under https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases
