### ISSUE TITLE
The mod manager login will not let me log in

### ISSUE THREAD

**Issue by ggggggg6** [Nexus-Mods/Nexus-Mod-Manager#779]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
I assume you're using 0.65 or older. Get the latest version here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by Nubbie** [comment]
As OP haven't replied in 10 days, he said he uses "NMM version: 0.1.0" (even though he probably have a newer version) and you need the newest update to log-in, I guess this can be closed
