### ISSUE TITLE
NMM 0.70.5 Can't log in

### ISSUE THREAD

**Issue by Romalisk** [Nexus-Mods/Nexus-Mod-Manager#783]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
When I try to login through the Nexus api approval thing, the NMM pretty much dies.  I have to close it, and when I open it back up, I get this message, "Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)" and am unable to load the Manager again until I delete the entire folder and re-download the NMM.

**Environment**
- NMM version: 0.70.5

[TraceLog20190517054445.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3190936/TraceLog20190517054445.txt)

**To Reproduce**
Try to login on the NMM.

**Comment by Velemeister** [comment]
Same here..

**Comment by DuskDweller** [comment]
For any of you having the "unable to load DLL" issue, try downloading the Visual C++ redist and install it, this should fix it.
Please report back in any case:
https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by Velemeister** [comment]
Nope, still not working for me.
