### ISSUE TITLE
NMM 0.70.5 Websocket error when trying to log in

### ISSUE THREAD

**Issue by Bansheedragon** [Nexus-Mods/Nexus-Mod-Manager#784]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
When I try to log in I get a websocket error when clicking Autohrize
"An error has occurred during the OnOpen event.
System.ComponntModel.Win32Exception: Unable to locate application/program"

If I click on the link to manage my API keys, I get another authorization error(see attached files)

**Environment**
 - NMM version: 0.70.5
 - Mod(s) used: _<link to mod(s) on Nexus> No mods installed.
 - Clean/fresh install of NMM 0.70.5

If there are any trace logs I dont know where they would be as I have not gotten any notifications about it.
Please let me know where this can be found so I can look for it.

**To Reproduce**
Click icon to log in and get an authorization popup.
Click Authorize and get a websocket error.
Click Manage API keys link and get Authorization error.

**Additional information** 
Attached screenshot of websocket error and error logs.
NOTE: error log has been translated from Norwegian to English using Yandex translator
Attaching original Norwegian log along with translation.

[Authorization Error.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3191058/Authorization.Error.txt)
[Authorization Error Original.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3191061/Authorization.Error.Original.txt)
![Websocket error](https://user-images.githubusercontent.com/50703842/57922340-d0d0f880-789f-11e9-8913-3d5dae532764.PNG)

**Comment by squid-box** [comment]
Ok this is new to me. What's going on is that your computer can't find a browser to open URLs with... Do you not have a default web browser?

The crash shouldn't happen / you should be getting a better error message, but the root cause of this is that your computer doesn't know how to open a URL.

**Comment by Bansheedragon** [comment]
I use Opera as my regular browser, but after I had the computer in for service a year ago, where they reinstalled windows at my request, it will for some reason not recognize/accept Opera as my default .browser.
I honestly do not understand why, as it's never been a problem before.
I have no idea how to fix it and dont want to mess around too much with settings as I'm worried about breaking something I would not know how to fix

However I managed to solve this particular problem by setting Internet Explorer as my default browser for the purpose of authorizing NMM.

**Comment by squid-box** [comment]
Alright, good that you could work around it at least, as I said what I will fix is the non-informative message. It's hard/inappropriate for NMM to try and scan your computer to decide which browser to use to open the URL, the proper way is to simply tell Windows "I want to open this URL." and have it handle that request per each users' settings.

**Comment by MugenMax** [comment]
I got a problem too for update it
Why I update it...
![Error](https://user-images.githubusercontent.com/50742118/57929954-120add80-788b-11e9-8ee3-8235c83076f6.jpg)

**Comment by Bansheedragon** [comment]
May I suggest you make the popup box either larger or resizeable if possible?
As it stands the window is so small that to me at least the lower text was was overlapping the upper text due to the small size so I could not see it all.
