### ISSUE TITLE
I can't open my NMM, Version 0.70.5

### ISSUE THREAD

**Issue by MugenMax** [Nexus-Mods/Nexus-Mod-Manager#786]
I can't open my NMM after update it from 0.70.4 to 0.70.5.

**Describe the bug** 
When I try open it, it open a window that says "Nexos  Mod Manager has encountered an error and needs to close."

**Environment**
- NMM version: _0.70.5_
- Mod(s) used: _Too many, but nothing new before and after upgrade NMM._

_
[TraceLog20190517133653.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3192308/TraceLog20190517133653.txt)
_

**To Reproduce**
 _Upgrade, open_

**Additional information** 
_I see a little bit the forum and I don't see any user with Skyrim LE. So, there are not problem solved for that.

And sorry my english._

**Comment by DrkMako** [comment]
fixed this myself, uninstall nmm  select keep mods and file location

reinstall nmm and it functions fine now

**Comment by squid-box** [comment]
This is a different problem from #728, will have to look into it.

**Comment by MugenMax** [comment]
> fixed this myself, uninstall nmm select keep mods and file location
> 
> reinstall nmm and it functions fine now

I already do that and nothing, keep with the same error

**Comment by MugenMax** [comment]
Now my game crash when I open it
First Vortex and now this "update" to 0.70.5... The game it is beginning to displease me for problems that don't even are from it

**Comment by Darkexxod** [comment]
same issue here, if my limited understanding of spanish is to be believed
[TraceLog20190517233059.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3193612/TraceLog20190517233059.txt)

**Comment by DuskDweller** [comment]
For any of you having the "unable to load DLL" issue, try downloading the Visual C++ redist and install it, this should fix it.
Please report back in any case:
https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by SteelMalak** [comment]
Similar issue, I think?
Attempted the work-around with uninstalling completely, then installing 70.5 with the config files intact.
I have the Visual C++ redist, Nexusclient.exe is whitelisted in my antivirus/firewall.

[TraceLog20190522063649.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3207614/TraceLog20190522063649.txt)

**Comment by Darkexxod** [comment]
i think i must've just downloaded the wrong version or something, i tried a reinstall and everything works fine now
