### ISSUE TITLE
Cannot install mods manually unless I first log to Nexusmods to receive an API key

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#792]
**Cannot install mods manually unless I first log to Nexusmods to receive an API key** 
_If you try to manually install mods without receiving an API key from Nexusmods, NMM will fail to install or crash. Logs included_

**Environment**
- NMM version: _0.70.0 to 0.70.6_
- Mod(s) used: _any downloaded mod archive_

[TraceLog20190518172044.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3194156/TraceLog20190518172044.txt)

**To Reproduce**
-  _Start NMM fresh, make sure that you have not registered a new key. Your config's [setting name="ApiKey" serializeAs="String"] must have an empty [value /]_
- _Open your mod via the Plus icon or rename the mod archive to .fomod and open it from Windows Explorer_
- _NMM will crash_
- _If you drag the mod archive to the Mods pane, NMM won't crash but the mod will never finish moving into your mods pane_

**Additional information** 
_If you have registered your API key from Nexusmods, the above will work fine. It will work even if you have firewalled NMM and you appear as Not logged in due to network error, as long as you had temporarily unfirewalled NMM to receive your key._

**Comment by squid-box** [comment]
This is happening because NMM tries to get info about the manually added mods, and I never considered the case of not being authenticated when doing this.

Thanks for the trace log, will help with getting it fixed.

**Comment by IamIbrahem** [comment]
me too I can't even log in

**Comment by squid-box** [comment]
Have a look at 0.70.7 and see if that fixed your problem as well.

**Comment by IamIbrahem** [comment]
no still i cant log in it says
login error: couldn't authenticate user:unknown

‫في الأحد، 19 مايو 2019 في 1:20 م تمت كتابة ما يلي بواسطة ‪Joel Ahlgren‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ghost** [comment]
Sorry, same as before:

[TraceLog20190519155441.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3195086/TraceLog20190519155441.txt)

**Comment by IamIbrahem** [comment]
is there a fix for it

**Comment by squid-box** [comment]
For now you'll need to authenticate with Nexus, I'll have another look tonight :(

**Comment by IamIbrahem** [comment]
Good luck

**Comment by Midgard229** [comment]
How does one get an api key from. The nexus? Because I'm. Having this same error and newest version of nmm community has the same problem.

**Comment by ghost** [comment]
@Midgard229, if you can download mods via NMM then you already have your key. Otherwise, click on the icon at the bottom left of the NMM window. If it doesn't work, then you have firewalled NMM.

**Comment by Midgard229** [comment]
@saxonis thank you! That worked lol just didn't know the button to do it.

**Comment by ghost** [comment]
Confirmed fixed on 0.70.8
