### ISSUE TITLE
Wont Launch And API issues

### ISSUE THREAD

**Issue by Tahzir213** [Nexus-Mods/Nexus-Mod-Manager#793]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Everytime i tried to launch nmm it kinda fails and it always has something to do with the Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found issue tried downloading https://www.microsoft.com/en-us/download/details.aspx?id=53587
but still wont work so yeah

**Environment**
- NMM version: 0.70.6

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._
[TraceLog20190518222003.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3194225/TraceLog20190518222003.txt)

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
and i cant log in to the API

**Comment by Tahzir213** [comment]
tried redownloading and deleting everything and instaling it in the same folder

**Comment by squid-box** [comment]
This is happening due to some missing installation, we're just not sure which.
