### ISSUE TITLE
0.70.6.0 Crash at startup

### ISSUE THREAD

**Issue by Ashuraman666** [Nexus-Mods/Nexus-Mod-Manager#799]
**Describe the bug** 
Basically NMM crashes at startup

**Environment**
- NMM version: 0.70.6.0
- Mod(s) used:  Too many to count, was working before the update

[TraceLog20190519015618.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3194667/TraceLog20190519015618.txt)

**To Reproduce**
Start NMM

**Additional information** 
It seems to be somehow relate to fallout 3 if i'm reading the tracelog right? Even though i don't even have fallout 3 on my PC right now

**Comment by Ashuraman666** [comment]
By uninstalling the previous version and installing the new one manually the problem stopped occuring

**Comment by squid-box** [comment]
Makes sense, it's the same error as in #728.
Closing this issue.
