### ISSUE TITLE
Dark Souls 2 setup isn't working!

### ISSUE THREAD

**Issue by MuppetMaestro** [Nexus-Mods/Nexus-Mod-Manager#80]
I have used NMM for a few games now, always kept the same settings and file locations for all the games, but when I tried to setup Dark Souls 2 file location, the Virtual Install keeps showing a red circle with an exclamation mark in it. I checked that the location was the same as the other games, i even changed the location multiple times, but I still have the error popping up and I can't continue until it's fixed.

**Comment by DuskDweller** [comment]
You need to install the GeDoSaTo tool and configure its path in that same panel for NMM to be able to install mods. (the gedosato tool is the only way to run mods for DS2)

**Comment by squid-box** [comment]
With no response after a year, I'm assuming this fixed the problem.
