### ISSUE TITLE
Nexus mod manager won't boot up 

### ISSUE THREAD

**Issue by joeface614** [Nexus-Mods/Nexus-Mod-Manager#800]
Recently just updated to the most current version and won't let me access my mod so I can fix an issue with my games.

Here is the trace log that was given when i tried opening it

[TraceLog20190519112919.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3195253/TraceLog20190519112919.txt)

I am rather new to all of this so I could use some of the help

**Comment by squid-box** [comment]
You've encountered the by now infamous #728. There's instructions in pretty much every linked issue on how to work around it.

Summarised you'll need to uninstall NMM, remove any lingering files, then install it again.

**Comment by DontBlnkBadWolf** [comment]
I can confirm that the work around does work for v0.70.5.0. Click on the #728 link and scroll down to get the work around.
