### ISSUE TITLE
Nexus crashes with log error when trying to install mods

### ISSUE THREAD

**Issue by Snoops365** [Nexus-Mods/Nexus-Mod-Manager#803]
Alright so this is a next gen laptop, I already had a problem where the .NET wasn't updated so I did that but now I am getting this new error.
"Nexus Mod Manager has encountered an error and needs to close. A Trace Lod file was created at C:\Users\19137\Documents\Nexus Mod Manager\TraceLod20190520071151.txt" 
I get this error whenever I try to install mods for Fallout 3 but I'm not sure about other games yet since I just got the laptop, I hope I could possibly get this fixed soon because I never have been able to play Fallout 3 without problems before!!

Would Really Appreciate the assist! - Snoops

**Comment by squid-box** [comment]
Please include the trace log.

**Comment by Snoops365** [comment]
[TraceLog20190520120925.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3199069/TraceLog20190520120925.txt)
[TraceLog20190520122823.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3199070/TraceLog20190520122823.txt)
[TraceLog20190520071151.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3199071/TraceLog20190520071151.txt)
[TraceLog20190520072342.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3199072/TraceLog20190520072342.txt)
I get new errors every time i make an attempt @squid-box

**Comment by squid-box** [comment]
Luckily they're all the same error, #792. I'm looking into it.

**Comment by brokecollegeboi** [comment]
I have also the same issue 
[TraceLog20190525105049.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3219124/TraceLog20190525105049.txt)
[TraceLog20190525110142.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3219125/TraceLog20190525110142.txt)
[TraceLog20190525110325.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3219126/TraceLog20190525110325.txt)
[TraceLog20190525112600.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3219127/TraceLog20190525112600.txt)

**Comment by fonvadml** [comment]
[file:///H:/Downloads/FNIS Behavior 7_4_5-11811-7-4-5.7z] Adding Mod to AddModQueue
[file:///H:/Downloads/FNIS Behavior 7_4_5-11811-7-4-5.7z] Starting Add Mod Task.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetModInfoForFile(String fileName)
   at Nexus.Client.ModManagement.AddModTask.GetModInfo(AddModDescriptor descriptor)
   at Nexus.Client.ModManagement.AddModTask.AddMod(Boolean queued)
   at Nexus.Client.ModManagement.ModManager.AddModQueue.AddMod(Uri p_uriPath, ConfirmOverwriteCallback p_cocConfirmOverwrite)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by leehelck** [comment]
i'm having the same issue with Enderal.
Trace file has been created: TraceLog20190529210945.txt
Mod Manager Version: 0.70.7.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Enderal: Supported
    Loading Fallout3: Supported
    Loading Fallout4: Supported
    Loading FalloutNV: Supported
    Loading Morrowind: Supported
    Loading Oblivion: Supported
    Loading Skyrim: Supported
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) Enderal
Game Mode Factory Selected: Enderal (Enderal)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Enderal (Enderal)
    Installation Path: C:\Steam 2\steamapps\common\Enderal
    Install Info Path: C:\Games\Nexus Mod Manager\Enderal\Install Info
    Mod Path: d:\Games\Nexus Mod Manager\Enderal\Mods
    Mod Cache Path: d:\Games\Nexus Mod Manager\Enderal\Mods\cache
    Mod Download Cache: d:\Games\Nexus Mod Manager\Enderal\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\Enderal\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\Enderal
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\GameModes
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: d:\Games\Nexus Mod Manager\Enderal\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\Enderal\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Steam 2\steamapps\common\Enderal\Data
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp
                Found: C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Update.esm
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Update.esm (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Adding from serialized queue
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Adding Mod to AddModQueue
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Starting Add Mod Task.
Launch Commands:
    Plain Command: C:\Steam 2\steamapps\common\Enderal\Enderal Launcher.exe (IsNull=False)
    SKSE Command: C:\Steam 2\steamapps\common\Enderal\skse_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command: D:\LOOT\LOOT\LOOT.exe (IsNull=False)
    Wrye Bash Command:  (IsNull=False)
    TES5Edit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm) (False)
    Loading: Update.esm (C:\Steam 2\steamapps\common\Enderal\Data\Update.esm) (False)
    Loading: Enderal - Forgotten Stories.esm (C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm) (False)
    Loading: Enderal Tools.esp (C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp) (False)
    Loading: No Magic Ninja Dodge - No DLC.esp (C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp) (False)
Setting up listener on Nexus Mod Manager-EnderalIpcServer/EnderalListener at 2019-05-29 21:09:50
Running Application.
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Adding Mod to AddModQueue
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Starting Add Mod Task.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetModInfoForFile(String fileName)
   at Nexus.Client.ModManagement.AddModTask.GetModInfo(AddModDescriptor descriptor)
   at Nexus.Client.ModManagement.AddModTask.AddMod(Boolean queued)
   at Nexus.Client.ModManagement.ModManager.AddModQueue.AddMod(Uri p_uriPath, ConfirmOverwriteCallback p_cocConfirmOverwrite)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Snoops365** [comment]
Hey I figured out the issue! I realized when reinstalling again that I put it on the incorrect drive, I have my games on my D drive instead of C on this laptop, I got use to automatically doing C drive and forgot I had to put my games onto D drive instead; Therefore this error occurs when you put the nexus manager in the wrong files to search for! This is now solved
