### ISSUE TITLE
Don`t instaling mods

### ISSUE THREAD

**Issue by yuredev** [Nexus-Mods/Nexus-Mod-Manager#806]
referencia de objeto não definida para uma instancia de objeto

**Comment by Nubbie** [comment]
Please specify what's wrong
Especially in English so it's easier for everyone to follow

**Comment by yuredev** [comment]
I have already corrected, i updated the nmm and this fixed the bug.

**Comment by Nubbie** [comment]
Aaah, so this issue maybe could be closed as it seems it might be resolved @squid-box
