### ISSUE TITLE
Error when launching NMM after update

### ISSUE THREAD

**Issue by ImmieGlam** [Nexus-Mods/Nexus-Mod-Manager#807]
When I tried to launch NMM after the latest update today an error message came up, see the attached screenshot. I've also attached the tracelog that came up. Please help me.

- NMM version: 0.70.7.0

[TraceLog20190521195644.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3203869/TraceLog20190521195644.txt)
![NMM error](https://user-images.githubusercontent.com/50884147/58119752-09f0cc00-7c04-11e9-9df1-8d4aefe7a9ff.png)

**Comment by squid-box** [comment]
What you're seeing is the same issue as #728, to get around this you'll need to uninstall NMM, remove any lingering files in the Program Files directory, and install it again.

**Comment by ImmieGlam** [comment]
But won't that remove all my mods? :(

**Comment by ImmieGlam** [comment]
Well, I did as you said after some googling (to reassure myself that my mods won't disappear) and the problem got fixed without any issues!
Thank you for your help and for responding so quickly to my bug report. :)
