### ISSUE TITLE
Always at 100% disk usage when downloading

### ISSUE THREAD

**Issue by fy0** [Nexus-Mods/Nexus-Mod-Manager#81]
Mod directory on my mobile hdd. Game is skyrim.

**Comment by squid-box** [comment]
This seems more like a hardware issue and not an issue with NMM. Could you explain what you want NMM to fix / so differently?

**Comment by fy0** [comment]
@squid-box Sorry, it's a long time passed and I can't remember any details...

**Comment by squid-box** [comment]
Alright, I'll take it as it's not a problem for you anymore and close the issue.

Thanks for replying!
