### ISSUE TITLE
Version: 0.70.7.0 Crash on Startup

### ISSUE THREAD

**Issue by Slorm** [Nexus-Mods/Nexus-Mod-Manager#812]
I have just attempted to update from v65.11 to v0.70.7 and it crashes immediately on startup. O/S is Win7 64bit. I have tried multiple times and even a reboot to be sure.

Log below

Trace file has been created: TraceLog20190524205959.txt
Mod Manager Version: 0.70.7.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)

**Comment by Slorm** [comment]
Fixed, by rolling back to 65.11, then uninstalling and clean installing 0.70.7.0

**Comment by huertgenwald** [comment]
Trace file has been created: TraceLog20190524230111.txt
Mod Manager Version: 0.70.7.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: S:\Games\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Die Methode "Parse" im Typ "Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser" der Assembly "Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
Full Trace: 
	System.TypeLoadException: Die Methode "Parse" im Typ "Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser" der Assembly "Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
   bei System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes()
   bei Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo environmentInfo)
   bei Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   bei Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)
