### ISSUE TITLE
NMM 70.7 - moving plugins seems to lock up NMM for a few minutes

### ISSUE THREAD

**Issue by dragonrdr6218** [Nexus-Mods/Nexus-Mod-Manager#816]
Hello all! 

I updated from NMM 65 to 70.7 recently and ever since when i try to move a plugin it hangs, goes to not responding in task manager, then moves the plugin. It does this every time and if i want to move it say 5 spaces up or down it takes forever to make the changes.

Any ideas why this might be happenin? Do you think an uninstall / reinstall of NMM be in order to fix the issue?

Thank you for your help!

**Comment by Nubbie** [comment]
If you mean the load order, it seems to be happening to everyone

A tip in the meanwhile is to export the list and edit it with a text document editor before importing the list again, then you can move everything around without it lagging

**Comment by dragonrdr6218** [comment]
> If you mean the load order, it seems to be happening to everyone
> 
> A tip in the meanwhile is to export the list and edit it with a text document editor before importing the list again, then you can move everything around without it lagging

Thank you. I've never exported or imported before could you tell me the steps or point me to the documentation on how to do it? I really appreciate your assistance.

**Comment by Nubbie** [comment]
1. Open Nexus Mod Manager 
2. Go to the tab "**Plugin**" 
3. Press the 5th button on the left called "**Export**" 
4. Save it somewhere like the desktop
5. Open it up with a text editor

Every line in that file is the load order, just copy and paste it somewhere else to change its position
_=1 means it's on, =0 means it's deactivated (the little checkbox on the side)_

6. Go back to Nexus mod manager
7. Press the 6th button "**Import**" and select the file you exported

-------------------------------------

**Tip**: There is a program called [LOOT ](https://loot.github.io/)which automatically change load orders according to a "master list" they have which should make it easier to get the right order



![image](https://user-images.githubusercontent.com/17282384/58383223-607b5300-7fd4-11e9-8378-9ba039b1ab1d.png)

**Comment by dragonrdr6218** [comment]
Thank you! Have an awesome day!
