### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by MisterTwelve** [Nexus-Mods/Nexus-Mod-Manager#819]
**Describe the bug** 
Instant crash after clicking program. I had an older version from a couple of months ago, but after starting it up today and installing the NMM update the program no longer opens and instead instantly directs me to the tracelog which happens to mention something about Fallout 3 over and over.

I don't even own Fallout 3.

[TraceLog20190527230742.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3225634/TraceLog20190527230742.txt)

**Comment by mrrogers75** [comment]
To fix:
In the Nexus Mod Manager Install folder (default location "Program Files\Nexus Mod Manager") rename the following files if they exist in the same folder as NexusClient.exe:
Antlr3.Runtime.dll to Antlr3.Runtime.old
FalloutNV.dll to Fallout.NV.old
RestSharp.dll to RestSharp.old

Once you have done that run Nexus Mod Manager and see if it works, if it does go ahead and delete the renamed files

**Comment by MisterTwelve** [comment]
That worked, thank you very much!
