### ISSUE TITLE
can't manually add mod or login (api issues)

### ISSUE THREAD

**Issue by leehelck** [Nexus-Mods/Nexus-Mod-Manager#822]
i can't login or add mods manually. every time i try to login the manager freezes. whenever i try to add a mod the manager crashes and creates a trace log report. here is the most recent report:

Trace file has been created: TraceLog20190530101110.txt
Mod Manager Version: 0.70.7.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4.CSharpScript.dll
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Fallout4VR.dll
        Initializing: Nexus.Client.Games.Fallout4VR.Fallout4VRGameModeFactory
    Checking: FalloutNV.CSharpScript.dll
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: ModScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\ModScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimSE.CSharpScript.dll
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: SkyrimVR.dll
        Initializing: Nexus.Client.Games.SkyrimVR.SkyrimVRGameModeFactory
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XmlScript.dll
        Cannot load D:\Nexus Mod Manager\Nexus Mod Manager\GameModes\XmlScript.dll: cannot find dependency Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Enderal: Supported
    Loading Fallout3: Supported
    Loading Fallout4: Supported
    Loading FalloutNV: Supported
    Loading Morrowind: Supported
    Loading Oblivion: Supported
    Loading SkyrimSE: Supported
    Loading Skyrim: Supported
Determining Game Mode: (From Selection Form) Enderal
Game Mode Factory Selected: Enderal (Enderal)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Enderal (Enderal)
    Installation Path: C:\Steam 2\steamapps\common\Enderal
    Install Info Path: C:\Games\Nexus Mod Manager\Enderal\Install Info
    Mod Path: d:\Games\Nexus Mod Manager\Enderal\Mods
    Mod Cache Path: d:\Games\Nexus Mod Manager\Enderal\Mods\cache
    Mod Download Cache: d:\Games\Nexus Mod Manager\Enderal\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\Enderal\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\Enderal
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\GameModes
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: D:\Nexus Mod Manager\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: d:\Games\Nexus Mod Manager\Enderal\Mods
    Found 0 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\Enderal\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Steam 2\steamapps\common\Enderal\Data
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp
                Found: C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm
                Found: C:\Steam 2\steamapps\common\Enderal\Data\Update.esm
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm
                Registered.
            Found: C:\Steam 2\steamapps\common\Enderal\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Update.esm (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp (IsNull=False)
            Loading C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Steam 2\steamapps\common\Enderal\Enderal Launcher.exe (IsNull=False)
    SKSE Command: C:\Steam 2\steamapps\common\Enderal\skse_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command: D:\LOOT\LOOT\LOOT.exe (IsNull=False)
    Wrye Bash Command:  (IsNull=False)
    TES5Edit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (C:\Steam 2\steamapps\common\Enderal\Data\Skyrim.esm) (False)
    Loading: Update.esm (C:\Steam 2\steamapps\common\Enderal\Data\Update.esm) (False)
    Loading: Enderal - Forgotten Stories.esm (C:\Steam 2\steamapps\common\Enderal\Data\Enderal - Forgotten Stories.esm) (False)
    Loading: Enderal Tools.esp (C:\Steam 2\steamapps\common\Enderal\Data\Enderal Tools.esp) (False)
    Loading: No Magic Ninja Dodge - No DLC.esp (C:\Steam 2\steamapps\common\Enderal\Data\No Magic Ninja Dodge - No DLC.esp) (False)
Setting up listener on Nexus Mod Manager-EnderalIpcServer/EnderalListener at 2019-05-30 10:11:15
Running Application.
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Adding Mod to AddModQueue
[file:///G:/Downloaded Games/Bethesda/TES/Enderal/mods/Sphere Enlargement-27-1-0-1551982744.7z] Starting Add Mod Task.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModRepositories.NexusModsApiRepository.GetModInfoForFile(String fileName)
   at Nexus.Client.ModManagement.AddModTask.GetModInfo(AddModDescriptor descriptor)
   at Nexus.Client.ModManagement.AddModTask.AddMod(Boolean queued)
   at Nexus.Client.ModManagement.ModManager.AddModQueue.AddMod(Uri p_uriPath, ConfirmOverwriteCallback p_cocConfirmOverwrite)
   at Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   at Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by IamIbrahem** [comment]
i have The same problem It says login error: couldn't authenticate user:unknown

**Comment by leehelck** [comment]
this thing is completely broken. it was working just fine before i updated. makes me wish i hadn't. i haven't uninstalled it and reinstalled an older version i have backed up due to the fact it would ruin any load orders i already have in place. this is a completely untenable situation. fix this thing!

**Comment by leehelck** [comment]
ok, it's been over a week since i filed this bug report and nothing from you guys? crickets? you do realize you have put ALL of my games on hold with this broken mess, right? fix this at once!

**Comment by leehelck** [comment]
still no reply or fix? nice going. i see you've got this in hand. NOT.

**Comment by squid-box** [comment]
@leehelck: turns out you get what you pay for, this is maintained during our free time, so if we're busy this project is not prioritized.

I assume you're not getting any trace log since you say NMM freezes when you try to authenticate - could you try [forcing the creation of a trace log](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) and upload it, then I can hopefully see how far you get before NMM freezes.

**Comment by leehelck** [comment]
thank you for your reply. by following the instructions after clicking on the link you provided NMM seems to be working just fine now. my apologies if i came off terse, but i was extremely frustrated over the whole matter. i know now to run NMM this way from now on. thanks!
