### ISSUE TITLE
Click Authorize NMM but no response

### ISSUE THREAD

**Issue by bennyyang2009** [Nexus-Mods/Nexus-Mod-Manager#823]
I am using NMM 0.70.7 and I want to log in my account, but when I click the Authorize NMM button below there is no response!! What should I do i cant using and log in the old version too because NMM website not support old version anymore
**Environment**
- NMM version: _0.70.7_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
Is this still occurring for you?
