### ISSUE TITLE
NMM Has Encountered An Error And Needs To Close

### ISSUE THREAD

**Issue by JimmyRJump** [Nexus-Mods/Nexus-Mod-Manager#825]
Hadn't opened NMM since January 2019.  Was at Version 0.65.11.  NMM opened as usual and gave me an update warning.  I updated NMM to v0.70.7 and now I get the error message from the topic's title when opening NMM.  This happenes with whatever version I install (tried v0.65.11 and v0.65.10).

Tracelog:

Trace file has been created: TraceLog20190531224212.txt
Mod Manager Version: 0.65.9.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: G:\Games\Nexus Mod Manager\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.65.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Full Trace: 
	System.TypeLoadException: Method 'Parse' in type 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' from assembly 'Fallout3.XmlScript, Version=0.65.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo p_eifEnvironmentInfo)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)

**Comment by Comdriver** [comment]
I had same bug and decided to see if there is a solution on github and there is.
I found it at last post of issue #728 :
https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/728#issuecomment-496752096
at least that helped to solve my problem with "method 'parse' in type..."

**Comment by JimmyRJump** [comment]
> 
> 
> I had same bug and decided to see if there is a solution on github and there is.
> I found it at last post of issue #728 :
> [#728 (comment)](https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/728#issuecomment-496752096)
> at least that helped to solve my problem with "method 'parse' in type..."

Cheers Comdriver.  Problem solved
