### ISSUE TITLE
0.70.7 api bug

### ISSUE THREAD

**Issue by Jaa7ru** [Nexus-Mods/Nexus-Mod-Manager#826]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_Just updated NMM to the newest version and i cant login anymore becouse the "Manage your API key(s) here" button dont do anything and thats why i cant "Authorize NMM"._

**Environment**
- NMM version: _0.70.7_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
That button doesn't do anything else than open a URL in your default browser.

To get more info on why it's not working we'd need a trace log. Check this page for info on how to force a log: https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log

**Comment by Jaa7ru** [comment]
The problem was that that button didnt open the url at all.
I opened NMM again just now and it opened the url and i could authorize NMM just fine, weird.
But thanks for answering anyway.
