### ISSUE TITLE
Authentication failed due to network issues

### ISSUE THREAD

**Issue by hisjerkinghand** [Nexus-Mods/Nexus-Mod-Manager#828]
**Describe the bug** 
When trying to authenticate API I get an error saying "Authentication failed due to network issues". 
[TraceLog20190602221705.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3245779/TraceLog20190602221705.txt)

**Environment**
- NMM version: 0.70.7.0

**Comment by ManReforged** [comment]
Exactly.............

**Comment by EbicGamer69** [comment]
I'm having the exact same error. I've only found it a couple of times. I've tried everything I could think of, made sure I had an API code, tried to use the chrome fix in the download settings, re-installed the manager, restarted my PC, tried to even manually install to avoid having to click on "install with manager" but that still required authentication. 
Version 0.70.7.0

**Comment by ManReforged** [comment]
Problem has been resolved apparently.... No idea why it wasn't working before, I am able to log in and download mods with NMM just fine now.

**Comment by Undeadhero012** [comment]
I'm still having this issue, nothing has fixed for me.

**Comment by Saara13** [comment]
I also have this issue

**Comment by Saara13** [comment]
Well it's working just fine today.
How strange

**Comment by Undeadhero012** [comment]
I'll have to try it again.

**Comment by Undeadhero012** [comment]
Weird. It's working for me too. I guess if anyone is having this problem, give it a day or two and it'll work!

**Comment by squid-box** [comment]
There have been intermittent issues with the SSO service at Nexus, I assume this was the same kind of problem. The logs state `Could not connect to "wss://sso.nexusmods.com"`.

#733 could help with this, when we get to implementing that.

**Comment by Therandom200** [comment]
wait so those that mean the error happens for one day and then the next day is perfectly fine ?

**Comment by Undeadhero012** [comment]
Seemingly yes, it took about 2-3 days for me. But still, given time it worked!

**Comment by Therandom200** [comment]
thanks for the info, i dint knew what was going on and i was deleting and reinstalling every thing because i had no idea what was going on. Mostly because i started modding yesterday

**Comment by Therandom200** [comment]
By the way one last question, those this happen on random days

**Comment by Luka-Nightwind** [comment]
Is there anyway we can manually put the API in the XML of the login Squid? 
`` <setting name="ApiKey" serializeAs="String">
    <value />
   </setting>``
I'm seeing this in the NexusClient.exe.Config file. I'm guessing that this would get filled upon a successful login?

**Comment by squid-box** [comment]
@Luka-Nightwind: That config file just defines the default settings, but you're correct it's possible to manually add the setting.

Shut down NMM, go to `%LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_<some gibberish>\<current version>\user.config` and find the ApiKey setting. Edit/Add your key as the value of that setting, eg:

```
<setting name="ApiKey" serializeAs="String"> 
<value>NotARealApiKey</value>
</setting>
```

and then start NMM again, and it should automatically authenticate you. Be careful to not mess up the formatting of the file, or you'll lose your settings (won't affect the mod lists etc, but still annoying.)

There is a pull request for #733, which will be included in 0.70.8, but if you don't want to wait this work-around should help you in the meantime.

**Comment by Babbian** [comment]
Squid-box, please explain better.

**Comment by squid-box** [comment]
If that explanation isn't clear enough, you should not be doing that work-around. With #733 implemented there is a manual work-around for these cases.
