### ISSUE TITLE
Mods Can't be Added/Incomplete

### ISSUE THREAD

**Issue by zbl4de** [Nexus-Mods/Nexus-Mod-Manager#83]
When I download a mod smaller than 1mb I get '' incomplete '' error, when download mod above 1mb works normally, this error only occurs in the current version of nmm, in the legacy version it works ok. Sorry for my bad english.

**Comment by WowOkay** [comment]
I'm getting the same one. I don't know how to fix it.

**Comment by otwpmetalanimal** [comment]
apparently you have to change mod to 7z to get them to download otherwise i get the same concept of incomplete

**Comment by squid-box** [comment]
@zbl4de: Are you still having this issue with the latest version of NMM? 

If so, what mods are you seeing this issue with?
