### ISSUE TITLE
nmm crashes when launched

### ISSUE THREAD

**Issue by swagpunchabitch** [Nexus-Mods/Nexus-Mod-Manager#830]
[TraceLog20190604162103.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3254695/TraceLog20190604162103.txt)

**Comment by a19957143** [comment]
Same thing here. HELP PLEASE!!!!!!!!!!!!!!!!!!!!!!!!
Tracing an Unhandled Exception:
        Exception: 
Message: 
	El método 'Parse' en el tipo 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' del ensamblado 'Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null' no tiene una implementación.
Full Trace: 
	System.TypeLoadException: El método 'Parse' en el tipo 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' del ensamblado 'Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null' no tiene una implementación.

**Comment by robboten** [comment]
same here

**Comment by robboten** [comment]
Uninstall/reinstall fixed it

**Comment by a19957143** [comment]
Robboten are you sure? I already reinstalled in order 2 times. I havent uninstalled yet, because I have like 300 mods instaled with Skyrim. I wil try.

**Comment by squid-box** [comment]
This issue is a duplicate of #728, there's detailed steps there to fix it - but you will need to uninstall (it won't remove your mods as long as you don't delete configuration files or change directories).
