### ISSUE TITLE
NMM Issue Opening

### ISSUE THREAD

**Issue by phillipcoulson1** [Nexus-Mods/Nexus-Mod-Manager#831]
Appears to have something to do with Fallout3, trace log below.  Thanks for taking a look.

[TraceLog20190608200739.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3269145/TraceLog20190608200739.txt)

**Comment by squid-box** [comment]
This is the same issue as in #728, there are some work-arounds detailed there.
