### ISSUE TITLE
Error with .net framework, even though i have the latest one.

### ISSUE THREAD

**Issue by ToastieDI** [Nexus-Mods/Nexus-Mod-Manager#838]
[TraceLog20190614031240.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3289268/TraceLog20190614031240.txt)

**Comment by squid-box** [comment]
The issue is a little sparse on info, but I think this has been solved in one of the latest updates. 

Please use the latest version and see if it works for you.
