### ISSUE TITLE
Nexus Mod manager needs to close, "not enough memory"

### ISSUE THREAD

**Issue by Jettrail** [Nexus-Mods/Nexus-Mod-Manager#840]
Basically when i just tried to active new mods i got the message that NMM needs to close and the trace log says "not enough memory", even tho i have 200GB left. When i looked at the issues page in the Nexus Forums i foundmy problem but no solution so i think my best bet is to try it here.

**Comment by Jettrail** [comment]
Checking if upgrade is required...
    
    Tracing an Unhandled Exception:
    Running Threads (1)
    5 () 
        Aborted
        Exception: 
Message: 
	Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

Full Trace: 
	System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei Nexus.Client.ModManagement.InstallationLog.InstallLog.Restore(String p_strLogPath)
   bei Nexus.Client.ApplicationInitializer.InitializeServices(IGameMode p_gmdGameMode, IModRepository p_mrpModRepository, NexusFileUtil p_nfuFileUtility, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   bei Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   bei Nexus.Client.ApplicationInitializer.DoWork(Object[] args)
   bei Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   bei Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by squid-box** [comment]
If the actual message states "memory", then it's a question of RAM and not storage space. But the second message you pasted seems to indicate your computer is out of storage space.

How much space is left on your C: drive, or wherever you've put the %TEMP% directory?

**Comment by Jettrail** [comment]
Over 200GB. I have NMM in german so it could also mean something different
than memory

Joel Ahlgren <notifications@github.com> schrieb am Mo., 17. Juni 2019,
07:07:

**Comment by squid-box** [comment]
The error message states (according to my elementary school German, and Google Translate: `There is not enough space on the disk.`. This message comes from the built-in copy file function from C#, so if it says there's not enough space to copy a file, Windows believes there is no space left for that file.

To re-iterate, are you sure you've got space left on C:\ and/or the drive where NMM is configured to put its mods/files? Looking at the log it's not failing to copy any downloaded upgrade, it's actually failing to copy an installation log file, which is typically fairly small.

**Comment by Jettrail** [comment]
I just fixed the issue. All i did was downloading NMM again and deleting
the old NMM files. It works fine now

Joel Ahlgren <notifications@github.com> schrieb am Mo., 17. Juni 2019,
12:44:
