### ISSUE TITLE
The object reference is not set to an object instance.

### ISSUE THREAD

**Issue by Jespicak** [Nexus-Mods/Nexus-Mod-Manager#842]
When i try to install / add mod from zip file i got error that closes the program.
When i look into Tracelog it says
The object reference is not set to an object instance. (it's written in my language)

**Environment**
- NMM version: _0.70.7_
- Mod(s) used:  any mod

Tracing an Unhandled Exception:
Exception: 
Message: 
	Odkaz na objekt není nastaven na instanci objektu.
Full Trace: 
	System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v Nexus.Client.ModRepositories.NexusModsApiRepository.GetModInfoForFile(String fileName)
   v Nexus.Client.ModManagement.AddModTask.GetModInfo(AddModDescriptor descriptor)
   v Nexus.Client.ModManagement.AddModTask.AddMod(Boolean queued)
   v Nexus.Client.ModManagement.ModManager.AddModQueue.AddMod(Uri p_uriPath, ConfirmOverwriteCallback p_cocConfirmOverwrite)
   v Nexus.Client.Commands.Generic.Command`1.Execute(T p_tArgument)
   v Nexus.Client.ModManagement.UI.ModManagerControl.addModToolStripMenuItem_Click(Object sender, EventArgs e)
   v System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   v System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   v System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   v System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   v System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   v System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   v System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   v System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.ToolStrip.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by squid-box** [comment]
This should've been fixed in a newer version, please update and try again.
