### ISSUE TITLE
How to correct NMM path names

### ISSUE THREAD

**Issue by cormell** [Nexus-Mods/Nexus-Mod-Manager#85]
I mis-typed the folder name where I want NMM to store files.  So now when I try to open NMM I get the error for write permissions.  I run NMM as administrator, but it doesn't matter really, NMM is looking in the wrong place.  How do I change the path?

**Comment by DuskDweller** [comment]
Uninstall NMM **removing config files when asked**, then reinstall it.

**Comment by cormell** [comment]
Thanks mate.  Makes sense.
