### ISSUE TITLE
nmm won't update

### ISSUE THREAD

**Issue by princessvelociraptor** [Nexus-Mods/Nexus-Mod-Manager#850]
**Describe the bug** 
nmm won't update, looked at the end of the tracelog and can't find the file pathway listed in the "unhandled exception" at the end. i'm not good with computers so apologies if this is a dumb question

[TraceLog20190620023237.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3309111/TraceLog20190620023237.txt)

i tried to manually download the current version and overwrite to update, but it returned this trace file

[TraceLog20190620024449.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3309117/TraceLog20190620024449.txt)

**Environment**
- NMM version: _0.65.6_

**Comment by squid-box** [comment]
This is a recurring problem with the installer, see #728 for workaround instructions, tl;dr: do a clean install (won't affect installed mods etc).

**Comment by princessvelociraptor** [comment]
ah, i didn't see anything like my issue in the suggested threads when i created mine, thank you so much!
