### ISSUE TITLE
tried to update nmm to 63.5 when no new release is available

### ISSUE THREAD

**Issue by Singleminded2020** [Nexus-Mods/Nexus-Mod-Manager#854]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
![image](https://user-images.githubusercontent.com/50594578/60199846-d01e7100-9812-11e9-92ad-e6f285c0f23b.png)

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

loaded up nmm and it said there was an update and it showed 63.5 as an update. currently on 70.8
**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by pokara** [comment]
nmm 0.70.8 here

same message from 2 days ago, pop up every day when i load nmm

**Comment by squid-box** [comment]
0.63.5 is just the covent of the changelog, the version pushed was (0.)70.8.

This was a configuration problem on our side, and was fixed some time ago.
