### ISSUE TITLE
update not need but ask every start 0.70.8

### ISSUE THREAD

**Issue by OldGamerDarthy** [Nexus-Mods/Nexus-Mod-Manager#856]
hello, the version: 0.70.8 every launch ask me update to 0.70.8 identic version but ask every start

sorry for my english i'm italian autodidact, thanks for all the works ;)

**Comment by LORD-PINKYDINKS** [comment]
i'm having the same problem

**Comment by GameZenChill** [comment]
Same here. Already on 0.70.8 but if I check for updates, it shows a 'newer' version 0.70.8. I accepted the update once to see if it fixes the 'bug'. 

But it doesn't. Even after updating as it wanted, it still shows 'newer' version 0.70.8 available if I check for updates

**Comment by Pultex** [comment]
Yes same keeps saying my version is 0.63.5 or something and it is not, it is 0.70.8.

**Comment by ramonxick** [comment]
same here, and the last update was 21 days ago

**Comment by EvilOssie** [comment]
I've seen the update notice twice now, even tho I have v0.70.8 installed.

**Comment by Zippomoon** [comment]
Throwing my hat into the ring.

**Comment by matt0x5B** [comment]
This is caused by the latest release being tagged incorrectly with "070.8" rather than "0.70.8".

**Comment by DesertRanger111** [comment]
@matt0x5B Is there a fix for this that I can do?

**Comment by squid-box** [comment]
This has finally been corrected 😅
