### ISSUE TITLE
Unable to download a specific mod

### ISSUE THREAD

**Issue by Dunnie97** [Nexus-Mods/Nexus-Mod-Manager#86]
I can't download Kryptopyr's mod "Complete Crafting Overhaul Remade" (http://www.nexusmods.com/skyrim/mods/49791/?) 
Every time that I try NMM gives the error message :Error registering this mod: Complete Crafting Overhaul Remade
Error: Could not find a part of the path 'C:\Games\Nexus Mod Manager\Skyrim\Mods\cache\Complete Crafting Overhaul Remade-49791-1-7\fomod'. 
No problems with other mods. Manual installation doesn't help.

**Comment by DuskDweller** [comment]
I tried with that mod and it works on my end, which version of NMM are you using?

**Comment by Dunnie97** [comment]
The latest version. I tried a full re-install of NMM but it didn't help. The Download just doesn't work and install from a zip archive gives the error message. I've since given up on the mod and am just gonna restart modding on a fresh install.
