### ISSUE TITLE
NMM won't list Wrye Bash in the Supported Tools drop down menu for Fallout 4.

### ISSUE THREAD

**Issue by Zippomoon** [Nexus-Mods/Nexus-Mod-Manager#863]
I have Wrye Bash installed for F4, but I can't seem to get it to appear as an option in the Supported Tools drop down menu.

**Environment**
- NMM version: 0.70.8

**Comment by squid-box** [comment]
That makes sense, as Wrye Bash is not a known tool in NMM. In [Fallout4SupportedTools.cs](https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/Game%20Modes/Fallout4/Fallout4SupportedTools.cs) you can see the known tools are:

* LOOT
* FO4Edit
* BodySlide
