### ISSUE TITLE
Odd version update behavior

### ISSUE THREAD

**Issue by Ceophthra** [Nexus-Mods/Nexus-Mod-Manager#866]
I installed the Community version of NMM just after it first came out. I would occasionally get a pop-up about a new release. I'm now at v 0.70.8. My problem is that about every tenth time I start NMM, I get a pop-up about a new release, but v 0.70.8 seems to be the latest. Is there an error in the update logic?

**Comment by pokara** [comment]
same here, i wrote a similar post days ago..  nobody answered..   youre not alone xD

edit: its not ocaasionalll, youll get that popup message i think every day first time open nmm

**Comment by dragonrdr6218** [comment]
I am also getting this. I tell it to update then a day or so later it does the same again. Any ideas why this is happening? Last time was this morning and I just told it to cancel as its the same update prompt every time.

**Comment by ghost** [comment]
I believe this might happen because the github release tag is 070.8, not 0.70.8 - i.e. it's missing the period between 0 and 7.

**Comment by squid-box** [comment]
Sorry for the delay, the release tag has been corrected.

**Comment by dragonrdr6218** [comment]
Awesome! Thank you.

J. McKinney
