### ISSUE TITLE
nmm crashes when i try to import mods

### ISSUE THREAD

**Issue by chairback** [Nexus-Mods/Nexus-Mod-Manager#868]
**Describe the bug** 
whenever I try to upload a mod to fnv it crashes and I don't have any anti virus software installed on my pc 

- NMM version: _ the latest community version 

tracelog20190714002710

 whenever I first had it deleted the mod file because I thought it was messing with my game audio

**Comment by squid-box** [comment]
You're going to have to attach the file to this issue, and it's usually a good idea to actually write out the version number.
