### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by ni9htwalker15** [Nexus-Mods/Nexus-Mod-Manager#87]
is says i cant log in because the servers are down or my firewall is blocking it neither of which are true. Hasn't this been a issues for years now?

**Comment by DuskDweller** [comment]
If you get this error then one of those must be true, since the NMM servers are currently up I'd say it's something on your PC that is preventing NMM from connecting to the internet.

(or you're using an old unsupported version)

**Comment by squid-box** [comment]
With no updates on this for well over a year, I'm closing this issue.
