### ISSUE TITLE
Always the same update revision

### ISSUE THREAD

**Issue by Aeiri** [Nexus-Mods/Nexus-Mod-Manager#871]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
For 4 times now when I've opened my Nexus Mod Manager, Community Edition, it has opened a dialog for its newest update. The update revision number has always been the same: 70.8. Is there a way of stopping this errant behavior until an update after 70.8 comes along?

Thanks!

**Comment by TheHacker66** [comment]
Yup it started happening to me as well.

**Comment by rlw6664** [comment]
Also having the same problem. Reinstalling update doesn't seem to cause any problems but it always comes back to 70.8 on next update check.

**Comment by Stealch** [comment]
Same problem. After ever start the NMM "found" new version 70.8. Installed version - 70.8.
![2019-08-11_07-53-16](https://user-images.githubusercontent.com/14859190/62829928-5c42f700-bc0d-11e9-86b1-1dbd5abdca5e.png)
![2019-08-11_07-50-43](https://user-images.githubusercontent.com/14859190/62829932-6107ab00-bc0d-11e9-8f3d-94fe14010e88.png)

**Comment by squid-box** [comment]
This has been fixed, there was a missing `.` in the 0.70.8 release tag...
