### ISSUE TITLE
Fallout 4 missing 

### ISSUE THREAD

**Issue by Ratatoskr-Squirrel** [Nexus-Mods/Nexus-Mod-Manager#873]
**Describe the bug** 
Fallout 4 doesnt show up in the Game Detection Directory

**Environment**
- NMM version:  0.70.8.0

**Additional information** 
![Screenshot (7)](https://user-images.githubusercontent.com/53475465/62125099-62aba780-b2cc-11e9-8660-2dc3fee458cc.png)

**Comment by squid-box** [comment]
It looks like you're missing several game modes - I'd check if you have the Fallout 4 .dll file under (your equivalent of) `C:\Program Files\Nexus Mod Manager\GameModes\`. If you do, please check the file version of it, if you don't I'd recommend reinstalling NMM to see if you get the missing modes.
