### ISSUE TITLE
0.70.8 keeps requesting to be installed

### ISSUE THREAD

**Issue by Moksha8088** [Nexus-Mods/Nexus-Mod-Manager#874]
0.70.8 keeps asking to be installed when I open up NMM 0.70.8.  I've gone along with this about four times just to humor the installation request, but most of the time I ignore it.

**Environment**
- NMM version: 0.70.8

Don't really have any trace logs, because 0.70.8 is working fine except for the part about not realizing it is already installed.

**Comment by Dark-talon** [comment]
I have same problem, it keeps wanting to update to itself over and over.

**Comment by playerlin** [comment]
https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/866#issuecomment-516628446

Looks like the tagged numbers was typo. Tagged 070.8, not 0.70.8 and since 70.8 always "newer" than 0.70.8 so NMM just keep say want to update it, just ignores that.

**Comment by squid-box** [comment]
Sorry for the delay, the tag has been corrected.
