### ISSUE TITLE
Nexus Mod Manger has encountered an error and 

### ISSUE THREAD

**Issue by GastonDreyfus** [Nexus-Mods/Nexus-Mod-Manager#884]
I try to install mod by file and nexus do that. (Skyrim SE)
[TraceLog20190820155742.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3522380/TraceLog20190820155742.txt)

**Comment by squid-box** [comment]
This was most likely fixed in one of the more recent versions, please try updating and try again.
