### ISSUE TITLE
skyrim SE cant be found in resan on nexus

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#89]
my nexus is up to date and when i rescan for sse its not there.
HELP!!

**Comment by DuskDweller** [comment]
During the gamescan process you can manually point NMM to the Skyrim SE folder by clicking on X beside Skyrim SE and then on the "..." button to browse your HD folders.

**Comment by squid-box** [comment]
With no further reply in a year, I'm assuming this some the issue.
