### ISSUE TITLE
NMM crashes on startup

### ISSUE THREAD

**Issue by theStrauss** [Nexus-Mods/Nexus-Mod-Manager#893]
on start up NMM says it has encountered a problem and needs to close
NMM version: 0.70.8.0

form the TraceLog:
"_Message: 
	Die Datei oder Assembly "file:///C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet._"

full TraceLog:
[TraceLog20190908190158.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3587813/TraceLog20190908190158.txt)

I checked, the "Skyrim.XmlScript.dll" is there so it would have to be a dependency,
but i'm not running any mods for Skyrim. Mainly because i got the SE.

**Comment by squid-box** [comment]
If the file is present but you're getting this error, it most likely means it's not the same version of the file that NMM was compiled against (likely an installation error). If you do a re-install of NMM it should get all the correct file versions. Or if you just don't feel like reinstalling and will never use Skyrim, just delete the three files:
* `GameData\Skyrim.dll`
* `GameData\Skyrim.CSharpScript.dll`
* `GameData\Skyrim.XmlScript.dll`

**Comment by theStrauss** [comment]
thanks for the advice
re-install did it
