### ISSUE TITLE
View filter box ignored when adding/removing a mod.

### ISSUE THREAD

**Issue by jbostrus** [Nexus-Mods/Nexus-Mod-Manager#895]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
When adding mods (manual or via download), or deleting a mod, the category list view refreshes ignoring the applied filter.

**Environment**
- NMM version: _0.70.8_ and earlier
- Mod(s) used: any

**To Reproduce**
Apply a visual filter. Either download a mod or add one manually. Once the mod is added to the list it refreshes showing the entire list ignoring the filter.

**Additional information** 
Patch ready just making bug report to tag in the commit.

**Comment by squid-box** [comment]
Closing on the assumption this was released as part of 0.70.9.
