### ISSUE TITLE
[Solution] If NMM crashes on Win8/10 with 'vorbis.acm' message

### ISSUE THREAD

**Issue by T0T4R4** [Nexus-Mods/Nexus-Mod-Manager#9]
Go in C:\Windows\System32 and simply rename vorbis.acm to vorbis2.acm.

This took me 2 days to find out, with hours of debugging on the source code...

**Comment by ghost** [comment]
When does this crash occur?

**Comment by T0T4R4** [comment]
Some time to time, on Win10. It is not specific to this software, but it may happen. 
So I guess for the log it's good to know how to solve it :)

**Comment by squid-box** [comment]
Given the time since the last activity on this issue, I'm closing it.
