### ISSUE TITLE
Incompatibility with XML 1.1

### ISSUE THREAD

**Issue by BalthorWasUnavailable** [Nexus-Mods/Nexus-Mod-Manager#906]
NMM versions 0.70.8 & 0.70.9 (and I'd assume all previous versions) can't load mods with FOMODs that use XML 1.1, even if you try and "fool" NMM by manually editing the version number (this was suggested by a Nexus user).
https://www.nexusmods.com/skyrimspecialedition/mods/29402 is the only instance of this I've personally found, but there seems to be more mods having similar problems. 
I feel like this may have already been reported, but I just wanted to make sure. 
Thanks for continuing to support NMM by the way, you guys rock

**Comment by squid-box** [comment]
There's no proper support for XML 1.1 in C#/.NET, and there's no actual reason for that mod to use XML 1.1 - so we won't try to add support for it in NMM either.

Replacing the 1.1 with a 1.0 works fine, just make sure you don't have a cached unzipped copy under `<wherever you place your mods>\Nexus Mod Manager\SkyrimSE\Mods\cache` and you'll be able to add it after modifying the version number:
![image](https://user-images.githubusercontent.com/864820/66687547-3674b580-ec83-11e9-9c60-0a6b435652ee.png)

Or just tell the mod author to "downgrade" his info.xml to 1.0, as he's not even using anything that requires XML 1.1.

**Comment by BalthorWasUnavailable** [comment]
Oh, I see. Is there any point in FOMODs using XML 1.1, out of curiosity? If
not, hopefully it'll be easy to convince modders to not use 1.1 or
downgrade to 1.0.
I didn't think of clearing the cache after changing the version number,
that makes a lot of sense.
Thanks for the info and the help, and apologies for making a pointless
report.
