### ISSUE TITLE
No NMM option for Nexus downloads

### ISSUE THREAD

**Issue by Moksha8088** [Nexus-Mods/Nexus-Mod-Manager#909]
In the past, there has always been a small window that opened after clicking the automatic download for mods at the Nexus.  Currently, that window is not opening and there is just the standard box asking to download with Vortex. I used the manual download and installed the desired mod with NMM.

Has something changed with Nexus such as a new API?  Will clicking the download with Vortex work with NMM?

**Environment**
- NMM version: 0.70.9

**Comment by DuskDweller** [comment]
Yes, it's the same link, just click download with Vortex and it'll download with any mod manager you got handling Nexus links.
