### ISSUE TITLE
Skyrim Special Edition Mods Not Activating

### ISSUE THREAD

**Issue by leo716** [Nexus-Mods/Nexus-Mod-Manager#91]
I had to do a fresh re-install on my laptop because of a completely unrelated issue. So when I re-installed my games and Nexus Mod Manager, No matter what I do, either for Skyrim SE or Fallout 4, none of the mods I previously downloaded or new ones work. I keep getting the message that this save requires mods that are no longer available.

**Comment by DuskDweller** [comment]
Is NMM pointing to the correct game folders? (check in Settings -> Game)

**Comment by squid-box** [comment]
No response after a year, assuming problem went away.
