### ISSUE TITLE
Nexus Mod Manager crash?

### ISSUE THREAD

**Issue by S3rena** [Nexus-Mods/Nexus-Mod-Manager#912]
_Please give as much information as you can, replace/remove italicized text._
I've tried multiple times to run a new mod "Bodyslide" off the Nexus mod manager but every time I click the check mark to activate it the app crashes and is forced to shut down, ive tried rearranging the security software like they suggest, and re downloading it but no luck.  all I get is another "tracelog" number latest one TraceLog20191103143541 and the app shuts down.. how do I fget this mod to work?
**Is your feature request related to a problem?**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
Mod manager and mod use.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
a quick and simple way to activate the mod so its not just greyed out and useable in the game.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by squid-box** [comment]
You need to attach the trace log, you only added the filename :)
