### ISSUE TITLE
nmm does not have a plugins tab

### ISSUE THREAD

**Issue by cade111** [Nexus-Mods/Nexus-Mod-Manager#92]
so I set NMM up for no man's sky and there is no plugins tab. I even tried to reset the UI but nothing worked.
![image](https://cloud.githubusercontent.com/assets/28840307/26284066/c447548c-3e00-11e7-8017-526da663efde.png)

**Comment by DuskDweller** [comment]
The No Man's Sky game mode doesn't need the plugins tab.

**Comment by cade111** [comment]
well the mods aren't working

**Comment by DuskDweller** [comment]
Well, are you downloading and installing them ? I see an empty list on the attached screen.

**Comment by cade111** [comment]
yes I was installing them it's just I reinstalled nmm to see if that worked

**Comment by squid-box** [comment]
@cade111: Is this still a problem (mods not installing) for you with the latest NMM? If so could you grab some trace logs from when this is happening? See [this page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#how-to-collect-information) on how to do this.

**Comment by cade111** [comment]
no this isn't a problem anymore sorry for the year long response.
