### ISSUE TITLE
Nexus mod manager dropping

### ISSUE THREAD

**Issue by MonRip** [Nexus-Mods/Nexus-Mod-Manager#93]
Every time when i want check for missing download IDs or when i want Fix download IDS and check for updates, the NMM drops and leaves this trace log. Can anybody help?

[TraceLog20170521192458.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1017191/TraceLog20170521192458.txt)

**Comment by DuskDweller** [comment]
Is your Mods panel in plain view (plain list of mods) or category view (category folders with mods in it) ?

**Comment by squid-box** [comment]
With no reply in about a year, I'm assuming this is not an issue anymore, and will close the issue.
