### ISSUE TITLE
GitHub page not showing the different cases

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/Nexus-Mod-Manager#930]
Tonight, I have added one bug (now two) bug reports and 2 feature Requests. I only see my my Feature Requests as a reported bug, when I clearly choose to Request a Feature. I don't know if this is a glitch on GitHub or if the NMM Repository is having an issue.

**Comment by squid-box** [comment]
GitHub only has "issues", no concept of bugs/improvements/etc.

We've just added templates for bugs/features that provide some pre-filled information when you create a new issue.

If something looks wrong in your created issue, you can edit it.
