### ISSUE TITLE
loot is not recognising any plugins from fallout 4

### ISSUE THREAD

**Issue by cade111** [Nexus-Mods/Nexus-Mod-Manager#94]
so I installed loot and a few mods and loot doesn't recognize them. how do I make loot see the mods? 

![screenshot 12](https://cloud.githubusercontent.com/assets/28840307/26287364/fa2bd6da-3e47-11e7-87b3-852e024a0ec8.png)

**Comment by DuskDweller** [comment]
Looks like LOOT and NMM are pointing to two different Fallout 4 Data folders.

**Comment by cade111** [comment]
How do i point it to the nmm data folder

**Comment by cade111** [comment]
so can I get help or...

**Comment by DuskDweller** [comment]
Sorry but NMM seems to be working, so since your issue seems to be with LOOT you'll need to ask for help on their side.

**Comment by DuskDweller** [comment]
Here's a link: https://github.com/loot/loot/issues

**Comment by cade111** [comment]
I already checked with them and they said it was a NMM problem

**Comment by cade111** [comment]
I gave them my loot debug and they said they couldent see anyrhing wrong.

**Comment by cade111** [comment]
Its funny the loot people say ask you and you say ask them so i guess ill never sort mods again

**Comment by DuskDweller** [comment]
It's not a LOOT issue, it's you selecting the wrong game folder in LOOT ;)

**Comment by cade111** [comment]
Im pretty good at computers just not loot or nmm but i only have one fallout directory

**Comment by cade111** [comment]
But if you want i will close this

**Comment by cade111** [comment]
both the loot and you guys don't know what's wrong where else should I ask?

**Comment by cade111** [comment]
should I ask anyone else or should I just give up and not play Fallout 4?

**Comment by cade111** [comment]
ok so you might not be moderating this anymore but I found the reason why loot isn't working with NMM... I think. so I have LOOT set to read the Fallout 4 main data folder but NMM isn't saving the mods there so do you know how I can fix that?

**Comment by cade111** [comment]
Nevermind i found what it was but thanks anyway!
