### ISSUE TITLE
DLL Updates

### ISSUE THREAD

**Issue by DarthVitrial** [Nexus-Mods/Nexus-Mod-Manager#948]
It would be helpful to see the included 7z dlls updated.

Namely the 7zip dll being updated to 19.02, and sevenzipsharp.dll being updated from 1.1.144.0 to 1.2.231. 
This might also fix the bug where NMM is unable to properly install fomod files with very large sizes (such as the LotD v5 patches).

**Comment by squid-box** [comment]
Partially already done, but I'll have a go at the 7z dll's too.
