### ISSUE TITLE
Plugins Tab not reloading after closing LOOT

### ISSUE THREAD

**Issue by MOVZX** [Nexus-Mods/Nexus-Mod-Manager#958]
**Describe the bug** 
Previously whenever we opened LOOT to sort plugins order and then closing it, the plugin lists on NMM Plugins Tab will automatically refreshing. But now it's not.

**Environment**
- NMM version: _0.71.1_

[TraceLog20200122214937.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/4097849/TraceLog20200122214937.txt)

**Comment by squid-box** [comment]
Do you know in which version it was working?

I don't recall any code for handling when LOOT closes.

**Comment by MOVZX** [comment]
0.70.9

**Comment by squid-box** [comment]
This should have been fixed as part of 0.71.2.
Please re-open if that's not the case.
