### ISSUE TITLE
The mod manager is just stuck in its initial loading screen when I try to start it.

### ISSUE THREAD

**Issue by Edulml** [Nexus-Mods/Nexus-Mod-Manager#97]
Verison 0.63.14. Any way I can give more data? It might be because I got rid of a hard drive that contained the skyrim mod files, I want to put them somewhere else.

**Comment by Xebeth** [comment]
I found a bug in the code that causes an infinite loop if a path is not found. This might be the cause of your problem.

Go to %AppData%\..\Local\Black_Tree_Gaming, it will contain folder(s) with a name like NexusClient.exe_Url_5qrmz1fcjhge2kc2knmpduzeaejvngno with a folder per version. Inside should be a file named user.config. Try to edit it and replace the paths for ModFolder and InstallInfoFolder.

**Comment by Ronkn** [comment]
@Xebeth this solved my problem. Running this in a VM and my passedthrough disk letter changed when I changed my host OS and rescued the VM system image. Thanks

**Comment by squid-box** [comment]
@Xebeth: did you submit a fix for this? (i.e. can this issue be closed?)

**Comment by Xebeth** [comment]
It's been a while so I'm not 100% sure but I think it was related to #185. If so, #186 should have fixed this issue and you can close it.

**Comment by squid-box** [comment]
Yes, looks like that's the case. I'll close the issue and we'll see if it crops up again ;)
