### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Swatchel** [Nexus-Mods/Nexus-Mod-Manager#977]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._
url http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe is unreachable now.
Please fix this url in your code

**Comment by squid-box** [comment]
I doubt we'll be able to fix this, this looks to be part of a compatibility script for Windows 98/ME - to install Windows Installer 2.0. Microsoft are no longer providing downloads for this.

The only fix I see for this is simply removing the URL and telling the user to find it themselves (and honestly, to move to a more modern OS...).
