### ISSUE TITLE
NMM PROBLEM

### ISSUE THREAD

**Issue by GAM1R** [Nexus-Mods/Nexus-Mod-Manager#985]
[TraceLog20200405185957.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/4434266/TraceLog20200405185957.txt)

**Comment by squid-box** [comment]
Install a later version (from [releases](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases)) and this should be fixed.
