### ISSUE TITLE
Unrecognized game mode: skyrimspecialedition

### ISSUE THREAD

**Issue by drwinder** [Nexus-Mods/Nexus-Mod-Manager#995]
On the Website Nexusmod.com I try to download a mod for Skyrim SE. Its the right one for my Version not Oldrim or Skyrim LE its Skyrim SE Website. But when I want to download via the Mod Manager the Error "Unrecognized game mode: skyrimspecialedition" pops up.

I used the same Mod Manager Version on another PC before and everything worked perfectly fine. Installed as always. Even Uninstalled the manager + the game over and over again and reinstalled. Deleted all files. Didnt help.

**Environment**
- NMM version: 0.71.2
Right now its clean and I dont use any other mod. no matter which one on the skyrimSE website I want to download it does the same error.

**Comment by DuskDweller** [comment]
Update to 0.71.3 please, Nexus changed the link format for some games and we had to patch it in.
