### ISSUE TITLE
Unrecognized Game Mode: skyrimspecialedition

### ISSUE THREAD

**Issue by Taipay** [Nexus-Mods/Nexus-Mod-Manager#996]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Cannot load mods from Nexusmods.com for Skyrim Special Edition

**Environment**
- NMM version:0.71.2
- Mod(s) used: _<link to mod(s) on Nexus>_https://www.nexusmods.com/skyrimspecialedition

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_
![Nexusfehler](https://user-images.githubusercontent.com/64017766/79771932-c3ce4c00-832f-11ea-89a9-00ac5aaf5896.jpg)

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by Aaronthelemon** [comment]
I have the exact same issue started today but for New Vegas instead.

**Comment by Taipay** [comment]
sry but i have to translate everything with the help of google since i don't speak english and i don't know what is written so SRY :-)

**Comment by DuskDweller** [comment]
Update to 0.71.3 please, Nexus changed the link format for some games and we had to patch it in.

**Comment by Taipay** [comment]
Thank you for the quick solution :-))
