### ISSUE TITLE
Unrecognized Game Mode: newvegas

### ISSUE THREAD

**Issue by Aaronthelemon** [Nexus-Mods/Nexus-Mod-Manager#997]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Cannot install any new mods from Nexusmods.com since the 0.71.2 update.
Appears to be an issue with reading the gamemode, game launches fine with current mod list.

**Environment**
- NMM version: 0.71.2
- Mod(s) used: Any

**To Reproduce**
By downloading any mod on Nexus for New Vegas.
![image](https://user-images.githubusercontent.com/64029884/79774480-c4b0af00-832a-11ea-935d-891442bb375c.png)

**Comment by DuskDweller** [comment]
Update to 0.71.3 please, Nexus changed the link format for some games and we had to patch it in.
