### ISSUE TITLE
Nexus Mod Manager won't recognize Skyrim special edition mods

### ISSUE THREAD

**Issue by IsCoronaTime** [Nexus-Mods/Nexus-Mod-Manager#998]
Trying to download a mod comes up with an error saying "Unrecognized Game Mode: skyrimspecialedition" i have no mods installed and i have uninstalled and reinstalled nexus mod manager 3 times. I cannot use mod organizer 2 due to issues with installation. what could be the problem as it started last night.

**Comment by scjohnson1981** [comment]
Same issue here.  Was working fine yesterday.  Now getting the error mentioned by IsCoronaTime above...  Please fix this mess.

**Comment by scjohnson1981** [comment]
Manual download/adding to NMM via the Add Mod button works just fine though...

**Comment by DuskDweller** [comment]
Update to 0.71.3 please, Nexus changed the link format for some games and we had to patch it in.
